### ISSUE TITLE
Migration simulator

### ISSUE THREAD

**Issue by shincoder** [laravel/internals#1]
This is a 2 months old proposal posted on laravel/framework (closed since proposals are not discussed there).

As you know, wrapping database migrations in a transaction has no effect in Mysql for table operations.
Which means that if migration fails, you most likely end up with a broken database state which stinks!!!

I made a package that simulates the migrations in a testing database and report back success or failure to the user, leaving the real production database intact.

So the main idea behind this is the following:
- We create a testing database for every connection specified by the user (or use the default one).
- We switch the configuration to the new database at runtime, replacing the real database.
- We refresh the connection so that Laravel can use the new configuration.
- We run php artisan migrate against the testing database.
- When done, we drop the testing database.
- Any eventual errors are displayed to the user.
- The real database stays intact.

This could be a great addition to the framework. I'm sure you can come up with a better implementation.

Working code https://github.com/shincoder/harmless-migration

Haven't experienced any issues so far.

**Comment by Mevrael** [comment]
How is it different from just testing migrations up and down on your local or dev server?

**Comment by shincoder** [comment]
If your ```up``` fails, the ```down``` won't succeed to revert the changes which will leave you in a broken state, especially if you have foreign key contraints in place.

So you either import a old sql dump of your database, or fight through the database tables making manual changes just to revert back to the original state.

As for a production server, if you ever have a mysql configuration that is different to the one you use locally, the ```up``` can still succeed locally and fail on the remote server. I has this problem once, where my default engine locally was InnoDB, and the prod server MyISAM (default in mysql prior to 5.5). Then I run ```migrate``` command and big red exception was thrown from no where.

I had to set the engine explicitly to InnoDB in all my migration files where a table is created for the first time.

This was just one single problem, other issues may rise in different scenarios.

So instead you could test and then if it succeeds, you continue with you migrations with no worries of breaking you database.

And if you use a deployment tool, you could ``` php artisan migrate:test ``` before ``` php artisan migrate ```, so if the simulation fails, the deployment is cancelled without ever touching your production database.

**Comment by Mevrael** [comment]
Always set table engines, encodings, etc and do not rely on default server settings. I extended Blueprint constructor like this:
```php
        $this->engine = config('database.connections.mysql.engine');
        $this->charset = config('database.connections.mysql.charset');
        $this->collation = config('database.connections.mysql.collation');
```
and always have engine, charset and collation I've set in config.


What are you trying to solve is pritty impossible. For such cases you must have a staging environment which is maximum close to production environment where you also have same data.

I don't think there is need in `php artisan migrate:test` because it is the same as `php artisan migrate` on local/test/dev/staging server.

When migration failed and I got broken structure, I'm repairing it fast using MySQL Workbench or just dropping all tables and running all migrations again.

**Comment by daison12006013** [comment]
and ofcourse there must be a backup of your production server.

**Comment by mikield** [comment]
I agree that Laravel`s migration system can be much better. My huge problem is with refrences and it`s a horible error for me.
But as for your suggestion @shincoder, you must realy test your migration on dev/local mashine and then you`ll be sure that if they pass in local so with the same database configuration they will pass on prod server. :)

**Comment by CzajekDC** [comment]
What about a runtime? Anyone benchmarked it?

**Comment by legshooter** [comment]
@shincoder makes some valid points. @Mevrael that's a lot of boilerplate, maybe migrations could be improved in the sense that you would be able to only specify these settings once, or make them default to the mysql conn implicitly, and specifying them per migration would allow overriding.

**Comment by raice** [comment]
@shincoder I totally agree. We do have testing servers with the same data as the live servers. But I still think the migration process could be better.

**Comment by jamesgrose** [comment]
@shincoder Could wrapping each migration in a database transaction help to stop the database being left in a broken state?

**Comment by franzliedke** [comment]
@jamesgrose Nope, at least for MySQL transactions cannot reverse DDL statements (CREATE TABLE etc.)

**Comment by shincoder** [comment]
@jamesgrose as @franzliedke said, it's not possible for Mysql. This is really where PostgreSQL shines.

**Comment by garygreen** [comment]
Should just use a proper staging server and test your database changes against a mirror copy of the existing database.

**Comment by taylorotwell** [comment]
Probably will not be included in core.
