### ISSUE TITLE
Eloquent Group By Relation

### ISSUE THREAD

**Issue by gaselec** [laravel/internals#10]
Hi,

I'm not too sure how to go about reporting an issue/bug even if it is.

////Model
public function leads()
    {
    	return $this->hasMany('App\Models\Lead', 'trackingId');
    }

////Controller
public function pageUsers($pageId){
        return view('admin.lists.pageUsers', [
                        'trackings' => Tracking::where('pageId', "=", $pageId)->groupBy('trackingId')->get()
        ]);
}

////View
@foreach($trackings as $tracking)
     <tr>
          <td>{{ $tracking->id }}</td>
          <td>
               @foreach($tracking->leads as $lead)
                    {{ $lead->firstName }}   <--- Nothing displays
               @endforeach
               {{ count($tracking->leads) }}   <--- Displays 0
               {{ $tracking->trackingId }}
          </td>
          <td>{{ $tracking->referer }}</td>
          <td>{{ $tracking->created_at }}</td>
     </tr>
@endforeach

**Comment by jlaswell** [comment]
Please wrap your code examples in [backticks](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) when posting.

This repo is for discussing modifying existing behaviors and feature additions in Laravel core. You can get help with this by hitting up [Laravel Slack](http://larachat.co/) or maybe posting to the [Larachat forums](https://laracasts.com/discuss). Worst case, feel free to drop me an email and I'll see if I can help too. ;)

I would suggest closing this issue.
