### ISSUE TITLE
FileSystem methods `put` and `append` fail if path doesn't exist

### ISSUE THREAD

**Issue by mtantawy** [laravel/internals#100]
This is my first contribution to Laravel which is not a bug but a little improvement that if approved in concept i will create the PR for it.

I got a Laravel app from a friend which was lacking some directories inside /storage, this caused Laravel to not be able to place compiled blade views correctly so the app failed, hinting at a permissions issue which was not the case.

After checking, i found that both methods `put` (the one actually causing the issue) and `append` do not first try to create the directories hierarchy if not found.

I am putting this first for discussion as some might argue that making `put` and `append` methods create the directories first is not a good practice as this is not their "purpose/responsibility", however, my argument is the simplicity and smoothness that comes with this change is worth it.

So, what do you think?!
Does anyone have a better solution?

**Comment by vlakoff** [comment]
I think it's fine as it is, better keep the concerns separated. Also, it may be helpful to detect erroneous paths.

You can easily create directories "on the fly" if needed, using one the relevant functions with the "recursive" flag.

**Comment by mtantawy** [comment]
![FileSystem error message](https://cloud.githubusercontent.com/assets/244932/15630225/0fee3f9a-2539-11e6-9611-deb37b49df80.png)

Do you see the problem now?

The error is not descriptive at all, i realize this is PHP's error message but it has many issues:

- It is indicating an incorrect path, so even if i will manually recursively-create the missing directories-hierarchy, i won't know where i should do that or what is missing.
- "failed to open stream" is kinda vague, it doesn't say that the path was not found, which leaves the user focusing on "Permission denied", and this is where most users will invest time and effort and most probably will even do chmod 777 on the whole laravel app, and still won't work.

**Comment by vlakoff** [comment]
I agree this is a very bad error message. And you have well summarized its cons.

On the other hand, I think it is better, as a general rule, to not complicate the codebase if the only benefit is friendlier error messages, especially for errors that are supposed to happen only during developement.

**Comment by mtantawy** [comment]
I don't 100% agree but let's try to think of another solution.

How about doing the path-checking logic in the Blade Compiler?

I don't like that solution as this way one will have to repeat the path-checking logic everywhere before calling `put` or `append` but let me know what you think of that.

Otherwise i'll close the issue, am out of ideas :smile:

**Comment by mtantawy** [comment]
Anyone?!

**Comment by vlakoff** [comment]
The `storage/framework/views` directory is not supposed to be missing. The `.gitignore` file inside it should prevent it from being accidentally deleted in most situations.

I think it's fine as it is. As I said above, better not complicate the code for this.
