### ISSUE TITLE
[Proposal] Add SFTP filesystem driver out of the box

### ISSUE THREAD

**Issue by jackmu95** [laravel/internals#1002]
In a current project we need to connect to a SFTP server on the fly (with dynamic username/password).
Laravel currently only has a FTP driver out of the box.

I know thats its quit easy to add a new storage driver as [described in the docs](https://laravel.com/docs/5.6/filesystem#custom-filesystems) but the `FilesystemManager` is then still missing the method to create the driver on the fly.

I do also know that its possible to solve that by extending the `FilesystemManager` and `FilesystemServiceProvider` but IMHO Laravel should ship with SFTP support out of the box.

**Comment by tomschlick** [comment]
https://flysystem.thephpleague.com/adapter/sftp/ this adds the adapter to flysystem.

I disagree it should be in core. 99% of apps don't interact with SFTP in any way.

**Comment by jackmu95** [comment]
The question is how many do with FTP.
I just expected that when FTP is supported, SFTP is too. Because they are kinda similar.

**Comment by mfn** [comment]
> Because they are kinda similar

Only by their name. Technically they're two different worlds.

I'm with @tomschlick on this matter.

**Comment by jackmu95** [comment]
Closed by https://github.com/laravel/framework/pull/23308.
