### ISSUE TITLE
[4.2] Eloquent model setConnection does not persist

### ISSUE THREAD

**Issue by kapitanluffy** [laravel/internals#101]
Setting a model's connection by using setConnection() is almost useless because most methods create a new static instance

see https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Eloquent/Model.php#L652

``` php
$model = new MyModel;
$model->setConnection('another_connection');
$model->find(1);
$model->find(2);
```

solved it by 
- manually setting the $connection property
- using setConnectionResolver()
- using on() on every query

This is just my two cents. The method is kind of misleading. I assumed that setConnection() will "set the connection"  to use. I stumbled upon this while trying to dynamically set the connection on a service provider.

**Comment by kdbcinco** [comment]
When I see `$model->setConnection('another_connection')`, I read it as "I'm setting this model's connection to `another_connection`".

And remember you are calling `find()` from an instance, so the static `find()` from `Eloquent\Model` is not called. It instead triggers `__call()` and the actual `find()` you are calling is `Eloquent\Builder`'s.

**Comment by kapitanluffy** [comment]
@kdbcinco yeah, that's how I read it too, "I'm setting this model's connection to `another_connection`". So I expect that when I query something (after setting the connection) I will use `another_connection.

And now that you mention it uses `Builder`'s method, `find()` seems useless. Though when I checked what method it does use, an instance seems to use the model's static `find()`. I tested it by simply dying (`die()`) inside Model's `find()` method

```php
// does not work, uses the Model's static find
try {
    MyModel::on('another_connection');
    $myModel = MyModel::find($id);
    echo "test 1 good<br>\n";
} catch(\Exception $e) {
    echo "test 1 fail<br>\n";
}

// works but uses Builder's find()
try {
    $myModel = MyModel::on('another_connection')->find($id);
    echo "test 2 good<br>\n";
} catch(\Exception $e) {
    echo "test 2 fail<br>\n";
}

// does not work, uses the Model's static find
try {
    $myModel = MyModel::find($id);
    echo "test 3 good<br>\n";
} catch(\Exception $e) {
    echo "test 3 fail<br>\n";
}

// does not work, uses Model's static find
try {
    $myModel = new MyModel;
    $myModel->setConnection('another_connection');
    $myModel = $myModel->find($id);
    echo "test 4 good<br>\n";
} catch(\Exception $e) {
    echo "test 4 fail<br>\n";
}

// does not work, uses Model's static find
try {
    $myModel = new MyModel;
    $myModel = $myModel->setConnection('another_connection')->find($id);
    echo "test 5 good<br>\n";
} catch(\Exception $e) {
    echo "test 5 fail<br>\n";
}

// works but uses Builder's find()
try {
    $myModel = new MyModel;
    $myModel = $myModel->setConnection('another_connection')->newQuery()->find($id);
    echo "test 6 good";
} catch(\Exception $e) {
    echo "test 6 fail";
}
```

As how I understood the method, setting the `instance`'s connection to `another_connection` then using the `instance`'s `find()` should use the `instance`'s connection.

Static methods called in the model should use `Builder`'s methods instead or just proxy everything to `Builder` instead of having a `find()` method.
