### ISSUE TITLE
[Proposal] Collections to have skip method

### ISSUE THREAD

**Issue by alexbowers** [laravel/internals#1017]
Currently, ordinary collections do not have a way to skip, in the same way that a query does.

You can `take(10)` but not `skip(20)` for example.

Is there a reason for this omission, or is it something that should be PR'd

**Comment by alexbowers** [comment]
Ah, its called slice. I was looking for skip. Okay cool, thanks :)

**Comment by alberto-bottarini** [comment]
Close please :)
