### ISSUE TITLE
Allow modifying model properties inside a scope

### ISSUE THREAD

**Issue by aleemb** [laravel/internals#1019]
```
public function scopeFoo($builder) {
    $this->setAppends(['foo', 'bar']);
    return $builder;
}
```

The above snippet doesn't work but it would be very useful if it did, allowing users to have more fine-grained control over the `$appends` or any other property, say for the purpose of dynamic data-serialisation or anything else.

**Comment by alberto-bottarini** [comment]
Scopes are intended to be a sort of "aliases" to improve query builder.
I don't think they are the best place to modifying properties.

**Comment by aleemb** [comment]
Makes sense, not sure why this made sense at the time. Probably borne out of frustration in #1018
