### ISSUE TITLE
[Proposal] Document migration transactions on laravel docs

### ISSUE THREAD

**Issue by maguilar92** [laravel/internals#1023]
I found that laravel Illuminate\Database\Migrations\Migration has the ability to run transactions in migrations but is not documented on laravel docs [https://laravel.com/docs/migrations](https://laravel.com/docs/migrations)

**Comment by sisve** [comment]
This sounds like something that doesn't need a discussion in laravel/internals, but just a PR to laravel/docs.

**Comment by maguilar92** [comment]
Oks, sorry y will commit in laravel/docs.
