### ISSUE TITLE
Resource routing in SPA/API scenario

### ISSUE THREAD

**Issue by daviestar** [laravel/internals#104]
My favourite feature of Laravel is the resource routes, and resource controller generators as I mainly use Laravel for rapidly developing a simple server-side API to a frontend SPA.

Using:
```php
Route::group(['prefix' => 'api', 'middleware' => 'api'], function() {
    Route::resource('trip', 'TripController');
});
```
Generates the following:
```
api/trip                                   | api.trip.index
api/trip                                   | api.trip.store
api/trip/create                            | api.trip.create
api/trip/{trip}                            | api.trip.update
api/trip/{trip}                            | api.trip.show
api/trip/{trip}                            | api.trip.destroy
api/trip/{trip}/edit                       | api.trip.edit
```
In the SPA scenario, this makes it hard to **separate concerns of your router and AJAX library**, as multiple routes have the same address, but different AJAX methods.

If I try to map these routes in JS, I end up with something like:
```javascript
// SPA routes
router.on({
  '/trip/create': {as: 'trip.create', uses: trip.create},
  '/trip/:tripId/edit': {as: 'trip.edit', uses: trip.edit},
  '/trip/:tripId': {as: 'trip.show', uses: trip.show},
  '/trip': {as: 'trip.index', uses: trip.index}
});

// Laravel routes
router.private({
  '/api/trip/:tripId': {as: 'api.trip.update'},
  '/api/trip/:tripId': {as: 'api.trip.destroy'},
  '/api/trip/:tripId': {as: 'api.trip.show'},
  '/api/trip': {as: 'api.trip.store'}
});

...

destroy({tripId}) {
  api('delete', router.generate('api.trip.destroy', {tripId}), response => {
    //
  });
}

...

destroyButton.onClick(destroy);
```
And as you can see, I run into problems as `update`, `destroy` and `show` have the same address, so I'll have to come up with a solution which includes the AJAX method, which I would ideally keep separate.

I propose slightly more descriptive routes:
```
api/trip                                   | api.trip.index
api/trip/store                             | api.trip.store
api/trip/create                            | api.trip.create
api/trip/{trip}/update                     | api.trip.update
api/trip/{trip}                            | api.trip.show
api/trip/{trip}/destroy                    | api.trip.destroy
api/trip/{trip}/edit                       | api.trip.edit
```
Thanks

**Comment by franzliedke** [comment]
Routes are not just paths - they consist of HTTP method (GET, POST, PUT, DELETE...) and paths, and that is important. Please read up on REST and [the different meanings of HTTP methods](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html). :)

**Comment by daviestar** [comment]
Yeah, I looked for a definitive standard for RESTful routes and couldn't find anything (could be wrong).  

Rails uses `new` instead of `create`.
http://guides.rubyonrails.org/routing.html

Seems like an intuitive 'flavor' which would be beneficial in Frontend Land?

**Comment by daviestar** [comment]
Forget this, finding it hard to agree with myself....!
