### ISSUE TITLE
[Proposal] Keep parameters when generating URL

### ISSUE THREAD

**Issue by henk23** [laravel/internals#1048]
Assuming I have a route defined like this
```
Route::get('/{arg1}/{arg2}', 'FooController@index')->name('foo');
```
and I am currently on page `/foo/bar`. When I generate a route on that page like
```
{{ route('foo', ['arg2' => 'newarg']) }}
```
I am currently getting the error "Cannot create URL, because arg1 is missing".

Why not change this behavior to: Since arg1 is already in the URL, leave it untouched and navigate to `/foo/newarg`?

Has this been considered before? Are there possibly some unwanted side effect?

I think especially with long URLs with a lot of parameters, this could lead to much cleaner code in the templates.

**Comment by sisve** [comment]
This is already supported. A common scenario is a middleware that handles routes with a locale segment (`/{locale}/slug`), and provide a default locale parameter for url generation.

    public function handle($request, $next) {
        // TODO: App::setLocale and stuff

        URL::defaults(array(
            'locale' => $request->route('locale')
        ));

        return $next($request);
    }

**Comment by henk23** [comment]
Thank you! After hours of googling and after opening this ticket, I actually found it in the docs: https://laravel.com/docs/5.6/urls#default-values 🎉
