### ISSUE TITLE
Add an Eloquent model `orderBy` property

### ISSUE THREAD

**Issue by sebastiandedeyne** [laravel/internals#106]
The `protected $orderBy` property would add an `orderBy` clause to all queries made through an Eloquent model, similar to the `with` property.

```php
class NewsItem extends Model
{
    protected $orderBy = 'publish_date';
}
```

```php
NewsItem::all() // => All news items ordered by publish date
```

`orderBy` can be a string, or an array if you want to specify the sort order.

```php
protected $orderBy = ['publish_date', 'desc'];
```

Alternative idea: specify the sort order after a colon:

```php
protected $orderBy = 'publish_date:desc';
```

Is this worth it? Or would it be considered cruft since it's also possible with global scopes?

If there's any interest in this I'd be willing to write a PR this weekend or next week!

**Comment by JosephSilber** [comment]
You can do this with a global scope:

```php
class Post extends Eloquent
{
    static public function boot()
    {
        parent::boot();

        static::addGlobalScope(function ($query) {
                $query->orderBy('publish_date', 'desc');
        });
    }
}
```
