### ISSUE TITLE
Discussion of Illuminate\Database\Eloquent\Model code length (~3000 lines)

### ISSUE THREAD

**Issue by lukepolo** [laravel/internals#108]
This is more of just a general programming question, but how do we make this file more manageable. 

What would be the best way to solve this ? Is it a problem ?

My thoughts immediately thought about traits to make it more organized into logical sections. 

Thoughts?

**Comment by lukepolo** [comment]
Also the reason why this coming is up is I manage a package for laravel : LaraCart. 

And want to make this file a bit more managable, as I still want to make it easy on the end user to just use the facade : 
https://github.com/lukepolo/laracart/blob/master/src/LaraCart.php

**Comment by KKSzymanowski** [comment]
Many people think that Laravel biggest performance issue lies in loading so many files.
Extracting functionality into traits may be a good idea regarding code managability(is that a word?) but it can have an impact on performance(or maybe not, prove me wrong) if we apply it to all these god objects(Container, Eloquent/Builder, Query/Builder, Validator).

Nevertheless this is something worth considering in my opinion.
