### ISSUE TITLE
Collection sortBy() on multiple fields

### ISSUE THREAD

**Issue by wmather** [laravel/internals#11]
I commonly find that there is no shorthand way of sorting collections by multiple fields. A large amount of extra code is required just by adding in an extra field. What I really want to do is this:

```
$collection->sortBy(['Surname', 'Forename']);
```

Instead you need to pass a callback concatenating all of the fields you want:

```
$collection->sortBy(function($item) {
  return $item->Surname.'-'.$item->Forename;
});
```

You have to do something similar if you want to `groupBy()` on multiple fields.

There have been several SO questions on the topic, but there's never been a clean solution
- http://stackoverflow.com/questions/25451019/what-is-the-syntax-for-sorting-an-eloquent-collection-by-multiple-columns
- http://stackoverflow.com/questions/33713392/how-to-sort-illuminate-collection-by-multiple-columns-in-laravel-5-1

**Comment by themsaid** [comment]
You may call multiple `sortBy()` just like the query builder:

```
$collection->sortBy('Surname')->sortBy('Forename');
```

**Comment by lbogdan** [comment]
@themsaid Not really, that ends up sorting by Forename alone.

From the 1st SO link:

> Intuitively, I initially tried to use the same syntax as orderBy.
> `sortBy('column1')->sortBy('column2')`
> but this apparently just applies the sorts sequentially and it ends up sorted by column2, disregarding column1.

**Comment by wmather** [comment]
@themsaid Unfortunately as above, that would sort by Surname then re-sort by Forename, unlike the query builder where chaining `orderBy()` creates a SQL query with a delimited list of order by fields.

Where that type of syntax would be good is to allow you to do different directions for different fields:

    $collection->sortBy('Forename')->sortByDesc('Surname');

However I don't see how this way could be implemented as each method only knows of it's own existence and returns a new collection.

**Comment by themsaid** [comment]
@lbogdan @wmather you are right, chaining won't make it work as expected. I think I can come up with a PR to suggest this feature for `sortBy` and `groupBy`.

**Comment by JayBizzle** [comment]
@themsaid did you get anywhere with this?

**Comment by MaxGiting** [comment]
This would be really useful any movement on this  @themsaid  ?

**Comment by KDCinfo** [comment]
Would love this as well. I had to conjure a ->sort() to do 2 columns that included eager loads. Now I have to do another ->sort() for 2 columns without eager loads (both supporting ASC and DESC for the first column, and just ASC for the 2nd column). 

The downside was, I couldn't figure out how to get ->sort() to support the SORT_STRING | SORT_FLAG_CASE parameters like the sortBy() and sortByDesc() functions do. So my 2nd column string sorts are a bit wacky when sorting lowercase vs. uppercase and strings beginning with numbers (i.e., 300 comes before 1408).

**Comment by DaveYoungV9** [comment]
How about something like: $collection->sortBy([ ['col1', 'asc'], ['col2', 'desc'] ])?

**Comment by yyc1217** [comment]
Maybe as a sorter?

```php
$collection->sortBySorter(function($sorter) {
    return $sorter

        ->sortBy('field1')
        ->sortBy('field1', SORT_NATURAL, 'asc')

        ->sortBy('field2', 'desc')
        ->sortByDesc('field2')

        ->sortBy(function($data) {
            return $data->field3;
        });
});
```
We can create codes which every digits represent different order index under each sort condition, then sort these codes in natural order.

**Comment by nickreynke** [comment]
Any updates on this?

**Comment by damiani** [comment]
My understanding is that chaining `sortBy()` and `sortByDesc()` _does_ end up sorting by multiple criteria, but that the clauses need to appear in reverse order from what is intuitive. So, to sort by `surname` first, and then `forename` second, this arrangement would yield the expected result:

```php 
$collection->sortBy('forename')->sortBy('surname');
```

i.e., in order to **_sort first by `a`, then `b`, then `c`_**, the correct clause would be 

```php
sortBy('c')->sortBy('b')->sortBy('a')
```

At least, this seems to work correctly in my testing. It makes sense, if you think about it, but is definitely counterintuitive. `orderBy` operates the same way, I believe.

**Comment by jrmadsen67** [comment]
@damiani - that's completely correct.

spinning up a little blog post to see if I can show & explain the different possibililties

**Comment by sisve** [comment]
That reverse sortBy chain works _accidently_ and is based on undefined behavior.

The implementation uses asort/arsort, both having the following warning in the docs:

> If two members compare as equal, their relative order in the sorted array is undefined.

Source: https://secure.php.net/manual/en/function.asort.php
Source: https://secure.php.net/manual/en/function.arsort.php

**Comment by damiani** [comment]
Wow, good to know @sisve ! 

I wonder if this is an issue in practice, and if so, under what circumstances `arsort` dumps the default order.

I also got to learn what the _Burrows-Wheeler transform_ is 😀
https://en.wikipedia.org/wiki/Burrows%E2%80%93Wheeler_transform

**Comment by jrmadsen67** [comment]
@sisve - I've always taken this to mean "yes, it should work the way you think, but we don't explicitly return it that way so you have the possibility of anomalies & we don't guarantee your result"

Do you know if anyone has ever studied result sets to see how often those anomalies occur? aka, What's the reliability level of doing it this way?

Personally I would only ever use this for non-critical tasks like displaying to page, but curious to know more

**Comment by damiani** [comment]
Turns out, it's pretty easy to get unpredictable results; running `asort` on 

```
['b', 'a', 'a']
```

will swap the order of the `a`s, while sorting 

```
['a', 'b', 'a']
```

will maintain them. The same unpredictability, of course, is true for `sortBy()`, meaning the reverse `sortBy()` chain will sometimes work, sometimes not. 

I've opened PR https://github.com/laravel/framework/pull/21214 to fix this behavior in `sortBy()`, so that it performs a stable sort, which should allow the collection multi-sort to work correctly every time.

**Comment by thunberg** [comment]
Looks like this was reverted, what's the current status?

**Comment by mvatansever** [comment]
Is it possible to do another sortBy() function? Like sortByMultiple() or sortByMany() or whatever because of it's very useful with an array.

**Comment by snapey** [comment]
Having just applied encryption to all user fields, I now find I need to sort the collection where previously I was able to easily orderBy on the sql query.  Being able to sort by multiple fields would have been useful.

**Comment by imbrish** [comment]
Totally agreed that some kind of multi-sort method would be a very useful functionality. I never had time to think it through and submit a PR and so I just wrote [this quick helper function instead](https://gist.github.com/imbrish/05e27a28dfc713a373044d7fd7807805).

I use it to this day so it may not be so bad after all :) Feel free to borrow and build on top of it. You can register macros on `Illuminate\Support\Collection` to integrate it directly into collections.

The helper also (or actually first of all) supports locale aware sorting.

**Comment by eithed** [comment]
`sortBy` on multiple fields can be emulated by simply creating hash of what you're sorting by, ie: `sortBy('name')->sortBy('surname')` becomes `sortBy(function($item){ return $item->name.'#'.$item->surname; });`

The more problematic is the assumption that it works by default. From working with it on 5.5.39 I can say that chaining of sort doesn't seem to work and I'm forced to use above mentioned.

**Comment by hackel** [comment]
This bug is still present in Laravel 5.5.  It seems that it was fixed, twice, and reverted, twice.  ([#21382](https://github.com/laravel/framework/pull/21382))  What's going on?  Is there any plan to fix this in the LTS release?  I've spent several hours debugging this issue before I finally landed here and started down the rabbit hole.  What is keeping this fix out of Laravel 5.5?

**Comment by pfloriginale** [comment]
same problem in ordering a collection on laravel 5.1

**Comment by m8tto** [comment]
Fixed mine by returning array in custom sorting.
Hope that it will help someone.

```php
$products->sortBy(function($product) {
            $param1 = $product->param1;
            $param2 = $product->param2;
	    ...some custom sort logic...
            return [$sum, $param2];
 });
```

**Comment by anantaramdas** [comment]
@m8tto Could you please bring some details in "some custom sort logic". It will be helpful for me :)

**Comment by m8tto** [comment]
@anantaramdas 
We currently have "param1" as a string in our database, and we need some complex sorting based on it.
It's not the best way, and we will change it for sure, but now that `$sum` variable presents some integer based on which we sort. But we also need that list sorted by "param2" field. 

So for 2 plain fields, this sorting should look something like this 
(should test though):
```php
$products->sortBy(function($product) {
            return [$product->param1, $product->param2];
 });
```
This will sort a collection by param2 first, and then by param1

**Comment by casbloem** [comment]
you cant sort 2 thinks at the same time. it makes no sense.
You can first sort on A and then B ofc.

**Comment by hkcoyant** [comment]
When run big querys, and ORDER BY in mysql cause problems, i apply this solution in php:
Query example:
```php
$result = $this->select('field1', 'field2')->where('xxx', 1)->get();
```

When i need sort for one field:
```php
$result = $result->sortBy('field1');
$result = $result->values()->all();
return $result;
```

When i need sort for two fields:
```php
$result = $result->values()->all();
$result = QueryArraySort::orderBy($result, 'LEAD_PRINT DESC, ID_LEAD DESC');
return $result;
```

Library:
```php
<?php
namespace App\Helpers;

class QueryArraySort
{
    public static function orderBy($ary, $clause, $ascending = true) { 
        $clause = str_ireplace('order by', '', $clause); 
        $clause = preg_replace('/\s+/', ' ', $clause); 
        $keys   = explode(',', $clause); 
        $dirMap = ['desc' => 1, 'asc' => -1]; 
        $def    = $ascending ? -1 : 1; 

        $keyAry = []; 
        $dirAry = []; 
        foreach ($keys as $key) { 
            $key      = explode(' ', trim($key)); 
            $keyAry[] = trim($key[0]); 
            
            if (isset($key[1])) { 
                $dir      = strtolower(trim($key[1])); 
                $dirAry[] = $dirMap[$dir] ? $dirMap[$dir] : $def; 
            
            } else { 
                $dirAry[] = $def; 
            } 
        } 

        $fnBody = ''; 
        for ($i = count($keyAry) - 1; $i >= 0; $i--) { 
            $k    = $keyAry[$i]; 
            $t    = $dirAry[$i]; 
            $f    = -1 * $t; 
            $aStr = '$a[\''.$k.'\']'; 
            $bStr = '$b[\''.$k.'\']'; 

            if (strpos($k, '(') !== false) { 
                $aStr = '$a->'.$k; 
                $bStr = '$b->'.$k; 
            } 

            if ($fnBody == '') { 
                $fnBody .= "if({$aStr} == {$bStr}) { return 0; }\n"; 
                $fnBody .= "return ({$aStr} < {$bStr}) ? {$t} : {$f};\n";                
            } else { 
                $fnBody = "if({$aStr} == {$bStr}) {\n" . $fnBody; 
                $fnBody .= "}\n"; 
                $fnBody .= "return ({$aStr} < {$bStr}) ? {$t} : {$f};\n"; 
            } 
        } 

        if ($fnBody) { 
            $sortFn = create_function('$a,$b', $fnBody); 
            usort($ary, $sortFn);        
        }

        return $ary; 
    } 
}

```

**Comment by oluomotoso** [comment]
> @anantaramdas
> We currently have "param1" as a string in our database, and we need some complex sorting based on it.
> It's not the best way, and we will change it for sure, but now that `$sum` variable presents some integer based on which we sort. But we also need that list sorted by "param2" field.
> 
> So for 2 plain fields, this sorting should look something like this
> (should test though):
> 
> ```
> $products->sortBy(function($product) {
>             return [$product->param1, $product->param2];
>  });
> ```
> 
> This will sort a collection by param2 first, and then by param1

This is the best. Fixed the issue like a magic

**Comment by lflucasferreira** [comment]
This issue is still occurring. 

I did @anantaramdas solution but it didn't fix. 

sortBy() should be more smart.

**Comment by federf** [comment]
I´ve found the following answer on stackoverflow
https://stackoverflow.com/a/33304416

Using that answer I've created the next function and works perfectly.
$array is an associative array
$paramCriteria is an associative array like 
['index1'=>'asc', 'index2'=>'desc', ...]
```php
public static function sortBy($array, $paramCriteria)
{
    $makeComparer = function ($criteria) {
        $comparer = function ($first, $second) use ($criteria) {
            foreach ($criteria as $key => $orderType) {
                // normalize sort direction
                $orderType = strtolower($orderType);
                if ($first[$key] < $second[$key]) {
                    return $orderType === "asc" ? -1 : 1;
                } else if ($first[$key] > $second[$key]) {
                    return $orderType === "asc" ? 1 : -1;
                }
            }
            // all elements were equal
            return 0;
        };
        return $comparer;
    };
    $comparer = $makeComparer($paramCriteria);
    usort($array, $comparer);
    return $array;
}
```

**Comment by iraklisg** [comment]
An alternative solution for those who want to sort a collection by multiple keys is using the `Collection::sort()` with a callback., as described [here](https://stackoverflow.com/a/33713443/2235814)

**Comment by JustinLawrenceMS** [comment]
Here's a couple of quick and dirty fixes, and they are far from perfect but easy to implement.  1. If you are sorting each of your multiple fields by ASC, creating an index field and concatenate your multiple fields into that.  Then you only have one field to sort by.

For example: 

$must_sort = array('make' => 'Jeep', 'model' => 'Cherokee', 'year' => 2006, 'plates' => 'Yeehaw6');
$index = $must_sort['make'].$must_sort['model'].$must_sort['year'];
$will_sort_this_now = array('make' => 'Jeep', 'model' => 'Cherokee', 'year' => 2006, 'plates' => 'Yeehaw6', 'index' => $index);

You might have doctor it by padding with zeroes, rearranging columns, etc.  But it's an easy fix.

The other thing you do, if you are retrieving your collect from SQL, is to let SQL sort for you.  

For example.

use DB;
use App\IAmAModel;

DB::statement("create table imgoingtodeletethislater like thisisthetableIwanttosort");
DB::statement("insert into imgoingtodeletethislater select * from thisisthetableIwanttosort");
DB::statement("truncate thisisthetableiwanttosort");
DB::statement("insert into thisisthetableiwanttosort select * from imgoingtodeletethislate order by 1,2,3 desc, 4");
DB::statement("drop table imgoingtodeletethislater");

$sorted_table = IAmAModel::get();

**Comment by spotwilliams** [comment]
Maybe an approach could be combine groupBy, map, sort and flatten to reach a "multi fileds sort" with Collections.:
```
$collection
    ->groupBy('Surname') // first level of sorting
    ->sortKeysDesc() // first level of sorting
    ->map(function (Collection $collection) { // sort the grouped collections
        return $collection->sortBy('Forename);
    })
    ->flatten(); // return to a one dimension collection
```

**Comment by rumus007** [comment]
`$collection->sort(function ($a, $b) {
                return $a->Surname === $b->Surname ? $a->Forename <=> $b->Forename : $a->Surname <=> $b->Surname;
            });`

**Comment by mantico91** [comment]
> If you wan to sort by two fields you can use the spaceship operatio <=>
> `$collection->sort(function ($a, $b) { return $a->Surname === $b->Surname ? $a->Forename <=> $b->Forename : $a->Surname <=> $b->Surname; });`
> 
> if you want to sort by multiple fileds then you can use
> `$collection->sort( function ($a, $b) { // sort by column1 first, then 2, and so on return strcmp($a->column1, $b->column1) ?: strcmp($a->column2, $b->column2) ?: strcmp($a->column3, $b->column3); } );`

Perfect! Absolutely working and fast.

**Comment by MarcosBL** [comment]
Just for the poor guy reading all the thread, for now we have two main solutions that actually works.

To sort, for example:
- First by a boolean (0/1) Inactive, with 0 first, so **inactive ASC**
- then by **filesize DESC** (note the prepending minus in both code samples)
- then by **filename ASC**

First solution:

```php
$sorted = $files->sort( function ($a, $b) {
    return
        strcmp($a->inactive, $b->inactive) ?:
        - strcmp($a->filesize, $b->filesize) ?:
        strcmp($a->filename, $b->filename);
});
```
Second solution (my preferred because of legibility):

```php
$sorted = $files->sortBy( function($file) {
    return [
        $file->inactive,
        - $file->filesize,
        $file->filename
    ];
});
```

**Comment by amirasyraf** [comment]
@MarcosBL Thank you. I was about halfway scrolling this thread when the browser gave me a notification on the tab about you reply.

**Comment by musapinar** [comment]
@MarcosBL You cannot prepend strings with minus. If you want to sort first column (string) by ASC, but second colum by DESC (still string), you cannot. Your solution is OK as long as all strings are ASC. One won't be able to mix ASCs and DESCs for strings. It's either ASC or DESC.

**Comment by PEscar** [comment]
> @MarcosBL You cannot prepend strings with minus. If you want to sort first column (string) by ASC, but second colum by DESC (still string), you cannot. Your solution is OK as long as all strings are ASC. One won't be able to mix ASCs and DESCs for strings. It's either ASC or DESC.

I think you are right. Not working for me, when trying to order by three columns, first boolean and others two strings.

**Comment by maganius** [comment]
How I can sort this collection?

```PHP
$array = [
    ['name' => 'String 2' => array('tags' => array(array('name' => 'Tag 2'), array('name' => 'Tag 3')))], 
    ['name' => 'String 1' => array('tags' => array(array('name' => 'Tag 8'), array('name' => 'Tag 7')))]
];
```
I need this result
```
String 1
   |- Tag 1
   |- Tag 2

String 2
   |- Tag 7
   |- Tag 8
```

I tried with this without luck

```PHP 
$Ordenes->limit(20)->get()->sortBy('Empresa.nombre')->sortBy('Empresa.tags.name');
```

I can't sort it with sql because I use `cviebrock/eloquent-taggable` it doesn't have a directly relation.

**Comment by JustinLawrenceMS** [comment]
I've been satisfied with PHP's array_multisort();

**Comment by sdwru** [comment]
> @anantaramdas
> We currently have "param1" as a string in our database, and we need some complex sorting based on it.
> It's not the best way, and we will change it for sure, but now that `$sum` variable presents some integer based on which we sort. But we also need that list sorted by "param2" field.
> 
> So for 2 plain fields, this sorting should look something like this
> (should test though):
> 
> ```
> $products->sortBy(function($product) {
>             return [$product->param1, $product->param2];
>  });
> ```
> 
> This will sort a collection by param2 first, and then by param1

This seems to work.  Thanks!

**Comment by sietzekeuning** [comment]
With the new short function it looks even better:
`$builder->sortBy(fn ($item) => [$item->param1, $item->param2]);
`

**Comment by danabrey** [comment]
@sdwru @sietzekeuning Is there a way to use 'asc' for one property but 'desc' for another using this closure method?

**Comment by sietzekeuning** [comment]
Well that is possible, but then you will need to do something like:
`$products->sortBy(function($a, $b) {
    if($a->param1 != $b->param1) { 
        return $a->param1 > $b->param1 ? 1 : -1;
    }
    return $a->param2 > $b->param2 ? -1 : 1;
});`

**Comment by matt-allan** [comment]
@danabrey assuming you're on PHP 7+ you can pass a callback to `sort` that sorts an array of attributes using the 'spaceship' operator.

For ascending order you put the first argument on the left side of the spaceship operator and the second argument on the right side:

```php
// sort by price ASC (lowest price first)
$products->sort(fn ($a, $b) => $a->price <=> $b->price)
```

For descending order you swap sides, so the first argument is on the right side of the spaceship:

```php
$products->sort(fn ($a, $b) => $b->rating <=> $a->rating)
```

To do a compound sort you can then combine them into an array:

```php
// Sort by highest rated (rating DESC), lowest price (price ASC)
$products->sort(fn ($a, $b) => [$b->rating, $a->price] <=> [$a->rating, $b->price])
```

This works because PHP compares arrays value by value when they're the same size.

There's [a longer example in this gist](https://gist.github.com/matt-allan/4ce3ba62396c3d71241f0da39ddb88e6).

**Comment by ademirrocha** [comment]
> 
> 
> You may call multiple `sortBy()` just like the query builder:
> 
> ```
> $collection->sortBy('Surname')->sortBy('Forename');
> ```

This solved my problem. Thank you

**Comment by ademirrocha** [comment]
> 
> 
> My understanding is that chaining `sortBy()` and `sortByDesc()` _does_ end up sorting by multiple criteria, but that the clauses need to appear in reverse order from what is intuitive. So, to sort by `surname` first, and then `forename` second, this arrangement would yield the expected result:
> 
> ```
> $collection->sortBy('forename')->sortBy('surname');
> ```
> 
> i.e., in order to **_sort first by `a`, then `b`, then `c`_**, the correct clause would be
> 
> ```
> sortBy('c')->sortBy('b')->sortBy('a')
> ```
> 
> At least, this seems to work correctly in my testing. It makes sense, if you think about it, but is definitely counterintuitive. `orderBy` operates the same way, I believe.

That's what I did. I think most people here have the same problem, they just don't know how to use

**Comment by matt-allan** [comment]
Chaining `sortBy` / `sortByDesc` does not always work correctly as @sisve and @damiani pointed out earlier in the thread. I wrote [a gist demonstrating the issue](https://gist.github.com/matt-allan/6d284f8c7f7437895b423c8580fae240).

The scary thing is it _does_ work correctly sometimes. With random sample data is appears to sort correctly ~80% of the time.

**Comment by tm1000** [comment]
FYI for anyone curious this exists on Laravel 8.x+ (https://laravel.com/docs/8.x/collections#method-sortby)

> If you would like to sort your collection by multiple attributes, you may pass an array of sort operations to the `sortBy` method. Each sort operation should be an array consisting of the attribute that you wish to sort by and the direction of the desired sort:

> ```php
> $collection = collect([
>     ['name' => 'Taylor Otwell', 'age' => 34],
>     ['name' => 'Abigail Otwell', 'age' => 30],
>     ['name' => 'Taylor Otwell', 'age' => 36],
>     ['name' => 'Abigail Otwell', 'age' => 32],
> ]);
> 
> $sorted = $collection->sortBy([
>     ['name', 'asc'],
>     ['age', 'desc'],
> ]);
> 
> $sorted->values()->all();
> 
> /*
>     [
>         ['name' => 'Abigail Otwell', 'age' => 32],
>         ['name' => 'Abigail Otwell', 'age' => 30],
>         ['name' => 'Taylor Otwell', 'age' => 36],
>         ['name' => 'Taylor Otwell', 'age' => 34],
>     ]
> */
> ```
