### ISSUE TITLE
[Database] loadCount

### ISSUE THREAD

**Issue by hiendv** [laravel/internals#110]
Just want to hear your opinions on the equivalent method of `load` but `withCount` instead of `with` for `Illuminate\Database\Eloquent\Collection`. I would happily make a PR.

**Comment by leewillis77** [comment]
I'm not clear from the description - but would this cover the issues highlighted in https://github.com/laravel/framework/issues/15573 ?

**Comment by hiendv** [comment]
@leewillis77 Yes, I shared the same thought with you ;)

**Comment by telkins** [comment]
If it's not already clear, I think it would be nice to be able to request nested relationship counts, too.  That is, `loadCount('relationA.relationB')`.  This would eager load `relationA` and get `relationA`'s `relationB` count.....if that makes sense.
