### ISSUE TITLE
Filesystem class: reading only part of file

### ISSUE THREAD

**Issue by vlakoff** [laravel/internals#111]
PHP's [file_get_contents()](http://php.net/manual/en/function.file-get-contents.php) allows to do this:

```
file_get_contents('filename', null, null, <offset>, <length>);
```

This could be useful in Laravel's `Filesystem` class as well. An use case I have in mind is `FileStore` that could get the expire timestamp (first 10 bytes) without having to parse the full file (possibly tens of MBs, and memory usage basically doubles because of the `substr`).

Sadly, `Filesystem::get` already has this signature:

```
get($path, $lock = false)
```

So for ideal BC, the feature would need to be in a new method, such as:

```
getPart($path, $offset, $length, $lock = false)
```

The feature would be a bit harder to implement in "lock = true" mode, though it's still feasible. The user wouldn't have to care about this implementation detail.

Thoughts about this feature? Would it be worth it?

**Comment by PedroFTW** [comment]
I think this could be useful, I've created a Pull request for what I believe would be a solution for what you ask.

https://github.com/laravel/framework/pull/14311
