### ISSUE TITLE
Provide a pipable trait and a pipable interface

### ISSUE THREAD

**Issue by lucasmichot** [laravel/internals#112]
We might use pipes in many part of the application, and collection could be a starting point.
Why not using a Pipable interface and a Pipable trait ?

See: https://github.com/laravel/framework/compare/5.2...lucasmichot:feature/5.2/pipable?expand=1

---

Related to https://github.com/laravel/framework/pull/13899

**Comment by ntzm** [comment]
From what I've seen in the Laravel source, there is no need to create a new trait and interface for something that will only be used on one class. If this was going to apply to multiple classes, I would support it.

**Comment by lucasmichot** [comment]
@ntzm see \Illuminate\Support\Traits\Macroable

**Comment by lucasmichot** [comment]
The purpose of this issue is also to provide a trait that you can use in any Laravel class (not only Illuminate classes)
