### ISSUE TITLE
[Proposal] make:auth easier translations

### ISSUE THREAD

**Issue by dsampaolo** [laravel/internals#115]
Hi,

I'm using "php artisan make:auth" in almost all of my projects, and it saves me a lot of time. But, as a french developper, I have to re-translate the views from scratch every time.

I'm willing to implement the existing lang/trans system for the stubs used by make:auth.

I should edit the stubs located in laravel/framework/src/Illuminate/Auth/Console/stubs/make/views/auth and fill resources/lang/en/auth.php

Anyone interested by that ?

**Comment by newuni** [comment]
👍

**Comment by taylorotwell** [comment]
This has been done.
