### ISSUE TITLE
Consider V8 Support? 

### ISSUE THREAD

**Issue by TheLarkInn** [laravel/internals#119]
There are a few teams at Angular core and GDE's researching ways to leverage the angular/universal platform for "server-rendered" angular2 applications.

My stack at work is using Drupal and Laravel and Angular2+Webpack and friends. 

Has there been any discussion on the use of V8 (for node v4+) in Laravel? I know the PHP module exists, but it would feel better to have this included as a laravel core extension (if even possible). This would also open up server side rendering for any javascript apps, not just angular. Thoughts?

**Comment by NgYueHong** [comment]
Better angular support is definitely needed.

**Comment by Garbee** [comment]
You can already do server-side rendering with just Laravel and have your JS application hydrate and take over on the client-side. It isn't as streamlined as an isomorphic JS stack from backend to frontend, however it is completely possible.

IMO Laravel shouldn't need to bake Node/V8 into the core. That is adding quite a bit of complexity on top of things that are already difficult for developers to understand fully.

**Comment by Garbee** [comment]
We now have this with a chrome handler in the new Dusk package for testing. This package runs Chrome directly on the testing system without bundling any kind of V8 internally.

**Comment by TheLarkInn** [comment]
@Garbee Yup very true!! And sorry I didn't see the original reply you posted. I think being able to render a JS library on the server side is what I meant at the time. So very interesting, is this the Headless Chrome instance (replace for phantom?)

**Comment by Garbee** [comment]
Dusk is not using headless chrome. It spins up a regular Chrome instance on the host machine.

I'd love to work on integrating headless once it is available for more platforms and is in stable. Currently that is dev channel on Linux only for builds from Google, but it is getting there.

**Comment by Garbee** [comment]
Just checked and specifically it is using Facebook's [Webdriver](https://github.com/facebook/php-webdriver) under the hood.
