### ISSUE TITLE
Add pre-query run event

### ISSUE THREAD

**Issue by garretfick** [laravel/internals#120]
I would like to add comments to every query that get's generated by Laravel (e.g. the stack track) so that we can identify the origin of the queries.

To achieve this, I suggest firing an event prior to executing the query, in Connection::run that can modify the query as required.

**Comment by franzliedke** [comment]
Since queries are synchronous, you can just use [`DB::listen()`](https://laravel.com/docs/5.2/database#listening-for-query-events) to achieve this, no?

**Comment by garretfick** [comment]
Thanks franzliedke and sorry for the slow reply. I didn't seem to get any notifications.

We want to add the information as a comment in the SQL that actually gets sent so that the DB can participate in the logging, not just Laravel.
