### ISSUE TITLE
[Proposal] Echo localization values as multiline using nl2br() by default

### ISSUE THREAD

**Issue by seblavoie** [laravel/internals#121]
I often need to add line breaks to my localized texts and currently there doesn’t seem to be a concise way to achieve this. I presume this is a pretty common need. 

I would propose that the `trans()` helper and `@lang` blade directive, could use `nl2br()` by default. We’d also need to make `@lang` non-escaped. 

So basically:

```
<p>@lang('messages.welcome')</p>
```

would become

```
<p>{!! nl2br(trans('messages.welcome')) !!}</p>
```

I wanted to have your opinion about it, but if that makes sense to you I could work on a pull request.

**Comment by johlton** [comment]
+1
