### ISSUE TITLE
Scheduled tasks output to Slack..?

### ISSUE THREAD

**Issue by stokic** [laravel/internals#122]
The idea is simple, to send output of the scheduled tasks to specified Slack hook/channel, just like we have it for email.

I've already have the code ready just wanted to check if community would consider this a good idea or something stupid :)

The command would be simple in line with the current emailOutputTo ie something like this:

`$schedule->command('inspire')->daily()->sendOutputTo($filePath)->sendOutputToSlack($slackHookURL, $slackChannel);`

**Comment by adamtester** [comment]
I like the idea, but probably a config file with the slack channels and hook urls and then use
`sendOutputTo($provider)`
Then you can plug in HipChat or other hooks in.

**Comment by stokic** [comment]
That's up for the discussion, it's one of the things I haven't decided on yet and where I would like some feedback from people... 

We could make it more general of course if that's what "people" want ;)

**Comment by aa-technik** [comment]
sound very useful :+1:

**Comment by taylorotwell** [comment]
Do we have an "after" hook which could be used to send notifications to whatever service you want?

**Comment by stokic** [comment]
There is an "after" hook according to the documentation and of course it could be used but I was thinking of keeping in line with the current email notification implementation.

**Comment by fitztrev** [comment]
I proposed something similar in #7 with `->thenPost($url)` so that it could be used for other services as well.

**Comment by nticaric** [comment]
@adamtester has a good point and here's a concrete implementation for the `sendOutputTo` method.
This piece of code would allow us to entirely remove the email related methods and cleanup the code. The provider would take the responsibility of sending the output to email/slack/hipchat which is of course a better separation of concerns and gives us more flexibility like ie. changing the email title.

```php
public function sendOutputTo(SchedulingOutputProvider $provider)
{
    if (is_null($this->output) || $this->output == $this->getDefaultOutput()) {
        throw new LogicException('Must direct output to a file in order to send results to provider.');
    }
    
    $params = [
        'text'        => file_get_contents($this->output),
        'description' => $this->description
    ]
    
    return $this->then(function () use ($params) {
        $provider->send($params);
    });
}
```

The `SchedulingOutputProvider` interface declaration would only have an `send` method

**Comment by stokic** [comment]
I would support this suggestion from @nticaric, I think it's a good idea to have multiple providers available although I only need Slack :P

**Comment by lucasmichot** [comment]
@stokic Why don't you just use https://github.com/NotifyMeHQ/laravel inside  `\Illuminate\Console\Scheduling\Event::then` ?

**Comment by stokic** [comment]
I actually wrote my own Slack notifier (it's really just a couple of lines of code) for my own needs but since I saw that email notification is "baked in" I've suggested to bake in Slack too. But yes of course one could use this package.... :)

**Comment by themccallister** [comment]
Looks like this is built into Notifications now :)

**Comment by stokic** [comment]
Looks like an old developer's rule was in play: if you wait long enough, the problem will go away :D
