### ISSUE TITLE
[Request] Using docker-compose

### ISSUE THREAD

**Issue by jlaswell** [laravel/internals#128]
Laravel currently has Homestead and Valet to run local development. With containers becoming a very common practice for development and deployment workflows, I would like to add a `docker-compose.yml` file to allow for developers to get started with Laravel, nginx, and MySQL out of the box. 

We have an [example repo](https://github.com/realpage/laravel-starter) that uses our stack, but I would like to add a docker-compose file that is much more generic and defaults to MySQL instead of Postgres.

**Comment by adamtester** [comment]
I was working on one a while a go that I need to revisit, it does the web, workers and cron so you can scale it
https://github.com/adamtester/laravel-docker/blob/master/docker-compose.yml
