### ISSUE TITLE
Allow make:migration and make:model to add a Seeder

### ISSUE THREAD

**Issue by jwcobb** [laravel/internals#13]
When creating a model you can add also create a migration using using `artisan make:model Kitten -m`. I am proposing adding a `--seeder` option to additionally create a Seeder class to match that model. 

I also think you should be able to add a Seeder class when creating a migration: 
`artisan make:migration create_kittens_table --create --seeder`.

I've worked up my suggested code for these two options at 
https://github.com/laravel/framework/compare/5.2...jwcobb:make-seeder-with-model

Is this something other people want? If so, are there any comments on the suggested code?

**Comment by jlaswell** [comment]
This looks nice to me! It's late here, but if I'm not missing anything,
this looks very clean to me. I really like the ability to throw a migration
into the make command already, and I think it's only natural that a seeder
should be available as well.

**Comment by jwcobb** [comment]
Any other thoughts here?

**Comment by gocanto** [comment]
It would create the factor as well?

**Comment by jwcobb** [comment]
@gocanto I'm not sure I understand your question.

**Comment by Jeroen-G** [comment]
These: https://laravel.com/docs/master/testing#model-factories

**Comment by jwcobb** [comment]
Currently it only adds the Seeder.

**Comment by jwcobb** [comment]
I submitted this to [laravel/framework as PR 16177](https://github.com/laravel/framework/pull/16177) and the documentation to [laravel/docs PR 2790](https://github.com/laravel/docs/pull/2790).
