### ISSUE TITLE
Remove methods that do nothing from \App\Exceptions\Handler

### ISSUE THREAD

**Issue by kwebble** [laravel/internals#131]
The methods `report` and `render` in the `\App\Exceptions\Handler` only invoke the same parent method without changing the implementation.

In my opinion this is unnecessary code and can be removed.

**Comment by JosephSilber** [comment]
It's their to document its existence, and make it easier for you to add your own code should you need to.

Laravel uses this technique all over.

**Comment by kwebble** [comment]
Unfortunately the class has no documentation that describes when I should use it, a technique I have also seen a lot in Laravel code.

I think I would write one my own class if I needed a more specific `ExceptionHandler` instead of changing a generated class that is not clearly documented.

**Comment by perfectmak** [comment]
Rob, I think the docs has a pretty good explanation on how to use this.
Check here https://laravel.com/docs/5.1/errors#the-exception-handler

On Wed, Jun 29, 2016 at 1:24 PM, Rob Schlüter <notifications@github.com>
wrote:

> Unfortunately the class has no documentation that describes when I should
> use it, a technique I have also seen a lot in Laravel code.
>
> I think I would write one my own class if I needed a more specific
> ExceptionHandler instead of changing a generated class that is not
> clearly documented.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/laravel/internals/issues/131#issuecomment-229340269>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC-bjYHwJB1XZjf1H-1BoxvYVD5m6S0Eks5qQmPqgaJpZM4JA1Pw>
> .
>



-- 
Perfect Makanju

**Comment by kwebble** [comment]
@perfectmak Perhaps, but while developing my IDE shows documentation on the class not an external website. It would be nice if this actually describes the class.

**Comment by perfectmak** [comment]
Oh, I see what you mean. Okay, a documentation can be added. It would be
cool.

On Wed, Jun 29, 2016 at 2:02 PM, Rob Schlüter <notifications@github.com>
wrote:

> @perfectmak <https://github.com/perfectmak> Perhaps, but while developing
> my IDE shows documentation on the class not an external website. It would
> be nice if this actually describes the class.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/laravel/internals/issues/131#issuecomment-229348793>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC-bjc5xWq_GJRuHHtelsZPOUYxodUP9ks5qQmzggaJpZM4JA1Pw>
> .
>



-- 
Perfect Makanju
