### ISSUE TITLE
Required handle() method not declared for generated Job class

### ISSUE THREAD

**Issue by kwebble** [laravel/internals#132]
A Job class generated by this command

```
php artisan make:job SendReminderEmail
```

looks similar to this:

```
<?php
namespace App\Jobs;

use App\Jobs\Job;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;

class SendReminderEmail extends Job implements ShouldQueue {
    use InteractsWithQueue, SerializesModels;

    /** ... */
    public function __construct() {
    }

    /** ... */
    public function handle() {
    }
}
```

I expect the `handle()` method to be declared in the abstract parent `Job` class, or the `ShouldQueue` interface. But it is not defined in these places.

Perhaps something is missing here, or am I missing something in the code structure of the framework?

Otherwise this looks to me as an undocumented magic method that a `Job` must implement because ... well it just has to.

**Comment by jlaswell** [comment]
Declaring the handle method as part of the abstract parent eliminates the
ability for method injection in the concrete class. I'm in agreement that
it feels like magic, and would prefer it declared in the parent, but PHP. :)

**Comment by kwebble** [comment]
Thanks! I still have to get used to these techniques that Laravel uses to make it 'easier' for users. I prefer more explicit OOP structured code.

Here I would not mind something like a `JobHandler` required as parameter which you inject during construction or with a setter.
