### ISSUE TITLE
[Proposal] Add newInstance( $array ) method to the Illuminate\Support\Collection class

### ISSUE THREAD

**Issue by michaelshaffer37** [laravel/internals#133]
I'm suggesting this because in the `Illuminate\Support\Collection` class there are many references to `new static( $array )`.  This makes it impossible to extend this base collection class with an object that might require a slightly different constructor (ie. an Injected Dependency) and still being able to use the base methods.  By implementing a `$this->newInstance( array $array )` much like the `Illuminate\Database\Eloquent\Model` (and others) then referencing this method when a new instance is needed from a newly formed array then someone who needs to extend the class with a new constructor argument can; as long as they also implement a proper newInstance method to handle their changes.  From my perspective this makes the Collection class more SOLID focusing on the open-closed principle.

The base implementation would be as follows

``` php
public function newInstance( array $array )
{
   return new static( $array );
}
```

If this is approved I don't mind implementing it (it's quite easy).  Otherwise I'll change my approach so that my application doesn't diverge from the expected long term behavior of the framework.

Hope this is helpful for others too.

**Comment by JosephSilber** [comment]
When would you ever want to inject anything into the constructor of a collection?

**Comment by michaelshaffer37** [comment]
I certainly can't imagine all of the scenarios where someone may want to inject something into the constructor of a collection but I see the use case of an auto mutating collection being an applicable situation.

```php

protected $mutator;

// The new constructor type hinting an interface for the mutator.
public function __construct( array $array = [], Mutates $mutator )
{
   $this->mutator = $mutator;
   $this->items = $this->mutator->mutate( $array );
}

// First Example use of the mutator
public function put($key, $value)
{Thanks for getting back,
   $value = $this->mutator->mutate( $value );
   $this->offsetSet($key, $value );
   return $this;
}

// Second Use
public function push($value)
{
   $this->offsetSet(null, $this->mutator->mutate( $value ) );
   return $this;
}

// The New Method needed
public function newInstance( array $array )
{
   return new static( $array, $this->mutator );
}
```

This allows the correct type of mutator to be provided when the collection is instantiated and remain persistence even after the collection set has been reversed, shuffled, or had some other operation preformed on it.

I recognize this same outcome can be achieved through other means. I just thought that seems to be the most appropriate approach to solving the problem in the given scenario.

It also seems odd to me that it is not following the SOLID principles (Laravel does a great job of that most of the time).  This is primarily why I listed it as a proposed change and not a bug because I thought that perhaps someone actually had a good reason not to allow a collection to be extended in this kind of way.  Though I admit I don't see what that reason is at this point.

Hope this is helpful.

**Comment by JosephSilber** [comment]
This seems quite awkward to me.

It should never be the collection's job to mutate values. A collection is simply an array on steroids. Nothing more.

If you really need such functionality, you should be using a decorator.

**Comment by michaelshaffer37** [comment]
Well I guess you could do that.  It seems a bit awkward to me to have to conform to the whole interface of the `Illuminate\Support\Collection` class (which isn't actually an defined interface) when the only intention is to overwrite the behavior few methods.

As you said "array on steroids".  So if we're implementing a Item Mutating, Filtered FIFO then maybe this is exactly the approach that we want.
(That is a contrived example, I'd have concerns about it being able to operate in ways other than as a FIFO due to the existence of the other public methods)

Or perhaps we just want to provide the constructor with a type on the object like so

```php

protected $type;
 
public function __construct( array $array, $type )
{
$this->items = $array;
$this->type = $type;
}

public function getType()
{
return $this->type;
}
```

My point is that neither of these scenarios are able to be implemented by extending the base Collection class due to seemingly unnecessary limitations of the base Collection class.  I personally would like to extend the Collection class to provide a solution within our software.

If there is a good philosophical reason for not allowing extending the class in this way then I can understand but otherwise why should we unnecessarily limit what someone might do with the class?

**Comment by Garbee** [comment]
What exactly is the solution in your software solving? There might be a different way to look at using collections to solve it.

IMO, Collections are fairly generic for a reason and making it more complex is troubling. I have yet to see an instance where extending collections to solve various problems was an issue. People have been very successfully doing it for quite a while.

**Comment by michaelshaffer37** [comment]
Well maybe I should have labeled this as a Bug; as that is how I see it.  I perfectly understand that I can develop many other reasonable solutions and if the laravel community is fairly set of having calls all over the Collection class to `new static( $array )` then I have to take a different approach.

But the primary focus of my proposal was to try to resolve the fact that if one extends the Collection class and uses a different signature in the constructor the whole application fails (throwing an ErrorException: Missing argument 2 for Class) even though PHP supports child classes using different constructor signatures than their parents (as they should, IMO).  If this is perceived as a bad practice with respect to the Collection class then I'll conform my code to work with the direction the community is taking it.  But I'd then suggest that if the constructor signature of any collection is so inherent to the functionality and purposed design of the class then I see two other solutions we should either define it as `final` or create an interface the defines the signature of the constructor and have the Collection class implement that interface.

I think both of those changes have major issues with backwards compatibility, extensibility, and just general style (ugly).
Perhaps someone else could provide a better approach, or perhaps we'll just say that people will figure it out when they try to do it.

As to your point on adding complexity I personally don't see it that way it seems to me to add a level of simplicity to the class by centralizing the instantiation of new instances of a collection which is a quite common operation in the class, 30+ times.  This would also allow people to override default instantiation behavior if desired.
