### ISSUE TITLE
[Proposal] Blade Stack Improvement

### ISSUE THREAD

**Issue by fernandobandeira** [laravel/internals#134]
Let's say you have an include that display some content(product list, for example), this content will be included on many pages.

for example:

```html
<div class="product">
  <span>{{$product->name}}</span>
</div>
```

Inside this content there's javascript animations and custom css.

Now you could create 2 stacks and push your css and js to your main view, however if you include this content more than 1 time in the same page, push will add the css and js again (normal behaviour).

```php
@each('product', $products, 'product')
```

If the animation would be to turn the name red on hover, for example, you would need to add the css and js to all the views that you would include the product, however there could be a new method called: @pushOnce, that would push the content inside it just 1 time, like the  include_once behaviour.

Would this be usefull to anyone else?

**Comment by maurocasas** [comment]
This actually sounds handy! :+1:
