### ISSUE TITLE
[Proposal] Adding median and mode to collections

### ISSUE THREAD

**Issue by amonger** [laravel/internals#138]
I found in a recent project that I needed to calculate the mode in a collection. While you could use an external class, I think it fits well into the collections class as you're already providing functionality which provides an average.

https://github.com/laravel/framework/pull/14305

**Comment by Garbee** [comment]
If you're going to make a PR, then making an issue here doesn't help much. Just let the PR speak for itself. Those get attention more quickly than Internals issues anyways.
