### ISSUE TITLE
Should collection forPage()  0  return NULL ?

### ISSUE THREAD

**Issue by chungth** [laravel/internals#14]
Hi 
I tried collection [forPage()](https://laravel.com/docs/5.1/collections#method-forpage) method in Tinker
and relize the if  I get element for page 0, forPage() method will return the last elements like following image. 

<img width="505" alt="collection_for_page" src="https://cloud.githubusercontent.com/assets/2556644/13804509/f53e8e20-eb90-11e5-95b1-69636b031f15.png">

For page 1 , We get the first 3 elements from collection. 
For page 0,  We get the last 3 elements from collection. 
For page -1, We get the 2nd last 3 elements from collection.

Should we change the behavior that:
For page 0, We get nothing.
For page -1, We get the 1st  last 3 elements from collection ?

**Comment by vlakoff** [comment]
I think only positive values should be supported, as the others don't make much sense.

Also I think the ability you suggested to "paginate backwards" wouldn't be very useful, but may be source of confusion:
* not the same at taking the last page (with your example, {8,9,10} vs. {10})
* order of items: forward, backward?

On the other hand, I could suggest a method `countPages` which could be used as so:
```
$perPage = 16;

$numPages = $collection->countPages($perPage);

// first page
$collection->forPage(1, $perPage);

// last page
$collection->forPage($numPages, $perPage);
```

**Comment by chungth** [comment]
@vlakoff   For current behavior, If I call 0 to return the lastPage. I can get the last page without count the $numPages 

 ```
//last page 
$collection->forPage(0, $perPage);
```

**Comment by vlakoff** [comment]
Nope:
```
$collection = collect([1,2,3,4,5,6,7,8,9,10]);

// last page is #4 and contains [10]
$collection->forPage(4, 3);

// [8,9,10]
$collection->forPage(0, 3);
```

Also, this behavior is because internally `array_slice` is called with offset `($page - 1) * $perPage`. So with page 1 we get offset 0 which is fine, but with page <= 0 we get a negative offset and that is unsuitable.

**Comment by chungth** [comment]
@vlakoff sorry I misunderstood here. You are right. The last page is  10 . 
So I can not get the last page like that => Maybe It also makes us confused here.

**Comment by RahamSher** [comment]
Dear,@chungth I noob to laravel.Kindly guide me on collection forPage().And what its functionality.Is not it query from Model(DB).Means its load all the data atonce and gives us data on each request or something else.Kindly guide me.

**Comment by vlakoff** [comment]
![what the fuck am I reading](https://cloud.githubusercontent.com/assets/544424/14526952/fee74f08-0246-11e6-87a4-ea37e0d9fa2a.png)
