### ISSUE TITLE
Cacheless Blade templates

### ISSUE THREAD

**Issue by tillkruss** [laravel/internals#142]
Currently Blade templates **require** a path on the local filesystem for caching. See: https://github.com/laravel/framework/pull/14291

It would great if Blade templates could be compiled in-memory from any string, without ever touching the filesystem. Furthermore it would be nice if a driver/store for Blade template could be configured, similar to the `session.driver` configuration. That way Blade caches could live in Redis, APC, Memcache, a SQL database, the local file system or just in-memory.

``` php
["file", "array", "redis", "apc", "memcached", "database"]
```

I'd be happy to provide a PR.

**Comment by franzliedke** [comment]
I don't think that's a great idea. Blade templates are not only *cached*, they are written to a file to be executable. The alternative would be `eval` and, I suppose, horrible performance.

**Comment by garygreen** [comment]
Doesn't opcode cache put the files in memory anyway? Seems unnecessary.
