### ISSUE TITLE
Conditionally Adding Rules for array validation, support index

### ISSUE THREAD

**Issue by rlems** [laravel/internals#144]
I've been through the docs at https://laravel.com/docs/5.2/validation#conditionally-adding-rules
Through this feature you can add complex validation like so:

```
$v->sometimes('reason', 'required|max:500', function($input) {
    return $input->games >= 100;
});
```

But this doesn't take into account array validation, let me give an example in code of what i mean:

```
$v->sometimes('reasons.*.reason', 'required|max:500', function($input) {
    // how could I add a condition for a field in reasons.*?
    // I can't do something like this:
    return $input->reasons['*']->games >= 100;
});
```

I would like to be able to at a condition using a field in an array, or maybe even nested arrays. Foreach `reasons.*.reason` I want to I want to add a condition using a field on `reasons.*`
Maybe we need to add indexes to the callback function's parameters.

I don't have the time to look into the internal workings of this `sometimes` function, but when I do I'll take a look to see if I can implement a feature like this.

**Comment by eduarguzher** [comment]
did you find anything?? I got a similar requirement

**Comment by moyvera** [comment]
anything ? same issue

**Comment by taylorotwell** [comment]
Open to PRs on this if someone wants to fix.
