### ISSUE TITLE
Consistency issue with Arr::first

### ISSUE THREAD

**Issue by alexbowers** [laravel/internals#145]
`Arr::first` accepts a callback, which passes through the arguments as `($key, $value)`.

Everywhere else in the system that I can see, the arguments are usually passed as `($value, $key)` for example, `Collection::filter()`

Places I found on a quick search that follow `$value, $key`:

`Collection::reject()`
`Collection::filter()`
`Collection::sortBy()`
`Collection::map()`
`Collection::each()`
`Builder::each()`

There are probably more, but yeah. I think this is a consistency issue we should look into.

**Comment by JosephSilber** [comment]
This has been fixed in 5.3

**Comment by alexbowers** [comment]
Ah has it? Thats great. I was about to pitch a fix for 5.3

**Comment by alexbowers** [comment]
Cool, this needs to be in the upgrade docs i think: 

https://laravel.com/docs/master/upgrade#upgrade-5.3.0

I can't see it there.

**Comment by JosephSilber** [comment]
https://github.com/laravel/framework/pull/12594

It'll make it into the docs shortly.
