### ISSUE TITLE
[Proposal] Command model binding

### ISSUE THREAD

**Issue by jhoff** [laravel/internals#148]
During @taylorotwell's presentation today at Laracon, he (tentatively) demonstrated using a console route file to setup artisan commands. It got me thinking about route model binding and if that same principle could be applied to artisan commands as well. For example ( from the docs ):

``` php
use App\User;

class SendEmails extends Command
{
    protected $signature = 'email:send {user}';

    // ...

    public function handle( User $user )
    {
        $this->drip->send( $user );
    }
}
```

Implicit command model binding would work automatically, but there would need to be a mechanism to register explicit bindings. Would that require a CommandServiceProvider? Would that be overkill?

Obviously, this would likely be a breaking change as it would change the core behavior of how command signatures are handled, so maybe it's something that can opted into via a trait or setting.

I would certainly find value in it, plus it seems like logical thing commands should do when compared to routes. I'm happy to write it if people think it would be useful.

**Comment by taylorotwell** [comment]
Pretty cool idea.
