### ISSUE TITLE
Session in Laravel 5.3

### ISSUE THREAD

**Issue by Eldair** [laravel/internals#149]
Hello,

I've noticed that session/$request->user/auth()->user is no longer available in controller constructor in Laravel 5.3. Is this change intended and is it possible to access user before called controller method?

**Comment by tomschlick** [comment]
I'm running into the same issue. It is related to laravel/framework#14824

**Comment by bram1028** [comment]
This is explained here and gives a workaround: https://laravel.com/docs/5.3/upgrade#5.3-session-in-constructors

**Comment by Eldair** [comment]
Yes, there are some workable solutions now, closing the issue.
