### ISSUE TITLE
Addition of a combine() function to Collection class

### ISSUE THREAD

**Issue by perfectmak** [laravel/internals#15]
I noticed that the laravel Collection class doesn't have a combine() function that is similar to the native php array_combine() but for collection. This is a really useful feature and its weird when one has to revert to array_combine() just for fullfil this. 
I'm wondering if there is a reason as to why this was not implemented, else i would gladly help add it as a contribution to the laravel/framework code.

Would love to hear comments on why this is absent?

**Comment by Jeroen-G** [comment]
Maybe you are the first person needing/thinking of this. :smile: 
Since it is quite a minor feature, I think you can just go ahead and code and PR it.

**Comment by perfectmak** [comment]
Yeah, maybe I'm the first, but I'm quite fond of using Collections and this tends to break my flow.

I'll add it and make a PR.
Thanks.

**Comment by JosephSilber** [comment]
I'm just gonna leave this here: https://github.com/laravel/framework/pull/12223

**Comment by perfectmak** [comment]
@JosephSilber What I'm proposing is different from what your pull request was proposing.

I've already created a pull request for this issue, it can be found here [/laravel/framework#12750](https://github.com/laravel/framework/pull/12750)
