### ISSUE TITLE
[Proposal] OneToMany sync()

### ISSUE THREAD

**Issue by kode-smith** [laravel/internals#150]
I have come across the need to perform a sync from a model on the "one" side of a "OneToMany" relationship a number of times. Some googling suggests that others have done the same after finding (surprisingly) that this isn't included in the OneToMany relationship type.

I suggest adding a sync() method to the OneToMany relationship in order to perform the a "sync" of the related models. The desired behaviour of this method is analogous to that of [ManyToMany::sync()](https://laravel.com/docs/5.1/eloquent-relationships#inserting-many-to-many-relationships)

I am very willing to contribute this code, should this feature be approved for inclusion in Laravel.

**Comment by lasselehtinen** [comment]
Thumbs up for this. I don't see any reason why you cannot sync OneToMany relations same way as ManyToMany. Now it feels dirty doing this because you get unnecessary deletes/inserts.

```
$post->links()->delete();
$post->links()->saveMany($links);
```

**Comment by saschagehlich** [comment]
@taylorotwell Could you elaborate why this has been closed?

**Comment by driesvints** [comment]
@saschagehlich probably because it was open for so long. We're welcoming PRs for this :)

**Comment by saschagehlich** [comment]
@driesvints Are you sure? In another issue, taylor mentioned he was "not comfortable with this": https://github.com/laravel/framework/issues/3251

**Comment by driesvints** [comment]
@saschagehlich ah ok, sorry. My bad.

**Comment by saschagehlich** [comment]
If anyone stumbles over this issue: This is probably a good starting point for a workaround: https://medium.com/@amithgotamey/laravel-5-2-sync-method-for-has-many-relationship-3e279d6dd07d

**Comment by twickstrom** [comment]
If anyone stumbles across this, this is how I solved sync on hasMany relationships in my application:

I have a model called `Location` with a hasMany relationship to `Assets`

In your controller (or elsewhere) you can use it like so:

```
use Location;

public function update(Request $request, Location $location)
{
    $location->fill($request->all())->save();
    $location->assets()->sync($request->assets);

    return $location->loadMissing('assets');
}
```

My request body looks like this:
```
{
  id: 1,
  location: "Nashville, TN",
  manager_id: 10,
  name: "Nashville Medical Center",
  assets: [{
    id: 1,
    name: 'Laptop',
    count: 4
  }, {
    id: 2,
    name: 'Server,
    count: 1
  }, {
    name: 'Desktops',
    count: 4
  }]
}
```

What this code will do:
1. Update any existing realted models if any fillable content has changed
2. Create new records if a new record is present (No primary key provided)
3. Delete any records that were not provided (optional, default true)

You can bypass deleting record like this:
`$location->assets()->sync($request->assets, false);`

`$location->assets()->sync($request->assets)` will return:
```
{
  'updated' => [], // list of primary keys that were updated
  'created' => [], // list of primary keys that were created
  'deleted' => [] // list of primary keys that were deleted
}
```

I have created a base model that all of my Models extend:

```
namespace App\Models;
use App\Models\Relations\HasManySyncable;

class Base extends Model
{

}
```

And here is the new class HasManySyncable

```
<?php

namespace App\Models\Relations;
use Illuminate\Database\Eloquent\Relations\HasMany;

class HasManySyncable extends HasMany
{
  private $_changes = [
    'created' => [], 'deleted' => [], 'updated' => [],
  ];

  private $_updates = [];

  public function sync($data, $deleting = true)
  {
    // Get primary key (usually id)
    $relatedKeyName = $this->related->getKeyName();

    // Get all Models
    $current = collect($this->newQuery()->get()->all());

    // Geat all current model Ids
    $currentIds = $current->pluck($relatedKeyName)->toArray();

    // delete any models not provided if $deleting is set to true
    if ($deleting) {
      	$deleteIds = $this->_changes['deleted'] = array_diff($currentIds, collect($data)->pluck($relatedKeyName)->toArray());

        if (count($deleteIds)) {
          $this->getRelated()->destroy($deleteIds);
        }

        // Update the current models and Ids
  			$current = $current->except($deleteIds);
        $currentIds = array_diff($currentIds, $deleteIds);
    }

    // loop through all current models and look for changes
  	$current->each(function ($item, $key) use ($data, $relatedKeyName) {
			$updatedItem = collect($data)->firstWhere($relatedKeyName, $item[$relatedKeyName]);
			if ($updatedItem) {
        $updateRequired = false;

        foreach($updatedItem as $field => $check) {
          if (in_array($field, $this->getRelated()->getFillable())) {
            if ($item[$field] != $check) {
              $updateRequired = true;
            }
          }
        };

        if ($updateRequired) {
          $this->_changes['updated'][] = $item[$relatedKeyName];
  				$this->_updates[] = $item->fill($updatedItem);
        }
			}
		});

    // Save changes if any exist
		if (count($this->_updates)) {
      $this->saveMany($this->_updates);
		}

    // Check for new models and create them
    collect($data)->where($relatedKeyName, null)->each(function ($item, $key)  use ($relatedKeyName) {
      $newItem = $this->create($item);
      $this->_changes['created'][] = $newItem->$relatedKeyName;
    });

    // return the priamry keys that changed
    return $this->_changes;
  }
}
```

Inspired by this answer on StackOverflow: https://stackoverflow.com/a/43989115/787796

**Comment by sebastiaanluca** [comment]
@driesvints @taylorotwell Would you guys be open to a PR for this? I took the `BelongToMany` `sync` method and implemented it for the `HasMany` relation using macros. The code is nearly identical with a few tweaks.

**Comment by driesvints** [comment]
It's best that you just attempt a PR so Taylor can see if it'd be valuable. He doesn't checks the ideas repo too often.

**Comment by sebastiaanluca** [comment]
I've found several issues related to this (https://github.com/laravel/framework/issues/2114 and other) where he mentions it's not really an issue, so won't be treating the PR as a priority. Maybe when I find some time. For others following this issue: feel free to take my code and submit the PR with tests, etc.

In the mean time, you can use the macro implementation to sync children of a `HasMany` relation to its parent (via its parent): https://gist.github.com/sebastiaanluca/79a59adf4eb08de7974a4874e365462c. Works perfectly fine here, might need some tweaking for certain situations. I didn't treat everything the same as the pivot table implementation, since that was quite unique.
