### ISSUE TITLE
[Proposal] Parse JSON when fetching from database

### ISSUE THREAD

**Issue by Kilgaloon** [laravel/internals#154]
Hello everyone,

So project im working on holds some JSON objects in database records, basically it uses PostgreSQL but that doesn't mather since i think this can come in handy for MySQL too, or any other database.

So proposal is to give option for people to decode json when data is fetched. Since i had problem with execution time. When i fetch column, json objects stay in string format (they need decoding). Then i need to loop through all records and json_decode all fields. For example there were 1000+ records in request and request took 8k ms at my localhost to execute.

I needed performance under 1k ms and i started to Query Builder and put some simple thingy. Method is called parseJson(). How it works:

```
$recipe = Model::where('country', $this->country)->parseJSON("locale")->get();
```

Row `locale` in this case will be parsed to json at runtime.

My execution time went from 8k ms to something around 700 ms.

**Comment by morloderex** [comment]
@Kilgaloon There is already the `$cast`  property on the model which will do the convertion fror you automatically :)

**Comment by Kilgaloon** [comment]
Thanks for info, property is actually `$casts`, thanks anyway.

**Comment by morloderex** [comment]
@Kilgaloon Hehe it actually is. Anyway go look it up in the docs :)
