### ISSUE TITLE
[proposal] Another layer to Validator Error Messages e.g. dimensions.ratio

### ISSUE THREAD

**Issue by Kyslik** [laravel/internals#155]
Since L5.3 there is a nice dimension validation rule [`dimensions`](https://laravel.com/docs/master/validation#rule-dimensions) with these options:
- min_width: Images narrower than this pixel width will be rejected
- max_width: Images wider than this pixel width will be rejected
- min_height: Images shorter than this pixel height will be rejected
- max_height: Images taller than this pixel height will be rejected
- width: Images not exactly this pixel width will be rejected
- height: Images not exactly this pixel height will be rejected
- ratio: Images not exactly this ratio (width/height, expressed as "width/height") will be rejected

The error message for all seven options is same

> The :attribute has invalid image dimensions.

which is (true BUT!) not **informative**; unless a HTML form specifies exactly what we want let's say  in help-block paragraph e.g.: `<p class="help-block">Picture must have same width and height.</p>`
### example (desired)

```
public function rules()
{
    return [
        'profile_picture' => 'image|dimensions:ratio=1,min_width=150,min_height=150',
    ];
}

public function messages()
{
    return [
        'profile_picture.dimensions.ratio' => 'Picture does not have square dimensions.',
    ];
}
```

**Comment by taylorotwell** [comment]
Open to PRs on this area.

**Comment by Kyslik** [comment]
@taylorotwell I just had a quick look in a validation internals and it seems its not doable without breaking the `dimensions` rule API, since every `validate*` function in [ValidatesAttributes trait](https://github.com/laravel/framework/blob/55b4efef29dd327af371ab35a016505f49ab1013/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L489-L552) must return boolean thus its impossible to distinguish why rule failed `failsRatioCheck(...)` vs `failsBasicDimensionChecks(...)` vs `validateDimensions(...)` itself. 

In order to extract information why rule failed we can either use exceptions (nope) or handle ratio as an extra new rule which tears `dimensions` rule in two new rules that are somewhat related.

Any hints if I want to make it work?
