### ISSUE TITLE
[Proposal] self updater

### ISSUE THREAD

**Issue by IgorDePaula** [laravel/internals#157]
I would suggest of build a type of self update like joomla or wordpress.

**Comment by Garbee** [comment]
`composer update` a problem?

Doing anything that touches app logic to handle the upgrade is also in-advisable. As developers can completely modify the structure and things may break if Laravel assumes everything is exactly as it is distributed.

**Comment by IgorDePaula** [comment]
Sorry, not composer update, but a self update for self framework, the
framework self update of 5.2 for 5.3 for example.

2016-08-12 19:11 GMT-03:00 Jonathan Garbee <notifications@github.com>:

**Comment by tomschlick** [comment]
Yeah that's not really in the scope of laravel. If you need that for an app you distribute you have to build it yourself as every use case would be custom. 

--
Tom Schlick




On Fri, Aug 12, 2016 at 5:42 PM -0400, "Igor C. de Paula" <notifications@github.com> wrote:












I would suggest of build a type of self update like joomla or wordpress.

**Comment by IgorDePaula** [comment]
ok, its only suggest

2016-08-12 19:13 GMT-03:00 Tom Schlick <notifications@github.com>:

> Yeah that's not really in the scope of laravel. If you need that for an
> app you distribute you have to build it yourself as every use case would be
> custom.
>
> --
> Tom Schlick
>
>
>
>
> On Fri, Aug 12, 2016 at 5:42 PM -0400, "Igor C. de Paula" <

**Comment by garygreen** [comment]
Tbh I'm +1 this even though I can't see it happening. How cool would it be to run `php artisan laravel:update` and it will update your app to the next laravel version. Of course this is difficult with dependencies and if you have heavily customised your app, but it *may* be do-able to at least have it update the things as described in the upgrade guide. 

In practise, the idea works. Take a look at https://laravelshift.com
