### ISSUE TITLE
[Proposal] Allow extend migration class for developers of packages

### ISSUE THREAD

**Issue by Siprah** [laravel/internals#158]
Hi! I'm working on a Laravel Application which will be expandable for developers. I'm going to make it possible to use some core's methods and features. For example: traits for models which extends it functionality.

Unfortuanely, there's a problem with migration. Current version in Laravel are great, but has some limitations. I'm dreaming about simple solution for developers, which adds needed columns to tables. For example: In Ruby on Rails it's possible.

Quick example: Module which adding reputation system to posts:

```
class Post extends Model {
    use Reputationable;
}
```
Above is a trait for model, which adds needed methods for posts.

```
class create_posts_table extends Migration {
    public function up() {
        Scheme::create('posts', function(Blueprint $table) {
            /* ... */
            $table->reputationable(); // My custom method injected to Migrations.
        });
    }

    public function down() {
        Scheme::dropIsExists('posts');
    }
}
```
And here we have an example with injected method to migration.

This would be really nice feature. Of course, I can just extend Migration class with my extended methods, but I think this is just hackable solution. So, what are you thinking about it?

**Comment by JosephSilber** [comment]
You can do this:

Reputation::columns($table);

**Comment by Siprah** [comment]
@JosephSilber Outh, I didn't think about it. You're right.
