### ISSUE TITLE
[Proposal] Use intl extension for translations

### ISSUE THREAD

**Issue by Skysplit** [laravel/internals#160]
It would be nice to have intl `MessageFormatter` implemented in current translation module.

Currently it is impossible to properly format plural rules in many languages, as this languages' rules are not just ranges, but often require modulo operations etc.

Examples: rules for [Polish](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#pl), [Russian](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#ru), [Arabic ](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#ar)and [many more](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html)

Examples of usage (sorry for posting own package here):  
https://github.com/Skysplit/laravel5-intl-translation#usage-examples

Downside: it requires installing php-intl extenstion (though most of the time if someone meets php 5.6 requirements, can also meet intl extension requirement)

Edit:
Also, due translation module being tightly coupled to validation module, issue #156 is related

**Comment by peterquentin** [comment]
Could we not make intl optional but recommended and fallback on current routine?

**Comment by Skysplit** [comment]
I could not find any polyfill for `MessageFormatter` on packagist, so it'd be required to create one.
However I think it is very complex task to do polyfill like this as there are really lot of rules that must be parsed, like: [spellout](http://stuff.cebe.cc/yii2docs/guide-tutorial-i18n.html#spellout), [ordinal](http://stuff.cebe.cc/yii2docs/guide-tutorial-i18n.html#ordinal), [duration](http://stuff.cebe.cc/yii2docs/guide-tutorial-i18n.html#duration) and [many more](http://intl.rmcreative.ru/tables?locale=en)
