### ISSUE TITLE
Dynamically register deferred service providers

### ISSUE THREAD

**Issue by garygreen** [laravel/internals#165]
At the moment you can't really register a deferred service provider dynamically. For instance

```php
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register the provider.
     *
     * @return void
     */
    public function register()
    {
        // All of the below are deferred.
        $this->app->register(ConsoleServiceProvider::class);
        $this->app->register(PasswordResetServiceProvider::class);
        $this->app->register(ValidationServiceProvider::class);
        $this->app->register(ViewServiceProvider::class);
    }

}
```

Maybe a new hint function could be added like `deferredProviders()`

```php
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{

    public function deferredProviders()
    {
        return [
            ConsoleServiceProvider::class,
            PasswordResetServiceProvider::class,
            ValidationServiceProvider::class,
            ViewServiceProvider::class,
        ];
    }

}
```

That way when Laravel is spinning through the list of deferred providers from `app.providers` it can also go through through hinted in `deferredProviders()`.

This would be a pretty nice change for packages because when you want to split your package up into many providers, you can't really make use of deferred providers unless you add in your installation notes to add all your providers to `app.providers` -- the downside to that is if you add/remove any  providers, they need to update their config.

Another option could be to support arrays within the `app` config. That would allow for things like:

```php
'providers' => array(

    // ... Laravel's providers

    CMS::providers(),

),
```

All of Laravel's default providers could even become:

```php
'providers' => array(

    Laravel::providers(),

),
```

**Comment by Garbee** [comment]
`$this->app->registerDeferredProvider()` not working as you expect?

**Comment by garygreen** [comment]
@Garbee :open_mouth: I didn't even know that existed, will check it out cheers buddy.

**Comment by garygreen** [comment]
@Garbee that doesn't really work... that just registers the provider and doesn't really add it as deferred. `addDeferredServices` seems more like what I want but that doesn't seem to work either. 

Basically I'm trying to overwrite one of Laravel built in deferred services, `PasswordResetServiceProvider`  - I want to register my own `auth.password.tokens` but I can see no way of doing this at the moment.

**Comment by garygreen** [comment]
Ok so what I've done is this which works. Took a bit of figuring out, maybe this is the only way but would be nice to know a better way if available.

```php
public function register()
{
    $this->app['events']->listen('bootstrapped: Illuminate\Foundation\Bootstrap\RegisterProviders', function($d) {
        $this->app->addDeferredServices(['auth.password.tokens' => 'App\Providers\PasswordResetServiceProvider']);
    });
}
```

**Comment by garygreen** [comment]
Further to this what I've done now is inside `app.php` changed it to:

```php
providers => array_flatten([
 
     // .. All the other providers

   App\CMS::providers(),
]);
```

(notice the use of `array_flatten`)

**CMS.php**
```php
namespace App;

class CMS {
   public static function() {
      return ['App\Providers\PasswordResetServiceProvider', ....];
   }
}
```

This means I can easily overwrite the built in providers (even deferred ones) and keeps everything contained in app.php.

**Comment by vesper8** [comment]
@garygreen thank you so much for sharing your awesome solution! I too have split up my dependencies into many packages and while most providers can be registered within a provider without problem.. a few of them only work if you put them in the app.php and I didn't understand why until now

your solution is very clean and makes it even easier to manage!
