### ISSUE TITLE
[Proposal] artisan make:api-auth

### ISSUE THREAD

**Issue by malhal** [laravel/internals#167]
Proposing a new artisan command to generate the necessary API controllers for user login, registration and logout as-well as adding the routes to the new routes/api.php file e.g. Auth::apiRoutes(). Login would validate the credentials and then return the token.

The current Http/Controllers/Auth e.g. LoginController cannot be called from an API route because they require a session driver and also has redirects, and by default the API routes require authentication yet no mechanism for achieving it is provided.

A design decision is would you like to redesign these controllers to also work as API routes e.g. by extracting the redirect calls and overriding them to return a JSON response instead, or would you rather have separate controllers, e.g. Http/Controllers/Auth/APILoginController.php or equivalent naming scheme. Unfortunately most of the authentication has been implemented using traits which might mean in addition to AuthenticatesUsers you would need APIAuthenticatesUsers.

Furthermore for adding API controller functionality the JSON response for exceptions from the App/Handler and the framework handler would need standardised. E.g. right now the authentication and validation use different JSON formats.

Happy to help implement this.

**Comment by DCzajkowski** [comment]
It would need a major redesign, unfortunately. I am very **for** the idea! Don't forget about password resets though! ;)

**Comment by nisace** [comment]
Just wondering why this issue was closed. Does it imply too much redesign? Is it considered not important? I would find such a feature very useful.

Thanks.

**Comment by nisace** [comment]
@malhal how do you handle this issue? I think I'll go with my own register/login/reset implementation. See https://laracasts.com/discuss/channels/laravel/rest-authentication where I asked the same question before I found this thread.

**Comment by malhal** [comment]
I can't remember exactly but I thought I would share a zip of my app folder I was working on at the time, hope that helps.

The files that mention security are unrelated to login, I was working on a sharing feature where a model had its own permissions.

[app.zip](https://github.com/laravel/ideas/files/2392286/app.zip)

**Comment by sisve** [comment]
@nisace Things are closed when Taylor has looked at them, and either considered it a good idea or a bad idea. You will sometimes get a comment that hint in what direction the decision is going, but many times not. You'll have to guess.

An example: https://github.com/laravel/ideas/issues/811#issuecomment-372795501
