### ISSUE TITLE
[Proposal] Null safe or  Safe Navigation Operator in blade template

### ISSUE THREAD

**Issue by mahabubulhasan** [laravel/internals#170]
Very often we need to chain object to show a value in blade files like this
`$classes->student->name`

if for some reason any part of this chain is null then it generates an error 

> Trying to get property of non-object

to workaround this error we need to write conditional code like this
`($classes)?(($classes->student)?$classes->student->name:''):''`

which is very tedious, so I'm proposing a new way to work around this in blade files
for example, it can be something like this:

`@nullsafe($classes->student->name)`
and this will compile into this
`<?php echo e(($classes)?(($classes->student)?$classes->student->name:''):''); ?>`

I've already implemented this for my projects, and i feel it's a nice to have feature in the core Laravel blade compiler, and I'm willing to contribute. Thanks.

**Comment by JosephSilber** [comment]
Already possible:

{{ object_get($classes, 'student.name') }}

**Comment by JosephSilber** [comment]
And in PHP 7:

{{ $classes->student->name ?? '' }}

**Comment by fgambino** [comment]
I've always wanted this to be a native language feature. 

`$classes?->student?->name`

It gets messy trying to do that on nested objects. +1 for this feature in Laravel!

**Comment by sebastiandedeyne** [comment]
@fgambino The null coalesce operator in php7 does that already.

https://wiki.php.net/rfc/isset_ternary

**Comment by kikim792** [comment]
Hmm,
{{ $classes->student->name ?? '' }}
gives me "syntax error, unexpected '?'"
I am using PHP 7.0.5, Laravel 5.4.15

I understand Laravel's been doing it already with 'or'
{{ $classes->student->name or '' }}
but wonder why ?? does not work in blade.

**Comment by morrislaptop** [comment]
Support for the null safe operator would be good... i.e. `{{ $team?->sparkPlan()->name ?? '' }}`

Atm if the team doesn't have a spark plan I get an error `Undefined variable $team` which is not the case.
