### ISSUE TITLE
[Proposal] redirect helper on router

### ISSUE THREAD

**Issue by brayniverse** [laravel/internals#172]
Sometimes routes change, and we need to redirect requests to the old URL to the new one.

I think it would be cool if we made the following possible.

```php
// Old approach
Route::get('/about_us', function () {
    return redirect('/about');
});

Route::get('/about', function () {
    return view('about');
});

// New approach
Route::redirect('/about_us', '/about');

Route::get('/about', function () {
    return view('about');
});
```

**Comment by garygreen** [comment]
I assume this would use a 301 permanent redirect?

**Comment by Garbee** [comment]
An optional 3rd param could decide which type to use. 301 should be the default IMO, but an easy way to say it is a temp 302 should be included.

**Comment by brayniverse** [comment]
@garygreen good idea.

**Comment by brayniverse** [comment]
I want to know what we'd do with query strings; I'd expect query strings to persist, but the framework doesn't persist them across redirects by default. Should this be a responsibility for this helper?

**Comment by taylorotwell** [comment]
I suggest making this a package or something. :+1:

**Comment by brayniverse** [comment]
Thanks for the feedback @taylorotwell.

I created a new package, [Laravel Redirect Helper](https://github.com/brayniverse/laravel-redirect-helper), to enable this syntax. It turns out I didn't need to modify the `Route` class to set additional data, as you can do it with `->defaults()`.

Any feedback would be appreciated.
