### ISSUE TITLE
[Proposal] Add methods for clearing query builder properties

### ISSUE THREAD

**Issue by justin-schroeder** [laravel/internals#173]
Interested to see if there is any public support for including methods to clear various `Illuminate\Database\Query\Builder` properties. For a simple use case, consider a model that automatically sorts its relationship:

``` php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function comments()
    {
        return $this->hasMany(Comments::class)->orderBy('created_at', 'desc');
    }
}
```

95% of the time this "default" orderBy is nice for comments, but lets say 5% of the time this default ordering is undesirable, :

``` php
Post::find(1)->load('comments', function($query) {
    $query->orderBy('rating', 'desc');
});
```

Unfortunately this will still load comments ordered by `created_at` first, and then rating. The proposed solution would allow the query to clear the `orders` property.

``` php
Post::find(1)->load('comments', function($query) {
    $query->clearOrderBy()->orderBy('rating', 'desc');
});
```

Most properties of the query builder could benefit from these kinds of clearing methods:
- columns
- joins
- wheres
- groups
- havings
- orders
- unions
- unionOrders

I would be happy to work up a pull request if this is something others would like to see implemented.

**Comment by tomschlick** [comment]
I don't see how it could hurt anything and would be useful in a few cases. Well worth a PR!

**Comment by franzliedke** [comment]
These kind of hidden internal defaults (which sooner or later lead to the situation where you want to undo them, for example with these proposed new methods), remind me of default scopes in Rails' ActiveRecord, which are widely [considered an anti-pattern](http://weblog.jamisbuck.org/2015/9/19/default-scopes-anti-pattern.html). Just saying. ;)
