### ISSUE TITLE
[Proposal] Eager Loading Pivot Model Relations

### ISSUE THREAD

**Issue by ajcastro** [laravel/internals#175]
There are many use-cases where in a pivot model has many relations to be eager loaded.
Example, in a procurement system, we have the following:

**Tables**

```
items
 - id

units
 - id 
 - name (pc, box, etc...)
plans (annual procurement plan)
 - id

plan_item (pivot for plans and items)
 - id 
 - plan_id
 - item_id
 - unit_id
```

**Models**

``` php

class Unit extends \Eloquent {
    protected $fillable = [];
}

class Item extends \Eloquent
{
    protected $fillable = [];

    public function plans()
    {
        return $this->belongsToMany('Plan', 'plan_item');
    }

    public function newPivot(\Illuminate\Database\Eloquent\Model $parent, array $attributes, $table, $exists)
    {
        if ($parent instanceof Plan) {
            return new PlanItem($parent, $attributes, $table, $exists);
        }

        return parent::newPivot($parent, $attributes, $table, $exists);
    }
}

class Plan extends \Eloquent
{
    protected $fillable = [];

    public function items()
    {
        return $this->belongsToMany('Item', 'plan_item')->withPivot('unit_id', 'qty', 'price');
    }

    public function newPivot(\Illuminate\Database\Eloquent\Model $parent, array $attributes, $table, $exists)
    {
        if ($parent instanceof Item) {
            return new PlanItem($parent, $attributes, $table, $exists);
        }

        return parent::newPivot($parent, $attributes, $table, $exists);
    }
}

// Pivot model
class PlanItem extends Pivot
{
    protected $table = 'plan_item';

    public function unit()
    {
        return $this->belongsTo('Unit');
    }
}
```

From the code above, `plans` and `items` has `Many-to-Many` relationship. Each item in a plan has a selected `unit`, unit of measurement. And it also possible for other scenario that the pivot model will have other many relations.
## Proposed Eager Loading for Pivot models

Use keyword `pivot` in eager loading pivot models. So from the example above, the `unit` relation can be eager loaded by this way:

```
return Plan::with(['items.pivot.unit'])->get();
```

The resulting data structure will be:

![image](https://cloud.githubusercontent.com/assets/4918318/17958278/0d3c962a-6acb-11e6-8415-c48d01457cd6.png)

You may also access other relations for example:

```
return Plan::with([
  'items.pivot.unit', 
  'items.pivot.unit.someRelation', 
  'items.pivot.anotherRelation',
  // It is also possible to eager load nested pivot models
  'items.pivot.unit.someRelation.pivot.anotherRelationFromAnotherPivot', 
])->get();
```
## Current Solution:

Create your own `BaseModel` and `EloquentBuilder` and override some methods:

**BaseModel.php**

``` php
class BaseModel extends \Illuminate\Database\Eloquent\Model
{
    /**
     * Override. Create a new Eloquent query builder for the model.
     *
     * @param  \Illuminate\Database\Query\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder|static
     */
    public function newEloquentBuilder($query)
    {
        return new EloquentBuilder($query);
    }
}
```

**EloquentBuilder.php**

```

class EloquentBuilder extends \Illuminate\Database\Eloquent\Builder
{
    /**
     * Eager load pivot relations.
     *
     * @param  array $models
     * @return void
     */
    protected function loadPivotRelations($models)
    {
        $query = head($models)->pivot->newQuery()->with('unit');
        $pivots = array_pluck($models, 'pivot');
        $pivots = head($pivots)->newCollection($pivots);

        $pivots->load($this->getPivotRelations());
    }

    /**
     * Get the pivot relations to be eager loaded.
     *
     * @return array
     */
    protected function getPivotRelations()
    {
        $relations = array_filter(array_keys($this->eagerLoad), function ($relation) {
            return $relation != 'pivot' && str_contains($relation, 'pivot');
        });

        return array_map(function ($relation) {
            return substr($relation, strlen('pivot.'));
        }, $relations);
    }

    /**
     * Override. Eager load relations of pivot models.
     * Eagerly load the relationship on a set of models.
     *
     * @param  array     $models
     * @param  string    $name
     * @param  \Closure  $constraints
     * @return array
     */
    protected function loadRelation(array $models, $name, Closure $constraints)
    {
        // In this part, if the relation name is 'pivot',
        // therefore there are relations in a pivot to be eager loaded.
        if ($name === 'pivot') {
            $this->loadPivotRelations($models);
            return $models;
        }

        return parent::loadRelation($models, $name, $constraints);
    }
}
```

You may visit my personal project, [iprocure](https://github.com/ajcastro/iprocure), where I implemented this solution. :)

**Comment by meriemMat** [comment]
thank you @ajcastro for this solution, i applied the changes u proposed but still have this problem to eager load pivot relationships  :
Argument 3 passed to App\EloquentBuilder::loadRelation() must be an instance of App\Closure, instance of Closure given, called in C:\wamp\www\Laravel\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php on line 402 and defined

**Comment by ajcastro** [comment]
Pls fix the loadRelation() method. Change Closure to \Closure.

**Comment by meriemMat** [comment]
thx @ajcastro for ur quick reply ... yeah it fixed the problem but it still not working ... am having this issue now: 
Call to undefined method Illuminate\Database\Query\Builder::pivot()

**Comment by ajcastro** [comment]
You're welcome. Im glad about it.

**Comment by mark-win** [comment]
Thanks! I would love to see part of this in a future release.

Please note the method name `loadRelation` was refactored to `eagerLoadRelation` in [08ba4fa](https://github.com/illuminate/database/commit/c2ad416c7c641ea65091063301c383db783df8b9).

`newPrivot` received a new [parameter](https://github.com/illuminate/database/commit/e02084889a99405daf14fb60ba7bb87700fcd60b), which can simply be added to your solution's implementation but you can also use it to improve your solution right away.

Now you can avoid overriding `newPivot` at all and simply call `using`on the relationship, to tell it what pivot class to use.

In case of your example the following is all a Model needs:
```php
class Plan extends BaseModel
{
    protected $fillable = [];

    public function items()
    {
        return $this->belongsToMany('Item', 'plan_item')->withPivot('unit_id', 'qty', 'price')->using(PlanItem::class);
    }
}
```

Extending `Model` by `BaseModel` and `Builder` by `EloquentBuilder` like you showed is still necessary, as 'pivot' is still not recognized as a keyword by `eagerLoadRelation`.

**Comment by ajcastro** [comment]
Yeah, thanks for the info!
I am new in creating PRs, so I am still studying on how to create PRs for this. Maybe someone would like to create PR for this will be a good help.

**Comment by ajcastro** [comment]
The `using(PlanItem::class)` is a very nice thing.. I am thinking that it could also be possible if we want to rename the pivot relation name, like this `->using(PlanItem::class)->as('plan_item');`. This way, we can access the pivot by `->plan_item` instead of `->pivot`.

**Comment by jass-trix** [comment]
does this solution still able to fix the problem in laravel 5.3? @ajcastro

**Comment by ajcastro** [comment]
what problem?

**Comment by jass-trix** [comment]
@ajcastro i mean, is this solution can be used for eager loading on pivot table? for laravel 5.3

**Comment by ajcastro** [comment]
Yes it should be applicable. But take note that there are things to be changed as @mark-win has mentioned above (https://github.com/laravel/internals/issues/175#issuecomment-295699732).

**Comment by mark-win** [comment]
@jass-trix it works in 5.4 as well.

**Comment by ajcastro** [comment]
I am glad to know that! Hooray!!! :smile: 
Maybe it's good to mention @taylorotwell about this. If he will agree on this.

**Comment by okaufmann** [comment]
Using this for a while and after rename `loadRelation` to `eagerLoadRelation` in the `EloquentBuilder` it works as expected.

**Comment by JordanDalton** [comment]
Doesn't look to work in 5.5.

**Comment by MicroDreamIT** [comment]
what if its look like, 
```
return $this->belongsToMany(Product::class)
            ->withPivot('quantity', 'price', 'discount','subtotal', 'unit_id', 'warehouse_id')
            ->loadWith(Unit::class, 'unit_id')   //here unit_id is the foreign key on id of units table & unit id must be a value from withPivot()
            ->withTimestamps();
```
here

**Comment by nicolasbuch** [comment]
Thanks for this answer, exactly what I was looking for. Worked perfectly in Laravel 5.6, when changing the loadRelations to eagerLoadRelations as pointed out by @mark-win

**Comment by JeanmarcoLujan** [comment]
Por favor podrían orientarme en la solución.
Please, I need help with this.

**Comment by ajcastro** [comment]
This seems officially supported: 
https://stackoverflow.com/a/37586367

**Comment by ajcastro** [comment]
To anyone who wants how to implement this in the latest laravel v5.8, I created a package for this. 
https://github.com/ajcastro/eager-load-pivot-relations.

@JeanmarcoLujan 
@nicolasbuch
