### ISSUE TITLE
Add change log to each releases like vue.js did

### ISSUE THREAD

**Issue by mul14** [laravel/internals#179]
It would be nice if we add change log to each [releases](https://github.com/laravel/framework/releases) like vue.js did on https://github.com/vuejs/vue/releases instead of [CHANGELOG.md](https://github.com/laravel/framework/blob/5.3/CHANGELOG-5.3.md) file.

**Comment by Padarom** [comment]
I wouldn't say _instead_ of a changelog file. Being able to just look through a file to find what you're looking for is super handy, so I'd say do both as it shouldn't be much more work (the same text can be used in both places).

**Comment by taylorotwell** [comment]
Done.
