### ISSUE TITLE
[5.3] (Revert) Resource Route Names No Longer Affected By Prefixes

### ISSUE THREAD

**Issue by yajra** [laravel/internals#181]
This is documented BC https://laravel.com/docs/5.3/upgrade and in my opinion, I think this should be reverted? Please see https://github.com/laravel/framework/issues/15058 for my reasons. 

Or can someone please give us some tips on how to properly group resource routes on Laravel 5.3?

Thanks!

**Comment by RDelorier** [comment]
I'm not sure if its intended to work this way but here is the solution I came up with.

```php
Route::group([
    'as' => 'admin.', // the trailing dot makes me this this is unintended
    'prefix' => 'admin'
], function () {
    Route::resource('users', 'UserController');
});

Route::resource('users', 'UserController');
```

Here is the resulting routes
```sh
php artisan route:list
+--------+-----------+-------------------------+---------------------+---------------------------------------------+------------+
| Domain | Method    | URI                     | Name                | Action                                      | Middleware |
+--------+-----------+-------------------------+---------------------+---------------------------------------------+------------+
|        | GET|HEAD  | admin/users             | admin.users.index   | App\Http\Controllers\UserController@index   | web        |
|        | POST      | admin/users             | admin.users.store   | App\Http\Controllers\UserController@store   | web        |
|        | GET|HEAD  | admin/users/create      | admin.users.create  | App\Http\Controllers\UserController@create  | web        |
|        | GET|HEAD  | admin/users/{user}      | admin.users.show    | App\Http\Controllers\UserController@show    | web        |
|        | PUT|PATCH | admin/users/{user}      | admin.users.update  | App\Http\Controllers\UserController@update  | web        |
|        | DELETE    | admin/users/{user}      | admin.users.destroy | App\Http\Controllers\UserController@destroy | web        |
|        | GET|HEAD  | admin/users/{user}/edit | admin.users.edit    | App\Http\Controllers\UserController@edit    | web        |
|        | GET|HEAD  | users                   | users.index         | App\Http\Controllers\UserController@index   | web        |
|        | POST      | users                   | users.store         | App\Http\Controllers\UserController@store   | web        |
|        | GET|HEAD  | users/create            | users.create        | App\Http\Controllers\UserController@create  | web        |
|        | GET|HEAD  | users/{user}            | users.show          | App\Http\Controllers\UserController@show    | web        |
|        | PUT|PATCH | users/{user}            | users.update        | App\Http\Controllers\UserController@update  | web        |
|        | DELETE    | users/{user}            | users.destroy       | App\Http\Controllers\UserController@destroy | web        |
|        | GET|HEAD  | users/{user}/edit       | users.edit          | App\Http\Controllers\UserController@edit    | web        |
+--------+-----------+-------------------------+---------------------+---------------------------------------------+------------+
```


https://github.com/laravel/framework/issues/15058 for reference

**Comment by yajra** [comment]
@RDelorier thanks for the workaround using `as`. Seems to work on grouping the resource route, however, manually created routes would also get appended with the alias on route name like:

```php
Route::group([
    'as' => 'admin.', // the trailing dot makes me think this is unintended
    'prefix' => 'admin'
], function () {
    $router->get('utilities', UtilitiesController::class . '@index')
       ->name('admin.utilities.index');
});
```

Will have a route name of. `admin.admin.utilities.index`. 

Anyways, this workaround is more acceptable than having to re-write all our resource routes. I just need to adjust the manual route name properly.

Thanks!

**Comment by enkay** [comment]
Can someone from the core team let us know if this workaround is going to get removed in a future version with no warning because it was "not intended" and "it's not the way you're supposed to do this" or if this is now the way to go? It would be nice not to have the dot.

**Comment by fernandobandeira** [comment]
I've created a PR there to remove the dot so we'll be sure if this behavior is intended or not.

**Comment by fernandobandeira** [comment]
The PR was closed, so actually this is the intended behavior of the function, you can use it this way, but the ',' won't be added automatically. I've created a PR to update the example given in the docs to reflect this change of behavior.

**Comment by yajra** [comment]
Then I guess it's decided that this is the intended way to go with on 5.3. Thanks for the feedbacks!

**Comment by marcnewton** [comment]
For users of 5.5+ finding this discussion the following will i can confirm will work, try it in 5.3 and 5.4:

```php
Route::namespace('Settings')->prefix('settings')->name('settings.')->group(function () {

    Route::resource('users','UsersController');

});
```

> Please note the DOT on the end of **settings** in the **name** method.

This will give you the dired route name: `route('settings.users.index');`

> Please leave comments if this works in 5.3 and 5.4
