### ISSUE TITLE
[Proposal] Views: Use dot in @include directive as path segments

### ISSUE THREAD

**Issue by IsraelOrtuno** [laravel/internals#183]
There is something that really bugs me when my views folder gets so many nested levels to keep everything organized. Including view partials may become cumbersome:

``` blade
# Example
@include ('path.child.child.child.view')

# More real life
@include ('hosting.shared._index.option-selector')
```

My proposal is to use the `dot` `.` path segment as any other filesystem does. This way we could access views this way:

``` blade
file: views/hosting.shared.index.blade.php

@section ('content')
    <div> ... </div>
    @include ('._index.option-selector')
@endsection
```

This way we would include a file located at `views/hosting/shared/_index/option-selector`.

Using this system we could also extend to the `..` dot segments to even access lower directory levels.

**Pros**
- Shorter and smarter include statements
- Easier refactoring
- Views do not get affected by global directory structure

**Cons / Considerations**
- May be a breaking change
- Packages

Thoughts?

**Comment by sebastiandedeyne** [comment]
Using a dot for this would be slightly confusing. Since the dot is similar to a slash seperator in the filesystem here, `._index.option-selector` would seem to translate to `/_index/option-selector`, which I'd interpret as 'start from the root', not 'start from the current directory'.

**Comment by Padarom** [comment]
I like the idea of not having to constantly rewrite the whole path in my views. 

All `.`'s are replaced by `/`'s in the [FileViewFinder](https://github.com/illuminate/view/blob/71b4d9aea6320afe1ade095ac679aafa7489cd67/FileViewFinder.php#L148-L150), so it would in fact be translated to `/_index/option-selector` as @sebastiandedeyne suggested. That path is just appended to the views path (`/path/to/your/project/resources/views`), so even having multiple leading slashes won't do anything. So looking at the architecture of Illuminate/View this would only be a breaking change if people prepended their view path with a `.` for some reason (which shouldn't be a concern, as it is nowhere documented why you should do this).

However I still agree that using the same character as a denotation for "start from current directory" and as a path delimiter, where the only difference is the placement, is confusing. How about introducing a different character, that is not used in this context (such as `~` or `@`)?

**Comment by IsraelOrtuno** [comment]
I don't think it may be that confusing. You can always use the traditional way. If you're using this way, it's because you have read docs and know how it works. Using another symbol may be even more confusing in my opinion.

Either way it gets implemented, I would really like to see this feature working. Hopefully will get more fans.

**Comment by JosephSilber** [comment]
The [AdvancedNewFile](https://github.com/skuroda/Sublime-AdvancedNewFile) plugin for Sublime Text uses a colon to denote relative paths:

```php
@include(':partials.option-selector')
```

I think that's better than `@` or `~`.

**Comment by IsraelOrtuno** [comment]
I really like that style @JosephSilber
