### ISSUE TITLE
[Proposal] Add arguments to update belongToMany to not need to use primary key column

### ISSUE THREAD

**Issue by evanmalmud** [laravel/internals#184]
Currently when using belongToMany it automatically uses the column that is set as the primary key on the models being used. This should not need to be set to change the columns used. I am proposing adding two new inputs to the method that will let you set the names of the columns for each of the tables.

**Comment by Garbee** [comment]
Can you please provide an example of what the proposed solution would look like for a developer coding it? Also elaborate on what use-cases within your application this would solve?

Thank you.

**Comment by bkuhl** [comment]
IMO this should be closed since it has gone so long without a response.

**Comment by evanmalmud** [comment]
The proposed change would stop the assumption of belongToMany operators. So the belongToMany method would take in more variables that would have defaults and these changes would need to trickle down to any other method being called this way. I am not sure how deep this would go.

**Comment by alberto-bottarini** [comment]
It's already merged on 5.5 branch.

https://github.com/laravel/framework/pull/17903

https://github.com/laravel/framework/pull/17915
