### ISSUE TITLE
[Proposal] Snake/Camel case helper for array keys

### ISSUE THREAD

**Issue by mikemclin** [laravel/internals#186]
I created 2 helpers that I've been using (mainly with Lumen) that have been great at transforming data back and forth from my API schema (camel) to the my internal Eloquent app schema (snake).  For more complex output, I use a full blown transformer like Fractal, but simple transformations, and for request transformations, I tend to fall back to these simple helpers.

``` php
if (!function_exists('camel_keys')) {
    /**
     * Convert array keys to camel case recursively.
     *
     * @param  array $array
     * @return string
     */
    function camel_keys($array)
    {
        $result = [];
        foreach ($array as $key => $value) {
            if (is_array($value)) {
                $value = camel_keys($value);
            }
            $result[camel_case($key)] = $value;
        }
        return $result;
    }
}

if (!function_exists('snake_keys')) {
    /**
     * Convert array keys to snake case recursively.
     *
     * @param  array  $array
     * @param  string $delimiter
     * @return string
     */
    function snake_keys($array, $delimiter = '_')
    {
        $result = [];
        foreach ($array as $key => $value) {
            if (is_array($value)) {
                $value = snake_keys($value, $delimiter);
            }
            $result[snake_case($key, $delimiter)] = $value;
        }
        return $result;
    }
}
```

**Comment by garygreen** [comment]
Please god not anymore helpers !! :cry:

**Comment by mikemclin** [comment]
At least you gave a good reason for the down vote. However, I would have preferred something like... "This isn't very useful", "this solves a very slim use case", "this negatively effects Laravel because of x, y, z", or even "this is already easily accomplished using a, b, c".

**Comment by crynobone** [comment]
@mikemclin based on my experience when developing SaaS type application with public API (for web and mobile app), the problem resolve mostly about ensuring the key to value maintain the same consistently during for a major version, so any automatic conversion isn't going to be much help.

At the same time I do feel agree that Fractal isn't useful for simple transformer, which is why I made a PR for https://github.com/laravel/framework/pull/14357#issuecomment-237132806

**Comment by sebastiandedeyne** [comment]
I'd rather see a `mapKeys` method added to the `Collection` class, like lodash has. That way it could easily be achieved without using helper:

```php
$user->mapKeys('snake_case');
```

https://lodash.com/docs/4.15.0#mapKeys

**Comment by garygreen** [comment]
@mikemclin I do think it solves a slim use case, rather than adding an additional 2 helpers I'd prefer to see `camel_case()` support arrays straight out the box. @sebastiandedeyne idea is the most dynamic along with @crynobone for simple transformer idea.

**Comment by JosephSilber** [comment]
The collection class already has a keyBy method.

**Comment by sebastiandedeyne** [comment]
Didn't realize `keyBy` also recieved the original key as an argument!

**Comment by mikemclin** [comment]
@JosephSilber As far as I know, the `keyBy` method does not accomplish the same thing.  Can you show an example?

**Comment by sebastiandedeyne** [comment]
It's not exactly the same, but similar.

```php
collect($user)->keyBy(function ($value, $key) {
    return camel_case($key);
});
```

**Comment by mikemclin** [comment]
@sebastiandedeyne The `keyBy` method is not recursive.  Of course, you could make it recursive by adding more functionality to it, but then you are right back where we started...needing something quick, easy and readable.

**Comment by mikemclin** [comment]
@crynobone I see your solution as more of a direct competitor to Fractal, only internal to Laravel.  You are manually setting every property.  The functionality I suggested as a much simpler device, that could potentially be used inside of your transformer solution, or inside of Fractal, or somewhere else in the app.  If I were using your transformer proposal, there is a good chance that I would just use my suggested functionality inside of your transformer.  Then, if the DB schema changes, I can modify the transformer to manually set the values when needed.

FYI, I am already using a sanitizer class for posted request data (e.g. `UserSanitizer`) which is just an opinionated transformer.  Then I am using Fractal for my output (e.g. `UserTransformer`).  So, my proposed functionality is designed to work in concert with these types of solutions, not necessarily compete with them.

**Comment by gr33k01** [comment]
In case anyone wants to go the route of using a recursive version of `keyBy`, take a look at this: 
https://gist.github.com/gr33k01/5cadc0860025a4c4cccca9423167f11c

And then to make it more expressive:

```php
Collection::macro('camelCaseKeys', function () {
      return $this->keyByRecursive(function ($value, $key) {
            return camel_case($key);
      });
});
```

Now you can do

```php
collect($array)->camelCaseKeys();
```

**Comment by martinhschei** [comment]
@gr33k01 useful - thanks!

**Comment by stevelacey** [comment]
Slightly simpler variation of the above for those that come here looking for it:

```php
function camel_keys(array $array) : array
{
    return key_by($array, 'camel_case', true);
}

function snake_keys(array $array) : array
{
    return key_by($array, 'snake_case', true);
}

function key_by(array $array, callable $callable, bool $recursive = false) : array
{
    return collect($array)
        ->mapWithKeys(function ($value, $key) use ($callable) {
            return [$callable($key) => is_array($value) && $recursive ? key_by($value, $callable) : $value];
        })
        ->toArray();
}
```

**Comment by lcdss** [comment]
Another adaptation using php 7.4 syntax:

```php
Collection::macro('transformKeys', function ($callback) {
    return $this->mapWithKeys(fn ($value, $key) => [
        $callback($key) => is_array($value) ? collect($value)->transformKeys($callback) : $value
    ]);
});

$array = ['documentType' => 1, 'content' => ['validationDate' => '2019-10-05']];
collect($array)->transformKeys(fn ($key) => Str::snake($key));

// [
//    "document_type" => 1,
//    "content" => [
//        "validation_date" => "2019-10-05",
//    ],
// ]

```
