### ISSUE TITLE
[Proposal] Map API routes before web routes

### ISSUE THREAD

**Issue by bryceadams** [laravel/internals#187]
I was recently working on a Laravel 5.3 app that is a SPA. In the `web.php` routes, I have a catchall  route that looks like this:

```
Route::get('/{subs?}', [function () {
	return view('base');
}])->where(['subs' => '.*']);
```

But when adding an API endpoint to `api.php`, of course the catchall took priority over all the API routes (as web routes are mapped first).

I'd like to propose that we map API routes before mapping web routes to avoid this sort of issue happening, as I cannot see much benefit to mapping web routes before API routes but I can see a lot of benefit to mapping API routes before web routes.

Please correct me if I'm wrong! Thank you.

PS. I know this is a tiny PR but I'd love to make it if enough people agree with this so I can have my first contribution to Laravel 😍

**Comment by jlaswell** [comment]
I think the inverse question applies here too. Why would we want api routes resolved before web routes? I can see the point in your specific use case, but I don't see concrete reasoning to change that default.

There are also common patterns to differentiate api request from browser request like URL prefixing and adjusting content-type.

**Comment by brayniverse** [comment]
@jlaswell `api.php` routes are prefixed with `/api` so a catch-all route wouldn't have the same effect as if in `web.php` (which isn't prefixed).
