### ISSUE TITLE
[Proposal] Container resolve class without class instance

### ISSUE THREAD

**Issue by a-komarev** [laravel/internals#188]
I haven't found a way to resolve concrete class name from abstract one without class instantiation.

``` php
public function comments()
{
    return $this->hasMany(app(CommentContract::class), 'user_id');
}
```

This code is creating a new concrete `Comment` class and under the hood in `hasMany` method it will instantiate this class one more time:

``` php
$instance = new $related;
```

It's not critical, but wouldn't it be more optimized to have an ability to get just concrete class name from the abstract one?

``` php
public function comments()
{
    return $this->hasMany(app()->concreteName(CommentContract::class), 'user_id');
}
```

Or have a check in all relation methods if instantiated class provided - use it instead of creating a new one.

**Comment by KKSzymanowski** [comment]
Currently I think the only way to achieve this is following:
```php
// Get application instance
$app = \Illuminate\Foundation\Application::getInstance();

// Get defined bindings
$bindings = $app->getBindings();

// Find the binding you want, eg. Kernel
$binding = $bindings[\Illuminate\Contracts\Http\Kernel::class];

// Get the Closure that produces the concrete class
$closure = $binding['concrete'];

// Instantiate a ReflectionFunction
$closureReflection = new ReflectionFunction($closure);

// This is what we pass in by `use` in `function() use ($foo, $bar, $baz) {}`
$staticVariables = $closureReflection->getStaticVariables();

// This is the concrete class name, in this case `App\Http\Kernel`
$concreteClassName = $staticVariables['concrete'];
```
You can wrap it in some helper function like `getConcrete($abstract)`.
It's quite complicated but I haven't found another way.

**Comment by benswinburne** [comment]
Surely all this would need would be for the existing `protected getConcrete()` method in `Illuminate\Container\Container` to be made public?

    /**
     * Get the concrete type for a given abstract.
     *
     * @param  string  $abstract
     * @return mixed   $concrete
     */
    protected function getConcrete($abstract)

Which would allow for

    app()->getConcrete(CommentContract::class);

**Comment by KKSzymanowski** [comment]
@benswinburne You would still need to instantiate a `ReflectionMethod` to get the class name if you don't want to instantiate the concrete class in the relatioship definition(which is how I understood the author).

**Comment by milosdakic** [comment]
Using the `getConcrete` method works fine on relationship definitions as it doesn't require the concrete class to be instantiated (its done when relationship is bound).

I've been getting around this by creating an alias and using the following:

```php
public function products()
{
    return $this->hasMany(app()->getAlias('App\Product'));
}
```

The other way is to extract the class name from the instance (extra object created).

```php
public function products()
{
      return $this->hasMany(get_class(app('App\Product')));
}
```

**Comment by milosdakic** [comment]
@themsaid any thoughts on this one?

**Comment by taylorotwell** [comment]
I'm open to this I think if people want to work on it.
