### ISSUE TITLE
Fluent BladeCompiler::directive 

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/internals#189]
How about `BladeCompiler::directive` would return `$this` to be able to chain method calls?

``` php
/**
 * Register a handler for custom directives.
 *
 * @param  string  $name
 * @param  callable  $handler
 * @return $this
 */
public function directive($name, callable $handler)
{
    $this->customDirectives[$name] = $handler;

    return $this;
}
```

What do you think?

**Comment by bkuhl** [comment]
What's an example of how blade methods would be chained?

**Comment by franzliedke** [comment]
@bkuhl I think this is not about chaining directives in a Blade template, but rather about chaining the `Blade::directive()` calls which are used to register new directive definitions.

**Comment by KKSzymanowski** [comment]
@franzliedke Exactly.
