### ISSUE TITLE
[Proposal] ->allOrFail on models

### ISSUE THREAD

**Issue by jacobfogg** [laravel/internals#190]
So I am using:

return self::where('somefield', $someValue)->firstOrFail()

in my models. I would love a similar feature for returning all results. Something like

return self::where('somefield', $someValue)->allOrFail()

The end result would be that if 1 or more results were found, it would return them, otherwise it would return the same exception as firstOrFail.

I'm willing to take a stab at developing the method, I'm just fairly new to the framework myself.

**Comment by franzliedke** [comment]
Can you go into more detail about what the use case is exactly?

`firstOrFail` exists because it is quite typical to want to display an error (or 404) when a singular resource (identified by ID) does not exist. For collections that are empty, they are typically just shown as that: an empty collection.

I am not saying your use case isn't valid, but off the top of my head I can't come up with a good example where I would really need it. Thus, I'm wondering whether it's common enough to be included in the framework.

**Comment by KKSzymanowski** [comment]
As for implementation, if you are new to the framework I think you should take a close look at how methods in `Eloquent\Builder` and tests for them are written. I will help you a lot.

Although I like the idea of having this method, I don't think it's probable that this will be merged into the core. The reason will be "you can just do"
```php
$collection = Model::get();

if(! $collection->count()) {
    throw new NotFoundException();
}
```

**Comment by Garbee** [comment]
If "you can just do" would be the case then `findOrFail` shouldn't exist either...

```php
$item = Model::find(1);

if (!$model) {
   throw new NotFoundException();
}
```

We really need a use-case here as @franzliedke requested. As there is a different pattern to take into account for collections typically.

**Comment by KKSzymanowski** [comment]
@Garbee Thats what I don't understand about this kind of explanation.

**Comment by tomschlick** [comment]
Just curious, whats the use case for throwing a 404 if multiple results are not found?

**Comment by ntzm** [comment]
Some APIs allow you to get multiple resources at once (e.g. `GET /products/2,5,3` would get product 2, 5 and 3)

**Comment by Garbee** [comment]
@ntzm APIs in that case would only return the ones that could be found. Not error if a single resource doesn't exist. As it is natural that resources may change ownership, get removed, or any other number of things that would make it so one query would work and then fail in the future.

**Comment by ntzm** [comment]
@Garbee If you read the OP, the proposal is to only error if *all* the resources don't exist.

**Comment by jacobfogg** [comment]
So a common use case is for find results that fall into something like a category. For me specifically, I am working on an ecommerce project. The user can define a category and then add products to those categories. While the navigational logic does only list those categories that do contain one or more products, it could still be possible for a user, especially an admin, to navigate to the page that shows products within a category. In a situation like that, having ->allOrFail(), or possibly better, ->getOrFail(), would allow me to simplify my code and respond accordingly.

It's worth noting, in a case like this, I am requesting a result of many records, where I am matching based on the id of a one to many relationship. (i.e. category hasMany products, uri = /category/apples,  select products where category_id = apples)

@franzliedke I agree that ->firstOrFail() is a very common use case. I am suggesting that there are many instances when dealing with one-to-many collections, that, not having any related results, one would expect an error.

@KKSzymanowski Precisely what I have done! That is the exact logic I have in my Model =)

@Garbee Hopefully the above use case makes more sense.

@tomschlick My intention would not to simply throw _a_ 404 error, but to throw a specific kind of 404 relating to no products matching the selected category.

@ntzm More specifically, throwing an error if _no_ resources matching the criteria exist. This logic would expect 1 or More results to be returned. Your example of GET /products/2,5,3 would be just as valid a use case.


At this point I have already overcome the issue in my implementation using if/then logic directly in my model, throwing the exception if there are 0 results.

I also think I almost have a working solution within the Eloquent\Builder class that I'd be happy to send as a pull request. I simply need to write the corresponding tests. I'm always open to suggestions and recommendations.

**Comment by franzliedke** [comment]
Cheers for the detailed reply!

I disagree that there are many instances. Especially since I could not find an issue suggesting something similar (though maybe my search terms were flawed).

I personally think that it is just cosmetics for something that is already easy to do. At the same time, I don't see a very large need, and am slightly afraid that it could lead to people abusing the ease of this feature for doing something that does not match the semantics of REST / HTTP as I understand them (empty collections != 404). But, again, that is just my opinion, I have no say in the matter.

**Comment by ebermann** [comment]
I think `getOrFail()` could be useful when it's not related to controllers and automatic `404` HTTP responses.

My current use case is fetching a lot of calculation components from the database. If something erroneously doesn't exist I have the throw an exception or the calculation will be wrong.

For fetching a single component I can use of `findOrFail()` or `firstOrFail()`.
For fetching a fixed list of components I can use of `findOrFail()`.
For fetching a variable list of components I have to check with `isEmpty()` and throw the exception myself.
