### ISSUE TITLE
[Proposal] Customized database notifications

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/internals#191]
Currently the Model representing `notifications` column in the database is hardcoded in `HasDatabaseNotifications` trait:

``` php
public function notifications()
{
    return $this->morphMany(DatabaseNotification::class, 'notifiable')
                ->orderBy('created_at', 'desc');
}
```

I propose a method on this trait called `getDatabaseNotificationsModel` and it would look something like that:

``` php
protected function getDatabaseNotificationsModel()
{
    if(property_exists($this, 'databaseNotificationsModel')) {
        return $this->databaseNotificationsModel;
    }

    return DatabaseNotification::class;
}
```

and the `User` model will then look something like this:

``` php
class User extends Authenticatable
{
    use Notifiable;

    protected $databaseNotificationsModel = MyCustomNotificationsModel::class;
}
```

That way we could customize the `DatabaseNotification` model(eg. the connection or table name) and not need to duplicate the relationship definitions as it is required now.

What do you think?

**Comment by fgambino** [comment]
It's a good start to making the database notification channel more customizable, but people still won't be able to modify the schema, and a custom model makes it seem like you can do that. I wound up creating my own database channel to get around the limitation, and it suits my needs perfectly. They made it very easy to create new channels.

**Comment by blhm** [comment]
@fgambino any documentation or links on customizing a new database channel?

**Comment by meysammahfouzi** [comment]
@blhm https://stackoverflow.com/a/43658694/69537

**Comment by BehroozBvk** [comment]
Where do you define this method `getDatabaseNotificationsModel ()` ? Where?

**Comment by kamalkhan** [comment]
Create and use your own `Notification` model and `Notifiable` trait and then use your own Notifiable trait in your (User) models.

App\Notifiable.php:

```php
namespace App;

use Illuminate\Notifications\Notifiable as BaseNotifiable;

trait Notifiable
{
    use BaseNotifiable;

    /**
     * Get the entity's notifications.
     */
    public function notifications()
    {
        return $this->morphMany(Notification::class, 'notifiable')
                            ->orderBy('created_at', 'desc');
    }
}
```

App\Notification.php:

```php
namespace App;

use Illuminate\Notifications\DatabaseNotification;

class Notification extends DatabaseNotification
{
    // ...
}
```

App\User.php:

```php
namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    // ...
}

```

**Comment by BehroozBvk** [comment]
Tanks.perfect

**Comment by synergixe** [comment]
Very Perfect @kamalkhan !!
