### ISSUE TITLE
[proposal] Provide a RFC-5988 compliant paginator

### ISSUE THREAD

**Issue by lucasmichot** [laravel/internals#192]
Providing a pagination system matching RFC-5988 would make sense in my opinion.

This is already the pagination system used by many API providers (e.g. Github...): https://developer.github.com/guides/traversing-with-pagination/#navigating-through-the-pages

---

See https://tools.ietf.org/html/rfc5988

**Comment by seanmangar** [comment]
That's a great idea. Would it be something similar to this: http://fractal.thephpleague.com/pagination/.

**Comment by lucasmichot** [comment]
This would be easy as pie to achieve it if https://github.com/laravel/framework/pull/17137 is merged

**Comment by lucasmichot** [comment]
Could also be integrated to https://github.com/laravel/framework/pull/18502
