### ISSUE TITLE
[5.4] Reduce the number of helpers

### ISSUE THREAD

**Issue by garygreen** [laravel/internals#194]
It's been spoken about a few times but I think the number of helpers in Laravel is pretty large at the moment. How about a rule is created where if a helper isn't much shorter than just calling the method directly, then get rid of the helper. If people like the helper and would like to use it in their own app, they can create their own alias - we can create an exception to some 'commonly used' helpers.

Some suspects:

array_add -> Arr:add
array_collapse -> Arr:collapse
array_divide -> Arr:divide
array_dot -> Arr:dot
array_except -> Arr::except
array_first -> Arr::first
array_flatten -> Arr::flatten
array_forget -> Arr::forget
array_get -> Arr::get
array_has -> Arr::has
array_last -> Arr::last
array_only -> Arr::only
array_pluck -> Arr::pluck
array_prepend -> Arr::prepend
array_pull -> Arr::pull
array_set -> Arr::set
array_sort -> Arr::sort
array_sort_recursive -> Arr::array_sort_recursive
array_where -> Arr::array_where

camel_case -> Str::camel
snake_case -> Str::snake
starts_with -> Str::startsWith
ends_with -> Str::endsWith
str_contains -> Str::contains
str_finish -> Str::finish
str_is -> Str::is
str_limit -> Str::limit
str_plural -> Str::plural
str_random -> Str::random
str_replace_array -> Str::replaceArray
str_replace_first -> Str::replaceFirst
str_replace_last -> Str::replaceLast
str_singular -> Str::singular
str_slug -> Str::slug
studly_case -> Str::studly
title_case -> Str::title

validator -> Validator::make

info -> Log::info

head -> reset

last -> end

resolve -> app

**Comment by bkuhl** [comment]
The value added by the methods is not having to import the façade in namespaces environments.  What's the value added by removing them?

**Comment by tomschlick** [comment]
Yeah it's hard to dislike app('instancename')->call() over \App::make('instancename')->call()
So much cleaner. 

--
Tom Schlick




On Sat, Sep 10, 2016 at 5:09 PM -0400, "Ben Kuhl" <notifications@github.com> wrote:












The value added by the methods is not having to import the façade in namespaces environments.  What's the value added by removing them?

**Comment by abellion** [comment]
@tomschlick The subject is not only about the app function (and personally I prefer using the OOP way).

All the methods proposed by @garygreen are shorter and cleaner than their related functions, and it avoid to overload the global namespace.

**Comment by taylorotwell** [comment]
Probably Str and Arr helpers will be removed in the future and classes will be preferred for those. The other helpers I am fine with.
