### ISSUE TITLE
is_empty helper function

### ISSUE THREAD

**Issue by jhowardjr** [laravel/internals#195]
Occasionally, I have to check if a long list of objects are empty. Instead of doing a long conditional statement perhaps if would be useful to have an helper function that checks if all the functions parameters are empty.  

```
 function is_empty()
 {
      $arguments = array_filter(
          func_get_args(),
          function ($argument) {
            return !empty($argument);
          }
      );
      return count($arguments) === 0;
 }
```

Use 

```
if(is_empty($foo, $bar))
{
   //do something
}
```

Instead of

```
if(empty($foo) && empty($bar))
{
   //do something
}
```

**Comment by tomschlick** [comment]
Side note: They proposed this for the core empty() function last year but was declined in it's RFC.

https://wiki.php.net/rfc/variadic_empty

**Comment by garygreen** [comment]
Suprised that RFC was declined, seems pretty nice. Lots of php functions accept variadic arguments, like `unset()`. Wonder what the reasons where for not including it.
