### ISSUE TITLE
Laravel Localization 2.0

### ISSUE THREAD

**Issue by Mevrael** [laravel/internals#2]
As discussed many times on slack Laravel today needs a full-featured support for easily making multilingual websites out of the box. Right now there are only translation files and App::set/getLocale() and many core features missing:
1. Laravel itself is not setting locale. It automatically can be done by 1st URI segment or by subdomain.
2. Routes, URLs, requests can't be easily used with translated URLs containing 1st segment like "/de", for example, redirect to url when you don't need to manually pass a locale string.
3. There is option to set default locale and fallback locale, but no way to set additional locales supported by application.
4. Laravel still uses languages instead of locales, for example, "lang" folder and not "locale" folder, "en" folder and not "en_US". There were many thoughts that it must be renamed. However, I personally not a fan of doing ab_CD and having /ab-cd/ in URL all the time. Combining languages and locales together would be the best choice. FOr example, if user wants to see page in en_GB and app doesn't support this locale we can search in language itself, "en" in this case.
5. From SEO point of view each URL should be unique. Same page in different language is a different page. Default language should not contain 1st URI segment or subdomain.
6. Switching locale system (change language menu).
7. Detecting user agent's preffered locale and redirecting if required.
8. Detecting auth user's profile locale settings if exists and redirecting if required.
9. Translated routes.
10. Translated models. Probably not needed in Laravel itself.

Now about implementation:

This is codebase I am currently using. RIght now it works only with locales set as 1st URI segment and does not works with subdomains. And it does not handle translated models.

**A.** New config `app.additional_locales` which is an array of supported languages or locales (does not include default locale). For default locale `app.fallback_locale` is used.
**B.** New methods in `Application` class:

``` php
     /**
     * Get locale prefix for URI.
     * For additional locales will return slash and locale name, for example "/de"
     * For default locale will return an empty string ""
     * Result from this method used to easily add locale to any URL
     * If first param is passed, will check against this locale. Current app locale used by default.
     *
     * @param null $locale_to
     * @return string
     */
    public function getLocalePrefix($locale_to = null)
    {
        if ($locale_to === null) {
            $locale = self::getLocale();
        } else {
            $locale = $locale_to;
        }
        if ($locale === config('app.fallback_locale')) {
            $lang_prefix = '';
        } else {
            $lang_prefix = '/' . $locale;
        }
        return $lang_prefix;
    }

    /**
     * Get all locales supported by app (default and additional)
     *
     * @return array
     */
    public function getSupportedLocales() : array
    {
        $app_locales = config('app.additional_locales');
        $app_locales[] = config('app.fallback_locale');
        return $app_locales;
    }

    /**
     * Check if app supports $locale
     * If second param $lang is true then $locale will be set to ISO2 format, for example, "en_GB" will be "en"
     *
     * @param string $locale
     * @param bool $lang = false
     * @return bool
     */
    public function checkLocale(string $locale, $lang = false) : bool
    {
        if ($lang) {
            $locale = substr($locale, 0, 2);
        }
        return in_array($locale, $this->getSupportedLocales());
    }

    /**
     * Same as checkLocale() but instead of returning bool returns $locale if supported or default locale instead.
     *
     * @param string $locale
     * @param bool $lang = false
     * @return string
     */
    public function checkAndGetLocale(string $locale, $lang = false) : string
    {
        if ($lang) {
            $locale = substr($locale, 0, 2);
        }
        if (!in_array($locale, $this->getSupportedLocales())) {
            return $this->getDefaultLocale();
        } else {
            return $locale;
        }
    }

    /**
     * @return string
     */
    public function getDefaultLocale() : string
    {
        return config('app.fallback_locale');
    }

    /**
     * @return array
     */
    public function getAdditionalLocales() : array
    {
        return config('app.additional_locales');
    }
```

**C.** New `LocaleServiceProvider` (can be placed in AppServiceProvider also) which sets app locale.

``` php
    public function boot()
    {
        // set app locale
        if (in_array($s1 = Request::segment(1), config('app.additional_locales'))) {
            App::setLocale($s1);
        }
    }
```

**D.** Locale prefix added in `RouteServiceProvider`:

``` php
    public function map(Router $router)
    {
        $router->group(['prefix' => App::getLocalePrefix(), 'namespace' => $this->namespace], function ($router) {
            require app_path('Http/Routes/routes.php');
        });
    }
```

**E.** New lang array to store translated routes, for example for en - /lang/en/routes.php
**F.** New `helpers`:

``` php
function route_url($route)
{
    return url('/' . trans('routes.' . $route));
}

// used when swithcing language or building an URL for different locale
// for example, /about can be translated to /de/about
// or if translated route is used - /about-us to /de/uber-uns
function trans_url($locale = null)
{
    if ($locale === null) {
        $locale = config('app.fallback_locale');
    }

    $route_langs = Lang::get('routes');
    $detected_route = '';
    foreach ($route_langs as $route => $route_lang) {
        if (strpos(Request::getPathInfo(), $route_lang) !== false) {
            $detected_route = $route;
            break;
        }
    }

    $new_route_langs = Lang::get('routes', [], $locale);
    if ($detected_route !== '') {
        return App::getLocalePrefix($locale) . '/' . $new_route_langs[$detected_route];
    } else {
        $segments = Request::segments();
        if (isset($segments[0]) && '/' . $segments[0] === App::getLocalePrefix()) {
            unset($segments[0]);
            //dd(App::getLocalePrefix($locale) .'/' . implode('/', $segments));
        }
        if (App::getLocalePrefix($locale) !== '') {
            return  App::getLocalePrefix($locale) . '/' . implode('/', $segments);
        } else {
            return  App::getLocalePrefix($locale) . '/' . implode('/', $segments);
        }
    }
}
```

**G.** Since all logic can't be done in service provider, for example auth user is not initiated yet or redirect can't be used there should be also new `Middleware` - `RedirectToLocale` which detects user agent's preffered locale and logged in user's locale. Field (column) can be configured.

This approach also does not use sessions/cookies. It depends on HTTP referer header which is always sent by application. When user enters site for the first time, he can be redirected, but, for example, when user switches language from menu he should not be redirected again.

``` php
    public function handle($request, Closure $next, $guard = null)
    {
        if (App::getLocalePrefix() === '') {
            if (isset($_SERVER['HTTP_REFERER']) && strpos($_SERVER['HTTP_REFERER'], $_SERVER['HTTP_HOST']) !== false) {
                // if user was redirected from app itself, do not change locale and redirect him again
                // for example, user changed language from menu and was already redirected by this middleware
            } else {
                // if user logged in, redirect to locale from user account settings
                if (Auth::guard($guard)->check() && Auth::user()->profile_locale !== config('app.fallback_locale')) {
                    return redirect(trans_url(Auth::user()->profile_locale));
                } elseif (isset($_SERVER['HTTP_ACCEPT_LANGUAGE'])) {
                    // if not logged in, check browser's preffered language
                    $lang = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);
                    if (in_array($lang, config('app.additional_locales'))) {
                        return redirect($lang);
                    }
                }
            }
        }

        return $next($request);
    }
```

**H.** Extended `Request::is()`

``` php
    public function is()
    {
        foreach (func_get_args() as $pattern) {
            $pattern = App::getLocalePrefix() . $pattern;
            if (Str::is($pattern, urldecode($this->getPathInfo()))) {
                return true;
            }
        }

        return false;
    }
```

**I.** Extended `UrlGenerator::to()`

``` php
    public function to($path, $extra = [], $secure = null)
    {
        // if $path is external, do not add lang prefix
        if (strpos($path, '://') === false) {
            $path = App::getLocalePrefix() . $path;
        }

        return parent::to($path, $extra, $secure);
    }
```

**Comment by Mevrael** [comment]
There are different opinions on should default locale always be in URL or not, i.e. if default locale is "en" should URL be www.domain.com or www.domain.com/en

I currently have a 1st option because not all apps need another language and there is no need in redirecting from / to /en.

However, probably adding new config would be better choice. Programmer will be able to choice localization format he needs. Later it could also be used to configure localization system to show locales as subdomains.

**Comment by juukie** [comment]
The way Laravel handles localization is enough for me. I don't think Laravel should support a full featured i18 system. The way people like to handle this a very different for each person and it would be better of as an optional package.
The naming of 'isLocale()' could be checkLocale() as well, of course. But for me 'checkLocale()' doesn't give me the clue it's checking for equalty with the active one. It might just be checking if it's an available one.
If your solution suits you, it's fine and keep using it. Perhaps create an awesome package.

**Comment by Mevrael** [comment]
> I don't think Laravel should support a full featured i18 system. The way people like to handle this differs for each person and it would be better of as an optional package so it won't make the framework larger than needed.

I totally agree here and don't like making things complicated. I am also not talking about implementing any aspect of i18n/l10n but only about core features like automatically setting app locale, configuring additional locales and may be something else. Also because of locales UrlGenerator and some other classes should be a bit extended.

The algorithm how you set app locale can be easily changed because this gonna be a part of laravel/laravel not laravel/framework like I separated routes to many files in RouteServiceProvider

Things become complicated when in each project I have to copy paste same such simple boilerplate, extend core classes and inject them with IoC and as a result I'm getting 2 extra codebase because of simple features. When working with another project you might see different API.

And those packages are also complicated. I preffer keeping everything as simple/maintainable as possible. Translated routes and models are not main goal, however, I came up with simple implementation for translated routes just by adding 1 file in "lang" folder. But I don' have any for models.

**Comment by mikield** [comment]
@Mevrael, you can create a packadge with your inplementation and juts `php artisan vendor:publish` your code to each new project you have. (like php artisan make:auth)

**Comment by Mevrael** [comment]
@mikield you can downgrade to Laravel 5.1 and use 3rd party package to make different auth guards, you can downgrade to Laravel 3 and use much more packages.

**Comment by Mevrael** [comment]
P.S. how do you extend `Application` and `Request` classes in package?

**Comment by devinfd** [comment]
I know +1's can be super annoying but I've got do it here. +1.  This is a feature that I've been working on for a few of my apps as well and if Laravel supported proper localization it would be wonderful.  I also don't think it needs to be a full on i18n  but it would be great if in each locale directory you could specify that locales language translations and time zone.  Another benefit of using localization over strict translation would be  the ability to define geographic regions. For example: State vs province vs county vs division and so on.

**Comment by apocalyarts** [comment]
There should also be various options for maintaining the localization arrays. One thing I actually liked about Zend 2 was the Poedit support.

**Comment by marfurt** [comment]
> The way Laravel handles localization is enough for me. I don't think Laravel should support a full featured i18 system. The way people like to handle this differs for each person and it would be better of as an optional package so it won't make the framework larger than needed.

We could say the same for ACL, Validation or Testing for example. The fact is that Laravel has many great features and I think that developers like to have those out of the box without reinventing the wheel so they can focus on their app instead of the tools.

In my opinion, localization really **is** a core feature in the sense that everyone needs it (maybe not in English-speaking countries, but there are plenty of other languages ;-) ) and it has an impact on lots of low-level parts of the framework (config, routing, database, translations,…). I think that every good framework should have tools for handling easily localization, without the need of importing third-party libraries or making its own code.

**Comment by franzliedke** [comment]
Can we break this down a bit? The biggest part of this issue seems to be route localization (and all that entails), right? I'd say model localization and other things like improving the translator itself should be discussed in separate issues...

**Comment by skyrpex** [comment]
I have a custom middleware that reads the locale from the first segment too. In my case, I implemented a custom Router, Redirector and UrlGenerator, so I can define routes like this:

```php
    Route::group(['as' => 'schedule_demo'], function () {
        Route::get('demo', ['locale' => 'en', 'uses' => 'ScheduleDemoController@show']);
        Route::get('demostracion', ['locale' => 'es', 'uses' => 'ScheduleDemoController@show']);
    });
```

The generated routes are en::schedule_demo (en/demo) and es::schedule_demo (es/demostracion).

My Redirector and UrlGenerator now accept a locale parameter.

```php
<?php

namespace App\Routing;

use Illuminate\Routing\UrlGenerator as BaseUrlGenerator;

class UrlGenerator extends BaseUrlGenerator
{
    protected $defaultLocale;

    public function setDefaultLocale($locale)
    {
        $this->defaultLocale = $locale;
    }

    public function getDefaultLocale()
    {
        return $this->defaultLocale;
    }

    /**
     * Get the URL to a named route.
     *
     * @param  string  $name
     * @param  mixed   $parameters
     * @param  string|null   $locale
     * @param  bool  $absolute
     * @return string
     *
     * @throws \InvalidArgumentException
     */
    public function route($name, $parameters = [], $locale = null, $absolute = true)
    {
        if (is_null($locale)) {
            $locale = $this->getDefaultLocale();
        }

        return parent::route("$locale::$name", $parameters, $absolute);
    }
}
```

```php
<?php

namespace App\Routing;

use Illuminate\Routing\Redirector as BaseRedirector;

class Redirector extends BaseRedirector
{
    /**
     * Create a new redirect response to a named route.
     *
     * @param  string  $route
     * @param  array   $parameters
     * @param  string|null   $locale
     * @param  int     $status
     * @param  array   $headers
     * @return \Illuminate\Http\RedirectResponse
     */
    public function route($route, $parameters = [], $locale = null, $status = 302, $headers = [])
    {
        $path = $this->generator->route($route, $parameters, $locale);

        return $this->to($path, $status, $headers);
    }
}
```

Then, the facade call ```URL::route('schedule_demo')``` will return the URL en/demo (if App::locale is EN) or es/demostracion (if App::locale is ES). I can specify a locale if needed, too ```URL::route('schedule_demo', [], 'es')```

This has proven to be very useful in my case. Hope this helps a bit.

**Comment by PatrickHeppler** [comment]
I use this route to switch locale
```php
Route::get('switchlocale/{locale}', 'LocaleController@switchLocale');
```
In the Controller I do:
```php
public function switchLocale($locale)
    {
        Session::put('locale', $locale);
        return back();
    }
````
And then I've a small middleware:
````php
 public function handle($request, Closure $next)
    {
        if (Session::has('locale')) {
            App::setLocale(Session::get('locale'));
            Date::setLocale(App::getLocale());
        }

        return $next($request);
    }
````
Works perfect for me.

**Comment by Mevrael** [comment]
- No URL translations;
- Same URL for different languages;
- Depends on session;
- Need to write custom code, not just install fresh laravel and everything works;

I can't call this "works perfect"

**Comment by josealgardataborges** [comment]
I would love to have gettext, ie PO files, support out of the box for laravel. 

As soon as you want to use other languages in your GUI, laravel localization system (arrays) becomes a issue.

As soon as you to use gender words (in portuguese for instance), we run into languages syntax issue.

Take the following examples:

- 	"The Boat" becomes "O Barco"

- 	"The House" becomes "A Casa"

This is a simple example of the localization issues i mention, arrays do not solve this in any way, gettext, as i see it, solves , and has solved, it.

Please take it into consideration that not all languages are genderless like english.

**Comment by josealgardataborges** [comment]
Also, currency and dates.

**Comment by sisve** [comment]
I cannot sit silently on this issue of Holy i18n War me and @Mevrael has started. ;)

@josealgardataborges Using gettext is currently all about calling setlocale() (the 'locale.changed' event is relevant) and calling gettext. However, I do not see how gettext would solve your gender issues. (Did that sound ... odd?) Are you talking about translating strings with placeholders, like plural forms? Could you give an example of how gettext solves it?

Some notes:
* Currencies depends on region/country, _not_ language or locale. Region needs to be determined by some magical way (ip2location, ask the user nicely, etc.)
* Date formats also varies per region/country, not language.

I'll refer to a Windows dialog that allows you to change formats of numbers, currencies, time and date separately from the UI language. This is what allows me to use english (guessing american english) for everything without falling into the pit of despair, doom and 12h datetime formats I can never really remember. 

Example: http://excelsemipro.com/wp-content/uploads/2011/06/Customize-Regional-Date-Format-1.png

**Comment by josealgardataborges** [comment]
It's not a "Holy war", but a valid need for laravel developers, already addressed in other developing environments, so i guess we can learn from them (or not).

@sisve in the case i mentioned, the "The" word in english needs to be translated into "A" (female) or "O" (male) words, for a specific language, like Portuguese. There's also the "Welcome" word, which translates into "Bem-vinda" (female) or "Bem-vindo" (male). We had, for one of our products, to use gettext .po files/syntax to address this issues.

I currently use the locale (language) to also adjust date and currency formats in the GUI. I do not use any ip2location,

As I said, "Please take it into consideration that not all languages are genderless like english.", because this small "things" matter.

I don't have a solution, I just gave my feedback as any other.

Also, "your gender issues.", in fact, sound very very odd, but no harm done. :)

**Comment by sisve** [comment]
Regarding the holy war, it was a continuation on a joke from the internals channel on Slack. Me and @Mevrael have talked about translation for some time now, and we still disagree about many things.

@josealgardataborges could you show an example of how the current translation systems fails on gender-bending words (...) and how gettext solves it? I do not see how the underlying translation system can solve such a thing without passing in gender information to the translation call.

For example, the string "Welcome $name", I do not see how that could be used with gettext to do what you want. The only solution I can think of would be to avoid the placeholder in portuguese, translating "Welcome $first_name" to "Welcome, fantastic and much appreciated user whose name we cannot output due to technical reasons" (but in portuguese).

I understand the need, but do not see how gettext could solve it. Are you mentioning grammatical genders as a thing to add to a wishlist?

**Comment by Mevrael** [comment]
I also would like to see real examples when array translation fails anf gettext solves them. There are real problems can't be solved by any simple automated translation system. I was working with gettext long time ago and don't see any advantages over simple PHP arrays which is the most popular and fastest way to translate strings.

Keep everything as simple as possible. If you need "Welcome" in english and two versions in another language, you can just create two keys, something like `users.welcome_male` and `users.welcome_female` which will be equal for english and different for some languages. In any case you will need to make a backend check for user->gender to display the correct lang string.

Anyway gettext can be used with Laravel, all you need is to set setlocale and use gettext function instead of Laravel's trans(). Right now I only may agree to set `setlocale(App::getLocale())` automatically.

Talking about currency and datetime format I totally agree with @sisve. They do not depend on locale/language. usually you should create currency select menu in your app. Datetime format can be stored in profile, for example, however, since we use Carbon, I can also set carbon's locale automatically when

**Please note everyone** that it is imposisble to cover all use cases and framework core should not do it. You will be able to easily add custom init locale logic when Laravel's locale will be set automaticaly in service provider. After installing fresh laravel version or upgrading you will have new app/Providers/LocaleServiceProvider where App::setLocale() will be called by framework. In this provider you can add setlocaleofmycooltool(); setdatetimeformat() and do whatever you will need for your specific use case.

**Comment by josealgardataborges** [comment]
@sisve I stand corrected... We only addressed the plurals and **not** the gender issues with gettext, due to PHP limitations.

I was under the impression, that the following gist was being used [https://gist.github.com/raulferras/7957177](url) **but**, in fact, there is an array manipulation taking place, as @Mevrael mentions, to achive the end result we wanted. 

We had to prefix the needed words with gender where needed (ie male.welcome and female.welcome), using the gender var of the logged in user, before outputing the string to the GUI.

@sisve Since it "seems" we cannot use the gettext Context property in PHP it would be nice to have "grammatical genders" support.

**Comment by Mevrael** [comment]
**Laravel already have [trans_choice()](https://laravel.com/docs/master/localization#pluralization)** which gives you enough power for what you need.

Let say you have a gender ID, $user->gender (0 - not set, unknown, 1 - male, 2 - female, 3 - x, ...)

English translation:
```php
'welcome' => 'Welcome :name',
```

X language translation:
```php
'welcome' => '|Welcome :name|{1}Welcome Mr. :name|{2}Welcome Ms. :name|{3}Welcome mid :name',
```
Start string with | or you will receive an exception if will try to translate for gender with ID 4 for example. Do not add starting "|" if you want to get exception.

And in controller/view:
```php
trans_choice('app/index.welcome', $user->gender, ['name' => $user->name]);
```
which will give you for X language
gender_id = 0 : Welcome name
gender_id = 1 : Welcome Mr. name
gender_id = 2 : Welcome Ms name
gender_id = 3 : Welcome mid name
gender_id > 3 : Welcome name

and for english language:
gender_id = whatever : Welcome name

**Comment by josealgardataborges** [comment]
@Mevrael living and learning... Thank you! I didn't know that, I guess all my needs are satisfied now. Please disregard all my posts above.

**Comment by mdaomega** [comment]
`trans_choice` and `trans` functions are so cool and flexible.

The thing is: 

Writing some languages in IDE and Editors are not well supported. For example, writing in _Persian_ or _Arabic_ in a text file mixed with special characters, PHP codes, and English words may break all text order, direction and decoration. And the main problem is writing and specially editing the sentences will be literally impossible. We have to copy it, paste it in some other editor, edit it, and paste it back in our IDE.

I personally prefer writing Persian sentences in some programs like PoEdit.

**I wish we could have both `trans_choice`, `trans` functions and a full featured i18 system.** That would be AMAZING.

**Comment by dakira** [comment]
@josealgardataborges 
> Also, currency and dates

Handling localization of dates falls in the area of Carbon and is being actively worked on. No framework should care about currency, though. If you need a library to handle such things, check out the works of the [commerceguys](https://github.com/commerceguys). Here's [a talk](https://www.youtube.com/watch?v=3GQCcua_qTU) summing it all up.

**Comment by Rjs37** [comment]
I agree with @juukie I think it would work best as an optional package.

On that note, I've got to say @Mevrael I thought your response to Patrick was a little abrupt. He did say "works perfect for me". It's simply an alternative way of handling localisation and his code sample may help a few people out. It has its downsides but so does route based localisation.

I handle my localisation in a very similar way. Working from sessions and user settings. If I had my database/models localised then I'd consider using route based localisation as well. But with most of my content being in the database, I'd rather not have that same content duplicated across multiple urls.

I'm not against route based localisation support being brought into the framework. Though I'd hope it'd keep in mind that not everyone who wants to use localisation will want to use localised routes.

In terms of localising dates, I currently make use of this library which extends from Carbon:
https://github.com/jenssegers/date

**Comment by iget-esoares** [comment]
Is there any idea of creating an strict mode on translations, where a Exception should be thrown if a translation key does not exists? This help a lot with big multi-language systems!

**Comment by arcanedev-maroc** [comment]
I've already created a package to manage multilingual websites. But i still waiting for Laravel to offer us a full-featured support out of the box.

\\[T]/ :pray: :sunny:

**Comment by Mevrael** [comment]
1st version of PR is now available. See references above.

**Comment by taylorotwell** [comment]
Hooks were put in place to make this much easier... notably URL::formatHostUsing and URL::formatPathUsing. These both make it easier to build localized application packages to share with the community. Also, new JSON translation files allow translations by messages instead of by keys.
