### ISSUE TITLE
Service Providers with routes

### ISSUE THREAD

**Issue by ahmedash95** [laravel/internals#201]
Hi , what about run service providers with specific group of routes like 

DashboardServiceProvider class

so i can only use this provider with group of dashboard routes 

``` php
Route::group(['prefix' => 'dashboard' , 'provider' => DashboardServiceProvider::class],function(){
    ....
});

```

**Comment by Jeroen-G** [comment]
When would you use this?

**Comment by bkuhl** [comment]
If service providers are causing so much overhead that you need to conditionally load them, they're probably doing too much.

**Comment by ahmedash95** [comment]
@Jeroen-G let's say i have menu items class, and messages & notifications list any the fixed menu in every page of my dashboard so i need DashboardServiceProvider to share these data with views so i need them in any /dashboard/.. route .. is this make any sense for you ?

**Comment by ahmedash95** [comment]
@bkuhl ya , I think i describe it at the comment above!

**Comment by Jeroen-G** [comment]
I think I would just [defer it](https://laravel.com/docs/5.3/providers#deferred-providers) then I guess.

**Comment by mattstauffer** [comment]
I would probably set a conditional in your DashboardServiceProvider so it knows when to run. It could either be aware of the routes it's appropriate for (e.g. just have the service provider check for the "dashboard" prefix), *or* I believe you can pass custom parameters to the route... something like

```php
// route
Route::group(['prefix' => 'dashboard', 'dashboard' => true], ...);
```

I can't remember the syntax right now for how to pass and retrieve custom variables from routes and route groups but i'm pretty sure it is possible.

**Comment by ahmedash95** [comment]
@mattstauffer thanks for sharing , the conditions is my only way right now , but i don't know anything about pass parameters to routes so i will check it , but is there any bad principle of use my proposal ?

**Comment by mattstauffer** [comment]
@ahmedash95 I can't speak for anyone else, but for me, every new feature introduces new complexity to the code base. More code paths, more tests, more things for people to document and learn, more ways you're making it possible to do something. So it's not worth putting something in unless it's needed. So while there may not be anything *wrong*, that's not the only metric for making a decision. Hope that helps explain my thinking.

**Comment by ahmedash95** [comment]
@mattstauffer ya it really did for me :)

**Comment by ahmedash95** [comment]
@themsaid any comment ?
