### ISSUE TITLE
[Proposal] Ability to define Notifications broadcast channel name

### ISSUE THREAD

**Issue by mikemclin** [laravel/internals#202]
Currently the Notifications broadcast channel broadcasts to a dot-separated, capitalized version of the notifiable's namespace (e.g. `App.User`).  However all of the example channel names in the docs seem to follow a lowercased basename format (e.g. `user`).

Obviously most people will want a consistent naming strategy for their channel names.  Personally, I prefer the convention in the docs, because my client app doesn't need to know about my model paths in my API.

Anyways, it would be great if there was a hook of some sort, so we could set the channel name for a notification.

**Comment by michaeldyrynda** [comment]
You can do this by returning a custom name to the `broadcastAs` method in your event class.

**Comment by mikemclin** [comment]
@michaeldyrynda That is correct.  But, I am talking about broadcasts from notifications, not events.

The channel is set via the `Illuminate\Notifications\Events\BroadcastNotificationCreated::broadcastOn()` method. Even though the method is public, we never get access to the instantiated object. The `BroadcastNotificationCreated` object is created by the `Illuminate\Notifications\Channels\BroadcastChannel` class. There are no hooks or ways in.

**Comment by michaeldyrynda** [comment]
Ah yes of course. I suppose it would be trivial to add a `broadcastAs` method within notifications that is the same as in events, then just update the `BroadcastNotificationCreated@channelName` method to check the event for the presence of a public `broadcastAs` method and return that.

It makes sense to have a consistent API.

**Comment by fgambino** [comment]
I created an issue for this a couple weeks ago, but I'm glad I'm not the only one who sees limitations with this design. 

https://github.com/laravel/internals/issues/162

**Comment by mikemclin** [comment]
@fgambino sorry, I missed that. I think your issue title might be poorly named, and possibly why it hasn't gained traction. "Allow custom notification type and channel names". I dismissed it without even opening the issue. We are already able to create and use custom notification types. The channel names for those custom types is the class name. Now, I see from the issue content, that you are actually wanting custom broadcast notification channel names, not notification channel names.

**Comment by fgambino** [comment]
@mikemclin no apology necessary. I can definitely see the confusion there. We can continue discussion in this issue!

What if a `routeNotificationForBroadcast()` method was added to the notifiable model/user? That would keep things consistent with how other routes are customized (email, slack, etc).

**Comment by stevethomas** [comment]
I think the `routeNotificationForBroadcast()` on the notifiable model would be better as `broadcastOn()` is a little ambiguous on a Notification and the route..() convention has already been set for other notification types. 

The biggest issue I have with not being able to specify a notification channel name is that it creates  overhead for every additional channel I need to listen to; for example if I am listening to 30 widgets that's 30 channel auth callbacks. 

I think a common approach would be to broadcast all activity onto the current User channel and delegate it from there. I'm not convinced that this is a great design pattern either, but it has to be better than dozens of auth callbacks.

**Comment by jamesgraham** [comment]
Is there a current workaround for this?

**Comment by uruloke** [comment]
Isn' this what the `receivesBroadcastNotificationsOn()` is for.

**Comment by SvenSchoene** [comment]
This is still unsolved: it is possible to overwrite the name of the channel that a **Notification** is broadcasting on. However, it is not possible to overwrite the **name of the event** that the Notification is sending.

The code for overriding this on an Event with `broadcastOn()` is here: https://github.com/illuminate/broadcasting/blob/master/BroadcastEvent.php#L43

The class where `broadcastAs()` should be overriden for a Notification should bere here: https://github.com/illuminate/notifications/blob/5.3/Events/BroadcastNotificationCreated.php#L10

In fact, if one adds the following code to the class:
```php
    public function broadcastAs()
    {
        return 'lol';
    }
```
A new event with the name `lol` will be sent to e.g. Pusher.

I'll keep looking, but currently I see no way to configure this from the Notification.

@uruloke: `receivesBroadcastNotificationsOn()` is the method that one puts on a **Notifiable**  in order to override the **name of the channel**, and not the name of the event.

**Comment by uruloke** [comment]
You can do this by extending the broadcasters broadcast method, so you have a custom broadcaster driver which extend eg. PusherBroadcsster and overrides the data sent to the parent broadcast method. It's a few lines of codes, and works great.

**Comment by SvenSchoene** [comment]
@uroloke: You sir, are a genius! With my new custom broadcast driver I can now add a `broadcastAs()`-method on my Notifications. Thank you very much! 👍

**Comment by uruloke** [comment]
@SvenSchoene, no problem, had that same problem and spend some time decoding how the framework did it so I could customize it.

@all: Anyone else interested in this feature, because we should be able to quickly create a pull request for this.

**Comment by a-komarev** [comment]
@SvenSchoene you can define event name since [v5.6.4](https://github.com/laravel/framework/releases/tag/v5.6.4) just return custom event name in `broadcastType` method of your notification.

**Comment by SvenSchoene** [comment]
@a-komarev Absolutely perfect, thx! 👍

**Comment by cadukiz** [comment]
Hello @SvenSchoene  could you send an example of this solution: 

"You sir, are a genius! With my new custom broadcast driver I can now add a broadcastAs()-method on my Notifications. Thank you very much!"

Because, I couldn't make it. Thanks a lot

**Comment by a-komarev** [comment]
@cadukiz read two coments above: https://github.com/laravel/ideas/issues/202#issuecomment-369428307
There is a link on a PR where changes were made. All the changes we completed with tests, so you could always look how its working in tests.

**Comment by cadukiz** [comment]
public function broadcastAs()
    {
        if (method_exists($this->notification, 'broadcastAs')) {
           return $this->notification->broadcastAs();
       }

       return get_class($this);  //  return default: BroadcastNotificationCreated
   }

**Comment by jonyw4** [comment]
I have the same problem here too +1
broadcastAs is not working!

**Comment by OleksandrVladymyrov** [comment]
@taylorotwell @antonkomarev what happened? 
broadcastAs is not working!

**Comment by antonkomarev** [comment]
@OleksandrVladymyrov method was renamed later https://github.com/laravel/framework/commit/4227bd78d5ab2743e694bfd34784a5ccced20bef

**Comment by jeanlucnguyen** [comment]
Same problem here. I'd like to change the `name of the event` being broadcasted:
From Illuminate\Notifications\Events\BroadcastNotificationCreated -> to MyCustomEvent

What we can do currently is only change the `type` in the payload of the event being broadcasted, not the name of the event itself.

When we broadcast from an Event in the app\Events folder, the name of the Event is the event itself, but there's no `type` in the payload unless we define it manually.
When we broadcast from a Notification, the name of the Event is always BroadcastNotificationCreated and we can only change the `type` in the payload.
It would be good to standardize broadcasting data being sent.

**Comment by drkwolf** [comment]
a quick fix for this, until the patch is accepted.

exclude the current implementation then import yours 

``` json
    "autoload": {
        "exclude-from-classmap": [
            "vendor/laravel/framework/src/Illuminate/Notifications/BroadcastNotificationCreated.php"
        ],
        "psr-4": {
            "App\\": "app/",
            "Illuminate\\Notifications\\": "app/libs/Illuminate/Notifications/"
        }
    },
```
cp vendor/laravel/framework/src/Illuminate/Notifications/BroadcastNotificationCreated.php app/libs/Illuminate/Notifications/

then add this to app/libs/Illuminate/Notifications/BroadcastNotificationCreated.php

``` php
    //patch
    public function broadcastAs()
    {
        if (method_exists($this->notification, 'broadcastAs')) {
            return $this->notification->broadcastAs();
        }
        return get_class($this); 
    }
```

```
composer dump-autoload
```

**Comment by infostreams** [comment]
Alternatively you can just override the 'broadcastOn' method in the Notification class.

**Comment by streamingcompany** [comment]
Hi All,

I spent hours yesterday trying to figure this out as well as I am trying to implement the broadcastAs in my Notification because it keeps sending down the BroadcastCreatedNotification as the class name. 

https://github.com/laravel/framework/discussions/33372

After looking through this thread, at this point is there any solution or workarounds? 

I appreciate your response as I new to Laravel (6 months) and learning as I go. 

Have a great day.

**Comment by streamingcompany** [comment]
> You can do this by extending the broadcasters broadcast method, so you have a custom broadcaster driver which extend eg. PusherBroadcsster and overrides the data sent to the parent broadcast method. It's a few lines of codes, and works great.

Hi,

Do you think you might take a minute and provide a code snippet on the few lines of code that would allow me to extend the broadcaster driver? This is exactly what I need. Thanks!

**Comment by sahilxjain** [comment]
Is there any way to just use the ShouldBroadcastNow on notification since i cannot extend BroadcastNotificationCreated event ?

**Comment by Yiidiir** [comment]
I isn't solved yet :( , how can we extend the broadcast driver? @olivernybroe

**Comment by viaativaweb** [comment]
Damn, 4 years and we still cannot change the notification class event name from `Illuminate\Notifications\Events\BroadcastNotificationCreated` . The 'solution' is to just overwrite everything, lol, I'd rather do an `if(payload.type == 'event')` instead if it comes to that.

**Comment by marciodsousa** [comment]
So, there was a problem reported 4 years ago, it was fixed at some point, [and then un-fixed](https://github.com/laravel/framework/commit/4227bd78d5ab2743e694bfd34784a5ccced20bef) and has been staying like that since...?

In what case does it make sense to send the event name as `Illuminate\Notifications\Events\BroadcastNotificationCreated` anywhere? This should be a really obvious thing to fix

**Comment by KenGuggelmeyer** [comment]
> So, there was a problem reported 4 years ago, it was fixed at some point, [and then un-fixed](https://github.com/laravel/framework/commit/4227bd78d5ab2743e694bfd34784a5ccced20bef) and has been staying like that since...?
> 
> In what case does it make sense to send the event name as `Illuminate\Notifications\Events\BroadcastNotificationCreated` anywhere? This should be a really obvious thing to fix

I agree that this should be reopened. What good is it to have the ability to override a Broadcast Event Name from Events but not from a Notification? Functionality should be leveraged between the two use cases.
