### ISSUE TITLE
Proposal to add two new rule to validation

### ISSUE THREAD

**Issue by muhamadzolfaghari** [laravel/internals#203]
- Laravel Version: 5.3.x
- PHP Version: 7.0.x
### Description:

**1.The "unacceptable" rule**

In some projects, depending on the type of users who use the system. It is necessary to use a feature that is in the form of _polymorphism_, for example, fields such as "activated" or "role" in the user interface is unacceptable, but in the "senior manager" should be accepted.
In the current case for it, we use the attribute "fillable" in models for filtering inputs, we can use "only" and "except" in the controller. But the main filtering should to be done at the "validation", is not available!

As is evident, in version 5.3 is a rule called "nullable" added to Laravel.
But more importantly, there should be a rule known as "unacceptable", As its name suggests That is refused entry, "unacceptable" fields. To the principles of validation and controller met in this case.

**2. Polymorphism "unique" rule**

In the current case, validation by "unique" rule, Regardless the type of method is request. One of the common problems of this rule, non-compliance with the Update method. This method needs to be smart. It is not hard. considering methods of "PUT" and "PATCH" a polymorphism "unique" rule to be defined. To meet this suggestion in standard mode or "restFul" only need to "context" and "route".

> The two cases mentioned, is an important option, which unfortunately does not exist in Laravel.

**Comment by Garbee** [comment]
"Unacceptable" sounds a lot like request authorization. What exactly would this look like and how would it differ from authorizing the request?

**Comment by muhamad12** [comment]
This method can be implemented in _two ways_:
1. A manual method
2. Based on user requests or special drivers

However, in a variety of requests to be determined, what Field **acceptable** and what is **unacceptable**.
Action to filter entries, only when validation is performed. The input filter so it is not necessary to be in the controller. 
In the second method we can use to specify user permissions Inputs that are **acceptable** or can not, be determined.

**Comment by Decadence** [comment]
I was searching for not_present rule too.

**Comment by Garbee** [comment]
Validation isn't about preventing attacks. It's only about making sure the
data you need is what you expect.

**Comment by Decadence** [comment]
@Garbee who said that? So I expect field don't present in validating array. Maybe one field should not present if another has certain value. What is bad to do some logic in validation layer?

**Comment by Garbee** [comment]
What you're saying is, "let's use validation to prevent an otherwise valid request because someone added data that shouldn't be here." It's an attack vector. There is nothing "invalid" about the actual data you care about storing with that request.

If you only get and handle the data you care about, then the request can complete fully without an issue. No need for new validation rules.
