### ISSUE TITLE
[Proposal] New Relation: HasManyViaTwoColumns

### ISSUE THREAD

**Issue by jcwatson11** [laravel/internals#205]
I came across a database structure that defined a HasMany relation between two tables that required the relation to use two keys for the join.

I am not alone in this. From a quick google search, it is clear that several others are dealing with similar issues for friendship relations.

```
Table: Project
ProjectId
```

```
Table: Area
AreaId
```

The following table joins Project and Area in a many-to-many relation

```
Table: ServiceArea
ServiceAreaId
AreaId
ProjectId
```

Project has many DataSubmissions, and belongs to an Area

```
Table: DataSubmission
AreaId
ProjectId
```

In the structure above, ServiceArea has many DataSubmissions via both AreaId and ProjectId.

Below is a starting point for a solution class HasManyViaTwoColumns. This class seems to work for all of our use cases. Thought others could use it, or perhaps be considered for inclusion in the framework.

Thank you for consideration!

```
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class HasManyViaTwoColumns extends HasMany
{

    /**
     * The second key on the far table
     *
     * @var string
     */
    protected $otherForeignKey;

    /**
     * The second key on the local table
     *
     * @var string
     */
    protected $otherLocalKey;

    /**
     * Create a new has one or many relationship instance.
     * This method is overridden to allow more constructor parameters
     * for the extra columns.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  \Illuminate\Database\Eloquent\Model  $parent
     * @param  string  $foreignKey      key on far table.
     * @param  string  $localKey        key on local table.
     * @param  string  $otherForeignKey other key on far table.
     * @param  string  $otherLocalKey   other key on local table.
     * @return void
     */
    public function __construct(Builder $query, Model $parent, $foreignKey, $localKey, $otherForeignKey, $otherLocalKey)
    {
        parent::__construct($query, $parent, $foreignKey, $localKey);

        $this->otherLocalKey = $otherLocalKey;
        $this->otherForeignKey = $otherForeignKey;
    }

    /**
     * Set the constraints for an eager load of the relation.
     *
     * @param  array  $models
     * @return void
     */
    public function addEagerConstraints(array $models)
    {
        $this->query->whereIn($this->foreignKey, $this->getKeys($models, $this->localKey));
        $this->query->whereIn($this->otherForeignKey, $this->getKeys($models, $this->otherLocalKey));
    }

    /**
     * Build model dictionary keyed by the relation's foreign key.
     *
     * @param  \Illuminate\Database\Eloquent\Collection  $results
     * @return array
     */
    protected function buildDictionary(Collection $results)
    {
        $dictionary = [];

        $foreign = $this->getPlainForeignKey();
        $segments = explode('.',$this->otherForeignKey);
        $otherForeign = array_pop($segments);

        // First we will create a dictionary of models keyed by the foreign key of the
        // relationship as this will allow us to quickly access all of the related
        // models without having to do nested looping which will be quite slow.
        foreach ($results as $result) {
            $key = $result->{$foreign}.'-'.$result->{$otherForeign};
            $dictionary[$key][] = $result;
        }

        return $dictionary;
    }

    /**
     * Match the eagerly loaded results to their many parents.
     *
     * @param  array   $models
     * @param  \Illuminate\Database\Eloquent\Collection  $results
     * @param  string  $relation
     * @param  string  $type
     * @return array
     */
    protected function matchOneOrMany(array $models, Collection $results, $relation, $type)
    {
        $dictionary = $this->buildDictionary($results);

        // Once we have the dictionary we can simply spin through the parent models to
        // link them up with their children using the keyed dictionary to make the
        // matching very convenient and easy work. Then we'll just return them.
        foreach ($models as $model) {
            $key1 = $model->getAttribute($this->localKey);
            $key2 = $model->getAttribute($this->otherLocalKey);
            $key = $key1.'-'.$key2;

            if (isset($dictionary[$key])) {
                $value = $this->getRelationValue($dictionary, $key, $type);

                $model->setRelation($relation, $value);
            }
        }

        return $models;
    }

}
```

**Comment by tomschlick** [comment]
In the above example, why wouldn't `DataSubmission` just use the `ServiceAreaID` instead of both project and area?

**Comment by jcwatson11** [comment]
Good question. DataSubmission has no column called ServiceAreaId. Changing the data model is not an option at this point. It would be better database design to add a ServiceAreaId column. However, this is not always an option in every day practice. This is one of those cases.

**Comment by jlaswell** [comment]
> It would be better database design to add a ServiceAreaId column. However, this is not always an option in every day practice. This is one of those cases.

If we're proposing to add functionality to help work around a case where better database design would solve the issue, that seems like a design smell. I don't think adding this into the framework itself is a good idea.

**Comment by jcwatson11** [comment]
Thanks for your response. I agree that my specific use case is not good database design. I can turn this into a third party package for others to use.

Unrelated to my case, but possibly related to this class, what is the status of composite key support in Laravel? Are there any plans to support multiple keys in relations?

Just wondering if any of the strategies here might be useful for that.

**Comment by lancepioch** [comment]
So I really like the core concept of this idea: being able to support more than one primary key. But instead of "TwoColumns", how about we just support composite keys in general in Laravel? If the primary key is an array, then we should assume it's a composite key.

**Comment by jcwatson11** [comment]
That would certainly be ideal for me. It seems a little daunting though, and I don't think I could spare the time to implement that, which is likely why it hasn't been implemented yet in general. Composite key support, and support for soft deletes on join tables (BelongsToMany/HasManyThrough with soft-deletes) are our two biggest wishes for this, already fantastic framework. But we can focus on one thing at a time. Composite keys would be nice.
