### ISSUE TITLE
[Proposal] Make down() method in migrations trigger when an error occurs, or include an error() method

### ISSUE THREAD

**Issue by dimkasta** [laravel/internals#208]
Just as a convenience when mapping your schema to migrations, so that you do not have to manually go and drop the changes every time an error occurs.

Or we should include a method error() in migrations where we can include calls to completely undo any partial execution.

**Comment by tomschlick** [comment]
It might be easier to wrap migrations in transactions.

**Comment by dimkasta** [comment]
It was mentioned in a discussion in Laracasts as well, but table creating and dropping cannot be rolled-back in a transaction in mysql.

**Comment by dimkasta** [comment]
Or perhaps add a column in the migrations table where on errors the migration would be marked as partially executed, so that a rollback and the down() method can still be called from artisan, even though the migration is still not considered completed.
