### ISSUE TITLE
[Proposal] Add File, Storage fakes for testing

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/internals#209]
Hi,

It would be really nice if we could have a File facade fake or storage fake.

How i see it, the fake will write files to the hard drive and then remove them at the end of the test.
This way the files created by tests will not persist on the hard drive.

**Comment by tomschlick** [comment]
This looks like it would handle what you want to do...

https://flysystem.thephpleague.com/adapter/memory/

Since laravel uses flysystem all you would have to do is change the driver for the tests.
