### ISSUE TITLE
Eloquent Query to Get Count and Rows

### ISSUE THREAD

**Issue by mavinothkumar** [laravel/internals#21]
Hi Is there any possible to get the row values and row count in a single query ? Some times we need to get the rows value and count of rows. So it will take two queries to get the result. Is there any possible to get it under one query like array first value will be count and second will be collection of rows?

**Comment by themsaid** [comment]
```
$results = DB::table()->...->get();
$count = count($results);
```

Is that what you need?

**Comment by gocanto** [comment]
I think he is talking about something like this

```
$q = Model::where('hello', 'yes')->get()->count();
````

if I am  right, this is not possible at this moment because I have seen errors when the result is ```null``` 

However, if I am wrong, I would like to know how it could be possible.

**Comment by themsaid** [comment]
`Eloquent\Builder::get()` returns a Collection and never null. So in your example `$q` will be equal to  zero or more.

**Comment by jlaswell** [comment]
This repo is actually for discussing modifying existing behaviors and feature additions in Laravel core. Can you please move this discussion to Laravel Slack or maybe posting to the Larachat forums? Worst case, you can all figure this out via email.

I would suggest closing this issue.

**Comment by themsaid** [comment]
@jlaswell you're right, just thought I could help.

**Comment by vlakoff** [comment]
If you want rows and count of these rows, just fetch the rows then count them, as themsaid answered. That's a single query. This should be closed.
