### ISSUE TITLE
[Proposal] There should be a way to add custom headers to a notification sent via mail

### ISSUE THREAD

**Issue by j3j5** [laravel/internals#214]
When sending a notification via mail, there is no way to add custom headers to it.

I understand notifications are meant to be simple messages, but for example, when using Mandrill you need to send a custom header if you want your messages to be sent through one of your subaccounts. This is impossible AFAICS for notification emails and that messes hard with my Mandrill account.

A similar function to the one on the Mailable class (withSwiftMessage) allowing to access the SwiftMessage would fix this. If the team is fine with it I'll make a PR adding this function to `Illuminate\Notifications\Messages\MailMessage` and a call to the callbacks added when running `send()` on `Illuminate\Notifications\Channels\MailChannel`.

**Comment by j3j5** [comment]
Ok, after digging up a bit more closely into the code I just realized that you can return a Mailable instance on the `toMail()` function of a notification, that would do for my use case although it isn't documented anywhere. Shall I make a PR for the docs stating that any instance of Mailable may be returned? At the moment it says _This method will receive a $notifiable entity and should return a Illuminate\Notifications\Messages\MailMessage instance. _ which is not entirely true.

**Comment by andrew-za** [comment]
Need to set custom headers on MailMessage object - but not finding a way todo this?
