### ISSUE TITLE
Add CSP to the framework.

### ISSUE THREAD

**Issue by lukasoppermann** [laravel/internals#216]
Hey,

I think laravel should include a content security policy middleware. https://en.wikipedia.org/wiki/Content_Security_Policy 

While I think it should be active by default with some sensible presets, e.g. allowing google analytics, fonts, etc. it could also be off by default to not risk any bc breaks.

If active by default it would help protect laravel projects form xss attacks by injecting stuff into the page or loading content via the console, which does happing especially in social engineering attacks.

**Changes needed**

However this means all inline scripts need to be removed. The logout button comes to mind in this context. However this should be a minimal change, moving it to a script.

**Comment by Garbee** [comment]
If provided it should be empty-by-default since if you add in "sensible defaults" you defeat the purpose of CSP which is the application itself to white-list only what it knows it needs to operate.

How would a developer add to the CSP list during the application lifecycle?  If they need to override the middleware or manually update something then that isn't really providing much benefit over simply writing your own if you need it.

**Comment by lukasoppermann** [comment]
Hey @Garbee,

I am fine with **empty by default** as well. I think you would just add a configuration file which could by default only allow the site itself.

I was just thinking if there is "fear" of confusion new developers, there could be a guess as to which sources will be used. E.g. google analytics is used by many people. I don't think this defeats the purpose, because it would still disallow anything else.

Of course, it will not be possible to really know which things are needed, so I agree that "sensible defaults" might be hard.

**Comment by yarcowang** [comment]
Adding such filter is great!!! Maybe `{{! $var_should_be_filters !}}` in the view?

**Comment by lukasoppermann** [comment]
@yarcowang I think you might have misunderstood the concept of CSP? The idea is not to add a filter for variables, it is to disallow files from untrusted sources (meaning any source you do not explicitly whitelist).

**Comment by yarcowang** [comment]
@lukasoppermann Yes, not quite understand, but if `XSS` for example, there are codes for doing the filtering. I think the website is controlled by the developer (No?), so which sources can be added into your site is decided by the developer... And for user input contents, of cause there must be a `filter` (input and/or output). Not sure your case...

**Comment by lukasoppermann** [comment]
@yarcowang you only partly control the website. You have no control over what a user puts into the console for example.

This means if a "hacker" tells your user to paste a code into the console to "activate a hidden feature" for example, this code could execute and send all of this users data to the hacker.

This is a serious social engineering attack risk, especially considering that many people building apps with laravel are building apps for non-developers who might actually do something like this.

**Comment by yarcowang** [comment]
@lukasoppermann Sounds right... Are you a developer? i think you can add it also. But please leave it disabled default. Or else i can make one in my spare time, but not sure laravel would add it or not. I'm not very familiar with the working flow on how to participate in open source project for now. :)

**Comment by lukasoppermann** [comment]
@yarcowang Yes, this can of course be added via a package.

However, frameworks guide developers and encourage best practises through using those as a default, which is why I think it should be added to the frameworks core and also be enabled by default. 

Additionally there should be a section describing how to work with CSPs.

**Comment by yarcowang** [comment]
@lukasoppermann I'm wondering how CSP deal with passing variable from php to js (considering it forbiden inline code)
```js
var api_url = '{!! $url !!}';
```
The meta data solution? ( i see github use it)
```html
<meta name="browser-stats-url" content="https://api.github.com/_private/browser/stats">
```

How about web application to set initialize values to those models? (large json data?)

**Comment by lukasoppermann** [comment]
You can control what is and what is not allowed using csp. You should not allow inline scripts, so you would need to get variables to php via data attributes or something else. 

However, you can allow inline scripts if you think it is really needed.

**Comment by Garbee** [comment]
You can allow inline scripts by providing the checksum of the inline script. Which you can compute on-the-fly for each time you make an inline script.

I would never  personally inject vars into JS. Instead, I assign data attributes to the elements where the data is needed and I then call on that at execution time. Eventually, with Web Components, it will help as well since they'll just be generic attributes on the component just the same.

These aren't points as to why to or not to implement CSP in Laravel though. Overall, it is a nifty idea but only if there is a way during app runtime to add entries dynamically. For example, some method or function call to add a domain to a ruleset. Otherwise, it is just an empty middleware that developers will need to manually update/override with a static list which isn't extremely useful to provide out of the box.

**Comment by yarcowang** [comment]
Yes, agree. CSP seems a bit complex ( https://www.w3.org/TR/CSP/#directives-fetch )
```
Content-Security-Policy: child-src https://example.com/
```
It seems a bit boring on defining those directives...low Capability/price Ratio. 
But if just add only one directive (for the whitelist domains), then i would feel too easy/small...no need a full package...Just add a user defined middleware is enough.

Em... capability/price ratio is the key, i think...

**Comment by lukasoppermann** [comment]
It would basically be a middleware with a config file, similar to the csrf middleware. Like in this package: https://github.com/stevenmaguire/middleware-csp-php

However, csrf, which is also an xss attack has a middleware, so I don't see a reason why there should not be a CSP middleware. To me it sounds like a no-brainer: easy to integrate, set it to `default-src: self`. And its secure by default.

There could be some kind of elixir thingy that builds hashes for inline scripts as well.

**Comment by BePsvPT** [comment]
https://github.com/BePsvPT/laravel-security-header, Is this package you need?

**Comment by yarcowang** [comment]
That is really very good...
But i hate i should define a lot of options to make it security.

**Comment by lukasoppermann** [comment]
I don't need a package, I am arguing for it being integrated into the framework, to encourage more people to use it and to make it easier to get started.

**Comment by BePsvPT** [comment]
@yarcowang thanks :)

CSP is highly dependent on project. In A project, it may depend on jQuery and Bootstrap. But in project B, it only depend on Vue.js.

Thus, using a default rule is not appropriate. To increase website security, setting up CSP is indispensable.

**Comment by IlCallo** [comment]
Any update on this? Or shall we rely on external dependencies?

**Comment by dwightwatson** [comment]
CSP has nothing to do with what JavaScript libraries you use on your app. It's about controlling what resources your app can fetch and talk to. I think it's reasonable that the framework ships with some sort of relatively flexible default but allows developers to customise it easily. If included as a new middleware in the app template it would let developers easily opt-out or adjust the rules as they see fit.

For the sake of comparison, Rails 5.2 will ship with a default CSP setup that's pretty loose. It's disabled out of the box but only requires uncommenting to enable. It allows connections to your own domain, assets over HTTPS and a couple of minor additions - [this is the template for reference](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/config/initializers/content_security_policy.rb.tt).

CSP seems like the sort of thing that's going to become more and more expected so I think it would be nice to have something ready to go for developers who don't even want to think about it but flexible enough for those that need more flexibility.

**Comment by sisve** [comment]
> ... to have something ready to go for developers who don't even want to think about it ...

Well, that part is already solved.

It's already flexible, anyone can create a new middleware with their own csp rules. I guess it comes down to if it is flexible _enough_.

What's the suggestion? To write a middleware that is always enabled that reads a configuration file that is fully commented out, so that people can enable the rules when needed?

**Comment by IlCallo** [comment]
The best would be to have csp configurable by a config file and all the blade directives/laravel helpers to do things (eg, printing nounce, generating hash etc).

https://github.com/mikefrancis/laravel-secureheaders
This can be a base (I'm using it with some minor tweaks).

Spatie is working on his own solution too
https://github.com/spatie/laravel-csp

**Comment by taylorotwell** [comment]
We can look at PRs that are sent. Packages also seem like a good solution though.
