### ISSUE TITLE
Log ::info calls to a seperate file.

### ISSUE THREAD

**Issue by garygreen** [laravel/internals#217]
At the moment the ::info calls get pushed into the main file, which I consider the exceptions file. It would be nice to have an option to log to a `info.txt` file which would be easier for debugging.

**Comment by tomschlick** [comment]
You could always write a custom monolog driver for this... https://laravel.com/docs/5.3/errors#custom-monolog-configuration

It just wouldn't be that common in my opinion to be part of the core.

**Comment by garygreen** [comment]
> It just wouldn't be that common in my opinion to be part of the core.

Maybe. I highly doubt most people are even using `Log::info()` at all, but when you do it's mostly for debugging and you quickly find out that it's rather cumbersome having it logged in the same file as the exceptions.

Custom monolog driver is probably the way to go though.
