### ISSUE TITLE
[Improvement] Extracting validation from RegistersUsers traits

### ISSUE THREAD

**Issue by Modelizer** [laravel/internals#219]
I think we can extract 

``` php
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:6|confirmed',
        ]);
    }
```

code to a custom RegisterUserRequest because its related to validaiton and its better to handle it outside controller. This [`$this->validator()`](https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Auth/RegisterController.php#L48) method is called on [RegistersUsers.php](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Auth/RegistersUsers.php#L29) 

``` php
public function register(Request $request)
```

so the only change here will do is 

``` php
public function register(RegisterUserRequest $request)
```

and then eliminating 

``` php
$this->validator($request->all())->validate();
```

In this way, user will have more advantage to control validation response and he only needs to make change in `RegisterUserRequest`

Sounds good?

**Comment by ctf0** [comment]
maybe something like https://gist.github.com/ctf0/bb137c135b6d9383184d4deec0b24d56

**Comment by Modelizer** [comment]
@taylorotwell if you think this is useful then please approve it so that I can submit a pull request.

**Comment by taylorotwell** [comment]
I don't think it's necessarily better to handle it outside of the controller.
