### ISSUE TITLE
Name of migration file

### ISSUE THREAD

**Issue by kamilpawlik** [laravel/internals#220]
Hi, what do you think about changing name of migration files to easier to manage? For example

1_create_users_table.php
2_update_users_table.php

and so on. There will be easier to create migrations manually?

**Comment by tomschlick** [comment]
This creates issues because you could have two developers working on separate branches that both use the same number. Using dates fixes that entirely.

What is so bad about using artisan to create the file?

**Comment by fgambino** [comment]
What about using `time()` to keep it short?

**Comment by tomschlick** [comment]
That wouldn't work because it would execute them in a non specific order. So if your have multiple migrations that depend on each other they would fail. 

--
Tom Schlick




On Thu, Sep 22, 2016 at 4:25 AM -0400, "Frank Gambino" <notifications@github.com> wrote:












What about using time() to keep it short?

**Comment by fgambino** [comment]
@tomschlick I mean using `time()` instead of the year_month_time. Example: `1474539181_create_users_table`. Correct me if I'm wrong, but I think that will be sorted correctly. It doesn't really save many characters, admittedly...

**Comment by kamilpawlik** [comment]
I'm creating application that is plugin based. Everyone can create plugin. Plugin has migration files included within of course. I don't like to force other developers to create migrations using artisan. Documentation about migrations is very clear, and everyone can create migration file, but needs artisan for it. This is not elastic solution. That's are my arguments.

**Comment by tomschlick** [comment]
Yeah the `time()` string is way less readable to me. Give me a date string and I can tell you what day/time it was generated easily, I'd have to plug a `time()` string into a converter to do that.

You should be fine to follow your own convention for migrations. I just wouldn't expect it to become the default because the current way isn't broken.

**Comment by kamilpawlik** [comment]
> You should be fine to follow your own convention for migrations. I just wouldn't expect it to become the default because the current way isn't broken.

Not at all, the `resolve` method in `Migrator` class expect only one filename pattern

**Comment by fgambino** [comment]
For reference, here is how the class name is currently deduced from the file name:
`Str::studly(implode('_', array_slice(explode('_', $file), 4)))`

I don't see this convention changing at all.

@tomschlick I haven't found a reason to know when a migration was created, so it doesn't matter to me personally. I can see why people may like it though.

**Comment by fgambino** [comment]
Created a PR: https://github.com/laravel/framework/pull/15559

**Comment by garygreen** [comment]
This is a bad idea just asking for trouble. Removing a well defined date-naming convention keeps things consistent for all developers and packages. If you have a custom format for your app, it creates fragile migration files that can no longer be migrated in a reliable order.

**Comment by tomschlick** [comment]
I agree @garygreen. Typing out a date is a small price to pay for the sake of consistency.

**Comment by fgambino** [comment]
The only consistency the current code provides is ensuring there are 4 underscores before the class name. `____class_name` is valid. The restrictions should be tightened to the exact date format, or be removed completely as in the PR.

**Comment by garygreen** [comment]
> The only consistency the current code provides is ensuring there are 4 underscores before the class name. ____class_name is valid. The restrictions should be tightened to the exact date format, or be removed completely as in the PR.

I was surprised too to find that Laravel doesn't have a tighter regex. I would suggest a PR to do that for 5.4.

**Comment by fgambino** [comment]
Thinking about it more, I agree with tightening the regex. Publishing migrations from packages completely slipped my mind.
