### ISSUE TITLE
Default timezone for Scheduler

### ISSUE THREAD

**Issue by HipsterJazzbo** [laravel/internals#221]
I'd love to be able to set a default timezone for the Scheduler. As it is, I have to set the timezone for each and every thing I schedule.

**Comment by seanmangar** [comment]
Hey Hipster. If I'm not wrong, isn't there a timezone setting in config/app.php?

**Comment by HipsterJazzbo** [comment]
There is, but unless I'm missing something it's not use for the scheduler. Also, I need to schedule things to happen in a timezone different than the one for the app in general.

**Comment by taylorotwell** [comment]
Fine with me if someone wants to work on it.
