### ISSUE TITLE
[5.4] Register the core laravel service providers inside the framework itself

### ISSUE THREAD

**Issue by garygreen** [laravel/internals#222]
The core laravel providers are in `app.providers` and they are essential to the functioning of the framework. How come it's even an 'option' to remove them? 

With almost every laravel upgrade there is a guide on changing these providers deleting or adding new ones.

If they were registered in the core of Laravel itself it would massively simplify the app file and remove fragile breaking changes in the framework during upgrades.

**Comment by tomschlick** [comment]
Eh I disagree. 

While things like the routing provider are necessary, others such as session are not if you are building something like an API that needs more than Lumen can provide. 

Also by defining them in the config, you gain the ability to override a provider to add in your own hooks.

**Comment by garygreen** [comment]
> Also by defining them in the config, you gain the ability to override a provider to add in your own hooks.

This slipped my mind completely, I haven't had to do that in a while. It would still be possible to have a custom provider override a core one, though -- provisions for that could be made in core.

You could in theory run without certain services providers and get away with it, but I mean really - who does that? Why would you risk doing that? Packages work on the assumption that the whole core Laravel features are available. If your running Laravel, you should have access to all of Laravel imo.

**Comment by fgambino** [comment]
I run one of my APIs with cookies, sessions, and a few other services disabled, so this flexibiloty is needed. However, I'd guess most people keep everything enabled, so perhaps another service provider can be made that registers all of service providers in the framework?

**Comment by garygreen** [comment]
> I run one of my APIs with cookies, sessions, and a few other services disabled, so this flexibiloty is needed. However, I'd guess most people keep everything enabled, so perhaps another service provider can be made that registers all of service providers in the framework?

Yeah that would be an idea - `Illuminate\Foundation\LaravelServiceProvider` - this would suit 99% of users but if you do want to disable a provider for whatever reason, you can copy the providers and put them in your `app.php`, if that floats your boat. 😄

**Comment by sebastiandedeyne** [comment]
Related: I wouldn't mind simplifying the app file by moving `providers` and `aliases` to their own config files.

**Comment by fgambino** [comment]
I'm afraid that a "god" service provider would hide important framework details from new developers though.

**Comment by tomschlick** [comment]
+1 to @sebastiandedeyne 

A seperate config for each might be good. Keeping the default `config/app.php` to commonly changed things would make sense IMO.

**Comment by tomschlick** [comment]
A `config/providers.php` and a `config/aliases.php` would be easy to add and would be an easy transition in the upgrade process to 5.4

**Comment by garygreen** [comment]
> I'm afraid that a "god" service provider would hide important framework details from new developers though.

Not what what you mean by hiding important framework details - new developers are looking at the docs to know what's available in laravel - they don't 'look at the providers and go "Ahhh I understand.". I would argue the `app.providers` is more for seasoned developers who want to hack into Laravel core providers, not for new developers at all.

> Related: I wouldn't mind simplifying the app file by moving providers and aliases to their own config files.

Sounds kinda cool but `app` has been used to define providers / facades since god knows when and people are familiar with it, so I'm not sure it's worth it. It's not really "simplifying" it - it's just segmenting it, simplifying it would be to move the core providers into laravel itself 😛

**Comment by joshmanders** [comment]
With the introduction to this PR https://github.com/laravel/framework/pull/19420 I wonder, why is providers and aliases even in the `config/app.php`? It feels weird that I register providers in config files.. Why not have these inside `app/Providers/AppServiceProvider.php`, as that seems like the best place to say "These are what are needed to bootstrap the app."
