### ISSUE TITLE
[Feature] Ability to remove a specific event listener.

### ISSUE THREAD

**Issue by rulatir** [laravel/internals#224]
It is currently impossible to subscribe to events temporarily (e.g. debug that one single query).

I request that `Dispatcher::listen()`, instead of being `void`, return a closure that could be called to remove that specific listener. Alternatively a new method could be added like `Dispatcher::listenTemporarily()` to keep the `listen()` API intact.

**Comment by vedmant** [comment]
Yeah, something especially important for long running commands, like queues.

**Comment by sebastiaanluca** [comment]
Needed this a few times, so came up with a hacky solution (I wouldn't use it in production). The following removes a single event listener from all events. Requires the `opis/closure` package. I'm sure those that need to unbind multiple events can extend this piece of code. Share it if you do!

```php
<?php

declare(strict_types=1);

namespace App\Providers;

use Closure;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\ServiceProvider;
use Opis\Closure\ReflectionClosure;

class EventServiceProvider extends ServiceProvider
{
    public function boot() : void
    {
        Event::macro('removeListener', function (string $listener) : void {
            foreach ($this->listeners as $eventName => $eventListeners) {
                foreach ($eventListeners as $closureIndex => $closure) {
                    $reflection = new ReflectionClosure($closure);

                    $reflection = $reflection->getUseVariables();
                    $inner = Arr::get($reflection, 'listener');

                    if ($inner === null || $inner instanceof Closure || $inner !== $listener) {
                        continue;
                    }

                    unset($this->listeners[$eventName][$closureIndex]);
                }
            }
        });
    }
}

```

**Comment by modstore** [comment]
We have to use a similar workaround for this. We have an account scope that gets applied on queued jobs, and we have account specific listeners that need to be registered before and destroyed at the end of the job. It would be great if there was a nicer way to do this.

**Comment by guice** [comment]
I came here just for this. I'll at this patch job (for now).
