### ISSUE TITLE
Capsule with bootEloquent(), setAsGlobal() using beginTransaction()

### ISSUE THREAD

**Issue by jgrossi** [laravel/internals#23]
Hi all!

I'm using Capsule Manager to boot some Eloquent models, without Laravel. It's used inside some unit tests and I need to rollback the changes that are made. All my unit tests classes extends my own `BaseTest` with `setUp()` and `tearDown()` methods, where I begin transactions and make the rollback.

First I tried to get Capsule as global but `Capsule::connection()->beginTransaction()` and `->rollBack()` is not working.

``` php
protected function setUp()
{
    foreach ($this->dbConnections as $name) {
        Capsule::connection($name)->beginTransaction();
    }
}

protected function tearDown()
{
    foreach ($this->dbConnections as $name) {
        Capsule::connection($name)->rollBack();
    }
}
```

Second I tried to begin transaction and roll inside my Eloquent model like:

``` php
$comment = new Comment;
$comment->getConnection()->beginTransaction();
// ... code
$comment->save();
$comment->getConnection()->rollBack();
```

No success in both cases.

Any suggestion?

Thanks.

**Comment by themsaid** [comment]
Closing since it's a question not a proposal.
