### ISSUE TITLE
How to override MandrillTransport send message for Templates

### ISSUE THREAD

**Issue by fakharkhan** [laravel/internals#232]
Hi i am looking for a solution to modify/override MandrillTransport class send function to use 
"send-template.json" api instead of "send-raw.json"
So that i can keep the notifcation system but just tell laravel to override Mandrill Api Method.

Thanks in advance for helping me.

**Comment by tomschlick** [comment]
This really isn't a support forum for Laravel. This is a forum to discuss new features / collaborate on Laravel's future development.

You should post this on the official laravel / laracasts forums. 

However I will suggest that you look into creating a custom driver for mandrill. With that you can use the template API instead.
