### ISSUE TITLE
Proposal elasticsearch

### ISSUE THREAD

**Issue by obb12** [laravel/internals#236]

**Comment by tomschlick** [comment]
uh... wut?

**Comment by obb12** [comment]
Better elasricsearch support

**Comment by mikerockett** [comment]
https://packagist.org/packages/cviebrock/laravel-elasticsearch

**Comment by tomschlick** [comment]
also https://github.com/laravel/scout

**Comment by constb** [comment]
also https://github.com/elasticquent/Elasticquent
