### ISSUE TITLE
Soft delete / global scope improvements

### ISSUE THREAD

**Issue by kamui545** [laravel/internals#237]
Tell me if I'm wrong on this one and there's a better solution but even if soft delete is awesome, it can also be really annoying to deal with when you want to disable it.

Here's my use case, I've got a lot of models using soft delete that I need on the "website" but need to disable for the "admin" section.

The first issue is, this is troublesome to pass `withTrashed()` to every queries and needing to have the same relationship duplicated with it too.

``` php
# app/User.php

public function comments()
{
    return $this->hasMany(Comment::class);
}

public function anyComments()
{
    return $this->hasMany(Comment::class)->withTrashed();
}
```

The second issue is, when using model binding, I need to bind the same model using a different name, and to pass a closure disabling the soft delete feature like the following:

``` php
# app/Providers/RouteServiceProvider.php
Route::model('user', User::class);
Route::model('anyUser', User::class, function ($id) {
    return User::withTrashed->findOrFail($id);
});

# routes/web.php
$router->get('/users/{user}', 'UsersController@show');
$router->get('/admin/users/{anyUser}', 'Admin\UsersController@show');
```

The code is not DRY anymore and if we had a more global way to disable/remove the global scope, we could even share code between "web" and "admin" making it easier to maintain.

We've got `Model::addGlobalScope()` but I don't see any `Model::removeGlobalScope()` or `Model::disableGlobalScope()` that we could use in a middleware to disable for the models we need.

Once again, maybe I'm totally wrong and missed something in the documentation or did not dig enough in the core. We could imagine doing this the other way and adding the global scope "on the fly" instead of removing/disabling it, but I think the other way is also worth considering.

**Comment by kamui545** [comment]
Maybe two ways we could achieve this:

Solution 1:

- Add `Model::removeGlobalScope($scope)` in Model.php
- Listen `eloquent.booted:modelName` event in a middleware and remove the global scope.

Solution 2:

- Fire a `eloquent.loaded:modelName` event in `Model::newFromBuilder()`
- Listen this event and add the `withTrashed()` to the query.

**Comment by shy7lo** [comment]
One of the issue I faced with soft delete is with unique field validation. If i soft delete a row, and if I have a unique field validation, then I can't add a new record with the same unique field value. 
If may be great to have a check not to check the soft deleted values, but i think it wont be a good idea.
