### ISSUE TITLE
Should touch owners after performed deleting

### ISSUE THREAD

**Issue by tsctao** [laravel/internals#240]
In case of deleting item of sales order, it should touch owner (sales order) to update the number of items after deleted the item.

**Comment by barryvdh** [comment]
That is specific for you application. If you need that, just touch() them yourself (eg. in an event handler, Model::updating() etc.)

**Comment by tsctao** [comment]
I think it should trigger like creating and updating that touch owners after successful creating/updating.

**Comment by bobbybouwmann** [comment]
Like barry said this is application specific. 

Let's say we have a user who has multiple blogs. When I deleted a blog I don't want the user to be touched since the user never changed, only it's related item.

**Comment by tsctao** [comment]
I mean to say if I assign touches variable in model to touch the related model, creating and updating action touch the related model after created/updated but deleting action touch the related model before deleted. This is the point I don't understand.
