### ISSUE TITLE
Job Rate Limits

### ISSUE THREAD

**Issue by tomschlick** [laravel/internals#242]
Would anyone else be interested in rate limits for jobs? I haven't done any coding on this yet but have had the concept in the back of my mind for a while.

The way I see it, you'd be able to define a rate limit on a job class. So if I set it as 20 jobs per hour (of that specific type) it would throw those jobs back onto the queue with a delay until it can try again.

This could be useful for querying 3rd party APIs or rate limiting customer's so they don't overwhelm your queue with background jobs.

**Comment by brayniverse** [comment]
This sounds like a great idea.

**Comment by tomschlick** [comment]
Now to just figure out how to code the damn thing... :)

**Comment by bkuhl** [comment]
Is there a use case where you'd want to limit the amount of work done on a queue?

**Comment by tomschlick** [comment]
Not on a queue as much as per job. You may want to do this to avoid hitting API limits on a third party, for QoS between customers, or to throttle things like emails which can trigger spam filters if too many send too quickly.

**Comment by tomschlick** [comment]
This may be easier now that #290 has been integrated into the framework.

**Comment by themsaid** [comment]
This PR would allow  you to rate limit anything including Jobs: https://github.com/laravel/framework/pull/20597
