### ISSUE TITLE
Allow alternative filename for composer.json

### ISSUE THREAD

**Issue by andzandz** [laravel/internals#243]
Composer specify that you may use an alternative filename for composer.json:
https://getcomposer.org/doc/03-cli.md#composer
At IFP we find this useful as we have sites with shared code; the shared code is in a "base" package. The "base" package (which each developer can use different branches of) is developed at the same time as the site-specific code, so we use a number of different composer.{x}.json files to specify a different branch of the "base" package for each developer.

An example:

```
$ mv composer.json composer.X.json
$ export COMPOSER=composer.X.json
This works fine:
$ composer update
But artisan make:x commands will complain that composer.json does not exist:
$ php artisan make:mail MyMail
```

I have made a PR for this in laravel/framework here: https://github.com/laravel/framework/pull/15849

Oops, I originally posted this issue to laravel/framework - this seems a more appropriate place.

Thanks!

**Comment by tomschlick** [comment]
This seems like an extremely specific use case. I have never even seen it done in the wild.

**Comment by michaeldyrynda** [comment]
It does seem extremely specific, but it doesn't look like too much trouble to implement it either.

I'd just use `env('COMPOSER', 'composer.json')` inline, rather than the current ternary check, though.

**Comment by andzandz** [comment]
Hi michaeldyrynda, agreed, changed. It was so obvious that I missed it. I usually use the PHP7 ?? operator, but Laravel needs to run on PHP 5.6.

**Comment by franzliedke** [comment]
Sorry for the shameless plug, but this seems like something that [my Studio package](https://github.com/franzliedke/studio) could help you with. It works as a Composer plugin that allows you to configure local path repositories (including Composer dependencies from a local directory rather than Packagist) without touching composer.json.
