### ISSUE TITLE
Laravel CLI Base Project

### ISSUE THREAD

**Issue by alexbowers** [laravel/internals#246]
The ability to use Laravel as a non-http project would be useful.

Aim:

- [ ] Accessing via HTTP will not respond
- [ ] Broadcasting is not available
- [ ] Session is not available
- [ ] View is not available
- [ ] Auth (?) is not available
- [ ] HTTP middleware, controllers etc removed.
- [ ] No default views
- [ ] No default css, js etc
- [ ] gulp and package.json not required
- [ ] No public folder
- [ ] No Routes (except console.php)
- [ ] Exceptions are handled and rendered for CLI 
- [x] Irrelevant commands removed (route:*, make:{auth, controller, middleware, request}, serve, auth:*, view:clear)

**Comment by alexbowers** [comment]
WIP Implementation: https://github.com/laravel/framework/pull/15859

**Comment by alexbowers** [comment]
Taylor doesn't want this in core, so i'll try to create it as a separate project entirely.

**Comment by Modelizer** [comment]
But why would someone will use Laravel as a CLI project?

**Comment by alexbowers** [comment]
Because Laravel has a lot of nice features, which are useful outside of a http/web based framework. For example, queueing, caching, database, Eloquent / ORM, Jobs, etc.

The benefit of Laravel is that its simple to use, and has a lot of useful features already available. The alternative for a CLI project would be to either use Symfony console itself, where you have to get these features implemented individually.

**Comment by Modelizer** [comment]
How eloquent will come in the picture where there is no frontend. And I think a user will not use CLI directly.

Right now I'm trying to understand the usage of Laravel-CLI project. In which scenario people will use Laravel-CLI as a base framework.

**Comment by alexbowers** [comment]
There is no frontend requirement for Eloquent; it is simply an ORM. 

For the purposes of a couple of projects im planning, the end user is not a standard user, but rather a developer. The CLI is a perfectly acceptable UI for these projects. I'm not saying that the CLI framework would be useful in all situations, but there are situations where a full HTTP endpoint isn't available, or acceptable for specific projects, but access to manage and control a database would be useful.
