### ISSUE TITLE
seeJsonEquals sorts normal arrays (against JSON specification)

### ISSUE THREAD

**Issue by vissermc** [laravel/internals#248]
The JSON specification states that the order of elements in an (non-assoc) array are preserved.

However, seeJsonEquals seems to sort the values of non-assoc arrays, leading to incorrect asserts or false posititives.

Example:

Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'{"columns":["common_id","name"],"rows":[["Admin",1.123456]]}'
+'{"columns":["common_id","name"],"rows":[["1.123456","Admin"]]}'

**Comment by nattvara** [comment]
Happens to me to

```
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'{"message":{"id":21,"public_id":"70520b688","text":"foo","attachments":"{\"foo\":\"bar\"}","created_at":"2017-03-10 11:08:26","updated_at":"2017-03-10 11:08:26","team_id":216},"status_code":200}'
+'{"message":{"attachments":"{\"foo\":\"bar\"}","created_at":"2017-03-10 11:08:26","id":21,"public_id":"70520b688","team_id":216,"text":"foo","updated_at":"2017-03-10 11:08:26"},"status_code":200}'
```


Re-encoding expected $data to json, then decoding with convert to associative array set to true seems to solve the problem

<code>in /vendor/laravel/lumen-framework/src/Testing/Concerns/MakesHttpRequests.php</code>

```
    /**
     * Assert that the response contains an exact JSON array.
     *
     * @param  array  $data
     * @return $this
     */
    public function seeJsonEquals(array $data)
    {
        $actual = json_encode(array_sort_recursive(
            json_decode($this->response->getContent(), true)
        ));

        $data = json_encode(array_sort_recursive(
            json_decode(json_encode($data), true)
        ));

        PHPUnit::assertEquals($data, $actual);

        return $this;
    }
```

**Comment by rybakit** [comment]
@nattvara Sorry to comment on a closed issue, but I ran into the same problem and do not see how your fix helps in @vissermc case, his example will still produce a false-positive result. Or did I miss something?

Here is a quick test:

```php
$this->response->setContent('{"cols":["id","name"],"rows":[[123,"Admin"]]}');
$this->seeJsonEquals(["cols" => ["id", "name"], "rows" => [["Admin", 123]]]); // should throw but it doesn't
```

@taylorotwell Could this issue be reopened?
