### ISSUE TITLE
Authentication of users in multi-tenant website where each tenant has multiple users

### ISSUE THREAD

**Issue by aisha90** [laravel/internals#249]
I am trying to implement authentication process for a multi-tenant site where we will have different companies registered for example: company 1, company 2 and etc and each company will have multiple users like company 1 will have User1, User2 and so on.

Here, I am using separate database for each company due to some strong reasons. I want the user to visit the site and just authenticate himself without using any separate domain. There will be a different domain for each company (e.g company1.mysite.com), but the user will be redirected to his respective domain after login.

So, my question is, how can I authenticate each user from his respective database at the time of login?
Or I have to use sub-domain approach in order to achieve the target? Should I use one tenant account and tied his respective users to his main account using MultiAuth, will it be a good idea?

If there is any better approach than this one, please share it.

**Comment by jacurtis** [comment]
I think stackoverflow would be a more appropriate place for this question. You'll also probably find that you get an answer much faster over there.

**Comment by Modelizer** [comment]
@aisha90 you can use `user@company` and can make a dynamic DB connection on basis of `company`.

And I also agree with @jacurtis
