### ISSUE TITLE
Route domain wildcard

### ISSUE THREAD

**Issue by tomadmiraal** [laravel/internals#251]
Hi all,

I'm having a problem with the domain option in routes. It is posible to create a variable domain by using {domain}.{tld} for example. In that case you have to declare segments and it will only allow a certain structure. When a .co.uk domain is passing by (domain.co.uk) the variable option doesn't fit.

In my case I will allow all domains with www. in front of it for a routegroup. whats behind www doesn't matter ("domain.com", "domain.co.uk", "sub.domain.co.uk").

I've tried an asterisk ('www.*') but that didn't work. There are no docs available and as far as I can see, this wildcard option is not available.

Question: is there a way to use a wildcard without declaring segments? if not, isn't it a nice feature for laravel to have?

**Comment by theomessin** [comment]
I believe that currently there is no way of using wildcards. However, what I usually do is use the APP_URL environment variable, strip the `https://` (if you're still using http then shame on you 😝) and concatenate it to my subdomain. This way, all my routes can be subdomain specific and simultaneously domain agnostic.

**Comment by tomadmiraal** [comment]
Hehe, yes we are using SSL ;)

Right now I'm exploding HTTP_HOST and use the parts. but in my opinion it's a dirty way.

There are more parts within routes where you can use Regular Expressions. Wouldn't it be nice to be able to use Regular Expresions in the domain part?
