### ISSUE TITLE
laravel Document URL not found

### ISSUE THREAD

**Issue by tetsuyusan** [laravel/internals#256]
https://readouble.com/laravel/5.1/ja/validation.html
in
http://svn.apache.org/repos/asf/httpd/httpd/trunkmime.types.html

This url is not found.

**Comment by Garbee** [comment]
The site linked to doesn't seem to be an official Laravel site at all. Therefore there isn't anything we can do about that. You need to get in touch with the person or group that manages that site so they can address it.

**Comment by tetsuyusan** [comment]
Oh,sorry...
