### ISSUE TITLE
[Idea] Make console commands environment "aware"

### ISSUE THREAD

**Issue by tyloo** [laravel/internals#259]
This is just an idea, but I'll try to explain it well: I think it would be great to have the list of your commands when typing `php artisan` based on the current environment. Indeed, when you are in production, you don't really need the `make` commands and It's in my case sometimes difficult to fetch threw the list (I use `| grep` to achieve this). I wanted to talk about it with Taylor at the last Laracon EU but couldn't find time ;)

Let me know what you guys think about it.

Cheers!

**Comment by clinoge** [comment]
I'm not sure as to whether this would be useful. Not saying it's a bad
idea, just that I would oppose to such change, maybe it could be
included as an opt-in argument?

**Comment by shez1983** [comment]
i agree.. but you should still be able to use those commands using --force arguement etc..

btw php artisan migrate already gives you a warning for production..
