### ISSUE TITLE
Handling option dates

### ISSUE THREAD

**Issue by TheShiftExchange** [laravel/internals#262]
Is there a better way Eloquent could handle 'optional' dates?

Lets say we have a `users` model with a `dob` (date of birth) column that is optional.

First of all - we need to be able to handle the input optionally. If you dont, you get a `InvalidArgumentException - Data missing` error.

So I find myself duplicating this type of code in my models:

```
class User extends Eloquent {

    protected $table = 'user';
    protected $dates = ['dob'];

    public function setDobAttribute($value)
    {
        if (strlen($value)) {
            $this->attributes['dob'] = Carbon::createFromFormat('d/m/Y', $value);
         } else {
             $this->attributes['dob'] = null;
         }
    }
}
```

Then separately when trying to display that data - this will not work:

```
@foreach (User::all() as $user)
    {{ $user->dob->format('d/m/Y') }}
@endforeach
```

...because you will get a `Call to a member function format() on a non-object error` if the `dob` column is null.

So that means you need to always pass this variable into a helper to filter it for `null` values, or you need to manually add `getter` methods for all your date variables.

I find I come across this issue a lot. And googling around it seems that other people do to. Surely there has to be a better way?

**Comment by drbyte** [comment]
Instead of 
```
    {{ $user->dob->format('d/m/Y') }}
```

I've used something akin to the following:
```
    {{ $user->dob ? $user->dob->format('d/m/Y') : '' }}
```

Unfortunately it's the opposite condition for what the PHP7 Null Coalesce Operator `??` offers, so can't use that instead.

Alternatively I've sometimes skipped using `User::all()` and instead used `User::hasDates();` and set a `scopeHasDates()` method on the model, so I only get records with a non-null date (or whatever else I scope it to).

**Comment by TheShiftExchange** [comment]
Yeah - I do something similar.

But given optional dates would likely be a very common thing for many people - I'm wondering if this can be baked into the framework by default somehow?

**Comment by Garbee** [comment]
It is difficult to abstract something like this away. If you have `null` stored for the date, then what is the date/time you put into the carbon instance? You *need* to have *something* stored within it, not null. You then would have no real way of knowing if what you are calling for is the actual stored data or the "default" data for `null`.

I think in terms of Laravel, this is a non-issue that you need to find your own way to abstract out in your application. (Personally, I use twig so the date filter there so null just doesn't output anything.)

However, this discussion may be something to bring up with Carbon to see if anyone there has an idea for how a nulled value within a carbon instance can be handled cleanly. If Carbon builds a way to handle this so you can call methods against an object with no data, then Laravel could later upgrade to use that and handle the storage piece transparently within Eloquent.

**Comment by tomschlick** [comment]
This is what I do for the display of the date. Basically in the view I do this https://gist.github.com/tomschlick/ae9d468ad56dbf70e58cf0088cbd14c0

```{{ $model->displayDate('created_at') }}``` on any model that implements the `NullableDate` trait. Not a perfect solution but seems to work 99% of the time for display.

**Comment by TheShiftExchange** [comment]
@Garbee - but what about for Input? If the value is optional in the DB, but you dont pass one in, you get a `InvalidArgumentException - Data missing` error - that is an eloquent/laravel isssue - not Carbon.

@tomschlick - that looks cool! I've use that. Maybe we could have an optional trait like that in the framework, not sure?

**Comment by Garbee** [comment]
>but what about for Input?

Can you give an example of the situation that causes this? I've set plenty of dates to null and it doesn't give me an `InvalidArgumentException`.

**Comment by tomschlick** [comment]
@TheShiftExchange for input you should be using the `$casts` array instead of casting it manually with attribute methods

**Comment by tomschlick** [comment]
https://laravel.com/docs/5.3/eloquent-mutators#attribute-casting

**Comment by TheShiftExchange** [comment]
Are you using the `$dates` method to set the eloquent field to a date, or only using `$casts`?

**Comment by tomschlick** [comment]
$dates can be removed entirely now that $casts exists

**Comment by tomschlick** [comment]
but the behaviour should be the same between the two, they both use the `asDateTime()` method internally

**Comment by TheShiftExchange** [comment]
Ok... I see the problem. The `asDateTime()` is hard code for date formats:

```
        if (preg_match('/^(\d{4})-(\d{1,2})-(\d{1,2})$/', $value)) {
            return Carbon::createFromFormat('Y-m-d', $value)->startOfDay();
        }
```

I'm using dates with `d-m-Y` (which is how we do it in Australia).

So if you dont give eloquent a `Y-m-d` - it wont work.

So we need to have a configurable value for `Y-m-d` in the model? i.e. I should be able to say what format I'll be passing the dates in?

**Comment by Garbee** [comment]
That shouldn't be triggered with the year last. As the year should be 4 digits long and that is being checked for in the *first* position by the preg check.

You can override the `$dateFormat` property and that should do the trick. Tell it the format is `Y-m-d` by the property. Then the final return clause should trigger (as that preg check shouldn't!) and it will use the models date format to do the initialization.

**Comment by TheShiftExchange** [comment]
Yeah - thats it - use `$dateFormat`.

Ok - thanks all - appreciate it.
