### ISSUE TITLE
Migrations to use one single file like Symfony

### ISSUE THREAD

**Issue by rsands2801** [laravel/internals#263]
Can laravels migrations code be updated to run like Symfony i.e. one file of truth.

Laravels migrations with multuple files for one table leads to multiple sources of truth.  It is unneccessary and messy to have multiple files just to see how a table should look

**Comment by tomschlick** [comment]
It would help if you could provide some links / examples as to how symfony's migrations work.

**Comment by barryvdh** [comment]
Funny that they recommend migrations over that ;)

http://symfony.com/doc/current/doctrine.html#creating-the-database-tables-schema
> Actually, this command is incredibly powerful. It compares what your database should look like (based on the mapping information of your entities) with how it actually looks, and executes the SQL statements needed to update the database schema to where it should be. In other words, if you add a new property with mapping metadata to Product and run this task, it will execute the "ALTER TABLE" statement needed to add that new column to the existing product table.
> 
> An even better way to take advantage of this functionality is via [migrations](https://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html), which allow you to generate these SQL statements and store them in migration classes that can be run systematically on your production server in order to update and track changes to your database schema safely and reliably.

**Comment by JamesGuthrie** [comment]
I don't really like this suggestion much at all. I have also found it a little confusing at times to figure out exactly what is in the DB due to the 'multiple sources of truth'.

The benefit that having multiple migration files provides is that you can actually migrate the data in the table as well (not just the schema). For instance if I add a new column to a table, I can run a couple of queries to populate the value for all existing rows in the table. This wouldn't be possible in a single-file-of-truth setup.

**Comment by rsands2801** [comment]
Its a suggestion guys.  I don't like the idea of application code controlling a database as that's not really the codes job in large scale applications

@JamesGuthrie Populating columns in a migration seems a bit risky i.e. a migration controlling live data.  You mention you don't like single source of truth but don't like having to look through multiple sources of truth.

@barryvdh Symfony does suggest this but their migrations are even smarter again...they can run migrate:diff (i know laravel doctrine has some capabilities for that) that allows one source of truth to programmatically generate migrations in sequence.  

I forgot to mention my reasoning behind this is during the initial development phase of a new program where things can and do change as it gets developed pre launch the number of alters being run ends up a big mess.  Maybe if we could namespace migrations would certainly help e.g. namespace "create" and "alter" separately in the migrations folder

**Comment by JamesGuthrie** [comment]
During the pre-launch development phase I just updated the migrations in place. I had to reset the whole database after each change, but it prevented having a huge number of migrations. As you say, during initial development things change a lot. I'm not sure if you're in the situation where you can do this, but I was.

**Comment by rsands2801** [comment]
@JamesGuthrie I definitely agree with you in that workflow - i use to get away with it but as I am part of a bigger team now it tends to cause issues as they don't like resetting each time.  I am currently updating the original create migration and all is nice and tidy but once you deploy to repo another dev will struggle on his/her local database.  I guess that's where an option to have single or multiple files would be a nice feature to have for the pre launch phase.

**Comment by tomschlick** [comment]
Migration files give you a lot more control over exact command & the order in which they execute in. They also let you move data around instead of just changing schema. 

If you're worried about the # of migration files, you can always do a rollup of them every so often. Basically migrate your database, dump a schema file + the content of the migrations table and have that run before your :migrate command. That way only the new migrations will run.

**Comment by rsands2801** [comment]
@tomschlick that is what we currently do but if a dev has not run migrate before we do that then it breaks still.  Its just a feature that Symfony has alot more power with and Laravel is somewhat lacking in.

**Comment by clinoge** [comment]
Well, the multiple sources of truth problem could be alleviated to 
something along the lines of what RoR does, namely, to maintain an 
updated schema.php file which sums up the entire set of migrations.

Perhaps it would be interesting to code a feature which would allow to
squash several migrations on the same table to reduce the number of
migrations.

I'm not sure about dropping them altogether. Would a single file
suffice every need?

**Comment by rsands2801** [comment]
@clinoge That sounds like a nice idea, something to run a tidy up every so often.  The compacter could save what it has compacted so should a developer not have run a migration before the compact was done they will not face issue as the script would know what was done.

A single file per table e.g. in the model file in an array would be good in my eyes.  Change the array run a migrate:diff and it creates a migration.  That would be a nice start
