### ISSUE TITLE
Return value for Cache::put and Cache::forever

### ISSUE THREAD

**Issue by enprixd** [laravel/internals#264]
Hello, guys!

Just a suggestion. Maybe this would be possible?

Because in the current version of Laravel, the forever method doesn't return anything.
And my current code looks like this.
```
$settings = null;
if (Cache::has('system_settings')) {
    $settings = Cache::get('system_settings');
} else {
    $settings = SystemSetting::all()->toArray();
    Cache::forever('system_settings', $settings);
}
```
It kind of looks like a mess and I thought the Laravel-like way, would be something like this, maybe?
```
$settings  = Cache::has('system_settings') ? Cache::get('system_settings') : Cache::forever('system_settings', SystemSetting::all()->toArray());
```
Or am I missing something crucial that could achieve this effect?

The current implementation of Cache::forever is this
```
    public function forever($key, $value)
    {
        $this->store->forever($this->itemKey($key), $value);

        $this->fireCacheEvent('write', [$key, $value, 0]);
    }
```
Maybe, if it's

```    
public function forever($key, $value)
    {
        $this->store->forever($this->itemKey($key), $value);

        $this->fireCacheEvent('write', [$key, $value, 0]);

        return $value;
    }
```

And something of the sort on the put method.

Any thoughts?

If this would cause problems or breaking changes, I'd understand.

**Comment by Garbee** [comment]
```php
if (! Cache::has('system_settings')) {
    Cache::forever('system_settings', SystemSetting::all()->toArray());
}
$settings = Cache::get('system_settings');
```

Just spin the way you are looking at the logic flow and you can do things more clearly in less space without needing any internal tweaking.

**Comment by sebastiandedeyne** [comment]
Isn't this what you're trying to achieve?

```php
$settings = Cache::forever('system_settings', function () {
    return SystemSetting::all()->toArray();
});
```

This checks the cache for `system_settings`, returns it if it's a hit, and otherwise sets and returns the value that gets returned from the closure.

**Comment by franzliedke** [comment]
@sebastiandedeyne I believe you're referring to `Cache::rememberForever` - and yes, that is indeed the best solution.

**Comment by enprixd** [comment]
Oh. Nice. That might work. Cache::sear or Cache::rememberForever would be proper for this instance.

Thanks guys.
