### ISSUE TITLE
[Proposal] Add "base64:" prefix support to env()

### ISSUE THREAD

**Issue by aarreedd** [laravel/internals#266]
The `APP_KEY` field in the `.env` file can be prefixed with `base64:` and it will be decoded in `Illuminate/Auth/Passwords/PasswordBrokerManager.php`. 

It would be nice to have base 64 support for all `.env` fields. This could be added to the `env()` helper function easily.

I am happy to send a pull request if this is a good idea.

**Comment by franzliedke** [comment]
What exactly would you use this for?

**Comment by aarreedd** [comment]
To encode passwords in the `.env`. Makes it a bit harder for someone to see a password over your shoulder.

**Comment by jacurtis** [comment]
I agree. This would be awesome. The functionality is already in Laravel since it's used for the `app_key`. Expanding it to other fields would be useful (and I believe fairly simple).

**Comment by tomschlick** [comment]
Wouldn't this be better added to vlucas/phpdotenv?
