### ISSUE TITLE
Query Builder - Chunk with pluck does not work

### ISSUE THREAD

**Issue by imphatic** [laravel/internals#270]
Theoretically these two operations should be identical:

```
DB::table('table_name')->select('id')->chunk(100, function($ids) {

});

```

```
DB::table('table_name')->pluck('id')->chunk(100, function($ids) {

});

```

However, only the operation with select works while, using pluck with chunk does not give any results.   Anyone else have this problem?

**Comment by imphatic** [comment]
Actually neither works as expected.  Interestingly, the select method with chunk only seems to work if you select 2 or more columns.  Once single column will return a collection with all the values set to 0 instead of the correct values.

**Comment by willsmanley** [comment]
Does this work now? Was this closed because it works or because it is a no-fix?

**Comment by uphlewis** [comment]
`->select()` returns a query builder which you can call chunk on to iterate over chunks of the results (executes mutlple SELECT queries with LIMIT equal to chunk size) whereas `->pluck()` returns an collection of all the desired values, and Collection chunk method does not support a callback.
