### ISSUE TITLE
mapWithKeys fails on integer keys

### ISSUE THREAD

**Issue by vissermc** [laravel/internals#272]
the following test fails, i.e. it returns [0=>1] instead of [2=> 1]

  public function test_test() {
        $result = collect([1])->mapWithKeys(function($i) {
            return [2=>$i];
        })->all();
        $this->assertSame([2=>1], $result);
    }

**Comment by tomschlick** [comment]
This is more appropriate as a bug report on laravel/framework

**Comment by fernandobandeira** [comment]
I fixed this on #16564 for 5.4, ping @vissermc ...
