### ISSUE TITLE
[5.4] Handle when pagination is out of bounds

### ISSUE THREAD

**Issue by garygreen** [laravel/internals#273]
At the moment when you try to access a page that is out of bounds it will return an empty page. This is a problem because:
1. If google has indexed those pages, it will always return 200 and will never get removed.
2. User's see an empty page and will get confused.

With this proposal, when the paginator page is set, it will detect if the bounds is valid and if not - throw a `PaginationOutOfBounds` exception that will redirect to the last available page.

Api based requests will remain the same (returning a 200 status code).

The handling of the exception can be overridden in your own app, if desired.

**Comment by willrowe** [comment]
> Api based requests will remain the same (returning a 200 status code).

I'm curious, why would you keep it the same for API requests?

**Comment by dwightwatson** [comment]
Yeah, I would expect the same exception to be thrown for API requests too so that you can handle it however you need.

**Comment by garygreen** [comment]
> Yeah, I would expect the same exception to be thrown for API requests too so that you can handle it however you need.

Of course, the exception would still be thrown but just handled differently (obviously not returning a redirect response!) 😄

**Comment by michaeldyrynda** [comment]
> With this proposal, when the paginator page is set, it will detect if the bounds is valid and if not - throw an PaginationOutOfBounds exception that will redirect to the last available page.

How do you suggest implementing an exception that then redirects? An exception is a panic-condition, which ought to halt code execution immediately, not have some further action take place.

If anything, I'd suggest hitting a page that doesn't have any content just return an empty data array. You can just handle it in your view (no results). A 404 or other exception is not appropriate; the route does exist, it just has no content.

**Comment by franzliedke** [comment]
@michaeldyrynda I'd say 404 is perfectly fine, according to its [definition](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html):

> The server has not found anything matching the Request-URI. No indication is given of whether the condition is temporary or permanent.

As for the exception - not the exception would redirect, but the exception handler that catches it. That's also how other mechanisms are implemented, such as [for the `AuthenticationException`](https://github.com/laravel/laravel/blob/5937bbe4caf4eb10820c1662698ea00ac63cd4ca/app/Exceptions/Handler.php#L50-L64).

**Comment by michaeldyrynda** [comment]
The query string is information to be interpreted by the resource, not part of the resource itself, though.

If I hit `/api/endpoint` and it didn't exist, I'd expect a 404. If I hit `/api/endpoint` and there were no results, I'd expect it to tell me there were no results, otherwise you'd have an endpoint that is sometimes unavailable, which I'd suggest is more confusing to a user than seeing a page with no results.

Can you imagine Google returning a 404 page (it returns a 200) when it couldn't find a result, rather than their 'your search didn't return any results' page?

**Comment by garygreen** [comment]
> How do you suggest implementing an exception that then redirects? An exception is a panic-condition, which ought to halt code execution immediately not have some further action take place. 

It would halt code exception, that's the whole point of it. Laravel extensively uses exceptions which take further action. `ValidationException`, `AuthenticationException`, `AuthorizationException`, `ModelNotFoundException`. That's nothing new, this proposal is following the same trend.

> If anything, I'd suggest hitting a page that doesn't have any content just return an empty data array. You can just handle it in your view (no results).

How is that any different than it is at the moment? Your trying to access a page that simply cannot be served because the results are out of bounds, that is an exception. It's not the norm. The norm would be to have results within the available context. Returning an empty page is no better and is just as confusing to both search engines and the user.

> A 404 or other exception is not appropriate; the route does exist, it just has no content.

Nowhere does this proposal mention returning a 404. The proposal is to send a redirect to the next last available page. For api stuff, it will return 200 with empty results.

**Comment by franzliedke** [comment]
@michaeldyrynda Query string parameters can be part of the URL as well, just remember the good old days of article.php?id=50. ;)

**Comment by tomschlick** [comment]
It was probably closed because its been dead for a year and a half. If it still makes sense to change the behavior then send a PR.

**Comment by decadence** [comment]
Haha. Can someone explain purpose of this repo then?

**Comment by garygreen** [comment]
@taylorotwell would you be open to seeing this PRd or did you close it because no interest?
