### ISSUE TITLE
[Proposal] auth()->attempt([['email', 'username'] => 'emailorusername', 'password' => 'secret'])

### ISSUE THREAD

**Issue by kocoten1992** [laravel/internals#276]
Not enough lvl to do a PR, just an idea

**Comment by ehtasham89** [comment]
Interesting...

**Comment by kocoten1992** [comment]
I think it currently not possible, php array don't accept key as an array,

It could be adjust key <=> value:

auth()->attempt(['emailorusername' => ['email', 'username'], 'secrect' => 'password'])

But it will break all current project, maybe different method like attempt2 -__

**Comment by michaeldyrynda** [comment]
I don't like the idea of discrete usernames - perhaps having a display name is ok in certain situations - but logging in via email is easier from the user perspective. A user is more likely to remember it.

I wouldn't say this would get used that often, though. It would make more sense to override the auth guard in your application for this functionality than to include it in the framework.

**Comment by kocoten1992** [comment]
Well, what do you know, there is a username() method: https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L128

In LoginController, just need to do this:
```
public function username()
{ 
  if (! filter_var(request()->input('email'), FILTER_VALIDATE_EMAIL)) { 
    request()->merge(['username' => request('email')]);
    return 'username';
  } 
  
  return 'email';
}
```
