### ISSUE TITLE
[Proposal] Multiple Exceptions collapsed by default

### ISSUE THREAD

**Issue by jmarcher** [laravel/internals#277]
Sometimes I find that when you get multiple exceptions it is a little bit annoying that I need to scroll down and search for the "important" Exception if there are more than one.

I would say, if there is one exception, the behaviour stays the same, but if there are two or more exceptions they should be collapsed only showing their headings and a plus icon or an arrow or something.

**Comment by jhoff** [comment]
I disagree.  I don't want to have to reach for the mouse every time to unhide the stack trace when I can just hit the page down key instead.

That said, I do think there are a few exceptions that I run into pretty regularly where the top exception provides little to no value and the second or even third are where the real meat is. I wanna say the one I run into the most has to do with having a syntax error in a certain type of file, but I can't recall exactly where or how that manifests itself. If some of those exceptions were cleaned up a little bit then this wouldn't be as annoying IMHO.

Either way, the exception screen that you see is fully provided by the Symfony `ExceptionHandler` class, so this question is really outside of the Laravel space anyways.

If you really wanted to, you could extend the Symfony `ExceptionHandler` class in your own project along with the calling method in `Illuminate\Foundation\Exceptions\Handler` through `App\Exceptions\Handler` to add in whatever javascript or css customization you'd like.

app/Exceptions/Handler.php
```
<?php

namespace App\Exceptions;

use Symfony\Component\Debug\Exception\FlattenException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Symfony\Component\HttpFoundation\Response as SymfonyResponse;

class Handler extends ExceptionHandler
{
    ...
    protected function convertExceptionToResponse(\Exception $e)
    {
        $e = FlattenException::create($e);

        $handler = new CustomExceptionHandler(config('app.debug'));

        return SymfonyResponse::create($handler->getHtml($e), $e->getStatusCode(), $e->getHeaders());
    }
}
```

app/Exceptions/CustomExceptionHandler.php
```
<?php

namespace App\Exceptions;

use Symfony\Component\Debug\ExceptionHandler;
use Symfony\Component\Debug\Exception\FlattenException;

class CustomExceptionHandler extends ExceptionHandler
{
    public function getContent(FlattenException $exception)
    {
        return parent::getContent($exception) . '
            <script>
                // Your JS here
            </script>';
    }

    public function getStylesheet(FlattenException $exception)
    {
        return parent::getStylesheet($exception) . '
            // Custom CSS Here
        ';
    }
}
```

**Comment by garygreen** [comment]
Why not just use whoops? There are other options other than Symphonys built in exception handler. This isn't Laravel issue anyway.

**Comment by jmarcher** [comment]
I mean it is a Laravel issue because maybe we should not rely on Symphony
in order to render Exceptions.

I know it is maybe just a matter of taste, but for me there is no point in
having the whole stacktrace by default when with the heading is most of the
times more than enough.

2016-11-01 12:34 GMT+01:00 Gary Green <notifications@github.com>:

**Comment by garygreen** [comment]
> I know it is maybe just a matter of taste

This. It's exactly why Whoops was removed from Laravel because viewing exceptions is purely down to taste - plus it's not difficult adding it back. Laravel relies on Symphony's components which ships with basic exception reporter built in, so it makes sense to use it as a basic starting point. Customising it is absolutely nothing Laravel wants to get into the market of or should be responsible for imo. Best served as an individual package.
