### ISSUE TITLE
[Proposal] --production flag for dangerous commands

### ISSUE THREAD

**Issue by ahjorth** [laravel/internals#280]
I'm proposing a change to how Artisan handles a dangerous command like `php artisan migrate:refresh`

In my proposal, that command would be outright denied if the app is set to production.
However, `php artisan migrate:refresh --production` would work.

As of now, these dangerous commands are protected with the `ConfirmableTrait`, which is great, but it still allows for one careless keystroke to be potentially devastating.

I'm sure there will be people opposed to this, but I believe that if you're required to type an extra 12 characters, on a command you may use several times a day - which is second nature in local development - could help save a few developers quite the shock.

**Comment by barryvdh** [comment]
Not sure if this is needed, but then you could just remove the confirmation question and use --force for this. Or ask I type the environment name instead of just yes.

**Comment by ahjorth** [comment]
Typing `production` would be a good solution as well.

You say
> instead of just yes
but in fact, you just have to type `y` which is what prompted me to raise this issue. Even forcing the whole word `yes` would be preferable.

I just don't think shortcuts should be taken with stuff like this. Sure, we can't make it too difficult, but usually these commands should be used rarely -- and doing something wrong can really mess up your project , so any safety net that doesn't overly complicates things should be considered.

**Comment by jhoff** [comment]
Maybe the more straight forward solution would be to remove the prompt provided by `ConfirmableTrait` and just have it throw a message that says something like "You can't do this in production. Please use the --force flag to override."

This has the benefit of not being a breaking change, as any deploy scripts using --force will still just work.
