### ISSUE TITLE
Better control over exceptions thrown by the routes

### ISSUE THREAD

**Issue by khru** [laravel/internals#281]
I 'd love to see an easy way if controlling exceptions thrown by the routes.

**Comment by jhoff** [comment]
What does this mean? Can you be more specific? What does "better control" mean?  `app\Exceptions\Handler.php` handles all exceptions thrown in the app, including route exceptions, so you can do anything you need to there.

**Comment by khru** [comment]
I mean, for example if I leave my website open and do not close my session, if I come back to my site, a few hours later and submit a form, I get and annoyng csrf token mismatch exception. Due to the fact That my session was close. And I have not seen any documentation Regarding esta matter. (If I do not express myself properly, sorry)

**Comment by Garbee** [comment]
Check the HTTP Kernel. You have all the control you need there with the handle method.

**Comment by jhoff** [comment]
@khru I think you're looking for this: https://github.com/GeneaLabs/laravel-caffeine

**Comment by khru** [comment]
@jhoff Yes, that's what I was looking for, thx for the help.
