### ISSUE TITLE
[Proposal] Defining routes in yaml

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/internals#285]
Hi,

In big applications, routes files get too big. Reading them become a pain.

How about using a yaml file for defining the routes ?
Of course, defining routes in php will be always possible.

**Comment by tomschlick** [comment]
Just split your routes into multiple files and include them. 

--
Tom Schlick




On Tue, Nov 1, 2016 at 5:30 PM -0400, "Melek REBAI" <notifications@github.com> wrote:












Hi,


In big applications, routes files get too big. Reading them become a pain.


How about using a yaml file for defining the routes ?

Of course, defining routes in php will be always possible.
