### ISSUE TITLE
[Proposal] Selenium test helpers

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/internals#287]
Hi,

Any chance this gets implemented ?

https://laracasts.com/series/whatcha-working-on/episodes/1

https://github.com/JeffreyWay/Laravel-Selenium-Extension/blob/master/tests/SeleniumTestCase.php

**Comment by Modelizer** [comment]
As made discussion on the internal group at larachat @taylorotwell is in favor to keep it as a package outside Laravel. And also I do agree on his point. Here is the [package](https://github.com/Modelizer/selenium) which totally build to keep selenium fluent support in mind.
