### ISSUE TITLE
[Proposal] MongoDB 

### ISSUE THREAD

**Issue by lukepolo** [laravel/internals#288]
I know theres a package out there (https://github.com/jenssegers/laravel-mongodb)

But having it in the framework would make it that much better. 

Its not for every project but, as we move forward it has great usages in laravel such as real time events , notifications that would allow flexibility of the data structure. 

Feel free to listen to this presentation to learn more about it : 

`What is MongoDB For` : https://www.mongodb.com/presentations/webinar-when-use-mongodb

**Comment by tomschlick** [comment]
I think the amount of work it would take to maintain such a thing isn't worth the time for the 5% of people who would actually use it. Best to stay as a package IMO.

**Comment by ntzm** [comment]
> But having it in the framework would make it that much better.

How? All you have to do is install a package and add the service provider

**Comment by lukepolo** [comment]
Its not maintained by the laravel team , meaning , it does not keep up as
quick . If current maintainer stops supporting another package / maintainer
must come forward
