### ISSUE TITLE
[Proposal] Job-based timeout

### ISSUE THREAD

**Issue by djtarazona** [laravel/internals#290]
Similar to #289, I'd like to specify the timeout for a job on the job class (`protected $timeout = 20; // timeout after 20 seconds`).  In Laravel 5.3, job timeout must be specified when launching the queue daemon.  This means I have to set up different queues for different timeouts.  I'd rather use different queues for job priority only.  By specifying the timeout per job, I could specify a long timeout for jobs that are known to take a long time (perhaps sending an email via SMTP) while using a short timeout for other jobs such as accessing local resources where database queries should be fast.

**Comment by tomschlick** [comment]
1000% yes!

**Comment by JesseObrien** [comment]
👍  Let's get this pushed.

**Comment by themsaid** [comment]
This is implemented now, you may close the issue :)

**Comment by lgalaz** [comment]
Is this not available in 5.7?
