### ISSUE TITLE
[Proposal] exists validation should consider soft delete model?

### ISSUE THREAD

**Issue by boynet** [laravel/internals#291]
its even not documented in the docs..

for example if you validate user edit with rule:
`'id' => 'exists:users,id',`

and the user got deleted the validation will pass.

I think like if we not fixing it then at least give a warning about it in the docs or create a exists_soft_deletevalidation rule that using the trait?(yeah a bad name need a better idea) 

see https://github.com/laravel/framework/issues/1820

**Comment by Garbee** [comment]
It absolutely should, as that record is still stored. Let's say you have a unique index on it (as primary ids do) trying to insert something again with that will fail.

For scenarios where you are verifying the ID exists in another table (foreign key), it is still technically valid to associate it as far as the database is concerned. 

The new fluent rule builder will let you specify how to handle softdeletes as a developer.

**Comment by boynet** [comment]
@Garbee  yes but there are cases for example when a "bad user" can find out that a model got deleted and post some info for example comment to a soft deleted post, and the validation will pass as it does not consider soft delete.. there is a reason for both way that's why I think we need another validation that use soft delete

**Comment by Garbee** [comment]
@boynet I think that case is better handled by authorization logic over the actual data validation. i.e. In the `authorize` method to the request check if the given user has comment access to the given resource. As the resources is soft deleted, it shouldn't be found which would cause a failure.

**Comment by boynet** [comment]
@Garbee but its depends on how you look at it.. by looking at the issue you can see that multiple developers fail on this assumption.. I believe that it easily solvable by adding comment in the docs about it or even better creating a new validation method that will make it more clear that exist check for existence in database even if it soft deleted.

I understand that I can check it in authorization logic or in 1000 different places but a lot will think that if I make a validation rules it will work with the framework own features

**Comment by taylorotwell** [comment]
Yes we should probably note it in docs. But, yes, fluent builder does give you full query control.
