### ISSUE TITLE
[Proposal] Dotenv implementation

### ISSUE THREAD

**Issue by jasonhebert** [laravel/internals#292]
### Description:

I would like to suggest making available within the bootstrapping process the instance of Dotenv used to load environment variables and provide a mechanism to add and enforce validations on the .env file using the `Dotenv` builtin validators.

Currently the environment variables are loaded within the `bootstrap()` method of the `Illuminate/Foundation/Bootstrap/DetectEnvironment.php` class using `(new Dotenv($app->environmentPath(), $app->environmentFile()))->load();`. The object instance is thrown away and doesn't give developers an easy opportunity to enforce environment variable validations such as `required()`, `notEmpty()`, `isInteger()` or `allowedValues()`.

**Comment by Garbee** [comment]
Just set the requirements in your `AppServiceProvider@register` like so:

```php
(new Dotenv(base_path('.env')))->required([
            'SERVICES_STRIPE_PUBLIC',
            'SERVICES_STRIPE_SECRET',
            'SERVICES_EASYPOST_SECRET',
            'MAIL_DRIVER',
            'MAIL_HOST',
            'MAIL_PASSWORD',
            'MAIL_USERNAME',
        ]);
```

**Comment by jasonhebert** [comment]
That's all fine @Garbee but it's a bit hacky to have to create a new instance of `Dotenv` when one was just thrown away.

**Comment by Garbee** [comment]
What would a good solution look like to the problem look like to you?

**Comment by jasonhebert** [comment]
What would be nice would be to have that initial instance of `Dotenv` registered and made available as a singleton so that the instance could be used anywhere in the app. This would give you the ability to do, as an example, things like: 
```
Dotenv::required([
    'MAIL_DRIVER',
    'MAIL_HOST',
    'MAIL_PASSWORD',
    'MAIL_USERNAME',
]);

Dotenv::required([
    'SERVICES_STRIPE_PUBLIC',
    'SERVICES_STRIPE_SECRET',
    'SERVICES_EASYPOST_SECRET',
])->notEmpty();
```

**Comment by sisve** [comment]
You should use cached configurations in production, and dotenv will never be loaded in Laravel 5.2 (and newer). This means that some kind of environment-validation function should only execute when the config is cached; and not on normal requests.

Relevant comments:
https://github.com/vlucas/phpdotenv/issues/76#issuecomment-167806230
https://github.com/vlucas/phpdotenv/issues/76#issuecomment-224899197
