### ISSUE TITLE
[5.4] Query "sets"

### ISSUE THREAD

**Issue by alexbowers** [laravel/internals#293]
Currently, in the database system we have a concept of array storage as json, however, sometimes this isn't ideal. Sometimes, a simple comma separated array would be fine. 

This could be covered by casting to a `set`. Which will convert arrays to comma separated, and the comma separated to array again.

There are ways to query this for all databases supported by Laravel. Not all are native solutions, like mysql FIND_IN_SET. However, all work.

The workaround / alternative is this:

```sql
where name like 'string%' 
or name like '%,string' 
or name like '%,string,%' 
or name like 'string'
```

**Comment by alexbowers** [comment]
To be added to Eloquent:

```
Model::whereInSet($column, $value);
Model::orWhereInSet($column, $value);
Model::whereNotInSet($column, $value);
Model::orWhereNotInSet($column, $value);
```

**Comment by kamui545** [comment]
IMO, I would rather stick to JSON or a separate table to do that, I think this solution could lead to performance issues

**Comment by alexbowers** [comment]
If you know what your limit is per column, for example 3 keywords then an
extra table with joins etc is heavier than necessary.

It also gives the option for a user to structure their app in a slightly
different way if it makes sense for them to do so.
