### ISSUE TITLE
[5.4] Queue Tagging

### ISSUE THREAD

**Issue by alexbowers** [laravel/internals#294]
Being able to track queues is a common feature in systems.

For example, you will see that `100` tasks left to be completed. Whether for internal use, or for a user to see.

There are several other use cases, but this is the one I have.

To do this, I would like to be able to do something similar to this:

```php
Queue::where('tag', '=', 'user.15.file_processing')->count();
```

**Comment by alexbowers** [comment]
I think this would be useful in conjunction with #293 where a comma separated string can be added as a column; so that a queue can be tagged with multiple values.

This would allow the syntax to be

```php
Queue:whereInSet('tag', 'user.15.file_processing')->count()
```

where the particular rows may have: 

```
user.15,user.15.file_processing,file_processing
```

That would allow:

- tracking of how many tasks that user has left by checking the `user.15` tag.
- tracking how many file processing the system has left to complete `file_processing`
- tracking how many file processing the user has left to complete `user.15.file_processing`

**Comment by alexbowers** [comment]
There is a current way to deal with this, but it involves parsing the payload, which is not very efficient, and prone to errors if done in raw SQL; and performance hit if done via PHP.

**Comment by tomschlick** [comment]
I started a package a while back to handle this kind of stuff but haven't had the time to finish it off yet. https://github.com/tomschlick/laravel-micro-manager

It would be nice to have in the core but if not I'll try to give that package a little more attention.
