### ISSUE TITLE
Vue component generator command

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/internals#298]
A command that would generate a VueJS component just like the ones for models or controllers.

Usage:
```
php artisan make:vue User\Index
```
It would generate a `resources/assets/js/components/User/Index.vue` file similar to this:
```js
<template>

</template>

<script>
    new Vue({
        data() {
            return {
                //
            };
        }
    });
</script>

<style>

</style>
```

What do you think? Should that be on the framework core or in a separate package?

**Comment by michaeldyrynda** [comment]
This isn't really adding much value other than creating a file. This is something I'd just scaffold with an editor snippet if anything.

**Comment by michaeldyrynda** [comment]
This may be of use to you @KKSzymanowski https://github.com/zachleigh/laravel-vue-generators

**Comment by KKSzymanowski** [comment]
@michaeldyrynda Thanks
