### ISSUE TITLE
Split laravel installer in different generators

### ISSUE THREAD

**Issue by rogervila** [laravel/internals#299]
It would be nice to have the Vue initial code as an option.

For example:

`laravel new blog` -> provides only elixir, without any css or js file
`laravel new blog --vue`
`laravel new blog --rollup`
`laravel new blog --angular`
`laravel new blog --react`
`laravel new blog --stylus`

We could event concatenate them:

`laravel new blog --rollup --stylus`

**Comment by KKSzymanowski** [comment]
Wouldn't it be easier to create a raw Laravel with the installer and then run a command to add some JS boilerplate?

**Comment by rogervila** [comment]
@KKSzymanowski the ideal is to make it with one command.

Maybe it could be achieved with Yeoman. Then, when `--vue` is passed, the Laravel installer calls a yeoman generator that adds the code.

**Comment by KKSzymanowski** [comment]
Yeoman may be a good approach, but in my opinion it would be best if Laravel provided a number of commands creating the JS scaffolding and the installer would call an appropriate one if a specific option(like `--rollup` or `--vue`) is provided.

That way you can easily add the scaffolding later, if you forgot to use some option for the installer command, or if you decide you need something else.

**Comment by rogervila** [comment]
Why not both?
You can choose either passing it on the installer, or scaffold it later.

**Comment by KKSzymanowski** [comment]
Yes, both. I meant it would be better to extract it to commands in order to avoid code duplication.

**Comment by drbyte** [comment]
@themsaid given that new scaffolding exists now in Laravel and the existence of https://github.com/laravel/internals/issues/525 maybe this issue no longer needs to be open?

**Comment by drbyte** [comment]
Oops - I meant https://github.com/laravel-frontend-presets
