### ISSUE TITLE
Compile non-existent directives as @section("x"). i.e.: @content -> @section('content')

### ISSUE THREAD

**Issue by sileence** [laravel/internals#3]
This is just an idea for Laravel 5.3. It has happened to me that I naturally write `@content` or `@footer` instead of `@section('content')` `@section('footer')`

What do you think?

**Comment by welcoMattic** [comment]
I like the idea, it would be cool to use some shortcuts for common sections like those you list (`@content`, `@footer`), and for instance `@header`, `@scripts` and `@styles`

**Comment by CzajekDC** [comment]
What about custom Blade directives? I don't think it's that much of a need to have those shortcuts in the framework itself.

Also, Taylor likes to keep Blade as tidy as possible.

`@section('content')` `@section('footer')` are not that hard to type anyway. And are typed only once or max twice per app.

And who would decide which ones to have, and which ones to not?

**Comment by sileence** [comment]
@CzajekDC actually my idea is that if a directive is not found, for example `@content` if it has no arguments it will fallback to `@section('content')`.

This is just an idea that I had.

**Comment by CzajekDC** [comment]
Oh, ok. That makes sense now. You should update your first post with the explanation :) :+1:

**Comment by Mevrael** [comment]
Exactly. Update 1st post.

Anyway how to deal with `@endsection`?

**Comment by sileence** [comment]
@Mevrael same: @endcontent

**Comment by themsaid** [comment]
Maybe @title("hello") should fall back to @section("title", "hello") then.

**Comment by sileence** [comment]
good point @themsaid

**Comment by AbrahamGreyson** [comment]
I think it may have little bit confusing with HTML tag. It should be left to user to create their own directives.

**Comment by cklmercer** [comment]
Is this something that could just be packaged up?
