### ISSUE TITLE
[Improvement] Consider changing behavior of Storage locally

### ISSUE THREAD

**Issue by AyubM** [laravel/internals#303]
Storage::disk('local') allows the argument of 'public' or 'private' to be set, e.g.
`$disk->put('myfolder/file.txt', $content, 'public')`

Currently, setting public on local disks does nothing.
The above will put the file in storage/app/myfolder/file.txt

I still have to specify the path to the public folder,
`$disk->put('public/myfolder/file.txt', $content, 'public')`

to get my desired result of the path being storage/app/public/myfolder/file.txt

Request:
If the visibility argument is set to 'public' on a local disk, automatically prepend the public folder path.

**Comment by guiwoda** [comment]
I think what you should be doing is using a `Storage::disk('public')` instead. Disks should be transparent, and adding prefixes to specific drivers IMO would make this more complicated to use.

Are you using different storage drivers based on environment?

**Comment by Modelizer** [comment]
@AyubM you can setup configuration details in `filesystems.php`.
Example 
```php
    'myfolder' => [
        'driver' => 'local',
        'root' => base_path('public/path/to/myfolder'),
        'visibility' => 'public',
    ],
```
Then you can use it like
```php
Storage::disk('myfolder')
```

I hope this should work.

**Comment by arcanedev-maroc** [comment]
Another issue with this `local` storage is when you call the `url` method.

Docs: https://laravel.com/docs/5.3/filesystem#file-urls

If you store an image with the `local` and you call the `url` you get this:

```php
'uploads' => [
    'driver' => 'local',
    'root' => public_path('uploads'),
],
```

The `visibility` is usefull if you're using a cloud disk like S3.

```php
$disk->put('images/image.jpg', $content);

echo $disk->url('images/image.jpg'); 

// You get '/storage/images/image.jpg' instead of '/uploads/images/image.jpg'
```

**Comment by shadoWalker89** [comment]
@arcanedev-maroc use the `url` config to get the desired path

```php
'uploads' => [
    'driver' => 'local',
    'root' => public_path('uploads'),
    'url' => '/public'
],
```

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Filesystem/FilesystemAdapter.php#L292-L294

This feature is not present in the official documentation

**Comment by arcanedev-maroc** [comment]
@shadoWalker89 you sir, you deserve a medal :medal_military: for your help
