### ISSUE TITLE
Determining the last piece of (Request to Response) pipeline in the Routes.

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/internals#305]
Route::get('my-web-url', 'UserCtrl@following')->view('my-html-template.blade.php');
Route::get('my-webapp-api-url', 'UserCtrl@following')->json('serializer@vuejs');
Route::get('my-mobile-api-url', 'UserCtrl@following')->json('serializer@mobileApp');

* Note that in all of these 3 route the controller and method are the same.

and the controller just returns data which should be injected into the view or serializer.

for example:
return ["data" => [1,2,3,4,5]];

**Comment by Garbee** [comment]
I think you're moving logic into places where it shouldn't be. The controller should (in many cases) get a request, delegate handling, return the response. You can use View Composers to construct the data for the view in another class. This way you're logic for constructing the view data does not lay within the controller. It simply returns the response needed. Doing things with view composers also means you aren't adding logic into the router that isn't the routers concern. Overall keeping you applications maintainable.

That works for *views*, but what about the API points returning json? Well, there are a few methods for abstracting that logic out to reduce duplication. Without knowing more specifics about the setup it is hard to provide a guide in a solid direction there.

**Comment by imanghafoori1** [comment]
- The whole Idea is to think as middle-wares, controller, (not so common) response middle-wares and views as a series of pipelines...The request travels through these the get promoted into a response. So why we define the middle-wares and controllers in the Routes but not the views.

- View composers can not accept parameters. So they have limited use.
- Sometimes we want our Raw data to be represented both as json and on an html web page...
So the same controller can be used to supply the same data source.(like above)

**Comment by Garbee** [comment]
> View composers don't take parameters.

What do you mean here? Just inject the request and pull what you need from
the route.

You can supply the same data to the controllers from a service layer. You
just need to do more work abstracting things, but for what you are doing it
is worth it to do that rather than ask for more complexity in the framework.

**Comment by imanghafoori1** [comment]
Ok, then we reach this code.
Route::get('my-url', function(){
    return view('my-template');
});

is it better to write it like this ?

Route::get('my-url')->view('my-template'));
