### ISSUE TITLE
Allow custom URL schemes in Validator

### ISSUE THREAD

**Issue by LarsJK** [laravel/internals#306]
Could we disable the protocol check on URL validation?

On iOS you can define custom url schemes (`my-app://some/url`) for communicating between apps. [ref](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html)

With passport the validation rules prevent you from registering these urls as OAuth callbacks, which is a problem.

**Edit:**
The host validation rules would probably also have to be adjusted to be able to validate iOS custom url schemes..

**Comment by michaeldyrynda** [comment]
Looks like this was changed [in 5.2](https://github.com/laravel/framework/pull/10149) amid security concerns, but, it also means somebody has to maintain the protocols when new ones are added.

For your case, you may want to extend validator and add a `validateSimpleUrl` and just pass it through `filter_var`, or add custom handling for your specific URL scheme.

Personally, I think whether the URL is a valid URL and whether your application will accept the URL as valid within the context of your application ought to be two different checks.

**Comment by LarsJK** [comment]
I'm OK with validating against IANA registered scheme.. In that case i will file an issue on laravel/passport so that passport can be used with iOS apps.

But I would prefer it if we could do something like pass in a list of schemes to match against. Like in Ruby [URI::regexp](http://ruby-doc.org/stdlib-2.3.2/libdoc/uri/rdoc/URI.html#method-c-regexp)

Anyway I think the host validation needs to change. 
The validator does not actually validate if it is a valid URL but rather if it is a valid **Web URL**..
Schemes like facetime://, tel://, mailto://, file:// pass the scheme test, but since the host needs to be a valid domain name or IP address they still can't pass the test.

I.e:
```
facetime://94637654
mailto://me@example.com
```

**Comment by Modelizer** [comment]
As Taylor specify in https://github.com/laravel/framework/issues/16840
> What if I only want to validate some protocols but not the others, etc.?

and I suggested `url:protocol=any|restrict=restricted-protocol` for restricting a protocol but after getting feedback from Taylor in Internal slack group need to come up with more elegant syntax.

Need some suggestions Thanks.
