### ISSUE TITLE
load dev providers separately to normal providers

### ISSUE THREAD

**Issue by alexbowers** [laravel/internals#308]

**Comment by bobsta63** [comment]
👍

**Comment by svenluijten** [comment]
I'm actually in favor of this. In the meantime, my package [sven/env-providers](https://github.com/svenluijten/env-providers) gives you the exact functionality I believe you're describing. It actually splits the loading of providers up into a `config/providers.php` file as described by @tomschlick in laravel/framework#16454.

**Comment by Modelizer** [comment]
Would it be nice to have a specific provders section to load dev providers? example
```php
'providers' => [
        Sven\ArtisanView\ArtisanViewServiceProvider::class,
        Barryvdh\Debugbar\ServiceProvider::class,
    ],
'dev-providers' => [...]
```

**Comment by svenluijten** [comment]
@Modelizer that kind of defeats the purpose of my package? You can define multiple groups with my package, like so:

```php
// Load providers and aliases in this group in the 'dev', 'local' and 'development' environments.
[
  'environments' => ['dev', 'local', 'development'],
  'providers' => [
    Barryvdh\Debugbar\ServiceProvider::class,
  ],
  'aliases' => [
    Barruvdj\Debugbar\Facades\Debugbar,
  ],
],

// Load the providers and aliases in this group in *all* environments
[
  'environments' => '*',
  'providers' => [
        Sven\ArtisanView\ArtisanViewServiceProvider::class,
  ],
],
```

**Comment by svenluijten** [comment]
Disregard that, I just kind of assumed you were replying to me directly. Sorry!

**Comment by RemiCollin** [comment]
@Modelizer : it may seems appealing, but on which rule would you define if you are on a dev environment or not ?

I have projects where some packages are used only in development, some other only on staging. And most (if not all) dev-oriented packages provide a simple switch to be activated/deactivated in the `.env` file anyway.

@svenluijten your solution is nice, but kind of overkill to me, as I think it's easier achieved via environment / configuration. Unless you have a special use case for this ?

**Comment by svenluijten** [comment]
@RemiCollin My solution might be overkill for the average user, but I quite like its extensibility. You can set multiple environments (`['dev', 'staging']`, for instance), preventing the debate whether or not to add `staging-providers` and `acceptance-providers` arrays in the `config/app.php` file.

**Comment by RemiCollin** [comment]
Well, that's more the idea of not loading some providers, that I don't get. I know it may seems appealing for performance reason (still I doubt that it would have a huge impact), but there are other potential issues. For example, we use a package that redirect to a simple password prompt on our staging applications. This package require to add a global middleware to the App\Http\Kernel.php file. How would you deal with this ?

**Comment by Modelizer** [comment]
@svenluijten My thought is to make it simple as we can. And yes it's overkilling :) As far as I understand we only want to load those service providers on production which will be used. 

@RemiCollin 
> it may seems appealing, but on which rule would you define if you are on a dev environment or not ?
by `APP_ENV` from `.env` file we can know we are in production or not. If not then `dev-providers` will be loaded.

**Comment by Modelizer** [comment]
@alexbowers We know your title is descriptive but you can add description to make it more clear how it can we useful :) Thanks.

**Comment by svenluijten** [comment]
@RemiCollin I'd just load that provider regardless of the environment the application is in 😄 

@Modelizer Ease of use is definitely a problem with my solution, but I have yet to find a flexible yet powerful configuration to use. 

Problem with the `APP_ENV` environment variable is that everyone uses different terminology. For instance, `dev`, `local` and `development` might all mean the same thing. Same for `prod`, `live`, `production` etc. How would you tackle that?

**Comment by Modelizer** [comment]
I'll go with default laravel `production` terminology. :sunglasses:

**Comment by Modelizer** [comment]
Another solution would be we can go with placeholders solution. Example
```php
'providers' => [
        Sven\ArtisanView\ArtisanViewServiceProvider::class,
        Barryvdh\Debugbar\ServiceProvider::class,
    ],
'staging-providers' => [...]
'local-providers' => [...]
'development-providers' => [...]
```
Just prefix it what ever environment you needed.

@RemiCollin frankly speaking for this [solution](https://github.com/laravel/framework/pull/16454#issuecomment-261510689) is good! but we are extracting conf related logic to a file and not putting where it actually belongs, correct? We also need to remember that we are registering service providers more than once place.

**Comment by sisve** [comment]
What does this accomplish that today's deferred providers doesn't support? I see a new way to break things between dev, staging and production by having different service providers (or perhaps just different order) for every environment.

Is this an attempt to avoid loading non-deferred service providers that you know is unnecessary? Wouldn't it be better to fix those providers instead; sending PR's or filing issues to the origin package?

> If your provider is only registering bindings in the service container, you may choose to defer its registration until one of the registered bindings is actually needed. Deferring the loading of such a provider will improve the performance of your application, since it is not loaded from the filesystem on every request.

> Laravel compiles and stores a list of all of the services supplied by deferred service providers, along with the name of its service provider class. Then, only when you attempt to resolve one of these services does Laravel load the service provider.

From: https://laravel.com/docs/5.3/providers#deferred-providers

**Comment by svenluijten** [comment]
The main problem *I* faced (which prompted me making my package) was that there is a distinction between dev and prod in the `composer.json` file, namely as `require` and `require-dev`. Let's say you only want to load [barryvdh's laravel-debugbar](https://github.com/barryvdh/laravel-debugbar) in your development environment, but not in prod. Your `composer.json` might look like this:

```json
{
    "require": {
        "laravel/framework": "5.3.*"
    }
    "require-dev": {
        "barryvdh/laravel-debugbar": "^2.0",
    }
}
```

When you now go through the deployment process and run `composer install --production`, you're going to run into an issue because when Laravel checks the registered service providers, it'll find the following in the `config/app.php` file:

```php
return [
    // ...

    'providers' => [
        Barryvdh\Debugbar\ServiceProvider::class,
    ],
];
```

And guess what? That class just outright doesn't exist because it wasn't pulled in by Composer. Which then throws a 500 error on your prod/staging environment(s).

**Comment by Garbee** [comment]
Easy enough to dynamically add them in your [app service provider](https://gitlab.com/garbee/Laravel-Skeleton/blob/master/application/app/Providers/App.php#L26) and if you're using middleware in the same way just register that in the [HTTP Kernel](https://gitlab.com/garbee/Laravel-Skeleton/blob/master/application/app/Http/Kernel.php#L61) dynamically.
