### ISSUE TITLE
SparkPost Transaction Options

### ISSUE THREAD

**Issue by djtarazona** [laravel/internals#31]
I recently began testing SparkPost for transactional emails and noticed that it was rewriting all my URLs for click tracking and inserting a small image for open tracking.  While I think that is fine for marketing / campaign emails, I'd rather have those features disabled for transactional emails.

To disable these features, you need to include an `options` object in the JSON payload with the appropriate keys such as:

```
"options": {
    "open_tracking": false,
    "click_tracking": false,
    "transactional": true
}
```

There isn't an easy way to do this — you must extend/override the [`send` method in SparkPostTransport](https://github.com/laravel/framework/blob/b62d55bb39479bbd955ca3512094db6d05f27f38/src/Illuminate/Mail/Transport/SparkPostTransport.php#L40).  I propose adding an `options` array to the [`sparkpost` service configuration](https://github.com/laravel/laravel/blob/d998b5bd0392f76dcaa461fdec919658947c2e65/config/services.php#L28).

```
'sparkpost' => [
    'secret' => env('SPARKPOST_SECRET'),
    'options' => [
        'open_tracking' => false,
        'click_tracking' => false,
        'transactional' => true,
    ],
],
```

Maybe not adding this to the default `services.php` config, but at least supporting it?  I'd be happy to make this improvement and submit a pull request.  I feel like most users will send transactional email from Laravel and may want to opt-out of these features as well.  Thoughts?

**Comment by tomschlick** [comment]
I think this would be easiest by going with what was suggested in #20 

Allowing you to send mail via classes instead of the closure syntax would allow for maximum extensibility & overriding.

**Comment by helloiamlukas** [comment]
Any updates on this?

**Comment by slakbal** [comment]
@djtarazona agree so much with this. How did you solve this now? Lately I've noticed e.g. on for example an account confirmation email with the token-link in there; that the "click tracking" is actually firing the links. Yes, you got it, Sparkposts services seems like they are actually checking if the links exists and in the process also fires of e.g. the new account confirmation link. I've litterly send of an email and saw the call came through a couple of seconds later...bit scary. Thus the users are getting confused that their accounts are verified automagically. We really need to be able to switch off the "click tracking" in an Laravel style and not have to extend and override classes etc. It is really a pitty that sparkpost doesn't allow it to be switched of via their web-portal... wonder why?

**Comment by djtarazona** [comment]
@slakbal Ya, I don't know why SparkPost doesn't allow you to disable the click tracking at the account level.  However, I made a PR for this and it was [merged into Laravel v5.2.40](https://github.com/laravel/framework/pull/14166) so you should be able to pass the appropriate options in your `services.php` config.

My `services.php` looks like this which has disabled the click tracking for us.

```php
'sparkpost' => [
    'secret'  => env('SPARKPOST_SECRET'),
    'options' => [
        'open_tracking'  => false,
        'click_tracking' => false,
        'transactional'  => true,
    ],
],
```

**Comment by slakbal** [comment]
@djtarazona really!!! Let me try that out immediately! Thanks so much!

**Comment by slakbal** [comment]
@djtarazona this rocks thanks! Maybe we can get a PR on the laravel documentation for this?

**Comment by mehdisbys** [comment]
@djtarazona The options do not seem to be taken into account (Laravel v5.4.13).

I have the options in my services.php file

```
'sparkpost' => [
    'secret'  => env('SPARKPOST_SECRET'),
    'options' => [
        'open_tracking'  => false,
        'click_tracking' => false,
        'transactional'  => true,
    ],
]
```

But the email links are still visited by Sparkpost. 

I tried these options through Postman and it works (the link is not visited), here is my example : 
```
{
   "options":{
      "open_tracking":false,
      "click_tracking":false,
      "transactional": true
   },
   "metadata":{
      "some_useful_metadata":"testing_sparkpost"
   },
   "recipients":[
      {
         "address":{
            "email":"me@mymail.com"
         },
         "tags":[
            "learning"
         ]
      }
   ],
   "content":{
      "from":{
         "name":"Awesome Company",
         "email":"testing@mycompany.com"
      },
      "subject":"Registration confirmation",
      "text":"Hi please confirm your account by visiting :  http://www.mycompany.com/register/confirm/zySprEXo9Tmm17dYir1gH8LMRFeWKX"
   }
}
```

Is it still working for you guys ?

**Comment by KristofMorva** [comment]
@mehdisbys based on `Mail/Transport/SparkPostTransport.php`, `options` is merged right next to `recipients` and `content`, however, SparkPost expects options to be under the `options` key. So actually what you have to do is:
`'sparkpost' => [
	'secret' => env('SPARKPOST_SECRET'),
	'options' => [
		'options' => [
                        'open_tracking'  => false,
                        'click_tracking' => false,
                        'transactional'  => true,
		]
	],
],`
One `options` for Laravel, and one for `SpartPost`.

**Comment by tomschlick** [comment]
We should probably get it changed from options -> settings in the config file to avoid confusion in the future.

**Comment by a-ghasemi** [comment]
@KristofMorva thank you so much, your comment helped me to save my time. rergards.

**Comment by djtarazona** [comment]
@tomschlick @KristofMorva @mehdisbys @a-ghasemi Looks like this behavior changed in [`5dace8f0`](https://github.com/laravel/framework/commit/5dace8f0d6f6e67b4862abbbae376dcd8a641f00#diff-a92e9ec1ecc36811d8edb01394beb2f6L79). It was not intended for you to have to do:

```php
'sparkpost' => [
	'secret' => env('SPARKPOST_SECRET'),
	'options' => [
		'options' => [
                        'open_tracking'  => false,
                        'click_tracking' => false,
                        'transactional'  => true,
		]
	],
],
```

But rather:

```php
'sparkpost' => [
	'secret' => env('SPARKPOST_SECRET'),
	'options' => [
                'open_tracking'  => false,
                'click_tracking' => false,
                'transactional'  => true,
	],
],
```

I'd say this is a bug now.  Ping @taylorotwell.  I can submit a PR to fix unless Taylor wants to fix it real quick.

**Comment by spaceemotion** [comment]
For anybody else stumbling upon this:

I had a very similar problem today, but wanted to set the options on a per-message basis. Searching only brought me to one laracasts thread (https://laracasts.com/discuss/channels/laravel/mailsend-passing-custom-parameters-for-sparkpost-api-call) where they eventually used the SMTP layer with a header in the end. I did not want to use that alternative and managed to add the functionality as a Laravel transport extension.

As suggested by the thread here's a handy package out of my version: https://github.com/spaceemotion/laravel-sparkpost-options

**Comment by WallyJ** [comment]
Did this get resolved? I am trying to use the Sparkpost Sandbox, and need to set the parameter in the options section and can't get anything to work.

**Comment by spaceemotion** [comment]
@WallyJ does my package not help you out? Not sure if it works with Laravel 6 though...

**Comment by WallyJ** [comment]
I appreciate that you created a package, and I'm still on 5.8, btw.
However, the sandbox functionality should work with Laravel/Mail without the need for any special coding/packages.
I simply need to figure out where to put the sandbox option in Laravel so that Sparkpost receives that parameter as they are expecting. I have Googled and can't find anything on it. And I don't want to go back to straight PHP for this functionality as it adds the Sparkpost package to my project, and removes my ability to use blade templates that I've already created for use with the Laravel/Mail functionality. Quite frankly I am very surprised that I can't find numerous resources online on how to easily connect my Laravel project to the Sparkpost sandbox. These types of basic emailing testing functions should be popular, simple to set up, then switch from dev to production, with a couple of lines of code in each step. Mailtrap is practically no setup. It just works. Sparkpost or Mailgun should be no different. How is it even possible that I seem to be the first developer on the planet to be searching for how to use Laravel with the Sparkpost Sandbox. I fully expected to find 60 Youtube Videos and 100 online blog tutorials with screenshots. I can't find a single one.

**Comment by spaceemotion** [comment]
@WallyJ please try using the package and see if it works with it. I had the same experience, not even with just the sandbox (the X-MSYS-API header in general). There's some funky stuff going on under the hood which the solution I came up with tries to circumvent. While not the prettiest, it would at least confirm that it works and could be integrated into Laravel via a PR.

**Comment by WallyJ** [comment]
So, if I download and try your package, what syntax would I use to add the sandbox option?
