### ISSUE TITLE
[Proposal] Easily allow package devs to register model factories like end-user devs

### ISSUE THREAD

**Issue by timacdonald** [laravel/internals#311]
Allow devs to create a 'factories' folder that is easily registered like end-user devs can.

Add function to `Illuminate\Support\ServiceProvider`

```

...

use Illuminate\Database\Eloquent\Factory as EloquentFactory;

...

/**
 * Register factories.
 *
 * @param  string  $path
 * @return void
 */
protected function registerEloquentFactoriesFrom($path)
{
    $this->app->make(EloquentFactory::class)->load($path);
}
```

Then a package dev can simply add this to their Service Provider...
```
/**
 * Register bindings in the container.
 *
 * @return void
 */
public function register()
{
    $this->registerEloquentFactoriesFrom(__DIR__.'/../factories');
}
```

**Comment by timacdonald** [comment]
Others looking for a similar solution...
http://laravel.io/forum/01-14-2016-loading-model-factories-from-vendor-packages
https://laracasts.com/discuss/channels/laravel/model-factory-in-package
http://laravel.io/forum/11-02-2015-how-to-define-factories-outside-modelfactoryphp

**Comment by crynobone** [comment]
This wouldn't be useful, there no reason to load factory other than when running it for phpunit.

**Comment by sebastiaanluca** [comment]
Package seeders for instance?

**Comment by cleitonsouza** [comment]
I'm using nWidart/laravel-modules and i need to load the module's factories when run tests. This is where the factories is located.

> modules/ModuleName/Database/factories

I can't add anything like modules/*/database in composer classmap autoload, then, to solve my problem i'm just adding the following code in createApplication() method in TestCase.php

    $modulesPath = Config::get('modules.paths.modules');
    if (is_dir($modulesPath)) {
        foreach (scandir($modulesPath) as $dir) {
            if (in_array($dir, ['.', '..']))
                continue;

            $dir = "{$modulesPath}/{$dir}/Database/factories";
            if (is_dir($dir)) {
                $app->make(Factory::class)->load($dir);
            }
        }
    }

**Comment by adam-devapp** [comment]
+1 for this. Useful for your own packages to run tests, whilst being completely seperate from other packages.

**Comment by deleugpn** [comment]
Would be nice to have this, indeed.
