### ISSUE TITLE
Allow exists rules to target multiple tables.

### ISSUE THREAD

**Issue by Garbee** [laravel/internals#313]
# Scenario

Have a database structure where two tables can represent the same object to the system. For example, `products` and `product_variations` where variations belong to products, yet are standalone objects with the same basic traits making them inter-operable with products.

Let's say we are adding these to a cart. You can either submit a product id or a variation id to the same endpoint. Currently, you can only validate against one table at a time.

# Solution

The [Exists](https://github.com/illuminate/validation/blob/master/Rules/Exists.php) rule could use an upgrade to allow and `OrInTable(string $table, string $column = null)` to allow a check to fallthrough to a secondary (or perhaps through any number?) table to check for existence of the value. This would then only error if it was not found in any of the given tables and their columns (if different from the primary column.)

**Comment by Garbee** [comment]
Thinking about this a little deeper just now, it may be best to introduce a new rule `existsInAny` to handle this. Since exists is explicitly looking for existence in a given table, undoing that to provide this extra functionality may not be the best path forward.

**Comment by garygreen** [comment]
Sounds pretty complex and best suited to a custom rule imo.

**Comment by Garbee** [comment]
It is straightforward logically. Just stack `exists` and do an `or` comparison of results. The main thing is should this be added to the `exists` rule somehow or would it be best to introduce this functionality in a new rule built to handle this fallthrough context.

**Comment by bestmajesty** [comment]
what was the conclusion of this issue?
