### ISSUE TITLE
[Proposal] Create a repository using artisan.

### ISSUE THREAD

**Issue by Modelizer** [laravel/internals#316]
Can we get an artisan command to create a repository? example `php artisan make:repository {model-name}` and add some more additional methods implemented like we do in resource full controller.

```php

class UserRepository
{
    protected $model = `{model-name}`

    public function get() { }
    public function first() { }
}
```

Note: I just gave an example for repository class stub. Feel free to suggest more appropriate or vote up if you think this idea is good.

**Comment by michaeldyrynda** [comment]
Maybe make it available as a package but I wouldn't think there's much use for it in the framework itself. All of the commands shipped with the framework currently are ones most developers would make use of at least once over the course of development in most applications.

Repositories are something that would need documentation of not only the command but also what they are and when to use them. That's unnecessary overhead I think.
