### ISSUE TITLE
[Proposal] artisan command for truncating tables

### ISSUE THREAD

**Issue by InvertedX** [laravel/internals#318]
Like db:seed , remove all table data from artisan console without re-migrating

**Comment by tomschlick** [comment]
What's the use case?

I don't see myself ever running that anywhere near production for obvious
reasons so I'm guessing you just want it for your dev environment?
-- 
Sent from my iPhone

**Comment by michaeldyrynda** [comment]
Not to mention that Laravel isn't aware of your table structure, so there isn't really an easy way to automate this. 

You're better off just doing this via your database CLI or tool directly.
