### ISSUE TITLE
Eloquent $model->fill() Relationships

### ISSUE THREAD

**Issue by mattwells** [laravel/internals#32]
With the awesome new array validation I think it would be extremely helpful if the `fill()` method on a model would fill relationships as well. I have been working with APIs that can create or update relationships and having to call multiple fill methods on the relationship. I also feel this would pair very well with the [`push()`](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L1430) method already in models.

Currently you would have to write something like this to save attributes of related models:

```
$user->fill($attributes);
if (isset($attributes['address'])) {
  $user->address->fill($attributes['address']);
}
if (isset($attributes['posts']) && is_array($attributes['posts'])) {
  foreach ($attributes['posts'] as $post) {
    $user->posts->find($user->posts()->getQualifiedParentKeyName())->fill($post);
  }
}
$user->push();
```

I propose that this could be shortened to

```
$user->fill($attributes);
$user->push();
```

I think it would be wise for the `$fillable` array to be respected for relations. 

It should be possible to both create an update *toMany relationships as well as long as the foreign key name/value pair is available in the item.

https://github.com/mattwells/framework/tree/recursive-fill

**Comment by troelskn** [comment]
What happened to the linked-to branch?

**Comment by troelskn** [comment]
I've found my self in need of this functionality and have implemented some support for it. I put the code up here:

https://github.com/laravel/framework/compare/5.4...troelskn:feature/fillable-relations

Obviously, this is still in need of tests and documentation, but would something like this be accepted into core, if I polish it and open a PR?

**Comment by troelskn** [comment]
I take it that there is no interest in integrating this feature into Eloquent core. As such, I've created a stand alone trait, that can be mixed into models as an add-on. Code is still a bit rough around the edges, but for anyone interested, you can have a look over here:

https://github.com/troelskn/laravel-fillable-relations

**Comment by mattwells** [comment]
Hi @troelskn I agree that a trait is an excellent solution to this issue, especially given that Eloquent models now use traits for most functionality. Also having this as a separate package would help to see if there is a need for this in the Laravel core and to work out the complexities first.

I don't remember the exact details about where I gave up on working on this any more but I think it was to do with updating side of things, especially with updating a many to many relationship. 

I will try and find some time to support your development work as I may have some ideas.

**Comment by decadence** [comment]
@troelskn You could make PR because internal proposals without it rarely has much attention from core devs.

**Comment by troelskn** [comment]
@mattwells Any insights would be much appreciated. The biggest issue I've noticed is that it is necessary to save the model in some cases, to get a primary key. This could cause problems as people would generally expect `fill()` to not hit the database. I don't think it's too bad though. It's probably going to be used mainly through `create()` or immediately before a call to `save()` anyway.

**Comment by troelskn** [comment]
Thanks for the suggestion @decadence - I actually offered to create a PR, if you see my earlier messages. That said, I think I agree with Matt that keeping this as a separate package may be preferable - at least for now. It could always be integrated into core at some later time.
