### ISSUE TITLE
fromJSON(): reverse of Eloquent model's toJSON() missing

### ISSUE THREAD

**Issue by andrisi** [laravel/internals#321]
The reverse of toJSON() is missing on Eloquent models. The toJSON() method works well when serialising models with relations to JSON, but there is no method to do the opposite, recreate a model, with it's relations from JSON. The create method seems to work for flat arrays (single records) only. It would be very helpful to have this, when receiving JSON from the client side, and then in turn saving it to the db, by comparing it to a model loaded with current data from the database.

**Comment by OwenMelbz** [comment]
Would you expect this to effectively do something like

```php
public function fromJSON($attrs)
{
    return new self(json_decode($attrs));
}
```

so you could use it as??

```php
$user = User::fromJSON('{"name": "demo","email": "demo@demo.com"}');
```

For time being i guess we'd do `$user = new User(json_decode('{"name": "demo","email": "demo@demo.com"}'))`

**Comment by andrisi** [comment]
Yes, @OwenMelbz - including relations. Because toJson() does work with relations, but without it's reverse, it's kind of half hearted.

**Comment by andrisi** [comment]
@taylorotwell Would be nice to have an explanation of why you're closing this. Is this functionality available elsewhere? Otherwise you're skipping a very important piece, which would help a lot of Laravel developers out there - with a standard solution.

**Comment by PDXfoster** [comment]
@taylorotwell any further explanation on this?
