### ISSUE TITLE
[Proposal] Separate array of rules for different HTTP methods in FormRequest.

### ISSUE THREAD

**Issue by pankitgami** [laravel/internals#323]
Recently, I came across a situation in which same FormRequest class was used by both get and post methods.
 
Currently, Laravel is providing a single function which returns an array of rules.

Instead, We can provide rules based on a current request, something like below:

    public function rules(){
		return [
			'global' => [
				//Global key value pair rules, apply to all request.
			],
			'get' => [
				//Key value pair rules, apply to only get request
			],
			'post' => [
				//Key value pair rules, apply to only post request
			],
			'put' => [
				//Key value pair rules, apply to only put request
			],
			'delete' => [
				//Key value pair rules, apply to only delete request
			],
			//Other request method and its rules
		];
	}

If required I could help you in developing this enhancement.

**Comment by sebastiandedeyne** [comment]
Not sure if this is worth adding to core. It can easily be done programatically as is:

```php
public function rules(): array
{
    $rules = [];

    if ($this->method() === 'PATCH') {
        // Modify `$rules`...
    }

    return $rules;
}
```

**Comment by pankitgami** [comment]
@sebastiandedeyne Indeed, it can be done programmatically as you mentioned. But If I want to extend validator and use its rules in some other way I can't use it.

Case 1:
I am trying to use Laravel's validator for my front-end validation. I want to re-use the rules and messages. But in the present scenario, I can't use it. Because my front end bridge doesn't have any way to know which rules are used for which method.

So if we have a separate array for separate HTTP methods we can reuse the same rules and messages in front end side.
