### ISSUE TITLE
[Proposal] Collection - only_with_keys method

### ISSUE THREAD

**Issue by rohansahai** [laravel/internals#324]
I found the [https://laravel.com/docs/5.3/collections#method-only](only) method on the Collection class a bit confusing. I was expecting back a collection of items with _only_ the keys I specified - but in reality it _only_ returns items in the collection that have a top level key that matches the keys passed through. I.E.

```
$collection = collect(
   ['product_id' => 1, 'name' => 'Desk', 'price' => 100, 'discount' => false],
   ['product_id' => 2, 'name' => 'Table', 'price' => 130, 'discount' => false]
);

$filtered = $collection->only(['product_id', 'name']);

$filtered->all();

// expected: [['product_id' => 1, 'name' => 'Desk'], ['product_id' => 2, 'name' => 'Table']]
// actual: []
```

I consulted with a few other people who were also initially confused - but we eventually realized `only`'s intended function. My proposal isn't to change `only` but to add an additional method to `Collection` - maybe called `only_with_keys` or something, that carries out what my initial expectation of `only` was. I'll happily make a PR with tests if the proposal gets traction/is accepted.

As of now accomplishing the `only_with_keys` functionality is fairly straightforward and can be easily achieved using `map` but I think there is enough use of this type of function that it merits a Collection instance method.

**Comment by sebastiandedeyne** [comment]
`only` just looks at the keys of the collection, not of the collection's items, the method has a different use case that mapping items.

The issue here looks more like a `pluck` operation to me, and I think it would make sense for `pluck` to accept an array as it's first argument.

```php
$collection = collect([
   ['product_id' => 1, 'name' => 'Desk', 'price' => 100, 'discount' => false],
   ['product_id' => 2, 'name' => 'Table', 'price' => 130, 'discount' => false]
])->pluck(['product_id', 'name']);
```

**Comment by sebastiandedeyne** [comment]
Looked in to PR'ing this, but unfortunately passing an array as the first parameter for pluck is already a thing (equivalent to the dot notation, e.g. `->pluck('product.id')` == `->pluck(['product', 'id'])`).
