### ISSUE TITLE
[proposal] operator eanabled where in collection

### ISSUE THREAD

**Issue by alimranahmed** [laravel/internals#325]
Its really boring to user filter when I just need a **not equal**(!=) check instead of **equal**(==) check. Where method of collection doesn't support any other condition than the equal check.

**Currently the following code is required to simply check where not equal**

`$users->filter((function ($user, $key) {
    return $user->is_active != 1;
});
`

**Expecting something as follow**

`$users->where('is_active', 1, '!=');`

**Or just like eloquent** 

`$users->where('is_active',  '!=', 1);`

**Comment by vlakoff** [comment]
This has already been implemented in Laravel 5.3: #12429.
