### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dhiman252** [laravel/internals#327]
Description:

Since Laravel has the support for the database validations, so for example we have the follwing validation:
exists:table,column
so here instead of passing the table name can there be a support for passing the Model class name
exists:App\User::class,column
The basic idea is to automatically retrieve the table name from the model class.

**Comment by Modelizer** [comment]
I think we don't change table name frequently. :thinking: So keeping it `table` would be more appropriate one.

**Comment by bobbybouwmann** [comment]
Well that might be a good idea, however `App\Model::class` returns a string. So it would be really hard to check if you have string for a table or a class. You can check if the string contains `App` or something, but if you moved your models to a separate directory or if you use a different namespace  it wouldn't be possible anymore. 

So I think the idea is good, but needs a bit more thoughts

**Comment by dhiman252** [comment]
Actually the thing is that I have created many request class in my project earlier so as we changed the table names via migration so this validation needs changes in my request class and it way a bit of pain, so now i have also checked the  model class to provide me the table name but found that there is no static method availabe on the model class, either there be a method like ModelClass::getTableName() or otherwise App\Model::class but in the latter need to check and throw an exception if the instance is not.of the eloquent model class. Any of these can be helpul if it gets implemented.

**Comment by dhiman252** [comment]
@bobbybouwmann

Well its a simple check that if the string contains a '\' then its a model class else otherwise the table name. I am sure no one will be intelligent enough to have the table name with a '\' 😋

**Comment by Garbee** [comment]
There isn't a way to determine that.

For example if an exist is called for with the string `Product,sku` (devs can, and should, do `Product::class . ',sku'` to let their IDEs help them refactor this.) Is this a class name or a table name? Case matters in both. Global classes exist, they could be inherited from legacy projects or someone just may not like namespaces. You could attempt `get_class` on the table parameter, however that could still lead to a false positive of finding a class that isn't a model. You then use the reflection class to figure that out if it is a class. From there, you see if it extends the model base. If it does, you then need to instantiate an object just to get the table name from it.

And all that is just *assuming* what you've been able to identify exists as a class is actually what was intended.

**Comment by dhiman252** [comment]
@Garbee 

I understand you concern but what if dynamicity has to play a role here, I hate hardcoded code as it takes a lot of pain to change them also I know if we need to fetch the table name  form a model need to create a class object but that is not required keeping the performance considerations point of view, any solution which has dynamicity  would be really helpful.

**Comment by Garbee** [comment]
I literally handed what you want over to you on a silver platter. Full functioning code. That is how you should do it in your application as the framework shouldn't be responsible for this highly unstable and unpredictable code.

**Comment by alibo** [comment]
Maybe we can implement it with a new method in `Exists` class: 🤔

```php
Rule::exists()->eloquent(App\User::class)->where(function ($query) {
    $query->where('account_id', 1);
})
```

```php
class Exists
{
    /**
     * @param  string|\Illuminate\Database\Eloquent\Model
     * @return $this
     */
    public function eloquent($class)
    {
        $this->table = is_string($class) ? app($class)->getTable() : $class->getTable();

        return $this;
    }
}
```

**Comment by Garbee** [comment]
I think the validation classes are aimed to provide a direct mapping from the string variants in object form. If there is current precedent of that not being the case then it could be considered.
