### ISSUE TITLE
[improvement] Allow developer to specify a log file to send logging output

### ISSUE THREAD

**Issue by gibtang** [laravel/internals#328]
Currently, all logs go to Laravel.log. But sometimes i want certain logging outputs to go into another logging file such as outputs for payment details etc. So something like 

Log::info('payments.log', 'payment made'); 

where i specify that I want log to be sent to payments.log instead of the default laravel.log. If I don't specific payments.log, then logging output goes to the normal Laravel log. Any comments??

**Comment by alibo** [comment]
A quick solution:

```php
class PaymentLogger extends \Illuminate\Log\Writer {}

// AppServiceProvider
$log = new PaymentLogger(new \Monolog\Logger('payment'))
$log->useFiles($app->storagePath().'/logs/payment.log');

app()->instance(PaymentLogger::class, $log);

// Usage:
$log = app(PaymentLogger::class);
$log->info('a payment was made!', ['id' => $payment->id]);
``` 

But I think we can also implement it in the framework:

```php
Log::newLogger('payment', function(Writer $writer) {
    $writer->useFiles($app->storagePath().'/logs/payment.log');
});

Log::logger('payment')->info('a payment was made!');
```

**Comment by garygreen** [comment]
Related to #217 it would be nice to log stuff easily to diff files. Would make using Log::info and stuff more useful when debugging.

**Comment by drbyte** [comment]
Related, although it's a system-wide change, not a per-call change: [Changing the Laravel Log File Name](http://fideloper.com/laravel-log-file-name)

**Comment by gibtang** [comment]
Digging up old issue. Is it ok if i do this and submit a PR?
