### ISSUE TITLE
Join by relationship in Eloquent.

### ISSUE THREAD

**Issue by Modelizer** [laravel/internals#329]
We use `with` on a model but its fire a separate query. What if we want to join table which has a relationship. Example:

```php
class User {
    public function comments() {
         return $this->hasMany(Comment::class);
    }
}
```

We can retrieve comments by `User::with('comments')->first()` but what if we want to join and make it more narrow down in just one single query for this what will do is 
```php
User::select('user.user_id', 'comments.comment_id' 'comments.message')
    ->join('comments', 'user_id', 'comment_id')
    ->first()
``` 

Which is kind of repetition?

What I was thinking is can we *join by relationship*? Example:

```php
User::select('user.user_id', 'comments.comment_id' 'comments.message')
    ->joinComments()
    ->first()
```

Does anyone have a simple solution than this? Would be appreciating. Or this would be a proposal. Thanks

**Comment by callmez** [comment]
related to #228  and https://github.com/laravel/framework/issues/14542

**Comment by falcon-git** [comment]
I need this as well. Simple example:

I have a content table and a user table. A content has an owner i.e. a reference to the user table. I want to sort the content on the owner's name, i.e. sort the content on a user table field.

**Comment by decadence** [comment]
Related https://github.com/laravel/internals/issues/668

**Comment by fico7489** [comment]
see https://github.com/fico7489/laravel-eloquent-join

**Comment by kananiraj10** [comment]
[Solved Here](https://laratuto.com/join-in-laravel-eloquent/)
