### ISSUE TITLE
Force Index on a query

### ISSUE THREAD

**Issue by danielbaylis** [laravel/internals#33]
I'd like to be able to push "FORCE INDEX (index_name)" into a query built with eloquent to force MySQL to use the correct index.  I understand I can chain "->from(DB::raw('table_name FORCE INDEX (index_name)')" into a query but this is hardcoding a table name and doesn't seem laravel-esque given the query would break if the model/table name changed.

Having a forceIndex method that allowed an index to be specified (but not a table name) would ensure the query continues to follow the model's auto-detected table name.

I need this specifically to resolve an issue where MySQL is not able to find existing records when it tries to create an intersect between two indexes on the fly on a WHERE EXISTS sub-select like the one below.  The issue is resolved by forcing MySQL to the correct index.  Granted this is not laravel's problem but it would be handy (and tidy) feature.

```
select * from `messages` where exists (select * from message_routes where `message_routes`.`message_id` = `messages`.`id` and `owner` = ?) and `messages`.`id` = ?
```

**Comment by ahmedash95** [comment]
then you need something like Model::forceIndex('index_name')->get(); ?

**Comment by danielbaylis** [comment]
Yes.  This would save needing to use DB::raw and hard code the table name.

**Comment by ahmedash95** [comment]
i will make a PR for it , hoping taylor to merge it :D

**Comment by tomschlick** [comment]
Make sure to link back to this discussion so he can see the reasoning behind it. Seems reasonable to me :+1:

**Comment by gocanto** [comment]
if I am not mistaking, you can achieve this performing a query using models relations, as so: 

```
$users = Loan::has('installments')->with(['user' => function ($query) use ($q){
            $query->select(['id', 'first_name', 'last_name']);
            $query->where('verified', 'yes');
            $query->where('status', 'active');
            $query->where('role', '!=', 'admin');
            if ($q != '') {
                $query->whereRaw("CONCAT (first_name, ' ', last_name) like '%" . $q . "%'");
            }
            return $query;
        }])->where('status', '!=', 'paid')->groupBy('user_id')->get();
```

**Comment by gcphost** [comment]
@ahmedash95 did you ever make a PR? Would like to see this missing feature.

**Comment by danielbaylis** [comment]
I don't believe this has become a feature.  It would be important that it worked on all possible database drivers and I am not sure if they all support specifying an index by name?

**Comment by ahmedash95** [comment]
@gcphost sorry for delay , but i'm agree with @danielbaylis , any idea what should we do ( let it as a DB class solution or try to make a PR for that ) ?

**Comment by gcphost** [comment]
What about a beforeWhere()?

**Comment by harshsanghani** [comment]
I also want to user FORCE INDEX with laravel Eloquent so Please message here if you implement that.

**Comment by maksimru** [comment]
My solution:

Add following to the model class:

```php
    public static function IndexRaw($index_raw)
    {
        $model = new static();
        $model->setTable(\DB::raw($model->getTable() . ' ' . $index_raw));
        return $model;
    }
```

Now you can use simply something like this:

```php
SomeModel::IndexRaw('FORCE INDEX (some_index_name)')->where('condition','=',true)->get();
```

**Comment by malhal** [comment]
So the where() method wraps the column name in single quotes but mysql does allow querying by index name as long as it does not use single quotes, so a simple solution is this:

    whereRaw($model->getTable().'.'.$indexName.' = ?', $value);

**Comment by adelf** [comment]
In complex queries with with() previous solution doesn't work. Better to overwrite base query 'from' value instead:

```php
    $query = SomeModel::where()->with()...->orderBy();

    $query->getQuery()->from(\DB::raw($query->getQuery()->from . ' FORCE INDEX (index_name)'));
    // or just
    $query->getQuery()->from(\DB::raw('`table` FORCE INDEX (index_name)'));

    $results = $query->get();
```

**Comment by thril** [comment]
I needed the `FORCE INDEX` for a join, so I used the following solution...

```php
DB::table('table1 as t1')
    ->join(
        DB::raw('table2 as t2 FORCE INDEX (index_name)'),
        't1.some_field', '=', 't2.some_field'
    )
    ...
```
