### ISSUE TITLE
helper for Str::words()?

### ISSUE THREAD

**Issue by manogi** [laravel/internals#330]
Would you accept a pull request that adds a helper for `Str::words()` ?

I use it as often as `str_limit()` and it feels strange that one is a helper class and one is not.

I would make a pull request for the core and for the docs.

**Comment by garygreen** [comment]
Not anymore helpers pls! Just add your own wrapper if you use it a lot imo

**Comment by Garbee** [comment]
If something is a simple PR, just PR it. That will get attention must faster than a discussion here.

**Comment by manogi** [comment]
Ok ok 😬
