### ISSUE TITLE
Better feature parity between Collection methods and Arr functions

### ISSUE THREAD

**Issue by sebastiandedeyne** [laravel/internals#331]
I expected `Arr` to have a similar feature set as `Collection`, but apparently it's way slimmer. Would it make sense to improve feature parity, and have `Collection` do more `Arr` calls under the hood?

Two examples off the top of my head:

- `Arr::where` is actually a filter method. It would make more sense to have an `Arr::filter` method, and have `Arr::where` behave the same as `Collection::where` (which allows you to specify an operator).

- `Arr` misses basic array function like `map`, `flatMap`, `each`,... These may exists in php's standard library, but it would feel more consistent to simply have everything on `Arr`. Also, php's standard `map` doesn't pass in keys by default, so the `Arr` functions would be a more powerful/streamlined version of the standard functions.

As a response to the possible argument 'why not just use a collection', if you're only doing one operation it's less tedious to use `Arr` than to wrap an array in a collection, apply a method, and unwrap it with `toArray`.

**Comment by tomschlick** [comment]
I agree. We should move those calls in the Collections to be wrappers around Arr methods.

**Comment by themsaid** [comment]
One thing maybe, won't it be confusing that `array_map()` & `Arr::map()` would act differently?

**Comment by sebastiandedeyne** [comment]
That's actually part of why I want `Arr::map` to exist—`Arr` would become a more sane array function library that the standard library that ships with PHP.

(concrete examples of improved sanity: always have the array as first parameter, pass array keys in the callback where applicable, two things that native `array_map` doesn't do.
