### ISSUE TITLE
Splitting the contracts package

### ISSUE THREAD

**Issue by abellion** [laravel/internals#334]
In my opinion, the interfaces should be in the component that they belongs to, and not all together in one package.

What are the benefits of grouping them ? Do you find using interfaces from a ```Contracts``` namespace make more sense ?

**Comment by Garbee** [comment]
If someone wants to build a package that replaces one of the internal bindings, why should they need to include the entire library they aren't going to use?

**Comment by abellion** [comment]
Yeah this is a good point. But what if someone wants to use one internal package for a non laravel application, why should they need to include the entire contracts library ?

**Comment by Garbee** [comment]
Because it is much smaller and non-intrusive going in the current direction.

**Comment by abellion** [comment]
Yes you got me ! I close this issue !
