### ISSUE TITLE
Collections' `min()` do not work with null

### ISSUE THREAD

**Issue by aarreedd** [laravel/internals#336]
`min()` does not work if the collection contains a null value. Instead of returning the lowest value, it returns the lowest value _after_ the null.

Example:

    $collect = collect([100, null, 200,  300]);
    $min = $collect->min();
    echo $min; // 200

Should the PR go to 5.3 or master?

**Comment by Garbee** [comment]
This is a bug, so 5.3 seems like the appropriate branch to PR. No reason to leave it broken when 5.3 is the latest supported version.

**Comment by tomschlick** [comment]
Question is, should it cast the `null` to an `int` like in #337 

I would think so to keep the consistency.

**Comment by Garbee** [comment]
+1 to casting. Once again, if you don't want nulls reject them beforehand.

**Comment by taylorotwell** [comment]
Do y'all agree I should just run `filter()` inside `min()` by default?

**Comment by aarreedd** [comment]
This could break things for people in 5.3. Other people have probably incorrectly assumed that `null` is already filtered because of this bug.

**Comment by Garbee** [comment]
Yea, SGTM. Anything that removes or casts null.

The feature is broken in itself @aarreedd. As you aren't actually getting the min value. If anyone is expecting this, their stuff may break but for the right reason.

**Comment by Garbee** [comment]
For example, someone could have a collection of cart items and plucking prices (which they could use `null` for free things), they run `min` on that and they could get the wrong lowest-cost item. Very bad. So, this needs addressing even if it is considered BC as, well, it is a massive possible bug that causes something to not function as you intend. And people expect this to "just work", I doubt many have hit this case in particular and caught it.

Very good catch here.

**Comment by taylorotwell** [comment]
OK I've pushed fix to run filter first.

**Comment by Garbee** [comment]
Thank you!
