### ISSUE TITLE
[Question] Get current user with relationship

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/internals#339]
I have a question about the Auth Guard. 
Is there a nice way to get the current user with eager-loading some relationships?

I currently use 
```php
User::with('roles')->find($this->guard->id());
```
but I think there must be a better way.

I know I can specify the `$with` property on the User class, but most of the time I don't need it, so I don't really wanna do that.

**Comment by sebastiandedeyne** [comment]
If you always want to retrieve the current user with roles, I think extending and using your own `EloquentUserProvider` would do the trick.

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Auth/EloquentUserProvider.php#L45

**Comment by KKSzymanowski** [comment]
Thing is, most of the time, I want user without role, but from what I know, the User object is *cached* on the Guard instance, so it doesn't really matter. I'll try your solution.
