### ISSUE TITLE
[Proposal] provide config for (custom) authentication urls

### ISSUE THREAD

**Issue by Frondor** [laravel/internals#341]
I've been coding a new package for multi-authentication "out of the box", and I'm facing the problem that I can't use `auth:guard` middleware because when an unauthenticated user tries to access a protected route (`/dashboard/settings`), the `AuthorizationException` redirects to `/login` route, and I need it to be `/dashboard/login` instead.

In my opinion, `'login'` shouldn't be hardcoded in `return redirect()->guest('login')` at [app/Exceptions/Handler.php#L63](https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php#L63)

This is the PR I'm proposing https://github.com/laravel/laravel/compare/master...Frondor:master

**Comment by Modelizer** [comment]
IMO we do not treat login URL as a config? I think you should directly handle it in `Handler.php` file.

**Comment by Frondor** [comment]
@Modelizer what if you need to handle it from a package? You can't override/extend that handler's method, which is pretty unique for this specific exception, neither the exception

**Comment by Modelizer** [comment]
It's quite rare we need to handle in an external package, can you give us a package name or a link which override default behavior? or elaborate on your point that its looks we need to put in a config file?

**Comment by Frondor** [comment]
The case is quite simple and it's explained within a comment in my PR.
You (for one of many reasons) decide not to use `Auth::routes()`, so you add them manually with different URLs. You still use `$this->middleware('auth')` in your controllers, but, let's say your _login route_ is now `example.com/dashboard/signin`.

Now, without being authenticated yet, you try to access `example.com/dashboard/signin` (which is _protected_ with `auth` middleware). Your request will be rejected because you have no active session, hence the `AuthorizationException` will trigger which response is handled at https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php#L57 
And there you go, instead of getting redirected to `example.com/dashboard/signin` it does redirects you to a route you're not using at all `example.com/login`.
