### ISSUE TITLE
[Proposal] A nicer way to save/delete without triggering events

### ISSUE THREAD

**Issue by robclancy** [laravel/internals#344]
Currently I am doing.

```php
    /**
     * Run a callback without firing events.
     *
     * @return mixed
     */
    public function withoutEvents(Closure $callback)
    {
        $dispatcher = static::getEventDispatcher();
        static::unsetEventDispatcher();

        $return = $callback();

        static::setEventDispatcher($dispatcher);

        return $return;
    }
```

This is because the only way to stop events from firing without overriding save/delete like methods is to have `static::$dispatcher` set to falsey. The above code means I can do what I need in a "good enough" way but would be nice if there was a variable you could set to disable events instead of having to remove and add the dispatcher.

```php
        $this->withoutEvents(function () {
            $this->save();
        });
```

So would be nice to have `protected $fireEvents = true;` (or maybe public?) in `Eloquent/Model.php` that is checked similar to the `static::$dispatcher` check. Then maybe the same sort of method as I am using now just setting that variable instead, or just using the variable directly which I think looks better than using a closure.

```php
$this->fireEvents = false;
$this->save();
$this->fireEvents = true;
```

**Comment by morloderex** [comment]
@robclancy This seems like a good idea maybe even allow for setting it to an array in order to have even more control over which events is fired during an event. :)

**Comment by kevdotbadger** [comment]
This is great. I've recently found myself disabling the eventDispatcher due to infinite loops but having a nicer method would be great.

**Comment by vahidalvandi** [comment]
simple add 
			wallet_logs::flushEventListeners(); // privent send notification
before insert or update
