### ISSUE TITLE
Model.php class toArray() method and a rigmarole of data conversions, is it needed?

### ISSUE THREAD

**Issue by Jameron** [laravel/internals#346]
In a recent LMS application I worked on we needed to return a collection of reporting data for a class of students. (10-35 students per class). The data was a collection of the students with nested results for their performance of a 16 week course.

Here is a shortened snippet for one student's data: (shows data for only one week vs. listing out all 16 weeks results)

`
 "students":[  
      {  
         "id":1,
         "email":"guest@example.com",
         "company":"",
         "first_name":"Jon",
         "last_name":"Doe",
         "weeks":[  
            {  
               "num_complete":0,
               "total_activities":14,
               "percent_complete":0
            },
         ]
    }
]
`

The report was taking more than 20 seconds to load and the client was very disappointed. I started to look for ways to optimize the load as it seemed strangely long. I pinpointed the problem, it was the Model.php class toArray() method which converts json to arrays, then back to json, and back to arrays again. This was very bad on performance. The page load time was significantly increased by the conversion of the collection data to array, then to json, and back to array multiple times. This was not necessary for my application and I am unable to find a scenario when it is.

 Data is the core of all Laravel applications. A large benefit of using Laravel is the elegant syntax and model methods that allow you to easily create nested collections of data based on relationships. The major downfall to using Laravel is that loading data retrieved from a database is very slow. Anyone who uses Laravel can attest to this. Sure, you can create a model white list to limit the column data returned, and you can paginate results. Even after taking these recommended steps Laravel is still slow, with respect to loading large sets of collection data with relationships. Fortunately this can be fixed manually by overriding toArray method on each model. You override the toArray method and assign the collection attributes directly to avoid a rigmarole of data type conversions that drastically slow down your load times.

Example:

`
class Student extends Model
{
    
    protected $table = 'students';

    public function toArray() 
    {
        // List out all attributes you want to get, anytime this model is called.
        $attributes = [];
        $attributes['id'] = $this->getAttribute('id');
        $attributes['email'] = $this->getAttribute('email');
        $attributes['company'] = $this->getAttribute('company');
        $attributes['first_name'] = $this->getAttribute('first_name');
       $attributes['last_name'] = $this->getAttribute('last_name');
       $attributes['weeks'] = $this->getAttribute('weeks');

        return $attributes;
   }
}
`

Once this override was put in place my load time went down from an average of 20 seconds to just under 1 second! This is a 95.24% decrease!

After discovering this method of improving my Laravel applications load times I have been overriding the model classes in many of my new projects as it seems to be the only way I can get acceptable load times.

I am suggesting either refactoring the toArray method to prevent the array to json to array rigmarole, or if this is absolutely needed, then I suggest introducing a clean way for users to bypass this toArray() rigmarole similar to this: https://laravel.com/docs/5.3/eloquent-serialization#hiding-attributes-from-json

**Comment by Jameron** [comment]
If you have the visible property set on your model you can override the toArray() method with the following:

	public function toArray()
	{

		$column = null;
		foreach($this->getVisible() as $attribute) {
			$column[$attribute] = $this->getAttribute($attribute);
		}
		return $column;	

	}

**Comment by lexxyungcarter** [comment]
Just experienced this even in `Laravel 5.8`. The default `toArray()` method takes almost 40s, but after overriding the toArray() method, the query runs for just 1s! I initially thought it was an "N+1" query problem, but after removing all relations and running the tests again, the `toArray()` method was the culprit! This essentially affects the performance of `toJson()` and also the response time taken to return even a single `eloquent API resource`.

**Comment by mintunitish** [comment]
I am also experiencing the same issue in **v5.8**. `toArray()` is causing the problem.

**Comment by bucalexis** [comment]
I also had this problem when working with `toArray()`,  my response was very slow. You can use the eloquent resources to deal with this, I think is more elegant than modifying the `toArray()` method inside the model. I think is available from Laravel 1.5 and above.

[https://laravel.com/docs/5.5/eloquent-resources#writing-resources](https://laravel.com/docs/5.5/eloquent-resources#writing-resources)
