### ISSUE TITLE
Magic __get for Illuminate\Support\Collection

### ISSUE THREAD

**Issue by imade-nl** [laravel/internals#35]
I would like to propose a magic __get method for the Illuminate\Support\Collection class to get the API more inline with, for example the Request class. 
It also gives a somewhat nicer syntacs when you cast a database column with multiple fields to a collection.

```
@if( $content->has('photo') )
    <img src="{{ $content->photo }}" alt="">
@endif
```

**Comment by dwightwatson** [comment]
But a collection is an array of items, not a key/value list. Getters work on the request because the request has a key/value list in the form of input.

**Comment by imade-nl** [comment]
Thanks for your reaction, I appreciate it! 
I see your point, but I also see plenty of examples in the docs whith single dimensioned arrays. 
There is already a get method in the class, I just would like it to be a magical one. :)

When I cast the db column 'fields' to an object I often find myself writing stuf like this: 
```
@if(isset($content->fields->header_photo) && !empty($content->fields->header_photo))
    <img src="{{ $content->fields->header_photo }}" alt="">
@endif
```

If I cast the fields column to a collection it would be like this:
```
@if($content->fields->get(header_photo))
    <img src="{{ $content->fields->get(header_photo) }}" alt="">
@endif
```

And with a magic __get it could be like this:
```
@if($content->fields->header_photo)
    <img src="{{ $content->fields->header_photo }}" alt="">
@endif
```

**Comment by acasar** [comment]
I'd love to see that as well. It seems someone already tried with a PR years ago but didn't succeed: https://github.com/laravel/framework/pull/2014

**Comment by jszobody** [comment]
Big thumbs up to this. I already access my model attributes with object syntax (`$user->first_name`), it trips me up when I expect to be able to do this with a Collection object.

**Comment by Dylan-DPC** [comment]
This issue can be closed :older_man:
