### ISSUE TITLE
[improvement]Put Pgsql connection parameters into DSN

### ISSUE THREAD

**Issue by iakio** [laravel/internals#351]
Currently, PostgresConnector issues some additional `SET` statements, `set names`, `set time zone`, and `set application_name`.

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Connectors/PostgresConnector.php

Actually, These parameters can be set via DSN. Like this.

```
new PDO("pgsql:options='-c client_encoding=utf-8';")
```

There are some test cases.

- https://github.com/iakio/pdo_pgsql_test/blob/master/pdo_pgsql_test.phpt
- https://circleci.com/gh/iakio/pdo_pgsql_test

These behaviors are not exists on PHP documents. But, you can see the specifications on the libpq documents (https://www.postgresql.org/docs/9.6/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS).

I think it may reduce connection costs.

**Comment by Garbee** [comment]
> I think it may reduce connection costs.

Why not setup a fork, modify the code, and run some tests and compare? That way we can have some actual data to discuss in place of theoretical possible benefits.

**Comment by iakio** [comment]
This is a patch.

https://github.com/iakio/framework/commit/da23b7d7c2f4a60d3f3b0682f9d8357d8ada810a

And I have created a small test project (https://github.com/iakio/laravel_pgsql_bench). There are two TestCases.  The only difference is how many options to pass. 

And I've run it on my laptop.

- php 7.0.9 (On Windows10)
- phpunit 5.7.5
- postgresql 9.6.1 (On Docker Machine)


```
> php -v
PHP 7.0.9 (cli) (built: Jul 20 2016 10:47:41) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.9, Copyright (c) 1999-2016, by Zend Technologies

> phpunit --repeat=1000 tests\FastCaseTest.php
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.
```

The result is:

TestCase |original(5.3)|my fork
--------|---|---
FastTestCase|12.58s|11.24s
SlowTestCase|16.12s|11.76s
