### ISSUE TITLE
[Proposal] Allow "asset" helper point to CDN

### ISSUE THREAD

**Issue by michelecurletta** [laravel/internals#353]
Imagine you've a CDN and want to work with local file during development, but switch to CDN in production.
Would be nice to have a flags in config, that changes the url created by the asset helper.
Obviously, there are a lot of different CDN providers (AWS Cloudfront, Cdnify, Akamai, etc), but the proposal consists in url switching behaviour.
Thanks

**Comment by Modelizer** [comment]
Can we go with environment variable to solve this problem? I mean 'CDN_ASSET_URL=http://example.com` also you can swap CDN specific creds if needed.

**Comment by michelecurletta** [comment]
@Modelizer I don't think that simple env variable could solve, because the configuration should be ["per disk"](https://laravel.com/docs/master/filesystem#obtaining-disk-instances).
The asset helper is a specific case which points to the "public" disk, but each disk could be accessibile behind a CDN, so the goal is to have a possible CDN for each disk instance, eg:

- images-disk -> images-disk-cdn.mydomain.ext
- video-disk -> video-disk-cdn.mydomain.ext
- etc...

Do you agree?

**Comment by Modelizer** [comment]
> images-disk -> images-disk-cdn.mydomain.ext
> video-disk -> video-disk-cdn.mydomain.ext
> etc...

Can storing them into `env` will solve?

**Comment by michelecurletta** [comment]
@Modelizer maybe yes... but probably a better place is in a config/cdn.php file, where is possible to insert a key-value list of disk-cdn_url settings

**Comment by Modelizer** [comment]
Yup! you can go with `config/cdn.php`
```php
`cdn` => env(`CDN_ENV`)
'testing-cdn' => [...],
'production-cdn' => [...],
```
and add this `CDN_ENV=testing-cdn` on your `.env` and access it by `config('cdn.cdn')`

I know `config('cdn.cdn')` do not looks good but you can think on your naming convention. :)

**Comment by michelecurletta** [comment]
Would be nice to have it in next releases :)

**Comment by michelecurletta** [comment]
@taylorotwell what do you think about it?
