### ISSUE TITLE
Controller generators for API vs web

### ISSUE THREAD

**Issue by chrispecoraro** [laravel/internals#355]
Now that web and API routes are separated into two separate files, it would be nice to have unique stubs to generate controllers more appropriate for their use.
For example, a RESTful API probably should not have `create()` and `update()`, since a view would normally be returned in this case.
A `-web` and `-api` flag could be added to the `artisan make:controller` command and use different stubs.

**Comment by Garbee** [comment]
Why not just delete the two methods in a generated resource controller?

I don't see the clear benefit to adding more pathways to maintain when it is not difficult for developers to just remove what isn't needed from the generated assets. It isn't like it is problematic.

**Comment by chrispecoraro** [comment]
I guess I'm using the latest change in 5.3.28 (`-m` to typehint the model) as a stimulus for more change. If somebody is new to Laravel, why would it be make sense to auto generate something that would then need to be deleted?

**Comment by jsposato** [comment]
If your api services mobile clients, create() and update() would not return views, they would return json responses indicating success or an error state.  I've done this and would find not having create() and update() generated a pain since I would then have to create them, thus making `make:controller` less effective.  Maybe I'm in the minority though.

**Comment by Garbee** [comment]
It would be optional via a flag. So if you want all of them you're just doing `--resource` or `--web` in this new world. Where `--api` would not have them. However, in your case your API does use them, so to you it would be confusing to have `--api` not generate the methods. I wonder which case more developers would even use.

Still not seeing the point in simply saving developers from needing to delete two methods.

**Comment by chrispecoraro** [comment]
@jsposato Right, what I'm saying is that each method returns either a response or a view, or other, depending on the situation. For example, whether it is a RESTful API or a web application resource controller (and whether the front end is blade views or something like Vue.js or Angular). However, we can't deal with return types (yet), until Laravel 5.5 is released. `create()` and `update()` may not always be needed, take the Zend RESTful controller for example:
```
// Or extend Zend_Rest_Controller
class RestController extends Zend_Controller_Action
{
    // Handle GET and return a list of resources
    public function indexAction() {}

    // Handle GET and return a specific resource item
    public function getAction() {}

    // Handle POST requests to create a new resource item
    public function postAction() {}

    // Handle PUT requests to update a specific resource item
    public function putAction() {}

    // Handle DELETE requests to delete a specific item
    public function deleteAction() {}
} ```
