### ISSUE TITLE
[Proposal] Force create model through a relationship

### ISSUE THREAD

**Issue by sepehr** [laravel/internals#356]
Currently the [`HasOneOrMany`](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php) class has no `forceCreate()` method implemented and as a result, we cannot do something like this:  

```php
$user->courses()->forceCreate($data);
```

Currently, [there seems to be no clean way to achieve this](http://stackoverflow.com/q/41406288/65732). It can be simply implemented along the lines of:  

```php
public function forceCreate(array $attributes) {
    $this->related->unguard();
    
    $instance = $this->create($attributes);
    
    $this->related->reguard();
    
    return $instance;
}
```

Of course, this needs to maintain model's guard state. And maybe implement related methods like `forceCreateMany()`. 

If you think it'd be a handy feature to have,  I'd be more than happy to submit a pull request.

**Comment by morloderex** [comment]
You could just use `forceFill($data)` and then append `save()`to the end of that :)

**Comment by sepehr** [comment]
@morloderex You can't use `forceFill()` **through a relationship**. The only way to do that is to get the underlying model by calling `getRelated()` on the relationship and doing something along the lines of:  

```php
$user->courses()
     ->getRelated()
     ->forceFill($data) // I can just call forceCreate() here and avoid that extra save() call.
     ->save();
```  

No matter what we call here, `forceCreate` or `forceFill`, the main problem is that we have to manage the foreign key assignment manually. See [this](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php#L324).

**Comment by taylorotwell** [comment]
Open to PRs.
