### ISSUE TITLE
[Proposal] Log out users by ID 

### ISSUE THREAD

**Issue by sepehr** [laravel/internals#360]
Currently, there's no straightforward way to [force a logout on a specific user](http://stackoverflow.com/a/41440830/65732) like there is with login using StatefulGuard's [`loginUsingId()`](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Contracts/Auth/StatefulGuard.php#L41).   

It'd be nice if we had a `logoutUsingId()` to logout a specific user by its ID.  

If you think it would be a nice little feature to have, I'd be happy to look into the implementation options and submit a PR, if possible.

Related discussion:  
[Multiple statements when logged users are deleted](https://github.com/laravel/framework/issues/3577)

**Comment by taylorotwell** [comment]
Not even possible for some drivers.

**Comment by anonymouse703** [comment]
Same problem here...  is there any update on Laravel 5.6 @sepehr and @taylorotwell ? seems Auth::logout will just logging out the current user and not the specific one.
