### ISSUE TITLE
[5.3/5.4] Default value for explicit bindings proposal 

### ISSUE THREAD

**Issue by segadora** [laravel/internals#363]
- Laravel Version: 5.3 or 5.4
- PHP Version: any
- Database Driver & Version: any

### Description:

I wish to have a change to **Explicit bindings** in [routes](https://laravel.com/docs/5.3/routing#route-model-binding).

If I understand it correctly. Implicit bindings hits the following code, which results in a **first** or **firstOrFail**, which means if I set a default value. I would expect to hit the method no matter, if the model is found or not.

https://github.com/laravel/framework/blob/f880e093dfbfc80a2ab0797d2056580e47e6888d/src/Illuminate/Routing/Router.php#L805

On route bindings (explicit bindings) it hits somewhere else, where it does not check if the method has a default value. This means it always will throw a 404 exception, if the model is not found.

https://github.com/laravel/framework/blob/f880e093dfbfc80a2ab0797d2056580e47e6888d/src/Illuminate/Routing/Router.php#L949

### Steps To Reproduce:

Create a explicit binding with a default value.

RouteServiceProvider.php
```
public function boot()
{
    parent::boot();

    Route::model('user', App\User::class);
}
```

routes.php
```
Route::get('profile/{user}', function (App\User $user = null) {
    //
});
```
**Notice:** ` = null`

I would expect it to hit the route, and not throw a 404 exception (ModelNotFound), because ` = null` is set.

Based on

https://github.com/laravel/framework/issues/17172
https://github.com/laravel/framework/issues/16727
https://github.com/laravel/framework/pull/16829

**Comment by michaeldyrynda** [comment]
Does this work as expected when you make the route argument `{user?}`?

Personally, I think I'd separate the two routes anyway.

**Comment by segadora** [comment]
```
	public function testModelBindingWithNullReturnDefaultValue()
    {
        $router = $this->getRouter();
        $router->get('foo/{user?}', ['middleware' => SubstituteBindings::class, 'uses' => function ($user = null) {
            return 'hello world';
        }]);
        $router->model('user', 'RouteModelBindingNullStub');
        $this->assertEquals('hello world', $router->dispatch(Request::create('foo/taylor', 'GET'))->getContent());
    }
```

returns

```
There was 1 error:

1) RoutingRouteTest::testModelBindingWithNullReturnDefaultValue
Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [RouteModelBindingNullStub].

/home/cn/Projekter/framework/src/Illuminate/Routing/Router.php:949
/home/cn/Projekter/framework/src/Illuminate/Routing/Router.php:828
/home/cn/Projekter/framework/src/Illuminate/Routing/Router.php:783
/home/cn/Projekter/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:37
/home/cn/Projekter/framework/src/Illuminate/Pipeline/Pipeline.php:137
/home/cn/Projekter/framework/src/Illuminate/Routing/Pipeline.php:33
/home/cn/Projekter/framework/src/Illuminate/Pipeline/Pipeline.php:104
/home/cn/Projekter/framework/src/Illuminate/Routing/Router.php:655
/home/cn/Projekter/framework/src/Illuminate/Routing/Router.php:629
/home/cn/Projekter/framework/src/Illuminate/Routing/Router.php:607
/home/cn/Projekter/framework/tests/Routing/RoutingRouteTest.php:662

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by segadora** [comment]
So to clarify, it does not make a difference.
