### ISSUE TITLE
Ability to pass variables into pagination view

### ISSUE THREAD

**Issue by pbelyaev** [laravel/internals#364]
That would be cool if there was a possibility to pass variables into pagination view. Somehow like so:

```php
$items->render('vendor.pagination.bootstrap-4', [ 'key' => 'value' ])
```

It seems nice for me and easy to implement. Anyone else finds that interesting?

**Comment by brayniverse** [comment]
Worth a shot if it's easy to implement. What's your use case?

**Comment by pbelyaev** [comment]
@brayniverse I would like to pass route name and make custom pages url like `/posts/page/1`

**Comment by pbelyaev** [comment]
I've just saw this https://laravel.com/api/5.4/Illuminate/Pagination/LengthAwarePaginator.html#method_render and I'm very happy Laravel 5.4 does have the second data argument which I hope will help to pass data into the view.

**Comment by pbelyaev** [comment]
Yes, it is! 
https://laravel.com/docs/5.4/pagination#customizing-the-pagination-view

**Comment by brayniverse** [comment]
Good work @pbelyaev :+1:

**Comment by pbelyaev** [comment]
@brayniverse actually, it wasn't me. I've just suggested and some of the core developers did that.

**Comment by Garbee** [comment]
It wasn't a core dev. The PR for the feature is [here](https://github.com/laravel/framework/pull/17331).
