### ISSUE TITLE
Relation::morphMap for Laravel Notification (database)?

### ISSUE THREAD

**Issue by DesmondPang** [laravel/internals#366]
I found that adding customized class/type name for morphMap dose not work for Laravel Notification. The default DatabaseChannel.php has just call get_class() to fill the type field. How to make the Relation::morphMap() that also fine to the notification model? Thank you.
```php
    public function send($notifiable, Notification $notification)
    {
        return $notifiable->routeNotificationFor('database')->create([
            'id' => $notification->id,
            'type' => get_class($notification),
            'data' => $this->getData($notifiable, $notification),
            'read_at' => null,
        ]);
    }
`

**Comment by phroggyy** [comment]
I'll have a look into this one. I have a good idea of it already

**Comment by phroggyy** [comment]
Hm, after looking into this, I realise what you're actually asking for is to rename notifications in the db from being the class name to also using a mapping. So a notification map, which I'm not sure I see the value of?

**Comment by DesmondPang** [comment]
What I mean is not to rename the notification name. I would like to change the string of 'type'.

Normally, I add the Relation::morphMap in AppServiceProvider.php file. For example 

```php
 Relation::morphMap([
            'shop' => Shop::class,
            'user' => User::class,
            'product' => Product::class,
        ]);
```

Then I have a imageable many-to-many polymorphic relations. The imageable_type field will store the value as I customised in AppServiceProvider.php. For example, it store "user" instead of "App\Models\User". 

If I provide a JSON web API. it will expose the architecture. e.g.: "App\Models\...\User"
If I change the path of class, the old data will not available as they stored the absolute path of class as the type.

Therefore, I suggest to add Relation::morphMap support in the build-in notification feature. Thank you very much.

**Comment by phroggyy** [comment]
Yes, I fully understand what you're asking for. However, the morph map is for polymorphic relations, the notifications system doesn't really have anything to do with that. Notifications are not involved in relations, and as such, using the existing `morphMap` makes no sense at all. The only option would be adding a notification map, and, again, I don't see the necessity for it. **Why** do you want this feature?

**Comment by DesmondPang** [comment]
Here is an sample data from the notification table. the notifiable_type works fine. However, the **type** shows the full path of the notifications.  Is it possible to have an option for us to choose to show the pull path or not.

```JSON
{
	"data":
	[
		{
			"id": "00ef2cc5-4296-41e2-be22-f7ca1246cdd4",
			"type": "App\Notifications\SellerOrderStatusUpdate",
			"notifiable_id": 1,
			"notifiable_type": "shop",
			"data": "{\"message\":\"System update\"}",
			"read_at": null,
			"created_at": "2017-01-16 23:10:04",
			"updated_at": "2017-01-16 23:10:04"
		},
		{
			"id": "00fda02b-487e-42e0-9a11-3c00400ffc3f",
			"type": "App\Notifications\SellerOrderStatusUpdate",
			"notifiable_id": 1,
			"notifiable_type": "shop",
			"data": "{\"message\":\"System update\"}",
			"read_at": null,
			"created_at": "2017-01-11 00:20:47",
			"updated_at": "2017-01-11 00:20:47"
		}
	]
}
```

**Comment by drewjbartlett** [comment]
I agree this would be nice to have just for consistency. For instance, my `morphMap` looks like:

```php
       Relation::morphMap([
            'comment' => 'App\Model\Comment',
            'post'    => 'App\Model\Post',
            'user'    => 'App\Model\User'
        ]);
```

And so my other tables store `user` for the user model yet notifications store `App\Model\User`:

```json
[
    {
        "id": "76b8ed56-481a-4b98-8bf9-68228da46228",
        "type": "App\\Notifications\\CommentRepliedTo",
        "notifiable_id": 1,
        "notifiable_type": "App\\Model\\User",
        ...
    }
]
```

I know I can just transform that string back to `user` But it would be nice to have it match up still :)

**Comment by jesstrux** [comment]
Hey @DesmondPang what are you using at the moment to combat the inexistent morphMap?

**Comment by DesmondPang** [comment]
@jesstrux As I used Fractal to create the api response, I used the transformer to change the type attribute.
[http://fractal.thephpleague.com](url)
For Laravel
[https://github.com/spatie/laravel-fractal](url)

**Comment by tadevosyankhachik** [comment]
Type didn't have any connection with morph relationship, it just simple type, so you can't set custom polymorphic types via Relation::morphMap, you can set for notifiable_type only.
See https://laravel.com/docs/5.7/eloquent-relationships#polymorphic-relations

**Comment by osbre** [comment]
I tried to create a pull https://github.com/laravel/framework/pull/29882

### and here is the **_solution that works_**:
https://gist.github.com/osbre/aee72ff8ce64d3daaec0f35c7dd445f6
