### ISSUE TITLE
Eloquent Events

### ISSUE THREAD

**Issue by lagbox** [laravel/internals#37]
I would suppose we want to move these away from strings and to objects in the future.
Any ideas of a smooth way to go about this in a general way?

**Comment by tomschlick** [comment]
It looks like that process has already been started https://github.com/laravel/framework/tree/5.2/src/Illuminate/Database/Events

So really it would be just migrating more of those events to objects from the string versions.

**Comment by lagbox** [comment]
What I mean is, if you have generic events for models as objects (Eloquent\Events\Saved for example), since this is a generic event, how would one define that they want to assign a listener to User Model Saved Event, not all Saved events from Eloquent?
`'Eloquent\Event\Saved:App\User' => 'Some\UserSaved'` ?
That is the part I am trying to figure out. Seems the dispatcher would need to treat all these events as special cases and pull a Model name from them to filter them as needed.

**Comment by tomschlick** [comment]
Thats a good question. There isn't a clean way to do it with object based listeners right now.

You would have to pass a parameter through on those "generic" events that contained the object type it was using and check on that. For now though, you can use the ```::saved()``` syntax and register listeners directly on a model that way. Not as clean though.

**Comment by lagbox** [comment]
Yea, via the model would remove the complication from the user side.
Though the goal would be to be able to easily register these in service providers, as I see that come up a lot in support and atm you can do it via the string for it, but would be really nice to have some way to do it via the objects in a way that isn't too crazy.
Not sure what is going on with that, but a simple syntax might make this all work out in the end.

I appreciate the input. Been trying to think of a smooth way to go about this without having to change much in the dispatcher.

**Comment by tomschlick** [comment]
Well the model is already passed through in those events so you'd be able to catch that. Maybe a wrapper around that catching would make it easier to catch but I'm not sure how that would look and would be much different than the current listener registration process.

**Comment by lagbox** [comment]
Yup, that is why I am trying to figure out a decent syntax or something to be able to register these like any other event in the entire system.
