### ISSUE TITLE
[Proposal] Optional Compression for Cache

### ISSUE THREAD

**Issue by ethanhann** [laravel/internals#370]
Compressing cached string data can save a lot of memory and network bandwidth, especially for high volume applications. This blog post describes the benefits: http://labs.octivi.com/how-we-cut-down-memory-usage-by-82/

The implementation would be pretty straightforward. In the cache stores' set method I would compress non-numeric/non-null data using gzcompress. In the get method I would check the first two bytes of the header information to determine if it is compressed. If it is, I would use gzuncompress to uncrompress the data before returning it. This functionality would be enabled or disabled with a per-store setting in config/cache.php.

Is there any interest in including this feature in Laravel? If so, I can put together a PR.

**Comment by tomschlick** [comment]
Sounds good to me. I would say just go ahead and make the PR!

Side note: That could be useful in the database level as well with a "compressed" cast type.

**Comment by ethanhann** [comment]
PR: https://github.com/laravel/framework/pull/17340

**Comment by ethanhann** [comment]
PR denied without an explanation... **shrug**

**Comment by ethanhann** [comment]
I created a package that adds a custom RedisStore class with the compression code from the PR:
https://github.com/ethanhann/Laravel-RedisStore
