### ISSUE TITLE
action() and trailing slash

### ISSUE THREAD

**Issue by superkozel** [laravel/internals#371]
there are two different routes:

Route::get('/shares/', 'ActionController@index');
AND
Route::get('/shares', 'ActionController@index');

action('ActionController@index'); generates the same url "/shares" ignoring trailing slash

this issue is somehow connected to this method:

    /**
     * Prefix the given URI with the last prefix.
     *
     * @param  string  $uri
     * @return string
     */
    protected function prefix($uri)
    {
        return ltrim(trim($this->getLastGroupPrefix(), '/').'/'.ltrim($uri, '/'), '/') ?: '/';
    }

**Comment by tomschlick** [comment]
Why is this an issue? Looks like intended functionality to me...

**Comment by RomainLanz** [comment]
This is the expected behavior. `/shares` and `/shares/` is exactly the same route.

**Comment by superkozel** [comment]
i don't think so. When i'am explicitly typing that slash, i'am expecting it to be at the end of the generated URL. Of course, i want both "/shares" and "/shares/" urls to work the same.
There is two different ways to handle trailing slash: remove it everywhere and add it everywhere, with htaccess. I wanted to add it everywhere to avoid 301 redirects in every page(I'am moving site from cms to laravel, this site was adding trail, so every url have that slash), but laravel doesnt allow this in the core, cause every generated url have trailing slash removed

**Comment by superkozel** [comment]
i found affordable solution
1. remove trail slash in .htaccess
2. replace every usage of action function with new one

/**
 * Action with trailing slash, laravel workaround
 */
function actionts($name, $parameters = [], $absolute = true)
{
    $url = action($name, $parameters, $absolute);
    $parts = parse_url($url);

    return (! empty($parts['host']) ? ($parts['scheme'] . '://' . $parts['host']) : '') . $parts['path'] . '/' . (! empty($parts['query']) ? ('?' .$parts['query']) : '');
}
