### ISSUE TITLE
[PROPOSAL] PLEASE ADD FEATURE FOR ELOQUENT ORM

### ISSUE THREAD

**Issue by ARKKYN** [laravel/internals#377]
Please add support for 
  -- getter and setter methods ( like getBy{columnName}($value) )
  --automatic transaction handling 
  --auto generation of models for tables with relationship
  --Grouping models in models folder by default

**Comment by crynobone** [comment]
> automatic transaction handling

```php
$user = new User($attributes);
$user->saveOrFail();
```

**Comment by tomschlick** [comment]
> Grouping models in models folder by default

The current way is intentional. If you want them in a folder you can do this when generating:

`
php artisan make:model "Models\Example"
`

**Comment by Garbee** [comment]
> -- getter and setter methods ( like getBy{columnName}($value) )

These are called "Accessors and Mutators". They are fully described in the Eloquent documentation.

> --auto generation of models for tables with relationship

This feature would need a lot more detail for discussion. Right now, no one has any clear idea of what you want much less to discuss implementation details if it should even be done.

Please file one issue per feature you want and describe the functionality you want to see in detail. This makes discussion and handling the issues far easier than trying to get one issue with 4 individual requests handled.

**Comment by taylorotwell** [comment]
Much of this is already supported.
