### ISSUE TITLE
[Proposal] Listen for works on different database connections

### ISSUE THREAD

**Issue by pabloleone** [laravel/internals#379]
Hi @all,

I'm on Laravel 5.2 and I couldn't find a way to trigger jobs on a specific database. As soon as the job is unserialized, the system lose the database connection specified in queue.php config file and it loads the default connection.

My environment has 3 different databases and each of those could have their own jobs.

Thank you.

**Comment by tomschlick** [comment]
Pass the connection name into the job as a parameter then bootstrap the connection from there.
