### ISSUE TITLE
[Proposal] Make Redis connections configurable like DB connections

### ISSUE THREAD

**Issue by ikari7789** [laravel/internals#381]
I would like to propose changing the way that Redis connections are defined to mirror the way that database connections are defined.

```php
<?php

'redis' => [
    'default' => env('REDIS_CONNECTION', 'redis'),

    'connections' => [
        'redis' => [
            'driver' => 'predis',
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 0,
            'options' => [
                'timeout' => 10.0,
            ],
        ],
    ],
],
```

The flexibility available with Redis connections is minimal in comparison to database connections. For instance, in database connection configurations, all configuration items are encapsulated within that specific connection's array item, whereas with the Redis configuration, it relies on setting global configuration items that apply to all defined connections. Allowing configuration to be handled in such a way allows more flexibility in the way that connections are defined and handled and removes any dependency on global configuration.

**Comment by taylorotwell** [comment]
Thanks will look into this

**Comment by taylorotwell** [comment]
This works for me:

<img width="670" alt="screen shot 2017-03-15 at 10 51 15 am" src="https://cloud.githubusercontent.com/assets/463230/23957437/5ccf49d0-096d-11e7-86b7-e0088611b57a.png">

**Comment by taylorotwell** [comment]
Am I missing something?
