### ISSUE TITLE
generate route url  forcly appending optional parameters without approving parameters 

### ISSUE THREAD

**Issue by shadywallas** [laravel/internals#384]
if you defined  named route like so , 

`

     Route::get('/brands/{brandName?}/{categorySlug?}/{subCategorySlug?}',
            [
                'as' => 'brands',
                'uses' => 'Categories\\IndexController@getList'
            ]);`

when generating url to this route  using the following 

`
       
         $url = route('brands',  [
                'size'=>20,
                'brandName' => 'Vans',
                'categorySlug'=>'Clothes',
                'subCategorySlug'=>'dress',
                'storeName' => 'Walmart'
            ],false);`
will work correctly because all of named parameters exist in the array and generated link will be  
`/brands/Vans/Clothes/dress?size=20&storeName=Walmart`

but in another case where we only include some of optional  parameters removing subCategorySlug
`

         $url = route('brands',  [
                'size'=>20,
                'brandName' => 'Vans',
                'categorySlug'=>'Clothes',
                'storeName' => 'Walmart'
            ],false);`

we Expect 
`/brands/Vans/Clothes?size=20&storeName=Walmart`
Actual Result 
`/brands/Vans/Clothes/20?storeName=Walmart` 
This happens because in replaceRouteParameters at line 355   in class 
`/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php` 
it call's `preg_replace_sub` which is a helper function in laravel which matches the rest of parameters by order to fill missing optional parameters first . 

what do you think about this behavior , i think it was mad that way to allow passing data without names but if we have provided names and it doesn't exist it should add to query string

**Comment by Garbee** [comment]
Have you tried setting the missing item to `null` to see what happens?

**Comment by shadywallas** [comment]
yes , i did  not working , as you can see the implementation uses `isset` which will see `null` values as not set 
so null values just got skipped
`

         protected function replaceNamedParameters($path, &$parameters)
            {
           return preg_replace_callback('/\{(.*?)\??\}/', function ($m) use (&$parameters) {
            return isset($parameters[$m[1]]) ? Arr::pull($parameters, $m[1]) : $m[0];

        }, $path);
    }`

**Comment by Garbee** [comment]
Yea, this looks like just a generic bug to me. Should probably be an issue on the framework repo over an internals discussion.
