### ISSUE TITLE
A documented way to change the controller and method from within middleware.

### ISSUE THREAD

**Issue by unstoppablecarl** [laravel/internals#385]
In Laravel 5.4 there is only one way I know of to change the controller/method to be resolved from within middleware. I'm pretty sure it will ignore controller middleware on the `Foo@bar` controller, I've never used controller middleware though so that is fine with me.

```php
class ChangeControllerMiddleware {
    
    public function handle($request, Closure $next) {
        
        $route = $request->route();

        $routeAction = array_merge($route->getAction(), [
            'uses'       => '\App\Http\Controllers\Foo@bar',
            'controller' => '\App\Http\Controllers\Foo@bar',
        ]);

        $route->setAction($routeAction);
        $controller        = app(\App\Http\Controllers\Foo::class);
        $route->controller = $controller;

        return $next($request);
    }
}
```

I'm not sure if the api was intended to function this way and I am weary of using it. If this is the intended behavior I would propose adding a function `changeControllerAction($controller, $method)` to the Route class that does it internally.  Ignoring controller middleware on the new controller could be intended and documented behavior. 

The use case I run into for this has been wanting to change a controller based on the type of a model being passed in a route param.

related but more specific issue #368

**Comment by unstoppablecarl** [comment]
This is a slightly cleaner way to do it. Clearing the cached controller object so the route recreates it with the new class.

```php
class ChangeControllerMiddleware {
    
    public function handle($request, Closure $next) {
        
        $route = $request->route();

        $routeAction = array_merge($route->getAction(), [
            'uses'       => '\App\Http\Controllers\Foo@bar',
            'controller' => '\App\Http\Controllers\Foo@bar',
        ]);

        $route->setAction($routeAction);
        $route->controller = false;

        return $next($request);
    }
}

```

**Comment by fernandobandeira** [comment]
Currently i'm doing something similar however I'm doing it inside a controller, this approach seems cleaner, I'll try to use it and check/make it intended sometimes we do need to change controllers and sometimes we can't do it from the route file...
