### ISSUE TITLE
[Proposal] Add more control over eloquent queries

### ISSUE THREAD

**Issue by Yorkii** [laravel/internals#388]
Why does laravel adds extra condition when querying relationship? In some cases (if not most) it is unwanted behaviour lowering database performance. It always check if foreign key is not null. To be more precise it happens in `Illuminate/Database/Eloquent/Relations/HasOneOrMany.php` on line `60`. We should have more control over this.

**Comment by fernandobandeira** [comment]
Do you know when we would need this not null where clause?
It seems that morphOneOrMany doesn't have it so it doesn't seem consistent at all...

**Comment by Yorkii** [comment]
Check SQL generated for `hasOne` relationship for ex. you join it by `email` field. This would look like `SELECT * FROM users_info WHERE email = ? AND email IS NOT NULL`. Let's say `User` model doesn't allow to `email` be `null`. So whenever it query relation, `SELECT * FROM users_info WHERE email = ?` is enough, because checking field for `null` values lower performance of query. Got the point?
