### ISSUE TITLE
[Proposal] Add get/set/isLocale() methods to Application Contract.

### ISSUE THREAD

**Issue by DaveBagler** [laravel/internals#389]
I'm building a package that gets and sets the application's locale, but this is complicated by not having access to the Application class's three locale methods in the contract.

I have a pull request that adds that exposes the three methods in the interface, the doc blocks and method declarations are copied directly from what is in the Application class.

https://github.com/laravel/framework/pull/17589

**Comment by Garbee** [comment]
There is no need to open an issue here if you already have a PR. The PRs get viewed much sooner and are acted on (at some point) by Taylor himself typically. This is superfluous unless instructed when a PR is closed to open an issue for further community discussion.

**Comment by DaveBagler** [comment]
Thanks @garbee. I'll close this issue.
