### ISSUE TITLE
InteractsWithQueue::failed with message

### ISSUE THREAD

**Issue by assertchris** [laravel/internals#39]
I think it would be useful if jobs and the `failed_jobs` table could accommodate a failure message. I find more complex jobs can have multiple calls to `$this->failed()` but it's difficult to track which instance triggered the failure condition...

**Comment by taylorotwell** [comment]
Yeah could be useful.

**Comment by tomschlick** [comment]
To me this is where a exception tracker like [Sentry](https://github.com/getsentry/sentry) really shines. You're able to not only track the individual exceptions but you're able to track similar exceptions across many servers if you need to and see the history of it all. Couple that with the deploy data and you can see exactly which version caused an issue.
