### ISSUE TITLE
[Proposal] Asset domain configuration

### ISSUE THREAD

**Issue by dwightwatson** [laravel/internals#392]
I've noticed that the `mix` helper returns an absolute URL for assets, where the `elixir` helper would return a relative one. However, you might not always want to be serving your assets from the same URL as the app. For example, a CDN that might sit in front of your app and cache assets.

I'd like to propose a second URL be added in `config/app.php` or wherever else is appropriate, something like `asset_url`. It could default to the primary URL but changed if necessary.

Is this a PR you'd consider? Otherwise, is the functionality I'm after already available in another way?

**Comment by drbyte** [comment]
Perhaps `mix.setPublicPath('path/to/public');` would work?

`node_modules/laravel_mix/setup/webpack.mix.js` says:
```
// Full API
// mix.js(src, output);
// mix.extract(vendorLibs);
// mix.sass(src, output);
// mix.less(src, output);
// mix.combine(files, destination);
// mix.copy(from, to);
// mix.minify(file);
// mix.sourceMaps(); // Enable sourcemaps
// mix.version(); // Enable versioning.
// mix.disableNotifications();
// mix.setPublicPath('path/to/public');
// mix.autoload({}); <-- Will be passed to Webpack's ProvidePlugin.
// mix.webpackConfig({}); <-- Override webpack.config.js, without editing the file directly.
```

**Comment by drbyte** [comment]
Oh wait. Duh. You're talking about the `mix()` helper function to *display* compiled assets, not giving instructions to Laravel Mix on where to put the compiled assets.

My bad.

**Comment by m1guelpf** [comment]
@dwightwatson So this can be closed?

**Comment by dwightwatson** [comment]
I still think it would be beneficial to have some sort of `asset_url` configuration so that it would be easy to use a CDN with your apps.  The PR I made above was just updated Mix to return a relative path rather than an absolute path so it's easier to replace with another host if you need.
