### ISSUE TITLE
Move providers and aliases configuration to its own file

### ISSUE THREAD

**Issue by rogervila** [laravel/internals#393]
It would be nice to have a specific config file for providers, and another one for aliases.

**Comment by jbrooksuk** [comment]
I don't see any gain to this at all. You only have a handful of either and it'd likely mean a slight performance hit as there would be more config files to load - even if it's almost nothing, it's unnecessary IMO.

**Comment by Garbee** [comment]
What is the benefit this provides? While most of this is cached in production so the penalty is non-existant, I still don't see a reason to do this. If anything they should be moved into dedicated service provider classes for the app so it is easier for developers to have a place to conditionally add ones based on their environment. Just moving them from one config file into dedicated ones provides no real benefit.
