### ISSUE TITLE
[proposal][5.5] Redis Sentinel support

### ISSUE THREAD

**Issue by andrewmclagan** [laravel/internals#395]
Predis now supports Redis Sentinel.

For Laravel to also have support it would only require very minimal configuration changes.

**Comment by tomschlick** [comment]
Looks like there are two decent packages for it here: 

https://github.com/monospice/laravel-redis-sentinel-drivers

and here: https://github.com/cooperaj/laravel-redis-sentinel

Might be a good starting point if you wanted to create a PR

**Comment by andrewmclagan** [comment]
Sure, I will get onto that in the next week

**Comment by cyrossignol** [comment]
@andrewmclagan Let me know if I can help 👍

**Comment by andrewmclagan** [comment]
@cyrossignol shall do!

**Comment by mrtariqkhan** [comment]
@andrewmclagan any updates on this? We are going to implement one of the packages mentioned by @tomschlick. Would be nice if we can use something native to laravel for this as it will have continued support. Thanks!

**Comment by cyrossignol** [comment]
@mrtariqkhan I maintain the first package which is getting an update in a week or two for Horizon, transactions, and pub/sub, with support for PhpRedis coming in a couple of months, and a full Sentinel API/Artisan commands by the end of the year.

If there's enough of a community need, I can merge some of the fixes and features into the framework, but development in the package context makes my life easier and allows room for some extra goodies that fall outside the framework scope.

**Comment by taylorotwell** [comment]
I'm fine with this being a package for now.

**Comment by mrtariqkhan** [comment]
@cyrossignol thanks for the detailed answer waiting on for the update for horizon transactions.

**Comment by cyrossignol** [comment]
@mrtariqkhan Couple days away...need to finish up acceptance tests for this.

**Comment by cyrossignol** [comment]
@mrtariqkhan Horizon support released in version 2.4.0.

**Comment by mrtariqkhan** [comment]
@cyrossignol thnx! for the update

**Comment by abaar** [comment]
> Predis now supports Redis Sentinel.
> 
> For Laravel to also have support it would only require very minimal configuration changes.

can you show us what changes do we need?

**Comment by ganeshkarki** [comment]
I created the pull request for it.
