### ISSUE TITLE
[Proposal] Read Only Model

### ISSUE THREAD

**Issue by fernandobandeira** [laravel/internals#396]
Moved from laravel/framework#17692

> This feature request comes from project requirements I'm actually working on. We have created Eloquent models and relationships to be able to play with a legacy database. But we are not supposed to change data in any way (create / update / delete).
I believe this is a trivial change to be implemented by someone acquainted of Eloquent internal details.
We just need a readonly property which defaults to true, keeping current normal behaviour, but which can be set to false, enabling the read-only behaviour.
I believe performance impact is minimal, if only the necessary ifcondition to verify the readonly boolean is placed in the proper strategic place inside the Eloquent Model class.
Thank you.
@jbruni

[Example package ](https://github.com/michaelachrisco/ReadOnlyTraitLaravel)
[Gist from jbruni](https://gist.github.com/jbruni/3f6de84d8b6ca96cf574bb2b41671916)

List of methods that would need to check this attribute:
- create
- forceCreate
- save
- update
- firstOrCreate
- firstOrNew
- delete
- destroy
- restore
- forceDelete
- performDeleteOnModel
- push
- finishSave
- performUpdate
- touch
- saveOrFail
Any others?

Also we should make sure that these events are not fired:
- saving
- saved
- updating
- updated
- creating
- created
- deleting
- deleted

Also would it be better to throw a ReadOnlyException(like on the gist example) or return false(like on the package example)?

**Comment by tomschlick** [comment]
> Also would it be better to throw a ReadOnlyException(like on the gist example) or return false(like on the package example)?

If this were to be implemented in the core, the ReadOnlyException is the way to go. Allows you to catch that from anywhere in the app instead of relying on return vals.

**Comment by RemiCollin** [comment]
I'm not sure I'm fully understanding the use case here. Would the `readonly` property be defined on a per class basis, or on a per record one (and therefore a part of the object's attributes) ? 

If it's on a per class basis, wouldn't it be better to have a `Repository` hydrate simple plain PHP objects ?

**Comment by jbruni** [comment]
1. Per class basis. Just like we have `protected $table = 'table_name';`

2. Repository? Simple plain PHP objects? I don't think so.

We have made the Model classes and quite complex relationships between them. We want to make use of Eloquent stuff, like "scope" and "attribute" methods for the individual records, as well as querying the relationships, using `::with` and et cetera.

We just don't want to modify the database contents. We shall read and analyse the data, but do not modify it. We can rely on developer discipline, but if we have a "readonly" we can switch on, it is safer.

**Comment by skyrpex** [comment]
The repository would just use the eloquent model internally.

**Comment by jbruni** [comment]
Repository or non-repository: it is irrelevant.

**Comment by skyrpex** [comment]
Another way would be using a readonly connection. Haven't ever tried that, though.

**Comment by jbruni** [comment]
This sounds good. But in this specific project, we have prefixed tables which are the only ones - inside the same DB - which this app is supposed to read/write.

**Comment by jbruni** [comment]
This is how I see: the feature is not *needed*, as there are many workarounds and strategies possible to deal with it.

But if the feature *is there*, then we do not need to even think about workarounfd or strategy: we simply put `public $readonly = true;` in there, and it's done.

**Comment by jbruni** [comment]
Well... I understand that later some dev can use `DB::raw()` and later someone will blame: "Hey! We have readonly models! How did we got data changed?" - and point fingers to the framework... Maybe Laravel does not want to assume this responsibility. :-)

**Comment by RemiCollin** [comment]
I think how I would approach this would be to create a base class extending the eloquent's `Model`, which override every method that are related to writing to DB : 

```php

use Illuminate\Database\Eloquent\Model;

abstract class ReadOnlyModel extends Model
{

    public function save()
    {
         throw new ReadOnlyException;
     }

     ... 
}

```

And then extends all the Read Only model from this base class.

**Comment by fernandobandeira** [comment]
@jbruni Regarding the connections workaround you should be able to set a connection for each model, so you can create a read only connection and set it on the models that you want only read access:

```php
    protected $connection = 'mysql2';
```

Haven't tested it but should cover your usecase...

**Comment by garygreen** [comment]
I really dislike this idea. It's totally unnecessary for core and has all sorts of weird side effects, particularly when it comes to saving relations and other quirky stuff.

Read only connection is pretty problematic as well, would it throw all kinds of errors when you try and save stuff? 

I would suggest to have some kind of `ReadOnlyMiddleware` that can be used on routes where your posting data to create or edit some resource, that would check if it's enabled or not. Then you can redirect back with an error message saying the model is in read only mode or something.

Having this baked into eloquent is a really bad idea.

**Comment by michaeldyrynda** [comment]
The only way to truly safeguard against accidental writes is to use a database user that only has `SELECT` privileges. You'll get a nice `Illuminate\Database\QueryException`. This way, it doesn't matter if you accidentally write to it a model or not.

Otherwise, as has been suggested, use your own base model or create a package if you need to reuse the functionality. I don't think it's needed at the framework level personally.

**Comment by deleugpn** [comment]
I agree with @michaeldyrynda here. The first thing that came to mind was exactly a user database without write privilege. You can easily setup 2 database connections with 2 different users and specify which models uses which connection. Instead of a simple `protected $readonly = true;` with a lot of side effects, you would just `protected $connection = 'mysql_readonly';` and without any change in the core at all.

**Comment by fgilio** [comment]
Just in case someone needs it, here you can see how to create a simple read only user for MySQL: https://gist.github.com/mmasashi/165b0d73cdc632ffa5ae9a0919e3f3cf

**Comment by hongaar** [comment]
We're using this observer to make models read-only:

```php
class ReadOnlyObserver
{
    public function creating(Model $model)
    {
        throw new OperationNotAllowed('Directly creating this resource is not supported.');
    }

    public function updating(Model $model)
    {
        throw new OperationNotAllowed('Directly updating this resource is not supported.');
    }

    public function deleting(Model $model)
    {
        throw new OperationNotAllowed('Directly deleting this resource is not supported.');
    }
}
```

Then in a service provider:

```php
class YourServiceProvider extends ServiceProvider
{
    public function boot()
    {
        YourModel::observe(ReadOnlyObserver::class);
    }
}
```
