### ISSUE TITLE
Make it easier to change the locale of Faker

### ISSUE THREAD

**Issue by garygreen** [laravel/internals#398]
At the moment Faker always defaults the locale to US. It would be nice if there was some kind of way of changing it through a config/env option.

I know you can change it by completely overriding the way the faker generator singleton is registered with something like the below, but it's a bit long-winded and would be easier to change through a simple ``env('FAKER_LOCALE')`` option.

```php
<?php

namespace App\Providers;

use Faker\Factory as FakerFactory;
use Faker\Generator as FakerGenerator;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton(FakerGenerator::class, function () {
          return FakerFactory::create('en_GB');
        });
    }
}
```

**Comment by RemiCollin** [comment]
I agree, plus it's very easy to implement with a config key. 

More and more we're using Faker & Factories as an easy way to quickly throw an API for prototyping frontend, and I'm pretty sure this is a pretty common use case, and we need to set the localization for this.

**Comment by drbyte** [comment]
I've long wished this was built in already too. 

I've been doing it this way, which pulls in the app.locale config setting.

```php
       // tell Faker to use the app's primary locale
        $this->app->singleton(\Faker\Generator::class, function () {
            return \Faker\Factory::create(config('app.locale'));
        });
```

**Comment by themsaid** [comment]
Next patch you'll be able to set a faker locale in config/app.php using a `faker_locale`  config key.

https://github.com/laravel/framework/pull/17895/files

**Comment by garygreen** [comment]
Thanks for update @themsaid much appreciated. 😄

**Comment by themsaid** [comment]
❤️

**Comment by jbrooksuk** [comment]
@themsaid I feel like that should go into a new `testing.php` or something. Seems weird to be in the main app config?

**Comment by garygreen** [comment]
Not really specifically related to testing though - I use faker in model factories and seeders to seed fake data into application for demo purposes, etc. It would be nice if it could just use `app.locale` setting but faker wants it in a slightly different format. Dunno, doesn't make much difference to me. Easy enough to configure with `faker_locale`, if you don't want it in your config then don't worry, it defaults to US.

**Comment by fendiseptiawan0709** [comment]
Really helpful.

I only need to add variable 
`'faker_locale' = 'id_ID'`
inside of my `config/app.php`

Or, if I want to make them more customization, just add a new varible `FAKER_LOCALE` in `env.php` and call it in the config `'fakse_locale' = env('FAKER_LOCALE', 'id_ID)`. 

PS : The second parameter is default value.

**Comment by bennyatc** [comment]
@fendiseptiawan0709 GREAT.
Thanks.
