### ISSUE TITLE
Queue::flush (for clearing pending jobs) vs Queue::flushedFailed

### ISSUE THREAD

**Issue by assertchris** [laravel/internals#40]
I think it would be useful to have a method by which to clear currently pending queued jobs.

**Comment by tomschlick** [comment]
For backwards compatibility it should probably be `Queue::flushPending()` which would default to flushing jobs from all tubes but you could specify a string or array of tube names to flush...

**Comment by TiagoMaiaL** [comment]
It'd also be nice if we had a default artisan command around this method.

**Comment by tomschlick** [comment]
yeah it would be trivial to add a `queue:flush-pending` method that calls
the method Chris is proposing

**Comment by ehtasham89** [comment]
It would be nice if pending queue list can display and flush specific or all pending jobs.

**Comment by tomschlick** [comment]
@ehtasham89 for that I would suggest using something like beanstalkd and [Beanstalk Console](https://github.com/ptrofimov/beanstalk_console)

You can have thousands of jobs in a queue and that would be too much for laravel's CLI to handle output for.

**Comment by taylorotwell** [comment]
I'm not sure if it will be technically feasible across all drivers, especially ones like SQS.

**Comment by ben-joostens** [comment]
I haven't really looked into this, but SQS seems to have a PurgeQueue method:

http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_PurgeQueue.html

**Comment by jakubkratina** [comment]
Yeah, it would be awesome to have this option

**Comment by barryvdh** [comment]
I would also like this fix. Could also be something like `queue:flush --all`.
If it's not feasible for all, perhaps just implement it for the ones that do allow it (db, redis, ..)?

Few common scenarios that I've run into:
 - Local development, ignoring queues with 'old' code or from a previous day (eg. didn't run the queue then).
 - Production: queue failed some time ago, no need to run the old queue again (old emails, unneeded calculations etc)

**Comment by jschutt** [comment]
I also frequently encounter the situation where I have a bunch of local jobs sitting on the queue that I don't want to run. Having a method to clear/flush them prior to starting the queue up would be helpful.

**Comment by pflirae** [comment]
I solved this problem using morrislaptop/laravel-queue-clear, at least until a solution is incorporated on Laravel (I am using redis, and it worked perfect)

**Comment by bolajipemipo** [comment]
@pflirae Looks good.

**Comment by taylorotwell** [comment]
I'm open to this if it can be implemented for all drivers. Some consideration for Horizon will probably be needed.

**Comment by zlanich** [comment]
Why was this closed with no resolution? I'm in the same boat as @jesseschutt.

**Comment by bolajipemipo** [comment]
@zlanich Solved mine using @pflirae option.

**Comment by zlanich** [comment]
@bolajipemipo Yea, I tried that too and it seems to work fine. This sure as heck seems like something that should be in core.

**Comment by shibinjj** [comment]
@pflirae Works for me too. Hoping to see a artisan command for the same in the near future. It will be pretty handy

**Comment by dmitryuk** [comment]
https://github.com/RoboFinance/laravel-redis-queue-clear
