### ISSUE TITLE
[Proposal][5.4] Add additional redis.connection alias

### ISSUE THREAD

**Issue by hskrasek** [laravel/internals#400]
Now that the Illuminate Redis component roughly matches the same pattern as the Database component, I propose we add a `redis.connection` alias so that you don't have to inject or type hint the the entire `RedisManager` class.

```php
$this->app->bind('redis.connection', function ($app) {
            return $app['redis']->connection();
        });
```

**Comment by taylorotwell** [comment]
Fine with me.
