### ISSUE TITLE
Simplify event handling

### ISSUE THREAD

**Issue by garygreen** [laravel/internals#402]
At the moment you have `App\Events` and `App\Listeners` -- why not have these combined into one file with a `handle()` method? I'm not sure there needs to be two separate classes as the event and it's handling are intrinsically linked.

**Comment by Garbee** [comment]
What about when you have multiple listeners doing different things for a single event?

**Comment by garygreen** [comment]
Hmm that's a good point. I can't say I've needed multiple listeners for an event before but obviously that's still a needed feature.

Laravel could detect if there is a `handle()` method in events and if so, call that. Listeners would still work the same way and still be called, but it's not a requirement for handling of a basic event.

Maybe inside the handle method you could `$this->dispatch([YourListener::class, YourSecondListener::class]);`, as an alternative to mapping an event and it's listeners in `EventServiceProvider`. That could even open the door to caching/deferring the event registration along with generally simplify event handling.

Would be interested in seeing how many people use multiple listeners for a single event...

**Comment by franzliedke** [comment]
I'd advocate against this. Decoupling events from listeners is the whole point of this pattern. :)

**Comment by garygreen** [comment]
I suppose it's not really simplifying it if there are multiple ways of then doing events.
