### ISSUE TITLE
Documentation for expectsNotification

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/internals#403]
There are several methods on `Illuminate\Foundation\Testings\Concerns\MocksApplicationServices` which are, I think, not documented.

1. `expectsNotification`
2. `expectsEvents`
3. `expectsJobs`

In the docs for 5.3 release, last two are mentioned, but this was removed with [this](81f7afdaa13d3221fea1e5c34708bfcc4346214b) commit. Is there a reason for not documenting this functionality or is it just a mistake and should be corrected?

**Comment by valterlorran** [comment]
After checking the code, I found out that you need add expection first, then you'll have to call the `php artisan queue:work --once ` in case you use queue:

```php
    public function testLive()
    {
        $liveStarting = $this->createLive(Carbon::now()->subMinutes(10));

        $this->actingAs($liveStarting->user);

        $this->expectsNotification(
            $liveStarting->user, 
            \App\Notifications\LiveMineStarting::class
        );

        $exitCode = $this->artisan('pdp:notifications:smart');

        $exitCode = $this->artisan('queue:work', ['--once'=>true]);
    }
```
