### ISSUE TITLE
[Proposal] [5.4] Testing Mailable - no way to access body of email

### ISSUE THREAD

**Issue by adamthehutt** [laravel/internals#405]
### Description:

I'm using Mail::fake() and Mail::assertSent() to test emails sent by the application. It's important that I be able to test the body of the email (i.e. search for a specific string). There are calls for things like hasTo() and hasCc(), and there is a public property for $subject, but there is no way to access the message body. It would be great to add an assertion for this.

### Steps To Reproduce:
````
Mail::fake()
// Do stuff that sends email
Mail::assertSent(TheMailableThing::class, function($mail) {
    // Nothing like $mail->hasBodyContents($string) exists
});
````

**Comment by jbrooksuk** [comment]
Would you get the HTML or plaintext version? You'd need two methods for that to test the bodies independently.

**Comment by adamthehutt** [comment]
Good point @jbrooksuk. Yes, we'd need two different methods.

**Comment by sebastiaanluca** [comment]
Would be great to have this. Need to check if a sent mail contains a specific string, but no way to do so at the moment. Trying to extend the mailable class to provide such a method, but all its properties (like `view`, `markdown`, etc) are `null` somehow.

**Comment by adamthehutt** [comment]
@sebastiaanluca Yep, that was my experience as well. I don't know the internals well enough, and I eventually gave up.

**Comment by Kyslik** [comment]
Why not test Mailable itself? (like test `build()` method or whatever you build your email with). 

And test "sending" email using MailFake (just if its send to proper emails) in separate test from Mailable test.

**Comment by sebastiaanluca** [comment]
I extended the base mailable class to include some assertions and a way to get the rendered body (since those methods are protected we can't test this from outside the class).

See https://gist.github.com/sebastiaanluca/514c72c95ae85ee188d698449a08c60c.

**Comment by adamthehutt** [comment]
Thanks @sebastiaanluca. It seems like your getRenderedBody() method could be added to the base Mailable class as a public method. Then the two assertions could be added to the test class.

Should I offer a pull request for that? @taylorotwell would you accept that pull request if it came in?

**Comment by sahibalejandro** [comment]
I think when using `Mail::fake()` the real `Mailable` is never built, so you can't check the view contents.

**Comment by reinink** [comment]
If you ever want to test the body of the email, you can do that like this:

```php
public function test_email_body()
{
    $email = new YourEmail();
    $html = $email->render();

    $this->assertContains('find this', $html);
}
```

**Comment by sandervanhooft** [comment]
I ended up with this for testing my markdown mailable (Laravel 5.6). Took some time to figure out that I should trigger the `build()` manually:

```
        Mail::fake();

       // Trigger sending the mail here ...

        Mail::assertSent(PackageSubmitted::class, function ($mail) use ($submission) {
            $mail->build(); // Trigger the build() method, otherwise subject and viewData etc are not populated

            $this->assertTrue($mail->package->is($submission));
            $this->assertEquals('site-admin@example.com', $mail->to[0]['address']);
            $this->assertEquals('Package submitted', $mail->subject);
            $this->assertEquals('https://www.packagist.org/packages/sander-van-hooft/laravel-invoicable', $mail->viewData['packagist_url']);

            return true;
        });
```

**Comment by juanvillegas** [comment]
@reinink _render()_ is available in 5.5, while the question clearly states a solution is required for 5.4...

**Comment by bcat-eu** [comment]
Here's the assertion that I use to test email's body - build mailable, render it's view into a string variable and then test it agains the needle. It's somewhat cumbersome, but works in 5.4.

```
Mail::assertSent($mailable, function ($mail) use ($needle) {
    $m = $mail->build();
    $body = view($m->view, $m->viewData)->render();

    return strpos($body, $needle) !== false;
});
```

**Comment by hettiger** [comment]
In case you're using markdown emails you may want to do it like this:

```php
Mail::fake();

// Your action that queues a mail

Mail::assertQueued(MyMail::class, function(MyMail $mail) {
    $markdown = $this->app->make(Markdown::class);
    $body = $markdown->renderText($mail->view, $mail->buildViewData());

    $this->assertContains('needle', $body);

    return true;
});
```

**Comment by neeravp** [comment]
@hettiger Your suggestion works with a caveat for me that is the `$mail->view` always returns null so I have to hardcode the view name eg`'emails.somemail'`. 

Am I missing something here?

BTW I am on Laravel 5.8

**Comment by hettiger** [comment]
@neeravp Do you have a clean repo where the issue is isolated? I’d take a look at it if you share one. I cannot remember having that issue.

**Comment by ssmulders** [comment]
>     $body = view($m->view, $m->viewData)->render();

Updated to work with 5.7, in case anyone else stumbles over this issue :)

```
Mail::assertSent(WelcomeEmail::class, function ($mail) use ($email_address) {
            $m = $mail->build();

            $body = view('email.' . $m->view, ['data' => $m->viewData])->render();

            return strpos($body, 'needle') !== FALSE;
        });
```

**Comment by paxcodes** [comment]
@hettiger I am also using 5.8 and experiencing the same as @neeravp. The 'view' property does not get set when using markdown, or at least it seems so in [5.8](https://laravel.com/docs/5.8/mail#generating-markdown-mailables). The markdown method only sets the 'markdown' property and the 'markdown' prop is protected so it cannot be accessed directly.

```php
public function markdown($view, array $data = [])
{
     $this->markdown = $view;
     $this->viewData = array_merge($this->viewData, $data);

     return $this;
}
```
What I'm doing to prevent hardcoding the view name in my test is to set the view prop in my Mailable's constructor.

```php
// My Mailable

public function __construct(...)
{
   $this->view = 'emails.my_template';
}

public function build()
{
    return $this->markdown($this->view);
}

```

**Comment by hettiger** [comment]
Thanks for summing up @paxcodes :-)

**Comment by iwasherefirst2** [comment]
@paxcodes one can actually read out the protected value from markdown with reflection, so there is no need to store the template in the `$view` variable.

I added this to my `BaseTestCase.php`:

 ```
protected function assertMailContains($mailable, $needle)
{
    \Mail::assertSent($mailable, function ($mail) use ($needle) {
        $mail->build();

        $reflectionClass   = new \ReflectionClass($mail);
        $reflectionProperty = $reflectionClass->getProperty('markdown');
        $reflectionProperty->setAccessible(true);
        $view = $reflectionProperty->getValue($mail);

        $markdown = $this->app->make(\Illuminate\Mail\Markdown::class);
        $body = $markdown->renderText($view, $mail->buildViewData())->toHtml();
         
        return strpos($mail->viewData['content'], $needle) !== false;
    });
}
```

**Comment by JoshMoreno** [comment]
The Mailable class has the following assertion methods

```
$mail->assertSeeInText();
$mail->assertDontSeeInText();
$mail->assertSeeInHtml();
$mail->assertDontSeeInHtml();
```

Example
```
$mail = new MyMailable();
$mail->assertSeeInText('3 days left');
```

**Comment by iwasherefirst2** [comment]
@JoshMoreno thats right. But if you want to make a feature test you may have no access to the mail-able to call that directly.
