### ISSUE TITLE
[Proposal] Do not use escapeshellarg

### ISSUE THREAD

**Issue by misog** [laravel/internals#407]
Hi. Several shared hosting services in Slovakia have disabled escapeshellarg function. I do not know if this is just default configuration or attempt to increase sales of virtual servers.

From my experience only one of them allows to enable this function in custom php.ini file. Admin graphic backends do not allow to configure this.

Laravel uses this function in artisan-related / command-related code and commands do not work on those hostings. I propose to find/implement an alternative to this function.

**Comment by Kyslik** [comment]
Seems that its because of charset.

>The default value for the encoding parameter was changed to be the value of the default_charset configuration option.

**Comment by misog** [comment]
It is because of `disable_functions=escapeshellarg` in php.ini on those hostings.

**Comment by tomschlick** [comment]
Honestly the best solution is to stop using shared hosting.

**Comment by misog** [comment]
Why would anyone pay 3 times more money for VPS when shared hosting is sufficient?

**Comment by tomschlick** [comment]
Digital Ocean is $5/mo. You pay for the freedom to do what you want on your server.

If you shared hosting is disabling a core feature then it's time to find another hosting provider.

**Comment by LKDevelopment** [comment]
On some shared Hostings you can define your own php.ini and overwrite this setting. 

And 3 * more for an VPS? You know that you can run multiple sites on one vps?

**Comment by misog** [comment]
@LKDevelopment no, on at least three popular hostings you can not define own php.ini.
It does not matter that I can run multiple sites on VPS - I can run multiple sites on multihosting (cheaper). Still, the price of one multihosting is less then price of one VPS.

I say it in different way. There is some userbase of Laravel in middle Europe, mostly people from which used Codeigniter before. There are multiple *popular* hosting companies which block escapeshellarg for whatever reason, one of them allows to define own php.ini and another can enable this on request only. At least two more companies may enable this on request.

Your arguments are valid however out of context.

**Comment by misog** [comment]
And I doubt that only middle-european companies block the escapeshellarg function: [https://goo.gl/X7wB2l](https://goo.gl/X7wB2l)

**Comment by tomschlick** [comment]
> You are not supposed to protect interest of those companies - you are supposed to protect interest of Laravel and its userbase.

It's not that we are protecting the interests of the VPS companies, its just we are advocating for a hosting system that doesn't disable critical features. 

So if you need to run artisan commands / queues you're using the wrong kind of service. It has nothing to do with Laravel as background processes are the only good way to run those commands.

Truthfully, I would never expect to get shell access to a shared host. Thats ripe for abuse.

**Comment by misog** [comment]
Well, sometimes at least Artisan::call('config:cache'); is really needed because of that nasty .env access bug outside of Laravel where it throws Error 500 if too many request are sent at the same time.

Again, I do not care that I use "wrong" type of service. The market prices are lower for shared hostings and customers often already use shared hostings and shared hostings are sufficient.

In the meantime while you are "advocating" for systems which does not disable critical features you are protecting Laravel non-compatibility with **popular** hostings. It will definitelly not convince shared hosting companies to enable this by default (I tried to chat with their support).

Be rational.

**Comment by Garbee** [comment]
So, can we justify not using a function used that is only aimed at *increasing security* of the running application? `escapeshellarg` escapes input going into a shell function so that they are treated as safe strings. You're asking that applications have decreased security to justify running out-of-the-box on hosts that disable critical security features.

**Comment by misog** [comment]
No. I propose to replace the function with a custom one. I do not argue that shared hostings have the right approach. I argue that Laravel can gain if it is compatible with those hostings and **still** be secure.

**Comment by misog** [comment]
For the purpose of Artisan::call facade, only two escapeshellarg calls need to be replaced with some equivalent. I am not sure now if there are more calls in the code.

**Comment by tomschlick** [comment]
> For the purpose of Artisan::call facade, only two escapeshellarg calls need to be replaced with some equivalent. I am not sure now if there are more calls in the code.

Replaced with what exactly? Anything that calls artisan is going to go through the shell which is blocked by your host. 

You would need to write a brand new console request wrapper for the whole Artisan class that could be invoked via code instead of shell command. Not a small task in my mind.

**Comment by misog** [comment]
Replaced with my_escapeshellarg() function. No need to write new console request. And I am not talking about shell, I am talking about escapeshellarg which is blocked in php.ini in disable_functions.

In ProccessUtils.php I changed this
```
return escapeshellarg($argument);
```
to this:
```
return $argument;
```
And it works, however it is not secure.

**Comment by Garbee** [comment]
> No. I propose to replace the function with a custom one.

The title of the proposal and initial description do not mention this at all. May want to address that so things are clearer.

FTR `ProcessUtils` is a Symfony piece. It would be **best** to file an issue there and have the fix implemented upstream. That way all users of Symfony benefit and not just Laravel.

Your proposal essentially is them doing something like this:

```php
<?php

if (! function_exists('escapeshellarg') {
  function escapeshellarg($param) {
    // Secure the parameter manually and return
  }
}
```

**Comment by Garbee** [comment]
Oh look, there is already a PR trying to address this: https://github.com/symfony/process/pull/14

**Comment by misog** [comment]
> Laravel uses this function in artisan-related / command-related code and commands do not work on those hostings. I propose to find/implement an alternative to this function.

Next time I will specify "artisan-related / command-related code"

**Comment by rezasys2** [comment]
hey misog 
can i use ur solution ? it may be danger ?

**Comment by misog** [comment]
@rezasys2 you can use it at your risk - however if you only pass your arguments you should be fine

**Comment by rezasys2** [comment]
@misog thanks for ur reply.
I found an alternative function for escapeshellarg :

`    public static function _escapeshellarg($input) {
        $input = str_replace('\'', '\\\'', $input);
        return '\'' . $input . '\'';
    }`

Is it good choice ?

**Comment by nicolas-grekas** [comment]
Recent versions of symfony/process don't use `escapeshellarg` anymore. This could be close I think.

**Comment by DojoGeekRA** [comment]
ping @themsaid
