### ISSUE TITLE
[PROPOSAL] Queue Delay Proposal - Parse DateTime *Strings*

### ISSUE THREAD

**Issue by johnpaulmedina** [laravel/internals#408]
Laravel Version: 5.x.x
PHP Version: 7.0.12
Database Driver & Version: MySQL 5.6.33/Beanstalkd 1.10
Description:

When pushing a job on to Queue::laterOn the function on the documentation expects the $delay to be a DateTime object or integer which will be converted to seconds on the getSeconds function. I had unintentionally been passing a DateTime string in 'Y-m-d H:i:s' format. Since this was a string and not a DateTime object it was skipping the if statement:
```
     /**
     * Calculate the number of seconds with the given delay.
     *
     * @param  \DateTime|int  $delay
     * @return int
     */
    protected function getSeconds($delay)
    {
        if ($delay instanceof DateTime) {
            return max(0, $delay->getTimestamp() - $this->getTime());
        }

       // @todo implement Carbon::parse ?

        return (int) $delay;
    }
```
I think that here at this level we can possibly implement the ability to check if the delay is a string that matches a DateTime string format and if so then getting the difference from current DateTime.

I was seeing unexpected behavior where it was just pushing the job out 1800 seconds by default when the request of delay was only suppose to be 2 minutes (120 seconds) but was not properly parsing the string.

What are your thoughts on this?

**Comment by tomschlick** [comment]
Carbon can handle DateTime conversion IIRC so we could remove that entirely if thats the case. Leaving only the integer & carbon/string formats to support.

**Comment by johnpaulmedina** [comment]
I definitely think this would be the better option. I think Laravel works great out the box. Me making that mistake has caused issues on re-queued items not being fired in a timely manner but wasn't so evident at first. Granted, human error on my part for passing a string but no exceptions were being thrown and my string was attempting to be cast as an integer. I can make a pull request if this is something everyone thinks can be beneficial.

**Comment by tomschlick** [comment]
I don't think this would be very controversial of a change, especially since it's backwards compatible.

**Comment by johnpaulmedina** [comment]
My only initial thought is what if `Carbon::parse($delay)` fails? How should we handle this?

Basic thought process would be check if $delay is the type of String and then see if it can match with `Carbon` but if it fails what should be the proper way to handle this.

**Comment by tomschlick** [comment]
If it's not one of these listed below I'd be inclined to throw an `InvalidArgumentException`

- null
- int
- Carbon instance
- date string

**Comment by johnpaulmedina** [comment]
Should we be testing for specific formats?

**Comment by tomschlick** [comment]
Not sure. Should be easy to test with carbon though. Just pass it some garbage and see if it errors out 😄
