### ISSUE TITLE
[Proposal] Fluent partial resource routes

### ISSUE THREAD

**Issue by salomoni** [laravel/internals#412]
In 5.4 you can register routes more fluently e.g.

```php
Route::name('users.index')->get('users', 'UserController@index');
```

It would be nice to get same behaviour for registering partial resource routes e.g. 

```php
Route::resource('users', 'UserController')->only('index', 'show');

Route::resource('comments', 'CommentController')->except('destroy');

Route::resource('posts', 'PostController')->only(
    'index', 'show', 'store', 'update', 'destroy'
);
```

**Comment by salomoni** [comment]
Implementing this seems to change how the route resources are handled. Currently calling `resource` method just registers normal routes immediately based on what option params you gave.

To get this working maybe there should be an RouteResource instance returned which removes unwanted routes (and possibly changes route names etc) on call.

Also lazy registering the resource routes somehow would be an option too. Would there be performance issues caused by this?

Other way around `Route::only('index')->resource('users', 'UserController');` would be a lot easier.

**Comment by franzliedke** [comment]
> Other way around `Route::only('index')->resource('users', 'UserController');` would be a lot easier.

I wouldn't suggest that. `only` and `except` only make sense here in the context of a resource route, so calling that first (and possibly not calling `resource` afterwards) could be called undefined behavior.

**Comment by taylorotwell** [comment]
It could be accomplished used a destructor on a PendingResourceRegistration class.

**Comment by salomoni** [comment]
Thanks!

Added PR for this using a destructor
