### ISSUE TITLE
Password reset - option to not require email

### ISSUE THREAD

**Issue by garygreen** [laravel/internals#414]
With every laravel version you've had to re-confirm your email address when resetting your password on the reset form.

I've not come across a site that asks you to confirm your email address during a reset request - it seems like an unnecessary step. It would be nice if you could optionally disable requiring this field inside your controller like:

```php
class ResetPasswordController extends Controller
{
    use ResetsPasswords;

    protected $confirmEmail = false;
}
````

**Comment by sebastiandedeyne** [comment]
Agree that this would be nice in core. One less thing we'd have to override in our own applications since we disable the e-mail field by default!

**Comment by fernandobandeira** [comment]
Actually there's a PR for this: #17499

> The email field has been removed from the reset form.
