### ISSUE TITLE
[Proposal] [Passport] Add grace period for access tokens

### ISSUE THREAD

**Issue by salomoni** [laravel/internals#417]
I'm currently generating a new access token to the users on every request. Sometimes there are **multiple requests happening in the same time with the same access token** and the first request revokes the token resulting other requests to fail.

The requests are made from Angular2 SPA to the Laravel app.

**Token.php**
```php
    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;
```
**TokenRepository.php**
```php
    /**
     * Check if the access token has been revoked.
     *
     * @param string $id
     *
     * @return bool Return true if this token has been revoked
     */
    public function isAccessTokenRevoked($id)
    {
        if ($token = $this->find($id)) {
            if (! $token->revoked) {
                return false;
            }

            return $token->updated_at->addSeconds(
                env('OAUTH_GRACE_PERIOD', 0)
            )->isPast();
        }

        return true;
    }
```

An `getRevokeAttribute()` accessor in the Token model would be OK too.

**.env.example**
```
OAUTH_GRACE_PERIOD=5
```

**Comment by garygreen** [comment]
> Sometimes there are multiple requests happening in the same time with the same access token and the first request revokes the token resulting other requests to fail.

Yah, doesn't that sound like a bug in your own app? 😕

**Comment by salomoni** [comment]
It's faster to send the request in the same time than sending one-by-one and waiting the previous requests to succeed.

Of course I'm talking about different resources, not requesting the same resource twice. Example a page may need all users, all roles and let's say the most recent comments.

**Comment by zackify** [comment]
Completely agree with @salomoni, what if you are requesting multiple endpoints at once. https://github.com/tymondesigns/jwt-auth/issues/291 they support it for that reason. This would help me too :)

**Comment by zackify** [comment]
Here's my solution for now, inside a global middleware I check if there is an auth'd user, then:

```
$token = $request->user()->tokens->find(Auth::user()->token());
        if ($token) dispatch(new DeletePassportToken($token));
```

That job I dispatch to does this:
```
public function handle()
    {
        sleep(3);
        $this->token->delete();
    }
```

**Comment by salomoni** [comment]
I ended up to register the AccessTokenRepository manually to the container using my own implementation of the TokenRepository.

    use App\OAuth\TokenRepository;
    use Illuminate\Events\Dispatcher;
    use Illuminate\Support\ServiceProvider;
    use Laravel\Passport\Bridge\AccessTokenRepository;

    $this->app->singleton(AccessTokenRepository::class, function () {
        return new AccessTokenRepository(
            $this->app->make(TokenRepository::class),
            $this->app->make(Dispatcher::class)
        );
    });

To enable Token model timestamps 

    use Laravel\Passport\Token;
    
    Token::saving(function (Token $token) {
        $token->timestamps = true;
    });

I still would like see this implemented to the Passport itself in the future.
