### ISSUE TITLE
Custom Auth Views

### ISSUE THREAD

**Issue by ZebTheWizard** [laravel/internals#420]
It would be nice if you could add a property to the **AuthenticatesUsers** and **RegistersUsers** traits that would allow users to define a custom view if they wanted.

I put this code in the **showLoginForm** and **showRegistrationForm** methods and it works like a charm.

    return isset($this->view) ? view($this->view) : view('auth.login');

Then just declared a view in my login/register controllers.

    protected $view = 'auth.index';

**Comment by Garbee** [comment]
If a change is straightforward and simple like this, just submit a PR to make the change against the framework.

**Comment by ZebTheWizard** [comment]
what branch / repo would I do this in?

**Comment by jbrooksuk** [comment]
Probably 5.4.

**Comment by brayniverse** [comment]
Can't you just override the `showLoginForm` method in your controller?
