### ISSUE TITLE
[Proposal] Include `db:empty` in framework

### ISSUE THREAD

**Issue by lioannou** [laravel/internals#421]
There's been some discussion around the usefulness of the migration `down` and that it isnt actually always useful.

@taylorotwell has discussed the idea here https://twitter.com/taylorotwell/status/792357708464652292 and here https://twitter.com/taylorotwell/status/792361818257711104

@adamwathan said something similar as a reply: https://twitter.com/adamwathan/status/792362831085723648

There were a few other people in that "twitter conversation" that supported the idea. Listening to all these people above - I'm no longer doing `down()` migrations - and found it to be much better (especially for 'destructive' up migrations).

@spatie @freekmurze have a package which solves this: https://github.com/spatie/laravel-migrate-fresh

But I propose this concept is useful enough that it should be directly in the framework as a default command.

Rather than tie the command directly into the migration - I think a different option is `db:empty`. This is explicit that it empties the entire database - rather than `migration:refresh` - because tables which might already exist, but were not included from a migration, will also be destroyed - so `db:empty` leaves no room for confusion.

You can then have the command have two options:

`db:empty --migrate --seed`

giving you a single simple command that will empty your database, do all migrations, and do all seeds.

I'm happy to do this PR if required. Alternatively - not sure if @freekmurze would want to do it (as most of the code would be similar to that package - and credit should go to him)? Either way - happy to do the work if required.

**Comment by RemiCollin** [comment]
I agree this would be useful. Never really used the `migrate:down` command, mostly dropping and creating a DB then re-run `migrate` instead.

**Comment by freekmurze** [comment]
I think this a great idea.

@lioannou I've you're moving forward with this, feel free to implement it using any code of my package. Hurray for open source!

**Comment by kamui545** [comment]
Got something similar in my projects, so it's a 👍 for me.

Here's the code in case anyone needs something simple:

```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class DbRefresh extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'db:refresh';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Reset and re-run all migrations then seed the database with records';

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $this->call('migrate:refresh');
        $this->call('db:seed');
    }
}
```

**Comment by lioannou** [comment]
Closing as this can now be handled in the PR

**Comment by lioannou** [comment]
So the PR was declined. 😞 

Anyone have thoughts on an alternative implementation that @taylorotwell has asked for?

I had a thought maybe it could be part of the Schema - and we add a command `Schema::dropAllTables()` - so you only define this once in one of your first migration files. But with the different impletations of SQL rules required to actually drop all tables for different drivers (mysql, sqlite etc) - I dont think it will work very well.

Any other ideas?
