### ISSUE TITLE
[Testing] Run migration until specified datetime

### ISSUE THREAD

**Issue by rentalhost** [laravel/internals#425]
- Laravel Version: 5.4
- PHP Version: 7.1 (_irrelevant_)
- Database Driver & Version: MariaDB 10.1 (_irrelevant_)
- Copy from: https://github.com/laravel/framework/issues/17996

### Description:

I think that should have a method for you controls how much you wants to run migrations when you are making tests. I think that the best method is you controls it by run `Carbon::setTest($datetime)`, then only migrations until this date will be run,

### Why it is important to general public:

Currently you can trait a testing class with `DatabaseMigrations`, and it will run `migrate` command, then will run `migrate:rollback` automatically, but in some cases you need to limit how much you like to migrate.

For instance: imagine that on version `1.0` you have a table called `users` that have a column called `fullname`, that stores obviously the user fullname. But on `1.1` you will need to split it in `firstname` and `lastname`, and with that you need run a update process to split all current database to new structure. This is currently possible by doing that on migration process, but you have no way to check if it is working like expected.

Then I thinking in something like that:

*My migrations:*

> 2017_02_18_100000_v010000 (fullname definition)
> 2017_03_36_100000_v010100 (fullname splitted into firstname and lastname)

*How test should do in cases like that*:

```php
class UserTest extends TestCase {
    public function testSplittingProcess () {
         // In this point, we are simulation the original structure.
         Carbon::setTest('2017-02-18 10:00:00');
         $this->artisan('migrate');

         $user = new User;
         $user->fullname = 'John Doe';
         $user->save();
         static::assertNull($user->firstname); // Currently not supported.
         static::assertNull($user->lastname); // Currently not supported.
         static::assertSame('John Doe', $user->fullname);

         // In this point we remove the fake date to run all migrations until now.
         Carbon::setTest();
         $this->artisan('migrate');

         // Then it should check if user update run without problems.
         $user = User::find($user->id);
         static::assertSame('John', $user->firstname);
         static::assertSame('Doe', $user->lastname);
         static::assertSame('John Doe', $user->fullname); // Mutator.
    }
}
```

**Comment by Kyslik** [comment]
I kind of understand what you describe above. Shouldn't different versions of application be in its own git-branches? (so problem above is solved?)

**Comment by RemiCollin** [comment]
Maybe you could extract the code that is making modification to the database tables , like in your example 'fullname' => 'firstname' + 'lastname' , from the MigrationClass to a separate class that you can Unit Test easily, then call this class from your Migration::up() method ?

**Comment by rentalhost** [comment]
@Kyslik It's expected that we have differents versions in differents branches, but in case of migration, we are treating about updates (not needly _fresh installs_). In this case, a breaking change will exists only if I remove all access of old `fullname` (to avoid that in an update, we should create a mutator).

@RemiCollin It's how I am working with that for now, but is not too pratical because I can't test if in fact my SQL Update is working like expected (once that the migration yet was full installed, then it is on last version of structure).

**Comment by Garbee** [comment]
I don't see how tests like this increase your reliability. You're literally saying "let's test the old application state" when it is entirely useless for the currently active production code.

What is a use-case for this that isn't testing code that shouldn't be running in production anyways?

**Comment by RemiCollin** [comment]
@rentalhost : Just test it with a dummy table that reflects expected structure before the migration runs. Should be more than enough to validate that your code works.

**Comment by rentalhost** [comment]
@Garbee @RemiCollin  In fact, I wants to tests if current production code was _SQL updated_ correctly. Let provides an better example that was similar what happen to me... 

I have a website fully tested that was structured to each user have an _unique phone number_. But a new specification was need to user accepts _more than one phone number_. In original structure, the phone number was attached to `users` table (something like `phone_number` column). _Note: here, the phone number could be any other type of data, it's just an example._

With the new specification was need to be introduced a new table called `phones`, that holds the user reference (`user_id` or _morph_) and the `phone_number` column. I can't loses all phone numbers that was registered before this change on live application, then I need make:

1. **SQL insert from users**: to copy phones from current `users` to `phones` table;
2. **SQL alter table on users**: to drop the `phone_number` column on `users` table (_now needless_);
3. **Create a mutators on User class**: to keep code compatibility (_before of a major update_);

The biggest problem is check if the _step 1_ was done successfully, because by some reason the data copy could fail (eg. column type, length [_crop_], properties like _unique_, and others specific issues), and tests could not be applied over what migrations does (except by _ugly workarounds_).

Then lets supposes that I have two migrations, one for _version 1.0.0_ with original structure and another with _version 1.1.0_ with changes that I mentioned here. On original migration I insert some need data to application, as default _address states_ and _countries_ that will be used by another part of application, but I don't insert phone numbers, because it is a personal data and will be insert only on live application. 

In this case, any SQL update over `users` will affect no rows, because it's originally empty. Then I can't know if it will run successfuly after I migrate a preinstalled 1.0.0 to the new version 1.1.0.
