### ISSUE TITLE
Translate/Change text reset password email

### ISSUE THREAD

**Issue by caiquecastro** [laravel/internals#426]
- Laravel Version: 5.4.12

### Description:
It would be interesting if it's possible to change the text (translate) from the reset password e-mail. Instead of inheriting the sendPasswordResetNotification($token) from Illuminate\Auth\Passwords\CanResetPassword trait on User model.

I don't know if there is a plan to change the reset password workflow for the next Laravel version and if it will still have meaning.

**Comment by barryvdh** [comment]
Perhaps similar to https://github.com/laravel/internals/issues/409 ?

**Comment by caiquecastro** [comment]
Yes. I'm closing this issue as it's duplicated.
