### ISSUE TITLE
Inverting validation rules

### ISSUE THREAD

**Issue by fernandobandeira** [laravel/internals#428]
Refs laravel/framework#14297

A useful enhancement would be the ability to invert a validation rule, for example it could work like:

```php
$rules = [
    'file' => '!mimes:exe',
];
```

The ```!``` indicates the result of the validation rule should be flipped so false becomes true and vice versa. This would be helpful for things like ```mimes``` so you can specify a blacklist of file types instead of a whitelist.

**Comment by jbrooksuk** [comment]
What about using a keyword such as `not`?

**Comment by brayniverse** [comment]
Sounds like a good idea with that use-case but would it be applicable to all the other rules? `!boolean` doesn't make much sense.
