### ISSUE TITLE
Command to generate view composers

### ISSUE THREAD

**Issue by vpratfr** [laravel/internals#430]
It would be handy to have a make command for view composers

`php artisan make:composer MyViewComposer`

Optionally a switch could allow to create the related service provider.

**Comment by ntzm** [comment]
There isn't an official place to put view composer classes though, where do you propose this command puts them?

**Comment by vpratfr** [comment]
Just like it is advised in the docs. Could be app/Http/Composers or app/Http/ViewComposers for instance. 

Belongs to Http in my opinion, as this is just kind of a mini-controller.

**Comment by Garbee** [comment]
I put mine in simply `App\Composers`. As some may get used just to generate files that get stored to the disk via CLI. They aren't always necessarily associated with the HTTP layer.

**Comment by jbrooksuk** [comment]
@vpratfr why would you put them under `Http`? Genuinely interested.

**Comment by sebastiandedeyne** [comment]
We store them in `Http\ViewComposers` too because views are related to web requests in 90% of the cases, and they don't really warrant their own top level folder since we don't use them that much.

I agree though that having them in `Http` by default would feed a bit off.

**Comment by vpratfr** [comment]
First, because that is what the docs suggest (even though I do not always agree with what the doc suggests, for instance I have an App/Models namespace on all projects)

Second, most of the time they do something that would be done by the controller itself if composers did not exist. Hence it feels natural for me to have them close by controllers.

ViewComposers are to views and controllers what Middlewares are to routes and controllers.

That said, my original proposal is to add a command to generate them. I am totally open to any other namespace and/or to make that configurable somewhere. This is just a detail, as long as the feature is there and that a default is suggested and not enforced.

**Comment by brayniverse** [comment]
If you don't like the default for any of the generators you can provide the exact namespace to change where the file will be stored.

```
php artisan make:model App\\Models\\Foo
```

That will place the model in `app/Models`.

However, typing the full namespace every time is not ideal so why not use `App\Http\ViewComposers` as the default and allow it to be configured in `config/views.php`, or a more generalised `config/generators.php` if other generators are to be configurable.

**Comment by vpratfr** [comment]
Yep. I was thinking about submitting a PR to provide a config file for these namespaces for the generators at the same time. I know you can specify it each time, but why should that be necessary ?

**Comment by vpratfr** [comment]
Just submitted a PR for that. https://github.com/laravel/framework/pull/18205 Hope it gets some attention :)

**Comment by vpratfr** [comment]
Closed with no reason :(

**Comment by Garbee** [comment]
Not like there isn't a reason. He just feels like it shouldn't be in the framework right now. These classes are pretty simple and how you want to hook them up will depend upon the project. I completely understand why he wouldn't want it right now.

**Comment by vpratfr** [comment]
> I don't particularly want to add a generator for this.

Not sure how I could consider that a reason rather than just a feeling or a statement. There is no explanation about "why". 

> These classes are pretty simple

Not sure why you would consider them simpler than a middleware for instance. From the generator point of view.

> How you want to hook them up will depend upon the project

Again taking middleware as a counter example: how is that different than a composer? Why does it deserve a generator and not a composer?


My intent is to try to understand the logic behind when @taylorot would accept a generator and when not. In order to submit something that would not just get rejected with no explanation. Not trying to argue or anything.
