### ISSUE TITLE
[Proposal] More information when migrations run

### ISSUE THREAD

**Issue by gsaqui** [laravel/internals#436]
Hi,

I'd like to see more information about the state of my migrations.  Currently if you have a large number of migrations that you are going to run you don't know which one is running at any given time.  The only feedback you get is at the end when all the migrations have finished.  I'd liked to see something along the lines of this:

```
"AddingExtraAddressInfo"
"/AddingExtraAddressInfo"
"UpdateCountryOnUserAddress"
"/UpdateCountryOnUserAddress"
```

**Comment by salomoni** [comment]
You can manually send messages to the console at any point when seeding.

```php
<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->command->info('Database seeding started');

        ...
    }
}
```

**Comment by Garbee** [comment]
@salomoni This is about *migrating* not seeding. Also with seeds, just use multiple classes and call them. The seeder dumps the class name to the terminal when they get called.

**Comment by tomschlick** [comment]
Yeah for long running migrations something that tells you that the migration has started / finished would be good. Maybe the name shows up first and then you get a checkmark / "Done!" as it finishes.

```
> php artisan migrate

Migrating: 2017_02_14_195410_create_users_table . . . . Done!

```

**Comment by gsaqui** [comment]
I'm wondering if we put this in if it would impact people's CI systems as there would be more information being put to the screen.  Should this be a configuration option so people can turn it off?

> `Migrating: 2017_02_14_195410_create_users_table . . . . Done!`

I think the time it took to run the migration might be more valuable:

```
Migrating: 2017_02_14_195410_create_users_table . . . . 36s
Migrating: 2017_02_14_195410_create_roles_table . . . . 2s
```

**Comment by tomschlick** [comment]
Why not both?

```
Migrating: 2017_02_14_195410_create_users_table . . . . Done! (2s)
```

And I don't think there should be any worry as it would only be adding 10 characters max per line. Not something a CI system typically throws a fit over.

**Comment by tomschlick** [comment]
@gsaqui I would think this would be pretty uncontroversial of a change, especially if targeted at 5.5. 

Probably a good idea to just make a PR for it at this point (if you don't have the time let me know and I'll make one).

**Comment by gsaqui** [comment]
@tomschlick I'm more than happy to take this on.

**Comment by kamui545** [comment]
Related issue I opened few months ago https://github.com/laravel/internals/issues/319
Leaving it here for tracking purpose, this issue has more activity lol.

**Comment by shalvah** [comment]
Nice one. It would really be helpful. @gsaqui
I agree with @tomschlick's suggestion.

**Comment by gsaqui** [comment]
My pull request was rejected with @taylorotwell stating that "No plans to add this for now." 

I'm not really sure what else I can do with this issue.  If someone knows how to move forward with this issue please let me know or feel free to take over.
