### ISSUE TITLE
[Proposal] Add Ability To Change Default Response Type

### ISSUE THREAD

**Issue by baileylo** [laravel/internals#438]
When you return an array, collection, or arrayable object from a controller, it gets converted to an instance of `Illuminate\Http\Response`. This happens in `Illuminate\Routing\Router::prepareResponse`.

Currently, the response object's type is hard coded. It would be beneficial to allow end users to specify this object, similar to the user resolved on the Request. The specific use case I have in mind is the formatting of my JSON API. With my proposal, I could write a sub class of `Illuminate\Http\Response` that could add standardized formatting around the controller's returned collection. This functionality can currently be implemented using middleware. However, this requires useless overhead. First, the collection will be converted to a JSON string when the Response object is generated. Then I'd need to format the original data on the response, then re json encode everything.

**Comment by franzliedke** [comment]
Hmm, not sure what others think, but my first reaction was this: Whether JSON-API or any other serialization, the result is still a HTTP response, so hard-coding this is fine. This is not the level of abstraction that deals with different content types, IMO.

**Comment by Garbee** [comment]
> that could add standardized formatting around the controller's returned collection

Why not just do the formatting from within the controller? Or create/use a service layer that does the formatting for you? [Fractal](http://fractal.thephpleague.com/) for example is a service that let's you mangle your data as-needed and specify your formatter (with plenty of defaults or you can write your own.)

The routing level certainly seems like the incorrect place to be doing that kind of handling.

**Comment by baileylo** [comment]
@Garbee 

> Fractal for example is a service that let's you mangle your data as-needed and specify your formatter (with plenty of defaults or you can write your own.)

I really just like the simplicity of directly return the collection or object with out having some intermediary. 

> The routing level certainly seems like the incorrect place to be doing that kind of handling.

To me, that would be an issue with the current implementation more than my solution.

**Comment by CristianLlanos** [comment]
I think this is because we don't have a Content Negotiator within the core packages. It'd certainly be great to have one.

**Comment by joshmanders** [comment]
Extend `App\Http\Controllers\Controller` and define your own `callAction` method, that's what I do. I have an `APIController` that my API controllers extend, that formats my response how I need.

**Comment by baileylo** [comment]
@joshmanders Thanks for the suggestion!

**Comment by taylorotwell** [comment]
You could probably define a custom Collection that implements Laravel's Responsable interface.
