### ISSUE TITLE
Don't set error_reporting(-1) internally

### ISSUE THREAD

**Issue by ArondeParon** [laravel/internals#44]
At this time, `error_reporting` is set to `-1` in [HandleExceptions](https://github.com/laravel/framework/blame/5.2/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php#L31). I appreciate the fact that code should be bug-free, but this default prevents the server value from being used.

Imo `error_reporting` should be set from the server and this override should be controllable through the Exception Handler. This would allow for more control over this setting and allows the server (default) value to be read.

Would love some opinions on this.

**Comment by crynobone** [comment]
You could override the class via IoC, if you really need to.

**Comment by themsaid** [comment]
Thank you for your suggestion, but looks like not enough members are interested in such change so I'm going to close this issue.
