### ISSUE TITLE
Throw exception on undefined policy checks

### ISSUE THREAD

**Issue by garygreen** [laravel/internals#442]
At the moment, if you check authorization on an "undefined" ability, it'll just return false:

```php
$result = Gate::check('func_doesnt_exist_on_policy_and_ability_not_defined', $user);
```

This creates the illusion that the check went through and returned false, when in actual fact it couldn't be checked because the function doesn't exist on the policy and the ability is not even defined! It should really throw an exception if it can't explicitly check the policy imo.

**Comment by taylorotwell** [comment]
This may be better behavior, yes.
