### ISSUE TITLE
[Proposal] Rename index column

### ISSUE THREAD

**Issue by anik786** [laravel/internals#443]
Sometimes you may want to rename an index column in your migrations files.
This is common if you rename the column the index is related to.

Currently this is not possible (as far as I'm aware) using native Laravel methods.

It is possible using raw SQL like so:

```
DB::statement('ALTER TABLE table_name RENAME INDEX old_index TO new_index');
```

Can we have a method that does this like:

```
$table->renameIndex('old_index', 'new_index');
```

**Comment by tomschlick** [comment]
The big question will be which databases support renaming an index? If it's just mysql it will probably be rejected as a framework feature.

**Comment by anik786** [comment]
It is supported on 3 out of the 4 databases:
    - MySQL (https://dev.mysql.com/doc/refman/5.7/en/alter-table.html)
    - SQL Server (https://msdn.microsoft.com/en-us/library/ms190776.aspx)
    - PostgreSQL (https://www.postgresql.org/docs/9.2/static/sql-alterindex.html) seems to support it.

SQL Lite does not seem to support it, but in that case we can just drop the index and re-add it like so:
```
$table->dropIndex('old_index');
$table->addIndex('column_name', 'new_index');
```
The issue here is we do need to know what the `column_name` is, which could be provided by the user as an parameter. There may also be much better workarounds, but I'm not too familiar with SQLite.

**Comment by anik786** [comment]
Turns for SQLite, we can get the index definition like so:

You can get the index definition from the schema:
```
SELECT sql FROM sqlite_master WHERE type = 'index' AND name = 'old_index';
```
Therefore I see no reason why we shouldn't add this feature!

**Comment by tomschlick** [comment]
I'd suggest making a PR then 😉

**Comment by anik786** [comment]
@tomschlick Just didn't want to waste time making a PR only to find out the feature will not be accepted for what-ever reason.

**Comment by anik786** [comment]
Sorry I know I didn't have time to do this, but I really think this would be a good feature to add for the next Laravel version.

**Comment by slava-vishnyakov** [comment]
Added a PR for this
