### ISSUE TITLE
Bring back assertion for lack of JSON

### ISSUE THREAD

**Issue by dwightwatson** [laravel/internals#444]
Prior to Laravel 5.4 we had `seeJson` and `dontSeeJson` which made it easy to check that certain content didn't appear in a response. It was great when testing filtering or searching endpoints which are meant to only return a subset of content.

In Laravel 5.4 we have `assertJson` but nothing that seems to be able to assert the lack of given JSON content. Is this something that would be considered to be brought back, or was there a reason for it's removal?

**Comment by taylorotwell** [comment]
I would be OK with having this.
