### ISSUE TITLE
SQL Server PDO library in Linux

### ISSUE THREAD

**Issue by sourov06** [laravel/internals#445]
Recently microsoft is releasing their official PDO driver for php [This](https://github.com/Microsoft/msphpsql) is their project link.

I installed laravel on server and then I see that it always use dblib driver to connect to SQL server. Then I see this file

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Connectors/SqlServerConnector.php

Which suggests that laravel try dblib driver first. If dblib is found then it use dblib directly. Is there any option to specify driver name directly?

You can call me dump but when I use dblib, I see sometimes connection are failing randomly. Then I feel that it is better to use official PDO driver to connect SQL Server but there is no way to use that unless I remove dblib from server.

**Comment by RobvH** [comment]
Typically, dblib will not be installed on a Windows, and until recently, that was the only platform PDO_SQLSRV would work on. That is now changed, making this a very compelling suggestion. dblib is still the "well known" solution on Linux systems, so perhaps ms PDO_SQLSRV should be vetted for a while before becoming the default choice on Linux?

In the meantime, anyone interested in this ought to remove dblib on their Linux systems, test and use PDO_SQLSVR and then report back their experiences.

**Comment by sourov06** [comment]
In linux I see some bad issues with PDO_DBLIB. It stops working randomly. Then I install PDO_SQLSVR  on one of my sandbox server. 

To make it working  in laravel I need to uninstall PDO_DBLIB extension from PHP so that laravel use PDO_SQLSVR. LOL. I am testing it on my installation. Till now it is working good. 

I will let you know the feedback. I also want to hear feedback from others.

I have also asked this question:
http://stackoverflow.com/questions/42524613/pdo-dblib-vs-pdo-sqlsrv

Yet no one replied. Thanks for your opinion. I exactly thinks exact way you think.  I need to hear opinion from others too,
:) :)

**Comment by Frondor** [comment]
@sourov06 I'm pretty sure you can provide a DSN for that, so you don't need to disable PDO_DBLIB, just provide a `sqlsrv:...` dsn in the connection array. Check the `SqlSrvConnection` file.

**Comment by sourov06** [comment]
That means I were silly. what is the config name for adding dsn value?
