### ISSUE TITLE
Configurable default namespaces for the make commands.

### ISSUE THREAD

**Issue by vpratfr** [laravel/internals#447]
A lot of developers seem to not like putting their models on the root `App` namespace. 

I know you can specify the namespace manually with each make command. 

However I would find it convenient if these default namespaces were configurable.

See also the discussion about my proposal for a new `make:composer` command #430

**Comment by shalvah** [comment]
I agree with this. I suggest there be some kind of `config` option or `artisan`command (similar to `app:name`) that does this. Perhaps `php artisan app:models`?

**Comment by Dylan-DPC** [comment]
Consider large projects have multiple folders. 

So say I have some models under `App\Models\Groups` namespace, and some models under `Groups` namespace. 

So when I run `php artisan make:model Groups\Member` how do i differenciate which namespace it should go to?

**Comment by brayniverse** [comment]
@Dylan-DPC if the configured namespace for models was `App\\` then you could pass a relative namespace like `Models\\Groups\\Member` or `Groups\\Member` and it will be stored in `app/Models/Groups` and `app/Groups` respectively.

Having a single configuration file like `config/generators.php` whereby you could modify where generated files would be ace.

```php
return [
    'model' => 'App\\',
    'controller' => 'App\\Http\\Controllers\\',
    'notification' => 'App\\Notifications\\',
    'provider' => 'App\\Providers\\',
    etc...
];
```

**Comment by shalvah** [comment]
Good idea @brayniverse.  And, @Dylan-DPC, if, by some chance, you meant top-level `Groups` namespace, you can always precede the name with a backslash.

**Comment by vpratfr** [comment]
PR submitted with some explanations. Hope it gets some attention.

**Comment by vpratfr** [comment]
Ok. Another one for nothing. Next time I got a few spare hours for open-source contributions, I'll make sure not to spend them submitting PR to Laravel :(

**Comment by Garbee** [comment]
You trying to add features that are highly opinionated. They aren't exactly jumped on right away. Things sit and Taylor keeps an eye on things beyond just the issue trackers to see what problems developers are having.

PRs are in no way a guarantee by any means that you'll get it merged or even discussed. Try focusing on actual bugs, documentation, or other things projects need. Everyone wants X feature added that they think will be useful, but they simply aren't. You also may notice this PR in particular has 3 up and downvotes right off the bat. So if it is that contentious with people following the tracker, it isn't something to jump on adding in.

**Comment by joshmanders** [comment]
A lot of these features can be added by 3rd party packages too.

You CAN override a default command, by forking the command and extending it's instance in the container instead of registering a new command.

I have a bunch of opinionated things I'd like to use, but I don't think they'll ever be entertained let alone accepted, but I don't want 300 make commands in my artisan output, so that's exactly what I am gonna do.

I am very interested in this PR as I too keep my models in `app/Models` so your work won't completely go in vein.

**Comment by Dylan-DPC** [comment]
> @Dylan-DPC if the configured namespace for models was App\\ then you could pass a relative namespace like Models\\Groups\\Member or Groups\\Member and it will be stored in app/Models/Groups and app/Groups respectively.

Then the only thing you are saving with your new feature is typing `App\\` which is giving marginal benefits.
