### ISSUE TITLE
[Question] How to register Views/Translations without namespace?

### ISSUE THREAD

**Issue by Mahmoudz** [laravel/internals#449]
The `loadTranslationsFrom` and `loadViewsFrom` functions require **namespace** as second parameter.

When trying to pass Null as namespace: _Translation Example_: 

```php
$this->loadTranslationsFrom($path, null);
```

You can access your translation like this `trans('::foo.bar')` but, how can I access it like this **`trans('foo.bar')`** instead, _(without the `::`)_ as if it's in the default directory _(`resources/lang/*`)_?

Same for Views.

**Comment by Dylan-DPC** [comment]
this repo is for future proposals. Use the slack channel or forums to solve your doubt :)

**Comment by pmochine** [comment]
@Mahmoudz have you found the solution?
