### ISSUE TITLE
Eloquent ArrayAccess

### ISSUE THREAD

**Issue by lagbox** [laravel/internals#45]
Can we adjust this to use the attributes only?

I don't think people expect this to return properties if they exist and has caused a few people to run into issues with property names that match attribute names. Especially because of how `Arr::get` and other functions work, since it will use the model as an array not as an object, which means it will return a property value not an attribute's value if a property exists.

**Comment by tomschlick** [comment]
It would also have to account for the "appends" logic but I agree it shouldn't include public vars on the model. Didn't even know that was a thing...


https://laravel.com/docs/master/eloquent-serialization#appending-values-to-json

**Comment by lagbox** [comment]
We don't have to account for any of the serialization stuff as this isn't serialization. It would just be using the methods we have currently to access the attributes instead of trying to access properties.

**Comment by tomschlick** [comment]
Not specifically the serialization, but if you're trying to access an appended variable on that class it should be accessible via ArrayAccess like it currently is. Was just pointing out its not just the `$model->attributes` array that needs added in.

**Comment by lagbox** [comment]
That is all that is needed. This is not serialization. Appends/Hidden don't come into play here.

**Comment by themsaid** [comment]
This is currently the behaviour in 5.5 https://github.com/laravel/framework/pull/18403/files
