### ISSUE TITLE
[Proposal] Update Bootstrap 3 to 4 in make:auth

### ISSUE THREAD

**Issue by davidpiesse** [laravel/internals#454]
Bootstrap 4 will eventually drop... eventually....

It is pretty stable by alpha 6 and has lots of benefits that BS3 lacked (flexbox etc.) and would require a defined number of changes to the npm calls, javascript, and auth views.

Maybe for 5.5 if BS4 isn't out of alpha we add another argument to the make:auth in preparation such as
```php artisan make:auth --bootstrap4``` which will replace the BS3 with BS4.

**Comment by bbashy** [comment]
alpha.6 is the last alpha so, beta next!

Been using it for live projects for about a year and had no real issues :+1:

**Comment by davidpiesse** [comment]
Closing this as it should be a potential package for the new presets ability. https://github.com/laravel/internals/issues/518

**Comment by m1guelpf** [comment]
I am having issues with the layouts.app file after upgrading to Bootstrap 4. Is there any working example off auth with bootstrap 4 on GitHub?
