### ISSUE TITLE
[Proposal] Add an option to convert scheduled task commands to queue jobs

### ISSUE THREAD

**Issue by leo108** [laravel/internals#457]
The purpose of this proposal is to create an easier way to balance scheduled tasks between multiple servers.

We can only set up the `schedule:run` cronjob in only one server right now, if there are many big scheduled tasks in a project, the server load of cronjob server may become very high and slow down the tasks which may cause unexpected problems.

For current version of Laravel (5.4), we can create a job that implements `ShouldQueue` and create an artisan command that triggers the job to do what we want, but why not provide an easier way to do this?

For example, we make an artisan command class implements `ShouldQueue`, when `schedule:run` triggered, it finds that the scheduled task implements `ShouldQueue`, then it dispatches a built-in job called `RunScheduledTaskJob`.

Or add a method called `queue` to `Illuminate\Console\Scheduling\Event` class, so that we can define a scheduled task by 

```
$schedule->command('foo:bar')->queue($queueName)->everyThirtyMinutes();
```

**Comment by tomschlick** [comment]
It might be better just to eliminate the middleman there and allow the scheduling of jobs directly...

```
$schedule->job(new JobNameHere())->everyThirtyMinutes();
```

**Comment by leo108** [comment]
@tomschlick good idea

**Comment by tomschlick** [comment]
I'm going to look into this tonight to see how viable it is... I really like this as I have a few commands that only exist to throw jobs in the queue every X minutes.

**Comment by tomschlick** [comment]
Just added a PR for it! :)
