### ISSUE TITLE
Make storage:link generated link relative

### ISSUE THREAD

**Issue by a-komarev** [laravel/internals#458]
When you call `storage:link` generated link will have fully qualified path of development machine, so it's useless to store it in version control. And then it should be ignored in `.gitignore` and generated on remote machine after first deployment.

Solution in Unix pretty simple but I only know how to do it from command line:

```sh
cd public && ln -s ../storage/app/public storage
```

So, my question to Laravel team, is there any chance to make such related paths using Laravel console command? Is there is an ability to generate relative links?

**Comment by tomschlick** [comment]
Why store it in version control? Just make `storage:link` part of your deployment process.

**Comment by a-komarev** [comment]
Hmmm... I've just thought it could be called in `composer.json` scripts section:

```
"post-root-package-install": [
    "php -r \"file_exists('.env') || copy('.env.example', '.env');\"",
    "php artisan storage:link"
],
```

But `public/storage` folder must be added to `.gitignore` then.
