### ISSUE TITLE
[Proposal] Dynamically change route controller/action

### ISSUE THREAD

**Issue by fernandobandeira** [laravel/internals#459]
A good addition to the framework would be to allow to change the controller of a route inside a middleware, for example there's many usecases for this, I'll explain mine:

I have a multi-tenant app, each tenant belongs to a group, for example website, ecommerce, etc.
Each group has it's own Modules like Products, etc, now I want to create a route called /products which will dynamically change the controller to use /Ecommerce/ProductsController or /Website/ProductsController based on which tenant is accessing the url. Notice that i don't want to create a route like /ecommerce/products and since my tenant configuration is set on a DB I can't separate them by route groups...

My proposal is to add the following method to the Router:

```php
    /**     
     * Change the controller method used for the route.
     *
     * @param  string  $controller
     * @return void
     */
    public function changeControllerMethod($controller) {
        $routeAction = $this->getAction();
        $routeAction = array_merge($routeAction, [
            'uses'       => $controller,
            'controller' => $controller,
        ]);

        $this->setAction($routeAction);
        $this->controller = false;
    }

//Example of use
$route->changeControllerMethod('\App\Http\Controllers\Foo\BarController@baz');
```

You can already achieve this since you can call setAction and modify controller from your middleware, the thing is that this doesn't seem intended, there's also a problem with this approach, controller middlewares won't work, it'll apply the middlewares that you were using on the first controller, before dynamically changing it...

So i'm posting this here to gather some feedback and check if there exists other workarounds for this...

**Comment by fernandobandeira** [comment]
If anyone reading this from the future has the same problem, I'd advise that you don't do this, I used a different approach for this, instead of changing the controller I changed the route definition, I create one routes file for each of my group and loaded the right one for the group this way things are simpler and everything works like how it's supposed to be.

**Comment by eminentcodex** [comment]
I have the exact probelm..any clue..?
