### ISSUE TITLE
Allow validation rule parameters to be defined using arrays

### ISSUE THREAD

**Issue by amitailanciano** [laravel/internals#46]
It'd be great if we were able to specify parameters to validation rules as arrays -- for several reasons:

1.) It's tedious to append parameters with `,` between each item, sure this could be remedied by joining elements with the `join` function, but it's just more boilerplate when it doesn't necessarily need to be there.

2.) Sometimes I want to pass non-scalar types -- for example I'm using the [Laravel Doctrine](http://www.laraveldoctrine.org/) package and I'd like to be able to pass hydrated objects to my custom validators.

3.) I'd like to be able to retrieve my parameters in my custom validators by key/name instead of a cryptic/ambiguous numeric index

4.) If I'm subclassing a form request or simply building rules based on conditions, unless I do some preprocessing like manually construct everything (keyed parameters included) with arrays, and then flatten all the rules at the end of my `rules` implementation, I am forced to redefine rules that I don't necessarily need to change, because I don't have access to specific parameters in those rules since they are part of the rule definition.

Example of desired definition:

```
...
'user' => [
    'required',
    'exists' => [
        'table' => 'users',
        'column' => 'id',
        'exclude' => 2,
        ... // etc
    ],
    ...
],
...
```

The rules could be parsed as follows: rules with numeric keys would have no parameters and the element would be the rule, rules with string keys would use the key as the rule name, and the element would be the parameters. If a string key was used, and the value is not an array, the value would be parsed as a 0 indexed parameter to the rule.

**Comment by themsaid** [comment]
This is quite interesting, specially with the case of conditionally changing parameters.

Currently this is very unreadable:

```
'email' => 'email|unique:users,email'.($item ? ",$item->id" : ''),
```

Having an way of adding/updating rules parameters can make the validation code more readable. I'm planning to propose some changes to the validator in 5.3 and I believe adding this option is very useful.

**Comment by franzliedke** [comment]
Not sure if you already know, but passing rules for a field as an array instead of separating them by pipes is already possible.

So, to get what you want, a simple helper function that returns an array of rule parameters into a stringified rule would be enough.

**Comment by franzliedke** [comment]
> passing rules for a field as an array instead of separating them by pipes is already possible

This part isn't really explained in the docs, except for a small mention in the regex rule (because it's the only workaround for using pipes in regexes).

**Comment by amitailanciano** [comment]
I am aware that it is possible to define rules as an array, but to my knowledge it is not possible to define the parameters in the same manner -- I mentioned in my OP that a helper could be used for that, sure -- however it is tedious and cumbersome, and it does not address or resolve points 2, 3, and most of 4

**Comment by taylorotwell** [comment]
I think this was essentially solved with introduced of fluent syntax for rules.
