### ISSUE TITLE
[Proposal] Re-work migration order logic

### ISSUE THREAD

**Issue by svenluijten** [laravel/internals#462]
## The problem
Currently, the order in which database migrations are ran is determined by the filename of the migration (so `2014_10_12_000000_create_groups_table.php` will run before `2017_03_09_202437_create_groups_table.php`). 

This often results in nasty errors like this:

```
[Illuminate\Database\QueryException]
 SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `users`
 add constraint `users_group_id_foreign` foreign key (`group_id`) references `group` (`id`))
```

because I've added a foreign key (`group_id`) to my `create_users_table` migration:

```php
public function up()
{
    Schema::create('users', function (Blueprint $table) {
        $table->increments('id');
        $table->unsignedInteger('group_id');
        $table->foreign('group_id')->references('id')->on('group');
        $table->timestamps();
    });
}
```

As the moment, I would have to go and rename the file to something like `2017_03_10_000000_create_users_table.php` to make sure it runs *after* the groups table is created, which isn't exactly the most elegant way to do it. Especially when you have several more migrations, this quickly becomes unwieldy and frustrating to work with.

## The proposal
A solution for this would be to add a property or method to the migration class so we can determine when it runs from within the code, instead of having to renaming the file.

```php
class CreateUsersTable extends Migration
{
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('group_id');
            $table->foreign('group_id')->references('id')->on('group');
            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::dropIfExists('users');
    }

    public function order()
    {
        return 1;

        // possibly even the (arguably) more elegant...
        $this->after(CreateGroupsTable::class);
    }
}
```

**Comment by sisve** [comment]
Wait... what? How ... why? 

The proper solution would be for a third migration to add the foreign keys. A migration that executes after the first two has created the tables. (You could also create the foreign key in the second migration.)

What you're suggesting would open up for changing the execution order of migrations after they've been written, committed and deployed. This issue originates from a developer mistake; adding a foreign key referencing a table that does not exist yet.

Repeat after me; you may _not_ change the source code of a deployed migration. It is static, it is untouchable, it shall be as it is, and forever stay that way. You must be able to execute the migrations anywhere, at any time, and get an identical result.

**Comment by svenluijten** [comment]
@sisve Yep, after discussing it with some other people they also asked me why I didn't just create a new migration to add the field to the users table. That makes a *lot* more sense, and I can't believe I didn't think of it myself 😖
