### ISSUE TITLE
[Proposal] Validate file extension

### ISSUE THREAD

**Issue by barryvanveen** [laravel/internals#470]
Hi there,

I was wondering why there is no default rule for validating file extensions. It *is* possible to check mime types and image dimensions, so why not the file extension?

Is it that checking the file extension is no fool-proof method for determining what type of file is under consideration? In that case, only checking the mime-type is not entirely fool-proof either. In my opinion it would be best to check both, for added security.

Not so long ago I had an issue were a user uploaded a PHP file to the server as an avatar. My validation checked the mime type, which was image/jpeg, but crafted into the image was PHP code. I'm not sure if that code could be executed (it contained "echo phpinfo()") but I don't want to take any chances anymore.

This is the custom validator that is now used to check the file extension of an UploadedFile:
```php
Validator::extend('file_extension',
    function($attribute, $value, $parameters, $validator) {
        if (!$value instanceof UploadedFile) {
            return false;
        }

        $extension = $value->getClientOriginalExtension();
        return $extension != '' && in_array($extension, $parameters);
    }
);
```

which can be used like so:
```php
$rules = ['image' => 'file_extension:jpg,jpeg,png,gif|mimes:jpeg,png,gif'];
```

Would it be an idea to add this to the rules that are available by default? I'd like to hear your thoughts!

Barry

**Comment by Mevrael** [comment]
How filename ends does not determine file type, there is enough with MIME type validation which is the only way to validate file by type and even in that case it might be not 100% sure.

Why do you even need to check for an uploaded file name endings, you still in any serious infrastructure will upload files using Storage to Amazon or whatever and generate a random hash instead of original file name and without any extension.

**Comment by Garbee** [comment]
> How filename ends does not determine file type, there is enough with MIME type validation which is the only way to validate file by type and even in that case it might be not 100% sure.

This times a million. Validating an extension provides no benefit and only leads the developer into an insecure way of thinking. It shouldn't be in core since it suggests using a practice that doesn't improve applications by any means.

**Comment by barryvanveen** [comment]
Okay, I get it. The reason why I asked is because I'd like the extension to match the mime type as much as possible. The way to go is to set the extension on the uploaded file yourself, based on the mimetype, if you want. 

Thanks for your feedback, will close this issue.

**Comment by mrkaymy** [comment]
This validation is needed. My web application (using Laravel) has been compromised. Hacker uploaded file with php extension and gif as mime type. There is validation for mime type (laravel validator) and file extension (on HTML5 validation) on my web app. I believe hacker remove HTML5 validation and manage to upload the file. These has cost me 2 years worth of SEO.

It is really good if can add this validation in Laravel core.

**Comment by sisve** [comment]
@mrkaymy

1. Why did you allow the client to choose the resulting filename? 
2. Why did you allow php to execute things that people have uploaded, in this case an image?
3. Are you using any of the `$file->getClient*()` methods which are all documented to be unsafe and untrusted since they are provided by the client?

**Comment by CDNRocket** [comment]
Even if extension means nothing for security or file type detection I think that some sort of extension validation should be useful for trustability and maybe also for seo.

**Comment by Garbee** [comment]
> For trust I mean that will be better for users to see .png on image url instead .pdf or .wtf

You can do this on the backed off you wish from the mime type. In fact, should do this. Not force the user to submit with the extension correct which doesn't mean anything to software properly interpreting files.

**Comment by CDNRocket** [comment]
Yeah, you're right..this should be enough for both problems that I have listed.

**Comment by garygreen** [comment]
@Garbee @sisve 

Sometimes validating extensions is the only realistic way to handle custom filetypes that aren't easy for Symphony to accurately determine the extension by mime type.
