### ISSUE TITLE
Custom Headers when sending mail via notification "MailMessage"

### ISSUE THREAD

**Issue by andrew-za** [laravel/internals#475]
Laravel Version: 5.3.9
PHP Version: 7.0.10
Database Driver & Version: mysql 10.1.17-MariaDB
Description:

When sending a notification via mail, there is no way to add custom headers to it.

I understand notifications are meant to be simple messages, but for example, when using Mandrill you need to send a custom header if you want your messages to be sent through one of your subaccounts. This is impossible AFAICS for notification emails and that messes hard with my Mandrill account.

A similar function to the one on the Mailable class (withSwiftMessage) allowing to access the SwiftMessage would fix this.

Steps To Reproduce:

Try to attach custom headers when sending a notification via email.

**Comment by craigpaul** [comment]
@andrew-za In your mailable class you can add a public `$callbacks` property with an array of closures that access the `\Swift_Message` through that. Would that solve your problem? Ex.

```php
public function __construct()
{
    $this->callbacks[] = function ($message) {
        $message->getHeaders()->addTextHeader('Header', 'Value');
    }
}
```

**Comment by andrew-za** [comment]
Thanks craig - that seems to be the only way.

**Comment by timersys** [comment]
Another way https://stackoverflow.com/questions/43505260/adding-headers-to-email-sent-by-the-laravel-5-4-notification-system/43653673

**Comment by debbiev** [comment]
I had to add parenthesis  ();    to the above code to get it to work:

    public function __construct()
    {
        $this->callbacks[] =( function ($message) {
            $message->getHeaders()->addTextHeader('Header', 'Value');
        });
    }
