### ISSUE TITLE
Mailgun sender uses ipv6, that is not supported on mailgun

### ISSUE THREAD

**Issue by terion-name** [laravel/internals#479]
digital ocean, a forge-provisioned server with php 7.0

cURL error 6: Could not resolve host: api.mailgun.net (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

This seems to be because host has ipv6 networking and curl tries to connect to mailgun via ipv6, that is not supported. Yes, this is mainly problem of mailgun, with their incorrect dns, but [a request](https://mailgun.uservoice.com/forums/156243-general/suggestions/9929925-add-support-for-ipv6) for ipv6 support is there for 2 years. So maybe `curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);` should be added to driver?

**Comment by barryvdh** [comment]
Are you sure it's not related to this? https://laravel-news.com/dns-resolver-issue

**Comment by terion-name** [comment]
@barryvdh very seems to be! I've searched a lot, but did not find this article, Thank you so much, we've gone nuts with admin about this, closing this issue.
