### ISSUE TITLE
ArrayAccess interface should be pulled up into \Illuminate\Contracts\Foundation\Application from abstract classes?

### ISSUE THREAD

**Issue by MatteoOreficeIT** [laravel/internals#481]
Hi

while looking at source Illuminate/Support/Facades/Facade.php we noticed the `$app` static member , who claims to honor the contract `\Illuminate\Contracts\Foundation\Application` 

```php
abstract class Facade
{
    /**
     * The application instance being facaded.
     *
     * @var \Illuminate\Contracts\Foundation\Application
     */
    protected static $app;
```

is accessed inside `resolveFacadeInstance` in a `ArrayAccess` fashion , see below:

```php
protected static function resolveFacadeInstance($name)
    {
        /// previous code omitted
        return static::$resolvedInstance[$name] = static::$app[$name];
    }
```

but looking at interface `\Illuminate\Contracts\Foundation\Application` the `ArrayAccess` interface is not implemented in this intereface but only in abstract classes like `\Illuminate\Container\Container` and ` \Illuminate\Foundation\Application` which in turn extends the former

```php

namespace \Illuminate\Foundation;
use Illuminate\Container\Container;

class Application extends Container implements ApplicationContract, HttpKernelInterface {
    // .....
}


namespace \Illuminate\Container;
use Illuminate\Contracts\Container\Container as ContainerContract;

class Container implements ArrayAccess, ContainerContract {
     ///   ...
} 
```

my question is : 

> accessing Application in `static::$app[$name];` doesn't break OOP ???

**Comment by franzliedke** [comment]
True, these interfaces are not always defined in the cleanest possible way (I believe there are - or were - some places where methods were used on an object implementing the interface, that were only added in concrete implementations).

In this case, this should probably be replaced by the `->make()` method. Please send a pull request!

**Comment by matteoorefice-it** [comment]
Hi

I am studying Laravel from source code ,  and I continue to find many inconsistences of this kind, there are methods calls on object instances but they are not declared in parent abstract class or interface , after all it works at runtime but looking at interfaces should be the right method to understand which methods could be called

I tried a pull request as you @franzliedke suggested, but it was rejected maybe at runtime it works, do you consider these kind of suggestions useful or it doesn't make sense raise a pull request ?

**Comment by sisve** [comment]
This has been the practice since long, many places have code that calls implementations directly, and not contracts. I'm on your side on this, I think that the interfaces must be complete. However, the view on this varies.

Maybe a larger PR will be accepted instead of small one-line fixes. This is perhaps something that should be talked through with someone that can merge before beginning the work.

> Sorry, but we do not include setters and getters on our interfaces.
> Source: https://github.com/laravel/framework/issues/12250#issuecomment-182817704

**Comment by sisve** [comment]
I realized that I could further clarify; what you point out exists on many places in the framework. Sending one PR per fix would result ... in many pull requests.

* [AbstractPaginator][1] calls `$this->hasMorePages()` which is unknown (and implemented by Paginator and LengthAwarePaginator).
* [AppNameCommand][2] calls methods (getNamespace, databasePath, bootstrapPath) not present on the contract.
* [Authenticate][3] middleware calls `$this->auth->authenticate()` where $this->auth is a [Factory][4] that doesn't have an authenticate method. The only implementation of the interface is [AuthManager][5] that doesn't have an authenticate method either, instead it uses a `__call` to forward the invocation.
* [AuthenticateSession][6] has same issues as Authenticate, it calls `$this->auth->viaRemember()` and `$this->auth->logout()` which isn't part of the contract.

... and so on.

[1]: https://github.com/laravel/framework/blob/bfa77109e2c752738732bbac0dd231044e7183c2/src/Illuminate/Pagination/AbstractPaginator.php#L282
[2]: https://github.com/laravel/framework/blob/bfa77109e2c752738732bbac0dd231044e7183c2/src/Illuminate/Foundation/Console/AppNameCommand.php
[3]: https://github.com/laravel/framework/blob/bfa77109e2c752738732bbac0dd231044e7183c2/src/Illuminate/Auth/Middleware/Authenticate.php#L57
[4]: https://github.com/laravel/framework/blob/bfa77109e2c752738732bbac0dd231044e7183c2/src/Illuminate/Contracts/Auth/Factory.php
[5]: https://github.com/laravel/framework/blob/bfa77109e2c752738732bbac0dd231044e7183c2/src/Illuminate/Auth/AuthManager.php#L9
[6]: https://github.com/laravel/framework/blob/bfa77109e2c752738732bbac0dd231044e7183c2/src/Illuminate/Session/Middleware/AuthenticateSession.php

**Comment by franzliedke** [comment]
@matteoorefice-it I totally agree with you, and, quite frankly, don't understand Taylor's reasoning here. If there "isn't a difference" between the two solutions, but one of them is more correct (in terms of OO) then why not go with the better one?

In some ways, this makes the interfaces somewhat moot, which is sad and makes integration with other projects harder.

**Comment by matteoorefice-it** [comment]
Hi @franzliedke and @sisve , thanks for your answers

also the official docs suggests they can get good expectations from contracts https://laravel.com/docs/5.4/contracts#simplicity 

> When all of Laravel's services are neatly defined within simple interfaces, it is very easy to determine the functionality offered by a given service. The contracts serve as succinct documentation to the framework's features.

When I need to approach a new software library / framework the first things I look are `Interfaces `

_for example navigating class / interface hierarchies with and IDE goto declaration is an hard task if contracts are not respected_

I can try to join the various inconsistencies I find during my laravel learning  in a single PR 

Bye

**Comment by skyrpex** [comment]
I guess you can still rely on contracts on your code (just don't use array access on the app or container, even if you know it's implemented...)

**Comment by matteoorefice-it** [comment]
Yes, if one develops application can rely
