### ISSUE TITLE
Eloquent: replacement to prefixes

### ISSUE THREAD

**Issue by rentalhost** [laravel/internals#482]
Currently we have some `Eloquent\Builder` methods like `where()` and `whereRaw()`, and too some prefixes like `or` that give possibilities like `orWhereRaw()`. It gives some limitations because you should prefixes all methods to give `or` possibilities to it (for instance, we have `whereDay()` but not `orWhereDay()`).

Then I thought about create a class that will works like a _pre-setup_ of subsequent method. 

**It should works like that:**

```php
$query->or->whereDay('day', 5);         // Suggested form.
$query->whereDay('day', 5, null, 'or'); // Current form.
```

You can note that `->or` will trigger the `__get('or')` that will returns a new instance of a "Query Setup" class that have the `where(column, value)` method. In this time, this method will setup the caller query to have a `OR WHERE` clause like specified.

**It will give a lot of possibilities, like:**

```php
$query->or->not->whereDay('day', 5);
$query->xor->where('a', 5);
$query->not->whereDate('date', $date);
$query->or->where('a', 1)->where('b', 2); // both OR
```

Finally, with that implemented, methods like `orWhere*()` could be deprecated and removed on future versions of Eloquent.

**Comment by Dylan-DPC** [comment]
this would allow you to do `or->GroupBy('id')`. How do you handle that?

**Comment by franzliedke** [comment]
@Dylan-DPC Not if you implement it with a proxy class (similar to the `HigherOrderCollectionProxy`) that only allows certain methods.

**Comment by franzliedke** [comment]
Strictly speaking, proxy wouldn't be the right term here, I guess. Needs a dedicated class, anyway.
