### ISSUE TITLE
Add email:test command

### ISSUE THREAD

**Issue by garygreen** [laravel/internals#483]
It would be nice to have a command that can be used to test if emails are working / being sent correctly based on your config options.

**Comment by Dylan-DPC** [comment]
How about a test that sends an email using your config?

**Comment by Garbee** [comment]
> test if emails are working / being sent correctly 

The only way to know this for certain is to check your mail service's logs. What exactly are you looking to verify?

**Comment by garygreen** [comment]
@Garbee something like:

```
php artisan email:test my@address.com
```

which would send a dummy test email to that address in order to verify that the email sends correctly, using the SMTP / other settings as in your config. I probably should have mentioned - this command is really only useful for production, as an easy way of testing the settings are configured correctly. 

Alternatively, you could use your contact form / whatever and change the email address temporarily to test, or write your own quick console command, but I think a super simple test dummy email would be very useful out the box.

**Comment by Garbee** [comment]
meh. :-1: 

No need for this to be in core. If you're worried about things not sending, you can handle writing or doing some test on your own. Including writing your own command if you wish. There is no need for a dummy email thing to be in core.
