### ISSUE TITLE
HasAttributes: add support to 'time' casting

### ISSUE THREAD

**Issue by rentalhost** [laravel/internals#484]
Currently we have `date`, `datetime` and `timestamp`, but not `time`. This is _inconsistent_ because the Schema Builder has `time()` support.

**Then I trought about two possibilities here:**
* Support casting time to _Carbon_; or,
* Support casting time to _DateInterval_;

**Carbon:**

In case of Carbon, it should be converted and set date to zero. Then the result for `02:30:45` sbould be like `00-00-0000 02:30:45` on instance.

The advantage with Carbon is that we can set the date easily by using methods like `setDate()`. It have some limitations about you set a Carbon instance on `setDate()`, then something like `setDate(Carbon::now())` is impossible currently.

```php
$today    = Carbon::now();
$datetime = $model->time->setDate($today->year(), $today->month(), $today->day());
```

**DateInterval:**

In this case, the result for `02:30:45` should be like `h = 2, i = 30, s = 45`.

The advantage with DateInterval is that we can use it to increment a DateTime/Carbon instance by using `add()` method.

```php
$datetime = Carbon::today()->add($model->time);
```

**Comment by atymic** [comment]
Now that custom casts are in laravel 7, i've released a package for this :)
https://github.com/atymic/laravel-dateinterval-cast
