### ISSUE TITLE
Modifying WhereBetween Method 

### ISSUE THREAD

**Issue by ghost** [laravel/internals#486]
I see https://github.com/laravel/framework/issues/18480 this feature is useful, so may I start working on it ?

**Comment by Dylan-DPC** [comment]
Yes you can start working on it and submit a PR. Then everyone here will decide whether to continue with it or not depending on the changes you have made.

**Comment by Dylan-DPC** [comment]
@mg-freelancer status on this?

**Comment by mg-freelancer** [comment]
@Dylan-DPC Yes I worked on it but it closed now https://github.com/laravel/framework/pull/18487

**Comment by Dylan-DPC** [comment]
@mg-freelancer close the thread accordingly if you don't want to pursue it further :)

**Comment by mg-freelancer** [comment]
OK but does this pull request solve this issue or I have misunderstand ?
