### ISSUE TITLE
New helper when

### ISSUE THREAD

**Issue by rorc** [laravel/internals#487]
For output html, often need to add classname depending of different terms, for example:
```
<div class="{{ Request::has('param') ? 'has-success' : '' }}">some html</div>
```
New helper function will do this more clearly and conveniently:
```
<div class="{{ when(Request::has('param'), 'has-success', 'default-class') }}">some html</div>
```

**Comment by franzliedke** [comment]
@rorc Honest question: What do you find more convenient about this solution? It is even longer than the ternary operator. 

Also, the ternary operator supports short-circuiting, which means that the part after the colon is only executed when needed. With a custom method, both arguments are always evaluated.

**Comment by michaeldyrynda** [comment]
I don't think this is any more clear than the ternary operator; it's certainly less concise.

**Comment by rorc** [comment]
Ok ok guys, i got excited 😄
