### ISSUE TITLE
[Proposal] Make 'higher order messages' work with relations

### ISSUE THREAD

**Issue by peterorosz** [laravel/internals#493]
Hi, I just wanted to say it would be nice to be able to do something like this in the database seeder :)

```
$users->each->posts()->saveMany(
    factory(Post::class, 5)->make()
);
```
Thanks for considering :)

**Comment by KKSzymanowski** [comment]
I don't think that's possible. Do you have some proposed implementation?
Problem is, `$users->each->posts()` executes `posts` method on each User model and returns back the `$users` collection, which obviously doesn't have the `saveMany` method.

**Comment by deleugpn** [comment]
I've tried and failed on this for the exact reason KKSzymanowski explains. The Higher Order Messages can only help you with single-calls, not chained-calls. At least I didn't find any way to keep it simple, yet powerful enough to allow multiple chaining.

**Comment by peterorosz** [comment]
Oh, well, now I understand the problem. Thank you both for the clarification :)
