### ISSUE TITLE
Request::has and Collection::has behave inconsistently

### ISSUE THREAD

**Issue by sebastiandedeyne** [laravel/internals#499]
`Request::has` returns determines if the request has a non-empty item. `Collection::has` determines if the collection has an item — which is allowed to be empty or null. `Request::exists` behaves like `Collection::has`.

Wouldn't it make more sense to make this consistent and change the behaviour of `Request::has` to that of `Request::exists`, and add a new method to both `Request` and `Collection` to determine if there's a non-empty value?

**Comment by ntzm** [comment]
I have an issue (albeit a bit old) about this issue here: #199

**Comment by sebastiandedeyne** [comment]
Missed that, way more thorough than this one, gonna close this down then!
