### ISSUE TITLE
Fluent interface for the validation package

### ISSUE THREAD

**Issue by sileence** [laravel/internals#5]
Several features in Laravel has a fluent interface which is nice, for example:

The migrations: `$table->integer('id')->unsigned()->index()`

Or Fluent: `->select()->where()->get()`

But not the validator:

`required|max:2|unique:table,column,id,this,make,no,sense`

What if we change this for a future version of Laravel?

```
$rules = rules();
$rules->add('title')
    ->required()
    ->max(2)
    ->unique('table','column')
    ->ignore($id)
    ->uniqueWhere(['this' => 'make', 'more' => 'sense']);

$this->validate($request, $rules);
```

We could even support both ways (fluent interface or strings).

What do you think?

**Comment by CzajekDC** [comment]
If both stayed, then I don't see a problem.

It would be welcome if someone made a PR for that.

**Comment by sileence** [comment]
I can try, and then the community can help me, but I'd like to know Taylor's opinion on this one before proceeding.

**Comment by OzanKurt** [comment]
I think it's so much method chaining and might confuse sometimes.

I would rather staying with arrays, I feel it's simpler that way.

**Comment by CzajekDC** [comment]
@OzanKurt You are right, it may be too messy...

I would rather see something more like this:
```php
'field' => 'required, unique(posts), max(255), in([foo, bar])',
```
or this maybe?:
```php
'field' => ['required', v::unique('posts'), v::max(255), v::in(['foo', 'bar'])],
```
it's more php a'like.

**Comment by sileence** [comment]
I like the second option: 

`'field' => ['required', v::unique('posts'), v::max(255), v::in(['foo', 'bar'])]`

it's interesting for rules that require parameters, then:

```
'field' => [
    'required',
    v::unique('posts')->ignore('id')->where(['foo' => 'bar']),
    v::max(255),
    v::in(['foo', 'bar'])
]
```

**Comment by gocanto** [comment]
I dont mind staying with the one in producction, but If there is something new I would to see @czajeckDC firts example

**Comment by sileence** [comment]
@gocanto the problem with strings instead of real code, is that sometimes you need to use variables, conditionals, etc. and it gets ugly. I have written helpers like:

`$array = [1,2,3];`

`$this->in($array)` returns: `in:1,2,3`

as a workaround of this problem. Same with the "unique" rule. That's the problem I'd like to fix.

**Comment by gocanto** [comment]
yes, you are right as well. Another problem there I see is if you will have to evaluate the string first, instead working straight with a method as you exposed above. Question for you, why don't you agree with the actual flow? Maybe I will be able to help you out in this matter! @sileence

**Comment by sherkhanz** [comment]
I would like to help if someone is going to develop it. Rules in a string are not that friendly when it comes to reading specially a lot of them

**Comment by sileence** [comment]
@gocanto because, again, sometimes you need more dynamic rules. Let's say that based on a certain condition outside of your field list a field will be required or not. So:

```
if ($condition) {
    $rules['field'] .= '|required; // or $rules['field'][] = 'required'; 
}
```

weird, isn't it? Now for simple rules, I agree strings are the best way to define them, but for more complicated ones, we should have an alternative.

**Comment by shssoichiro** [comment]
There is the array method of writing validators, ala:

    ['required', ['in', 1, 2, 3]]

This does make it a bit easier to use variables in validators, however this is still somewhat unwieldy, and very scarcely documented. I say unwieldy because to do something like validate that a value is in an array, you'd have to do:

    $x = [1, 2, 3];
    $validator = [array_merge(['in'], $x)];

**Comment by gocanto** [comment]
what I really  do not like about is this: 

```
protected function validator(array $data, $rules = [])
    {
       return \Validator::make($data, count($rules) > 0 ? $rules : [
            'email' => 'required|email|exists:users,email'
        ]);
    }
```

So if we can come out with a solution for this, it would be nice. But, @sileence said something important on the top, we need to wait on either @taylorotwell or somebody else to see if the ideas are worthy because I don't know yet how this repo will work out

**Comment by CzajekDC** [comment]
Have a look here: https://twitter.com/mitchfizz05/status/710091092893388800. @taylorotwell doesn't seem to be enjoying the idea.

**Comment by gocanto** [comment]
That was my first thought anyways. It is just the fact that the validator works as it is so I think this forum is to treat either new stuff or core ones.

**Comment by taylorotwell** [comment]
I personally don't plan to implement this now that we have more fluent rules available.

**Comment by timacdonald** [comment]
If anyone is still interested in this kind of functionality, I build a little package for it that I've been really enjoying using.

https://github.com/timacdonald/rule-builder

**Comment by m1guelpf** [comment]
@taylorotwell Any option of getting the fluent validator?

**Comment by DCzajkowski** [comment]
@m1guelpf There is no need for any changes since we have array syntax and Rule objects now 😛
