### ISSUE TITLE
Should be able to access route in a before middleware

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/internals#50]
Hi,

At the moment of this post, if you try `$request->route()` in a before middleware you will get `null`
Because in the before middleware the router is not yet dispatched.

There is a lot of use cases when it makes sense to have access to the route in the before middleware one of them is.
In a multi tenant application where each one of them has it's .env file

So `app1`will have a `.env.app1` file
`app2`will have a `.env.app2` file

Each application is accessible via a subdomain like this app1.domain.com
app2.domain.com

Depending on the subdomain i'll load the proper .env file.

If we had access to the route in the before middleware, detecting the domain will be as easy as `$request->route()->domain()`

**Comment by themsaid** [comment]
If that's the only thing one can extract from the route I think `$_SERVER['SERVER_NAME']` can do the job. Are there any other benefits you think this can bring?

**Comment by shadoWalker89** [comment]
That is what i'm doing right now, using the $_SERVER to detect to subdomain, but this is not the laravel way.

Right now i can't think of another use case, but at least in my mind i think that we should have access to the route in a before middleware. After all the purpose of middleware is to protect a route, do some setup ... based on the current request. The route is a vital part of the request and it should be available.

**Comment by shadoWalker89** [comment]
@themsaid Also the user should be available, and there is a lot of use cases :

- Check if the user has a permission with the gate.
- Log some data about the user before any other execution.
- Update some data before any other execution : last time a user connected.

This what i can think of right now, and i'm sure there is a lot more.

**Comment by lagbox** [comment]
I can access the route from the request in the middleware just fine.

**Comment by shadoWalker89** [comment]
@lagbox We can't access the route on the global middlewares.

**Comment by taylorotwell** [comment]
This is just the nature of global middleware.
