### ISSUE TITLE
Why not a Illuminate\Mail\Events\MessageSent event?

### ISSUE THREAD

**Issue by CyrilMazur** [laravel/internals#505]
There is a `Illuminate\Mail\Events\MessageSending` event that's triggered before the mailer attempts to send an email. Why not also triggering a `Illuminate\Mail\Events\MessageSent` event after the email is sent?

I think the use case in the example from the official doc is a bit clumsy (https://laravel.com/docs/5.4/mail#events), because the listener for logging the message is executed whether the email is actually sent or not. There could be an error while actually sending the email (ex: network issue, temporary API error from Mandrill / SparkPost etc...) and `MessageSending` would still be triggered. However, it would be guaranteed that `MessageSent` is actually triggered only if the email was successfully sent.

On top of that, we could access the message id (SES) / transmission id (SparkPost) that's set into the swift message's headers AFTER the email is sent, allowing us to do nice things like this:

```php
public function handle(MessageSent $event)
{
    $sparkpostId = $event->message->getHeaders()->get('X-SparkPost-Transmission-ID');

    // log message with sparkpost id, useful for processing webhooks later
}
```

**Comment by tomschlick** [comment]
Seems like a good addition to me.

**Comment by CyrilMazur** [comment]
What do you think @taylorotwell?

**Comment by joshmanders** [comment]
Yes please!

**Comment by CyrilMazur** [comment]
PR merged ^^ I close the issue.
