### ISSUE TITLE
Implicit model binding middleware makes 'withoutMiddleware' trait/method less useful.

### ISSUE THREAD

**Issue by jfadich** [laravel/internals#506]
When testing 'withoutMiddleware' is very useful for bypassing stuff like authentication/csrf checks. Implicit model binding is also very useful, but since 'SubstituteBindings' was moved to middleware you can no longer use these two tools at the same time. This was brought up in the [framwork repo](https://github.com/laravel/framework/issues/15163) but I couldn't find a relevant conversation here.

I'm not sure the best way to resolve this but moving the binding resolution to middleware has made 'withoutMiddleware' all but useless if you want to take advantage of implicit model binding. Possibly allow a whitelist orblacklist of middleware that should be excluded in tests.

**Comment by brayniverse** [comment]
Something like `$this->withoutMiddleware([/*middleware classes go here*/]);` may be useful in this situation. You could just switch out said middleware for a null middleware that just returns the request. You could do this in your base TestCase class if it's not accepted into the framework.

I think `withoutMiddleware` already exists, not sure if it can be extended. If not, you could call it `disableMiddleware`  or something similar.

**Comment by jfadich** [comment]
@brayniverse I think `$this->withoutMiddleware([/*middleware classes go here*/]);` would work well in tests, but it's not that simple to implement. `withoutMiddleware()` is currently implemented as all or nothing. The `withoutMiddleware()` method sets 'middleware.disable' to true on the app instance. So it would require a rework of how middleware is currently disabled to allow more granular control over which middleware should be included for tests.

**Comment by brayniverse** [comment]
On the contrary it's very simple to implement. Or at least appears to be. The following snippet allows for backward compatibility with the old functionality, while also enabling you to disable specific middleware classes.

```php
class NullMiddleware
{
    public function handle($request, $next)
    {
        return $next($request);
    }
}

public function withoutMiddleware(array $middleware = [])
{
    if (empty($middleware)) {
        return parent::withoutMiddleware();
    }

    foreach ($middleware as $abstract) {
        $this->app->instance($abstract, new NullMiddleware);
    }
}
```

You can use it like so.

```php
// Disables all middleware classes
$this->withoutMiddleware();

// Disables specific middleware classes
$this->withoutMiddleware([
    ExampleMiddleware::class,
]);
```

And if you're using PHP 7 you can make it even simpler with an anonymous class.

```php
public function withoutMiddleware(array $middleware = [])
{
    if (empty($middleware)) {
        return parent::withoutMiddleware();
    }

    foreach ($middleware as $abstract) {
        $this->app->instance($abstract, new class {
            public function handle($request, $next)
            {
                 return $next($request);
            }
        });
    }
}
```

**Comment by jfadich** [comment]
@brayniverse Thanks for implementing this!

**Comment by brayniverse** [comment]
@jfadich No problem, I'm glad it got merged :)
