### ISSUE TITLE
Move `env` function from Foundation to Support

### ISSUE THREAD

**Issue by mloberg** [laravel/internals#512]
I find myself using Illuminate/Support on a lot of projects I work on, even if they aren't Laravel. The env function is useful, but in Foundation, so I end up copying it over to my project because I don't need to pull in Foundation. Is there a reason why that function is found in Foundation instead of Support?

**Comment by Garbee** [comment]
This would make a very simple PR. Why not just make a request that does the move and see what Taylor says in a PR? He responds to PRs much faster than Internals discussions in general.

**Comment by brayniverse** [comment]
If there's no side affect, I can't see this being declined. Worth giving a PR a go.

**Comment by mloberg** [comment]
Done - https://github.com/laravel/framework/pull/19409
