### ISSUE TITLE
Laravel Presets - Proposal to add Zurb Foundation!

### ISSUE THREAD

**Issue by IamManchanda** [laravel/internals#518]
Just got to know that presets are getting added for Laravel 5.5
=> https://medium.com/@taylorotwell/laravel-frontend-presets-eca312958def

So i purpose [Zurb Foundation](https://github.com/zurb/foundation-sites/) for the same 
as its one of the top css frameworks out there with bootstrap.

-------------------------------------------------------------------------------------------------------

**Why?**: Well its mostly requested => https://laracasts.com/discuss/channels/elixir/zurb-foundation-6-and-laravel-53

**Comment by Garbee** [comment]
:-1: 

I think it best if we discuss making the preset system modular allowing for packages to add other scaffolds directly. Instead of trying to cram everything possible into internals to be maintained there. That way as the other systems evolve the people who use them can maintain it directly.

**Comment by IamManchanda** [comment]
Good idea @Garbee

**Comment by joshmanders** [comment]
Agreed with @Garbee. First thing I thought of when I saw that tweet was Laravel Valet drivers all over again.

**Comment by Dylan-DPC** [comment]
@IamManchanda you can close this issue since we already have #525
