### ISSUE TITLE
Better exception information in php artisan console

### ISSUE THREAD

**Issue by vpratfr** [laravel/internals#52]
When an exception is occuring when running an artisan command, we have very little information about what actually caused that error. The output is just the exception class and the file name. 

What would be useful is to have more information like line number where the exception was thrown, call stack, etc. 

We have that inside the web view with debug on, but nothing useful for artisan even when debug is on.

**Comment by vpratfr** [comment]
See also https://github.com/laravel/framework/issues/11279 for more information

**Comment by themsaid** [comment]
You may define the verbosity of the command, for example:

```
php artisan make:controller -v
```

Using this will print the Exception trace below the normal exception message.

**Comment by vpratfr** [comment]
Cool. One learns every day.
