### ISSUE TITLE
dd() calls array_map

### ISSUE THREAD

**Issue by rentalhost** [laravel/internals#521]
For some reason, the support function [`dd()`](https://github.com/laravel/framework/blob/eebb805156ab807784c95d0dacbb31a59610d0c0/src/Illuminate/Support/helpers.php#L511) calls `array_map()` instead of a simple looping. There are some reason for that?

**Comment by Garbee** [comment]
It's just a simple way to quickly dump all the items before exiting. Is it causing a problem for you?

**Comment by rentalhost** [comment]
Not really, just by thinking about it seems a workaround where it is not need (`foreach()` solves the problem and maybe is more clear), and about use a function that is no side-effect in cases like that (in case, by not using the `array_map()` output). In all cases, it'll use more the hardware to generate a never used array.

I know that it is about a debug function, but I guess that it could be improved on this direction.

**Comment by Garbee** [comment]
Well... [let's see](https://github.com/laravel/framework/pull/18736) what Taylor thinks.

I don't see much of a point in this really, it's just micro-optimizing to an extreme degree in an area where it doesn't really serve any purpose.

**Comment by rentalhost** [comment]
Thanks for PR. But it is not a case of micro optimization, but the better way to handle it. In my context, I am working on a new inspection of the phpinspectionea (PHPStorm plugin) that detects no side-effect calls(), and it found this case.

**Comment by Garbee** [comment]
Merge approved so the next tag of 5.4 will include the change.

**Comment by deleugpn** [comment]
Close?
