### ISSUE TITLE
[Proposal] Laravel Presets modular packages

### ISSUE THREAD

**Issue by davidpiesse** [laravel/internals#525]
The Laravel community will as they always do build out the other potential options for a front end preset package.

Please add to the list of:

- [x] Bootstrap 3 & Vue
- [x] React
- [x] Zurb Foundation #518 
- [ ] Angular 2
- [ ] Angular 4
- [ ] Bootstrap 4 (to then replace the current BS3)
- [x] Bulma (@JeffreyWay would love this!) (@Laraveldeep)

**Comment by IamManchanda** [comment]
+1 for angular 4 .... No need to add angular 2 though!

**Comment by bbashy** [comment]
UIkit?

**Comment by joshmanders** [comment]
It'd be better to make the `preset` command pluggable so that packages can add presets than bake all these into core.

**Comment by davidpiesse** [comment]
I think that a little Dev from the main package and then a composer repo that can be referenced in an array would be ideal. It can use 98% of the code that exists...

**Comment by ConnorVG** [comment]
I think it would make more sense if we could just have remote presets...

`php artisan preset:github connorvg/laravel-super-duper-preset`

**Comment by davidpiesse** [comment]
@ConnorVG What if you have to require via composer first a package that contains all the files (connorvg/laravel-preset-zurb) and then register a service provider like normal that adds the option into the artisan commands to then run?
It's a more Laravel-y way of doing it...
```php
php artisan preset:zurb
```

**Comment by m1guelpf** [comment]
@davidpiesse Now that the preset command is macroable, you can define custom presets!

**Comment by ConnorVG** [comment]
@davidpiesse that's not a preset, that's a dependancy.

**Comment by davidpiesse** [comment]
I get that :)
And it isn't necessary to make such a thing work. But it is how many other "drivers/extensions" get added to Laravel.
Just thinking that keeping it similar to other paths would make it easier / consistent to use.

https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Console/PresetCommand.php

**Comment by ConnorVG** [comment]
Well, like I said, it's not a dependancy. Scaffolding isn't something you _depend_ on, it's something that helps bootstrap the journey.

That said, due to it being macroable, it's stupidly simple _anyway_ to make a package to add functionality.

**Comment by GIANTCRAB** [comment]
Hello! I would love to contribute to the scaffolding of Angular 4! How can I help or participate?

**Comment by Laraveldeep** [comment]
Like to see preset for Zurb Foundation plus pages created by make:auth uses foundation specific tags instead of bootstrap after this. Wanna contribute, but still new. Have forked the framwork... just gaining insight on how preset thins is orchestrated.

**Comment by Laraveldeep** [comment]
My pull request for zurb foundation was denied that core package may bloat with preset, so thought of using this in unofficial way.

Added Zurb Foundation and Bulma presets... so far working for me perfectly.

just 'laravel new myapp --dev' and overwrite the folders as instructed here https://github.com/Laraveldeep/Laravel-Scaffolding-Presets

Anyway this is unofficial.

Give it a try and tell what do you think... I think major frameworks should be supported out the box.

I can pull request any time if needed.

Thanks!

**Comment by davidpiesse** [comment]
Cool!
This is pretty much the raw process for adding a UI framework to Laravel. Ideally we can wrap this up in a package that auto loads / copies / injects all the necessary things into a simple command.
By the looks of it it needs a lot of file copies to resources (css / js) that is later used in Laravel Mix / Webpack. 
Where you overwrite the Laravel Preset file - that can be done with a community package that extends it (and with auto package loading - could be done with just a composer require!)

I guess we also need to create the auth pages, along with the welcome page in each UI preset as well...

**Comment by m1guelpf** [comment]
We have created a GitHub organization for hosting community-made presets. You can find it [here](https://github.com/laravel-frontend-presets). Also, we are open to anyone who wants to contribute one!

**Comment by davidpiesse** [comment]
As Miguel links to - there is anow a package / means to create and include other presets @ [https://github.com/laravel-frontend-presets](https://github.com/laravel-frontend-presets)

Closing this down!

**Comment by lakinmohapatra** [comment]
I think , if angular cli package will work out of the box in the background of php artisan preset , it will automatically fetch latest version of angular.
