### ISSUE TITLE
[Proposal] $deleteRelations Eloquent model attribute

### ISSUE THREAD

**Issue by amouillard** [laravel/internals#526]
A $deleteRelations attribute would automatically delete the specified relationships before deleting the model (akin to a cascade deletion).

I often find myself having to add this kind of deletion on delete event models, I think a shortcut would be a good idea.

I'm willing to work on it if you think it would be useful.

**Comment by tomschlick** [comment]
[This package](https://github.com/michaeldyrynda/laravel-cascade-soft-deletes) by @michaeldyrynda does it quite nicely.

**Comment by michaeldyrynda** [comment]
Whilst I wrote the package, I would still recommend delegating this work to the database whenever possible.

It can get quite inefficient (and slow), as you must load the models and delete them individually in order for the events to cascade down the chain, so be mindful. Not something I'd suggest adding to the framework.

**Comment by tomschlick** [comment]
Yeah, what I tend to do is delete the top model, and then queue a job to "cleanup" the models below.

**Comment by amouillard** [comment]
Ok, so the correct way to achieve related model deletion is using @michaeldyrynda 's package or database cascade deletion. Thanks !
