### ISSUE TITLE
Increment and Decrement doesn't respect attribute guarding

### ISSUE THREAD

**Issue by pankitgami** [laravel/internals#532]
In the current code of increment and decrement function of the model, It doesn't check whether column being updated is guarded or not.

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Model.php#L415

**Comment by laurencei** [comment]
If you are explicitly saying to update a column - what is there to "guard"?

That seems like correct behavior to me?

**Comment by pankitgami** [comment]
Sorry, my mistake. Misunderstood the concept of attribute guarding.
