### ISSUE TITLE
Deleting logs folder?

### ISSUE THREAD

**Issue by m1guelpf** [laravel/internals#544]
Do we really need a `storage/logs` folder for only a `laravel.log` file?

**Comment by sebastiandedeyne** [comment]
Laravel supports daily logging too, which creates a new log file each day.

https://laravel.com/docs/master/errors#configuration

**Comment by Dylan-DPC** [comment]
Well some people set it to daily or monthly log files

**Comment by m1guelpf** [comment]
@sebastiandedeyne @Dylan-DPC Thank you!
