### ISSUE TITLE
[proposal] Having a compatible PSR-11 container instance.

### ISSUE THREAD

**Issue by bweston92** [laravel/internals#550]
After [this comment](https://github.com/prooph/laravel-package/pull/1#issuecomment-178617825) I want to get started a plan to allow for a [PSR-11](https://github.com/container-interop/fig-standards/blob/master/proposed/container.md) compliant wrapper around the Illuminate container.

As there is an increase in the number of packages I've seen being developed which make use of PSR-11, 450 of them registered on packagist as a dependant. I think it would be a good time for Laravel to have a wrapper implemented in the framework.

Other projects such as Zend Service Manager have this built into there service manager. I my self have had to make a [temporary patch](https://github.com/prooph/laravel-package/pull/14/files#diff-e8de58fd14d9d019615264b7c973fe20) to a project in order to satisfy this requirement when using Laravel.

**Comment by Garbee** [comment]
I think Taylor was clear enough on this in the references issue. Just submit a PR for him to look at. Not sure what more really needs discussion at this point.

**Comment by deleugpn** [comment]
PSR-11 hasn't been accepted yet, though?

**Comment by bweston92** [comment]
@deleugpn no but an increasing amount of packages are using it. I my self maintain a Laravel package that provisions a framework agnostic package that uses the PSR-11 container interop.

**Comment by avermeire** [comment]
PSR-11 has been accepted now.

**Comment by deleugpn** [comment]
Anybody working on a PR for this?

**Comment by bweston92** [comment]
@deleugpn not that I know off. However here is an implementation just needs porting:
https://github.com/prooph/laravel-package/blob/master/src/Container/LaravelContainer.php

**Comment by deleugpn** [comment]
Looks like Taylor was interested in having the container compliant with PSR-11.
