### ISSUE TITLE
[Proposal] User contract in stock Laravel application

### ISSUE THREAD

**Issue by a-komarev** [laravel/internals#556]
## Proposal

Add User Contract to stock Laravel Application.

It will be helpful to:
- Relate on concrete User Model in external package without worrying about custom namespace or class name. It could be just empty interface file but even in this case it would do the job.
- Check type of the model by typecasting User Contract instead of concrete implementation when you know that user model should be received.

For example we'll be able to do so in package to get a relation:
```php
// Models/Comment.php
public function author()
{
    return $this->belongsTo(app(UserContract::class), 'user_id');
}
```

```php
// Events/CommentWasCreated.php
public function __construct(CommentContract $comment, UserContract $user)
{
    // 
}
```

## What we have now

I know 3 ways to achieve relation on user model currently.

### 1. Using package config

```php
public function user()
{
    return $this->belongsTo(config('package-name.models.user'));
}
```

I don't like this way because in this case a lot of the packages will have the same definition of the user model in many packages.

### 2. Using application config

```php
public function user()
{
    return $this->belongsTo(config('auth.providers.users.model'));
}
```

This way will prevent duplicating user models definition in each package config file, but it's relate on application file which is a black box for the package.

### 3. Custom interface

```php
/**
 * Bind User model from config to User contract.
 */
protected function bindUserModel()
{
    $this->app->bind(UserContract::class, function ($app) {
        // It could use config from the package + app here if required.
        return $app->make('config')->get('auth.providers.users.model');
    });
}
```

After that this code will work:

```php
public function user()
{
    return $this->belongsTo(app(UserContract::class));
}
```

[See example of custom user interface in action in Laravel Ownership Package](https://github.com/cybercog/laravel-ownership/blob/master/src/Providers/OwnershipServiceProvider.php#L41-L53).

But after all thats just using 1st and 2nd method described above and binding result value to your custom user interface what doesn't gives you any big benefits and require to add more contracts to user model which would have the same logic.

**Comment by svenluijten** [comment]
There's already the [`Authenticatable`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Contracts/Auth/Authenticatable.php) interface the the current default `User` model already implements (as you can see [here](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Auth/User.php)), so you can always typehint against that.
