### ISSUE TITLE
Consistent behaviour between MessageBag constructor and public API

### ISSUE THREAD

**Issue by michaeldyrynda** [laravel/internals#56]
Currently, the behaviour between initialising a new `MessageBag` and using the `add` method is inconsistent.

The `add` method tests for uniqueness (of the key, and the message in the keyed array), whereas the constructor will accept duplicate messages.

``` php

$messageBag = new MessageBag(['messages' => ['first', 'second', 'third', 'third']]);

// $messageBag->getMessages()
// ['messages' => ['first', 'second', 'third', 'third']]

$messageBag = new MessageBag;
$messageBag->add('messages', 'first');
$messageBag->add('messages', 'second');
$messageBag->add('messages', 'third');
$messageBag->add('messages', 'third');

// $messageBag->getMessages()
// ['messages' => ['first', 'second', 'third']
```

I'm not certain if this is on purpose, so I propose to fix the constructor behaviour, which will bring consistency between the constructor and public API of the MessageBag (`add`) method.

It appears this has been around since [January, 2013](https://github.com/laravel/framework/issues/84#issuecomment-12636821), so this would likely be targeted to next release due to backwards compatibility breakage.

**Comment by taylorotwell** [comment]
Yeah we should fix this.

**Comment by sahilsharma011** [comment]
@taylorotwell If no one is working on this, then I would like to get assigned on this issue.

**Comment by taylorotwell** [comment]
If this isn't fixed yet, I'm open to PRs.
