### ISSUE TITLE
No way to customize confirmation postfix in validatior

### ISSUE THREAD

**Issue by sartatpdev999** [laravel/internals#565]
- Laravel Version: 5.4.19

### Description:
There is no way to customize confirmation postfix in validatior. For example, it's impossible to use `password-confirmation` instead of `password_confirmation` because `validateConfirmed` method has hardcoded `_confirmation`.

### Steps To Reproduce:
1. Add `$confirmation_postfix` parameter to `validateConfirmed` method in `Illuminate\Validation\Concerns\ValidatesAttributes`
2. And something else...

Moved from: [laravel/framework#19050](https://github.com/laravel/framework/issues/19050)

**Comment by laurencei** [comment]
Why do you need to customize it?

i.e. why cant you just use `_confirmation`?

**Comment by Decadence** [comment]
@laurencei just for flexibility and what if I need confirmation field with certain name.

**Comment by sartatpdev999** [comment]
First of all it's flexibility

**Comment by decadence** [comment]
@sartatpdev999 by the way you can use `same` rule where you can set name of second input. Confirmation rule is just wrapper.

**Comment by sartatpdev999** [comment]
@decadence Yeah, thanks.

I have the following code:
```
$response = $this->broker()->reset(
  $request->only('email', 'password', 'password-confirmation', 'token'), function ($user, $password) {
    $this->resetPassword($user, $password);
  }
);
```
I try to reset password via PasswordBroker and as you can see i use hyphen as delimiter in password confirmation field. It doesn't work. I get the following error:
```
ErrorException in PasswordBroker.php line 172: Undefined index: password_confirmation
```
With ```password_confirmation``` it works as expected.

Not obvious behaviour. Of course, it's not critical. But please let me know if i don't understand something

**Comment by decadence** [comment]
In this situation just use `password_confirmation` because it's shipped and PasswordBroker validation expects this key name.

**Comment by sartatpdev999** [comment]
Ok, thanks
