### ISSUE TITLE
[Proposal] Eager loading certain relation columns

### ISSUE THREAD

**Issue by salomoni** [laravel/internals#566]
Sometimes only certain columns are wanted from the relationships eg with APIs.

### Currently 

You have to write these nasty closures to achieve that. 

```php
Post::with([
    'comments' => function ($query) {
        $query->select('id', 'post_id', 'user_id', 'title')
              ->with(['user' => function ($query) {
                  $query->select('id', 'name');
              }]);
    },
    'labels' => function ($query) {
        $query->select('id', 'post_id', 'name');
    },
]);
```

### Proposed

A cleaner way would be to specify them in array and select them in under the hood.

```php
Post::with([
    'comments' => [
        'id', 
        'post_id',
        'user_id',
        'title',
        'user' => ['id', 'name'],
    ],
    'labels' => ['id', 'post_id', 'name'],
]);
```

The related keys (`post_id`, `user_id`) also could be omitted and selected automatically.

**Comment by sisve** [comment]
This syntax would conflict with any future attempts to allow callables since callables can also be arrays with 1-2 entries.

**Comment by salomoni** [comment]
@sisve 

```php
if (method_exists($model, $relation)) {
    //
}
```

**Comment by sisve** [comment]
I don't follow. The problem isn't the relation name, but the closure/callable/second thingie. The `['id', 'name']` which also is a valid syntax for a callable.

	class id {
	    static function name() {
	        echo 'name invoked!' . PHP_EOL;
	    }
	}

	$array = ['id', 'name'];
	$array();

**Comment by salomoni** [comment]
I see, you are correct. Thanks for clarifying.

A choose between the columns or the class has to be made with the proposed syntax.

Going deeper doesn't make a much sense as the whole purpose was to make the structure simpler. e.g.

```php
Post::with([
    'comments' => [
        'columns' => ['id', 'post_id', 'user_id', 'title'],
        'relations' => ['user' => ['columns' => ['id', 'name']]],
    ],
    'labels' => [
        'columns' => ['id', 'name'],
    ],
]);
```

There sure are other ways to tackle this.

- Add new methods that only supports this or at least takes the priority over callables?
- Columns as strings `['columns' => 'id, post_id, user_id, title']`?

<hr>

Going too far? I just really like the idea of that clean eager loading. I've probably written those queries in every real Laravel API.

**Comment by timacdonald** [comment]
I'm not to fussed on the implementation of this (as I'm not doing this kinda thing in my projects), but perhaps if this was to be implemented, a better way might be something like seen elsewhere:

```php
Post::with([
    'comments@id,post_id,user_id,title',
    'comments.user@id,name',
    'labels@id,name'
]);
```

or

```php
Post::with([
    'comments:id,post_id,user_id,title',
    'comments.user:id,name',
    'labels:id,name'
]);
```

**Comment by salomoni** [comment]
After looking how the relations are parsed this feature has already been implemented.

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Builder.php#L1046:L1092

Works exactly like @timacdonald proposed as the validation rule builder style.

I couldn't find that anywhere from the docs..

**Comment by timacdonald** [comment]
No way, haha , TIL :)
