### ISSUE TITLE
[Proposal] Add hability to comment tables.

### ISSUE THREAD

**Issue by carusogabriel** [laravel/internals#567]
Hello there.

_[Scenario]:_ As a big fan of comments (that help us in future maintenance), I love the ability to comment my columns with the [column modifier](https://laravel.com/docs/5.4/migrations#column-modifiers) `->comment('my comment')`, but hate to have to add a ugly `DB::statement` in the bottom of my migration as: `DB::statement("ALTER TABLE <table> comment <comment>");` just to have a comment in my table.

_[Doubt]:_ It's just me, or there's a considerable members here at the community that agrees that we could have an better (and cleaner way) to add <b>table comments</b>?

_[Proposal]_: Add a method (maybe to `\Illuminate\Database\Schema\Blueprint` or `\Illuminate\Database\Schema\Builder` class) that allows us to comment to our table.

_[Code]_: Inside the `up` method in your migrations, this is what (could) looks like:

With `\Illuminate\Database\Schema\Blueprint` implementation:
```php
Schema::create('posts', function (Blueprint $table) {
    $table->increments('id')->comment('id of the post');
    $table->string('title')->unique()->comment('title of the post');
    $table->text('body')->comment('body of the post');
    $table->timestamps();
    $table->comment('table that stores posts inside the blog');
});
```
Or with `\Illuminate\Database\Schema\Builder` implementation:
```php
Schema::create('posts', function (Blueprint $table) {
    $table->increments('id')->comment('id of the post');
    $table->string('title')->unique()->comment('title of the post');
    $table->text('body')->comment('body of the post');
    $table->timestamps();
});

Schema::comment('posts', 'table that stores posts inside the blog');
```

**Comment by Decadence** [comment]
It has been discussed already: https://github.com/laravel/framework/issues/93

**Comment by carusogabriel** [comment]
@Decadence thanks, didn't saw that one.
