### ISSUE TITLE
[Proposal] Add `->conjoin()` Method To Collection

### ISSUE THREAD

**Issue by mikebronner** [laravel/internals#568]
I would like to propose adding an `->conjoin($collection)` method that behaves similarly to `->merge()`, but does not overwrite items with the same key. Please forgive me if this is already doable with a collection method, but I couldn't find one.

Would be happy to write up a PR for this. Here's a sample of what I had in mind:

```
<?php namespace App\Services;

use Illuminate\Support\Collection;

class CustomizedCollection extends Collection
{
    public function conjoin(Collection $source) : self
    {
        $source->each(function ($item) {
            $this->push($item);
        });
        
        return $this;
    }
}
```

**Comment by Dylan-DPC** [comment]
What will happen if both have same indice?

**Comment by Garbee** [comment]
@Dylan-DPC Well, if it *is not* overwriting like the existing method then it must... skip over it and keep the base collections value?

**Comment by sisve** [comment]
Uhm. So you have $a and $b, and want to `$a->merge($b)` without overwriting stuff? Wouldn't that be the same result as `$b->merge($a)`?

**Comment by mikebronner** [comment]
@Dylan-DPC @Garbee No, it adds all items, even if the indexes are the same. I have implemented this in production already, and thought to share this here. Granted, its not a common use-case, as it only happens when mixing different types of objects in a collection that have the same id.

@sisve Not really, because doing `$b->merge($a)` will also overwrite any keys that exist in both collections.

**Comment by Garbee** [comment]
Ah, so you want to entirely ignore the keys and create a new collection of only the values. So a built-in way of doing `collect(...$collection, ...$another)` or `collect($collection, $another)->collapse()`.

**Comment by Garbee** [comment]
Or you could also do `$collection->prepend($another)->flatten()`. Either way, the requested functionality is simply a minor syntax improvement. Go ahead and submit a PR, you already have the code written. Although, I would recommend making the method not mutate the current object but create a new collection to return.

**Comment by mikebronner** [comment]
@Garbee no, I don't want to ignore keys, I want to allow for duplicate keys, but different values. but good idea on not mutating, thanks :).

**Comment by mikebronner** [comment]
PR was merged in. Thanks for the feedback everyone! :)
