### ISSUE TITLE
[Proposal] artisan make:controller --api

### ISSUE THREAD

**Issue by salomoni** [laravel/internals#580]
## Currently

Creating controller resources with `--resource` option gives two unnecessary methods when creating **API**s.

```php
public function index() { }
public function create() { }
public function store() { }
public function show() { }
public function edit() { }
public function update() { }
public function destroy() { }
```

## Proposed

Add an option `--api` | `-a` to the `make:controller` command that makes the controller without `create` and `edit` methods that is going to be removed immediately anyway.

```php
public function index() { }
public function store() { }
public function show() { }
public function update() { }
public function destroy() { }
```

**Comment by tomschlick** [comment]
With this you could also supply a `--model` | `-m` parameter which would autofill the contents with some default CRUD statements.
