### ISSUE TITLE
[Proposal]To have URL path for mix() similar to asset() and url()

### ISSUE THREAD

**Issue by ruchern** [laravel/internals#581]
`mix()` helper currently sets the url to the root directory rather than the full path as seen in `asset()`, `url()`. For projects that are deployed in subdirectories, this results in broken links.

May I know if there is a special reason for this?

In addition to that, is `url(mix())` recommended as a good practice to set the full path should the project be deployed in subdirectories? 

Attached below is an example of what I am trying to explain.

Just look at `asset()` and `url()` and the difference in `mix()`. There is clearly full paths for `asset()` and `url()` but not in `mix()`.

<img width="653" alt="screen shot 2017-05-11 at 8 25 55 am" src="https://cloud.githubusercontent.com/assets/10343662/25926756/8f15163a-3623-11e7-8725-58d7a819ca47.png">
^ URLs shown with `mix()`

<img width="833" alt="screen shot 2017-05-11 at 8 26 21 am" src="https://cloud.githubusercontent.com/assets/10343662/25926758/90b4d8ea-3623-11e7-8cce-b73f36077c3a.png">
^ URL shown with `asset()`

**Comment by m1guelpf** [comment]
See https://github.com/laravel/framework/pull/18996 and Taylor's response

**Comment by ruchern** [comment]
@m1guelpf Okay, thank you. I guess this solves my concern now.
