### ISSUE TITLE
Make array validation return friendly messages

### ISSUE THREAD

**Issue by w4** [laravel/internals#59]
Messages are currently returned in dot notation, giving not very nice messages back to the user.

"The test.0 field is required"
"The array.test field is required"
"The test.0.text is required"

Arrays should be treated specially, possibly via another language key, such as:

```
'array' => 'Field :1 in the :0 group'
// Field 0 in the test group
// Field test in the array group
```

or possibly a callback, allowing loops for varying depth inputs (see example 3 above):

```
'array' => function (array $fields) {
    echo "The {$fields[1]} field in the {$field[0]} group.";
}
```

Thoughts and improvements?

**Comment by themsaid** [comment]
The thing with array validation is that the possibilities are endless. The level of nesting can be very deep or no depth at all, so it's hard to generate a friendly message. I believe every application need to define custom attribute names for those fields to produce friendly messages.
