### ISSUE TITLE
Use namespaces in tests

### ISSUE THREAD

**Issue by JosephSilber** [laravel/internals#60]
The way the internal framework tests are currently structured is quite a bit of a mess.

Can we structure the tests to use proper namespaces, matching the structure of the code being tested?

---

While we're at it, it'd be beneficial if we could split integration tests and unit tests into their own separate directories.

**Comment by vlakoff** [comment]
Sounds great, could you please provide samples?

**Comment by JosephSilber** [comment]
Uh... samples of what?

**Comment by vlakoff** [comment]
Simply of what you are suggesting, so readers get it faster :)

**Comment by mark86092** [comment]
@JosephSilber Is it possible to autoload class in tests? Then the traits and dummy classes can be reused

**Comment by JosephSilber** [comment]
Of course. That's the whole point!

**Comment by mateusjatenee** [comment]
Yeah. That'd be great.

**Comment by TiagoMaiaL** [comment]
I know this is trivial, but even the psr2 coding standard requires namespaces.

**Comment by sileence** [comment]
Does PHPUnit work well with namespaces?

**Comment by JamesGuthrie** [comment]
@sileence It works exactly the same as without them

**Comment by mariomka** [comment]
You can use "autoload-dev" property of composer https://getcomposer.org/doc/04-schema.md#autoload-dev

```
"autoload-dev": {
    "psr-4": {
      "Tests\\": "tests/"
    }
  }
```

**Comment by Milewski** [comment]
+1

**Comment by sisve** [comment]
Just make sure that the old classes are kept for backward compatibility reasons. Mark them as @deprecated for some time before removing them completely. Guessing they would be empty and derive from the new namespaced classes.

    /**
     * @deprecated This class was moved to \Namespaced\NewClass in Laravel 5.x.y. Please use that class instead. This class will be removed in the future. 
     */
    class OldClass extends \Namespaced\NewClass {
    }
