### ISSUE TITLE
[Proposal] Allowing class and instances for validation rules

### ISSUE THREAD

**Issue by timacdonald** [laravel/internals#604]
Thoughts on including the functionality to do this with the built in Laravel validation classes:

```php
Rule::unique(Post::class, 'title')
```

```php
Rule::unique($post, 'title')
```

and internally determining the table name by instantiating an instance of the class and retrieving the table name, or grabbing it off the instance passed in. Would also work for:

```php
Rule::exists(User::class, 'email')
```

[This discussion started in here](https://github.com/laravel/internals/issues/591#issuecomment-302018299)

**Comment by ConnorVG** [comment]
I've made a follow up PR and attached it to this issue.

**Comment by timacdonald** [comment]
haha - all over it :)

**Comment by timacdonald** [comment]
Taylor isn't keen on this, soooo...
