### ISSUE TITLE
Use JSON Web Tokens in the Token Guard

### ISSUE THREAD

**Issue by themsaid** [laravel/internals#61]
The current `TokenGuard` saves the user token into the database, if we use JWT instead we can have the following:

1. Token expiration control.
2. Multiple tokens per user (Logging in from multiple front-ends).
3. Attach extra data into the token (scopes, language, etc...)

**Comment by mark86092** [comment]
There are packages implement JWT for Laravel. Is it worthy to rebuild it ?

For example, I recently use this: https://github.com/tymondesigns/jwt-auth

**Comment by themsaid** [comment]
Agreed, but since there's a `TokenGuard` already I suggest we use JWT instead of a database based one. Maybe just the basic stuff, authentication, token generation, attaching data, etc..

**Comment by fredrkr** [comment]
@mark86092 Jwt-auth does not currently go along well with L5.2 and the new Auth-system. They are working on a jwt-auth guard, but it is not documented at all and progress is slow.

**Comment by taylorotwell** [comment]
Passport provides this use case.
