### ISSUE TITLE
2014_10_12_100000_create_password_resets_table.php file breaks in windows

### ISSUE THREAD

**Issue by karolis699** [laravel/internals#62]
I downloaded laravel master zip file, extracted it o my desktop and now i cant delete laravel/database/migrations/2014_10_12_100000_create_password_resets_table.php it says permission denied, furthermore the problem is that i have a ubuntu vm with shared folder to windows and i cant install laravel because this file breaks and windows cant do anythig with it. I'm ussing windows 10. Does anyone know where is the problem is it my problem or is it the file? cause i cant find any answers on the internet.

**Comment by JosephSilber** [comment]
This is not the place to post such things.

This is for discussions on how to improve the Laravel internals.

Please close this issue and post this on the forums or in Slack.
