### ISSUE TITLE
Reverting to the old docs menu 

### ISSUE THREAD

**Issue by introwit** [laravel/internals#626]
As already asked by many in the laravel/docs issue section I again propose to revert back to the old menu/sidebar that is open and NOT collapsed. The reasons are:

- Since its the documentation, a collapsed menu makes less of a sense.
- Many of us (almost all) don't have it memorised which part is in which section so it becomes more of a guessing game and definitely annoying.
- Search is more useful when we know the exact term for what a thing is called but I guess considering every level of developer will be using this documentation which is actually true in this case the chances of the usual "Oh the X thing might be in this section & clicks on it" is more. Also sometimes search is not the way preferred especially while revising docs to boost up your laravel skills.

**Comment by Kyslik** [comment]
There are 2-3 issues related to this on docs already, I hope this gets some attention.

**Comment by introwit** [comment]
Yep, hoping for the same.

**Comment by bbashy** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by vlakoff** [comment]
At the very least (or as a compromise), several sections should be openable at once, i.e. unfolding a section shouldn't fold the previous one. "Accordion menus" belong the UX horrors that irk me the most.

**Comment by vlakoff** [comment]
Meanwhile, one more on my pile of "fixing the web, wip" Greasemonkey scripts…

```js
// ==UserScript==
// @name        Laravel Documentation
// @namespace   laravel.com
// @description Unfold (and compact) the side menu
// @include     https://laravel.com/docs/*
// @version     1
// @grant       GM_addStyle
// ==/UserScript==

GM_addStyle(
      '.sidebar h2 + ul { display:block }'
    + '.sidebar h2 { cursor:auto }'
    + '.sidebar h2:hover { color:inherit }'
    + '.sidebar h2::after { content:none }'
    + '.sidebar > ul > li { line-height:inherit }'
);
```

**Comment by introwit** [comment]
@vlakoff lets see what @taylorotwell has to say

**Comment by taylorotwell** [comment]
Hit `/`... use fuzzy-search. Better than Cmd+F.

**Comment by bbashy** [comment]
@taylorotwell Bit disappointed in that response, to be honest.

**Comment by introwit** [comment]
@bbashy same here, though his alternate solution : https://twitter.com/taylorotwell/status/871775692639264770

**Comment by kasparsklavins** [comment]
The thing with page defined shortkeys is.. they conflict with user defined, browser-global shortkeys. 
I already have a shortkey mapped to `/`, as do many other users. 
Any shortkey introduced to expand/collapse navigation will conflict with some user self defined shorkeys. 

**This wasn't about adding accessibility and convenience - it was explicitly taking it away in the first place, and then reintroducing it in a broken way to not even all users.**

**Comment by introwit** [comment]
@kasparsklavins very well written but @taylorotwell seems to discard so many people's opinion just because he himself alone feels good with this. Immense respect for Taylor but sometimes when he doesn't even considers the counter point scares me to be honest. :cry:

**Comment by n0rz** [comment]
@taylorotwell Hi Taylor Boy, great response, and very thought provoking! Indeed, what is this crazy idea to have multiple expanded sections at once! My goodness, your face is really white dude, but anyway, sorry, just kidding about that one, youre really quite handsome, I love the way the sun reflect off your white skin and catches a glint in my eyes. To the point, I think vlakoff makes an excelent point with the multiple expanded sections at the same time, imagine if you could only navigate ONE folder tree at a time in an IDE. Anyway, thank you so much Taylor baby, you're looking fit as hell, and I honestly wouldn't mind taking a bite out of that.﻿

**Comment by wing5wong** [comment]
is '''/''' a common feature for searching? It's not on Windows.
This change has made it more difficult to find things at a glance. 
The new menu makes it impossible to tell what is available in the documentation. there is no "index" anymore

Recommend that navigation be expanded by default, or at the very least, have multi-expand option (better yet, "expand all" button)

**Comment by Kyslik** [comment]
@wing5wong no its not common, for example GitHub uses "s" for search not slash.

**Comment by introwit** [comment]
I am now tired because no one from the laravel team gives a damn to so many people's opinion and finds it useless to come and atleast put up their opinion. The thing I hate is if it was adam , Jeff or any telegram group member this might be the most important thing for them to discuss about. I hate saying this as much I found it to be true. Afraid of future proposals & contributions to Laravel.

**Comment by introwit** [comment]
You cant justify removing "**The Index**" with a _search box_ from the official docs. These are entirely 2 different ways how millions of developers consume a documentation, either through the index or via search, 2 complete different approaches.

**Comment by ncpope** [comment]
I was initially concerned about the usability of the docs since based on the reaction here it seemed that the / key was mandatory. This would have been a pain point for me since I use a Spanish keyboard layout and / is bound to shift+7. However, I found that the search box location isn't difficult to access since it is in the top navbar and I personally think the new layout https://laravel.com/docs/master/installation is more navigable than https://laravel.com/docs/4.2/installation.

My only suggested change would be to not force toggling the currently expanded sidebar section when activating a new section.

On a side note, people seem very touchy about the response that Taylor gave. While he most likely isn't going to win any customer support awards any time soon he does give a response to many open issues and pr's. He shouldn't have to explain every single design or architectural decision in depth.

**Comment by introwit** [comment]
@ncpope you use the search , I use the index to navigate. And on the Taylor's part , the response is flawed and you shouldn't advocate for a third person on a issue faced by a second person. I don't go on every issue reported and say "I am not getting this issue haha losers it's your fault not Laravel's". If you aren't facing the issue nor do have solution for it also without asking what's the problem you are here advocating for someone!?

**Comment by sisve** [comment]
@ncpope The current search does not conform to the html standard. There's is an [accesskey attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey) that is meant to define access keys. This isn't used. If this were used there would at least be a chance for all browsers and accessibility addons to list all available hotkeys. If this were used it would at least conform to the standard browser keys (which differ between browsers). If this were used I would now both which access keys exists, and how to invoke them.

How would someone know that the "/" character would be used for search? Should all the visitors first read the laravel/internals, laravel/docs and other issues to find this information? Or should they read the minified javascript containing `i.bind("/", function(t) { t.preventDefault(), e("#search-input").focus() })`?

If you want people to use the search function; why is it the feature with the lowest contrast on the page? All the documentation content, the side bar, the top-menu, _everything_ has higher visibility than the search.

The body text has font-size: 14.5px (`.docs article p`), but the placeholder text saying "SEARCH" is 12px. It's not only smaller, the color (for me, in Chrome) is even brighter (#757575) than the any other text-content on the page (#525252). Testing this color on a [wcag compliant contrast checker](http://webaim.org/resources/contrastchecker/) show that it is too low contrast to pass wcag as normal text, which is the "wcag context" it is used in. It is not styled as a textbox and the only hint about the area being focusable is the mouse cursor when you hover _some areas_ of the search area. At least the icon area and an area to the right of the "hidden" textbox is not focusable/writable.

This is how I would style a feature that I was forced to implement, but didn't want to draw attention to.

The comment about the /-search being better than cmd-F assumes that people want all-expanded menu sections to use the browser search functionality to search through them.

**Comment by ncpope** [comment]
>  "I am not getting this issue haha losers it's your fault not Laravel's"

@introwit I didn't say that or even imply it

This is a public discussion. People can have input that differs from your own or from the OP. Just because someone has an issue with the way things are done doesn't mean that it will change to suit their needs.

Also yes I am sticking up for Taylor. Although the commenters seemed to be irritated with his response, I am offering my own view. If you don't like what he said that's fine and you can say that, if I think what he said isn't a big deal that also is fine and I can say that if I want to.

**Comment by ncpope** [comment]
@sisve The search is one of the only three elements that remains in the top navbar when the window width is at its narrowest. At a 385px window width search takes up 220px. That doesn't sound like it's being exactly hidden.

In regards to the accesskey attribute, neither github, google, nor twitter seem to use it on their inputs. That doesn't seem like a reason expectation for it to be used on the laravel docs.

I agree that the font color on the search box placeholder could be darker.

I also agree that using / isn't a good fit for a search shortcut. I mentioned it in my reply earlier that on my keyboard layout it isn't convenient. However, nothing is preventing me from just clicking on the search box and entering my query.

My suggestion for improving the navigability would be to turn off toggling on the sidebar sections and allow the user to expand all of them.

**Comment by introwit** [comment]
> "Just because someone has an issue with the way things are done doesn't mean that it will change to suit their needs." 
@ncpope Didn't this applied when the index was not collapsed and it was made so recently?

Also yes you are right its a public platform so you can give your inputs, but I found your comment odd as so many people are saying a thing and Taylor just discarded without even considering the points we made. If he at-least gave the reason, maybe just a single line in response to the point so many people were making we would have understood and might have even closed the issue but ...

**Comment by introwit** [comment]
@ncpope yes atleast this! And hot key shouldn't be the solution for it as @sisve said the readers wont even know its there without reading the laravel/internals issue thread.

> My suggestion for improving the navigability would be to turn off toggling on the sidebar sections and allow the user to expand all of them.

**Comment by sisve** [comment]
> At a 385px window width search takes up 220px.

I'm pretty sure that those of us complaining, those that want to see the full list of documentation topics, those that have issues with collapsing menus with cmd-buttons, aren't using their phones... But yes, I am guessing at that point.

The problem isn't that there's been a change in design. The problem is that there is now input on stuff, and we get responses like "Hit /... use fuzzy-search. Better than Cmd+F." or "sorry. there is 0% chance i change it back." (Ref: [twitter](https://twitter.com/taylorotwell/status/871775159392256000))

**Comment by vlakoff** [comment]
This is getting out of hands, but just a few notes about the Search functionality:
* Since the latest website redesign, the search bar is really not noticeable. I remember having missed it for a long time.
* The autocompletion results cannot be middle-clicked, which is for me a big no-no. See https://github.com/algolia/docsearch/issues/159

**Comment by introwit** [comment]
@Kyslik @bbashy @vlakoff @kasparsklavins @wing5wong since no reply from Taylor I decided to go with it and made this PR: https://github.com/laravel/laravel.com/pull/133
