### ISSUE TITLE
Sync pivot column with an array of values

### ISSUE THREAD

**Issue by haleksandre** [laravel/internals#64]
For certain use case it would be useful to be able to pass an array of values of a certain pivot column via the sync array like so:
##### Products

| id | name |
| --- | --- |
| 1 | Product 1 |
| 2 | Product 2 |
##### Specs

| id | type |
| --- | --- |
| 1 | Width |
| 2 | Height |
| 3 | Optional Spec (multiple size) |

I want the intermediary table to look like this:
##### Product_Spec

| id | product_id | spec_id | value |
| --- | --- | --- | --- |
| 1 | 1 | 1 | 100 |
| 2 | 1 | 2 | 50 |
| 3 | 1 | 3 | 10 |
| 4 | 1 | 3 | 20 |

The `Optional Spec` has multiple sizes available to that particular product. So it would be useful to be able to pass an array to the `value` column for that particular spec. The sync array would look something like this:

``` php
// Get product
$product = Product::find(1);

// Set data array
$data = [
    1 => ['value' => 100],
    2 => ['value' => 50], 
    3 => ['value' => [10, 20]],  //An array of values to put multiple Optinal Spec sizes
];

// Sync data
$product->specs()->sync($data)
```

**Comment by alexdrakeonline** [comment]
Hi i am newbie on Laravel framework, actually I want to know is there a way to sync only specific type records i.e in above example sync records that have value less than 100 replace with new records.

**Comment by haleksandre** [comment]
@alexdrakeonline 

If your data is an array like above you could simply filter your array and remove anything more than 100. You could use something like `array_filter` :

```php
// Data array
$data = [
    1 => ['value' => 100],
    2 => ['value' => 50], 
    3 => ['value' => 10],
    4 => ['value' => 300],
];

// Filter your data
$filteredData = array_filter($data, function ($item) {
    return $item['value'] < 100;
});

// Sync filtered data
$product->specs()->sync($filteredData);
```

**Comment by StefanijaK** [comment]
I am having the same issue ad @haleksandre. Is there a solution for this yet?

**Comment by Hesesses** [comment]
Also having the same problem

**Comment by graphicmist** [comment]
Why is this issue closed without any solution?

**Comment by graphicmist** [comment]
For anyone still looking for solution, check this out: https://stackoverflow.com/questions/42091778/how-to-sync-multiple-values-of-the-same-attribute-in-laravel

**Comment by ErPrateekSingh** [comment]
Also having the same problem. Did you @StefanijaK or @haleksandre find any solution yet?
