### ISSUE TITLE
Email Validation of Laravel 5.4 failed

### ISSUE THREAD

**Issue by akbansa** [laravel/internals#640]
While using laravel validation I found a minor issue that it does not validate emails properly. It means validation do not fails on some emails which are not compliant with IETF standards.

Basically, it passes the emails as **user-name@company-name.x**

So here x is not an acceptable domain name extension.

Have a look into this and fix!

**Comment by decadence** [comment]
It uses `filter_var($value, FILTER_VALIDATE_EMAIL)` so it's PHP behaviour.
I don't think it will be changed.

**Comment by m1guelpf** [comment]
@akbansa You may want to use [nojacko/email-validator](https://github.com/nojacko/email-validator) to check for that kind of things.

**Comment by akbansa** [comment]
@decadence man laravel is big framework today, it should overcome the limitations of PHP as well

**Comment by m1guelpf** [comment]
@akbansa Laravel **is** built on PHP

**Comment by akbansa** [comment]
@m1guelpf  I also know that but while writing framework, they had used many regex where necessary, so they should also use custom regex for email
That is what I'm writing to say!

**Comment by decadence** [comment]
Then feel free to open PR with fix you assume applicable.

**Comment by tomschlick** [comment]
A custom regex wont solve this problem. Using the PHP `filter_var($value, FILTER_VALIDATE_EMAIL)` approach is correct. All that validation is supposed to do is check if an email address's formatting is correct. [Which it is.](https://en.wikipedia.org/wiki/Email_address#Domain)

What you're asking for is validation of a domain using MX records which would be the only way to tell if a domain is valid, and has an email server attached to it. @m1guelpf linked you to a package that does just that. With that you can create your own validation rule (maybe something called "valid_mx") and validate your users that way.

**Comment by akbansa** [comment]
@tomschlick I am not trying to verify mx, I am just trying to validate email format because **user-name@company-name.x** will be passed by `filter_var($value, FILTER_VALIDATE_EMAIL)` which are not syntactically correct. For example visit [Email address validator](http://verifalia.com/validate-email) and enter above address

And then check for **user-name@company-name.xx**

You will know what I am trying to tell!

**Comment by m1guelpf** [comment]
@akbansa That email is valid if using the RFC 822.

**Comment by akbansa** [comment]
@m1guelpf After so much discussion above you came to the point which is the start of discussion.
Do you know any TLDs with single character or any domain name with single character.

**Comment by m1guelpf** [comment]
@akbansa See [this StackOverflow answer](https://stackoverflow.com/a/21872376/6386024)

**Comment by akbansa** [comment]
It will never come because that will be overhead for ICANN

**Comment by Dylan-DPC** [comment]
@themsaid can be closed
