### ISSUE TITLE
[proposal] Collect map method

### ISSUE THREAD

**Issue by troelskn** [laravel/internals#644]
I often find myself writing code like this:

```
$things = collect[new Thing, new Thing]);
$result = $things->map(function($thing) { return $thing->stuff(); });
```

And wishing I could do something like this instead:

```
$things = collect[new Thing, new Thing]);
$result = $things->mapMethod('stuff');
```

This seems like a common enough case that it might be worth adding to `Collection`. For comparison, in ruby we can do:

```
things = [Thing.new, Thing.new]
result = things.map(&:stuff)
```

as a shortcut for:

```
things = [Thing.new, Thing.new]
result = things.map {|thing| thing.stuff }
```

**Comment by decadence** [comment]
Isn't it what you want?
https://laravel.com/docs/5.4/collections#higher-order-messages

**Comment by troelskn** [comment]
@decadence Indeed it is.
