### ISSUE TITLE
[Proposal] Route::redirect();

### ISSUE THREAD

**Issue by Evertt** [laravel/internals#654]
Sometimes I want to change the url of an existing route. And in such case I want the previous URL to still exist, but to redirect to the new URL using a 301 code. You know, for SEO purposes.

So therefor it would be super nice to be able to write that like this:

```php
Route::get('/new-url', 'SomeController@someMethod');
Route::redirect('/old-url', '/new-url');
```

If people like this then I'm willing to write a PR for it.

**Comment by decadence** [comment]
https://twitter.com/davidhemphill/status/879415709255782400

**Comment by decadence** [comment]
Taylor says he wants to consider including this into the core.

**Comment by Evertt** [comment]
> https://twitter.com/davidhemphill/status/879415709255782400

@decadence yes I'm aware this can be solved with a macro, same with my other proposal of a fallback route. That's how I've solved these things so far. It would just be nice to have it in the core and have doc-blocks for it in the facade.

**Comment by decadence** [comment]
I posted this link not for macro solution but for Taylor comment:
![screenshot_1](https://user-images.githubusercontent.com/1434668/27575007-0f82cc3c-5b21-11e7-9837-3b84b00e966c.png)

So you can try do PR.

**Comment by sebastiandedeyne** [comment]
If this would be part of core, ideally it would be implemented in a way that the route can be cached.

**Comment by decadence** [comment]
I think this is the main trouble for person who wants make PR.

**Comment by brayniverse** [comment]
I'm working on an implementation based off my [Laravel route macros](https://github.com/brayniverse/laravel-route-macros) repo, I should push it up tonight or tomorrow. It allows for caching of redirects by using an internal RedirectController. My PR will be targeting 5.5 but if you want this functionality in 5.1+ then my package has you covered.

**Comment by decadence** [comment]
It's merged. You can close this issue.
https://github.com/laravel/framework/pull/19794
Thanks @brayniverse 
By the way what do you think about https://github.com/laravel/internals/issues/653 ?
