### ISSUE TITLE
[L5.4] How to implement PDO Fetch Mode as described in the upgrade guide?

### ISSUE THREAD

**Issue by emcarson** [laravel/internals#659]
The ability to customize the fetch mode was removed from L5.4 and is defaulted to PDO::FETCH_OBJ.

The upgrade guide states that you can override this by using an event listener:

```
Event::listen(StatementPrepared::class, function ($event) {
    $event->statement->setFetchMode(...);
});
```

I can't for the life of me understand how to implement this:

1) Where should I place the code? Should I register it with the `EventServiceProvider`? 
2) When does the `StatementPrepared` event fire? (I only need to change the Fetch Mode  for specific repository functions, not on a global scale).
3) Does the FetchMode revert itself automatically for subsequent queries?

Here's an example of my code:

app / Repositories / Backend / SystemRepository.php
```
<?php

namespace App\Repositories\Backend;

use DB;
use PDO;

class SystemRepository
{
    /**
     * Get the connection status variables.
     *
     * @return array
     */
    public function getConnectionStatus()
    {
        DB::connection('backend')->setFetchMode(PDO::FETCH_ASSOC);

        $result = DB::connection('backend')
            ->select(DB::raw("
                SHOW STATUS
                WHERE Variable_name = 'Max_used_connections'
                OR Variable_name = 'Max_used_connections_time'
                OR Variable_name = 'Threads_connected'
            "))
        ;

        DB::connection('backend')->setFetchMode(PDO::FETCH_CLASS);

        return $result;
    }
}
```

Thank you!

**Comment by mfn** [comment]
I know it's now what you asked for: but reading your code, you can try to cast the individual results with `(array)` and should give you the associated array:
```PHP
foreach ($result as $row) {
  $row = (array)$row;
  // ...
}
```

**Comment by emcarson** [comment]
Thank you @mfn!

I ended up convertir all the object collections like this:
```
$collection = $repository->getConnectionStatus();
$array = json_decode(json_encode($collection), true);
```
Best regards,
