### ISSUE TITLE
Support vagrant hosts updater in Homestead

### ISSUE THREAD

**Issue by vpratfr** [laravel/internals#66]
A popular vagrant plugin is [vagrant-hostsupdater](https://github.com/cogitatio/vagrant-hostsupdater), that updates the hosts file automatically on vagrant up and halt to remove the hostname of the VM.

It does not work properly with Homestead: only the hostname is added to the hosts file and not each domain specified in the `sites` configuration. If you have multiple sites declared, they won't be automatically added to the hosts file.

Note: I noticed that someone forked Homestead to add support for that: [farmhouse](https://github.com/erikbelusic/farmhouse) I however would prefer to stick with the official Homestead repo as you can easily understand. That could however help to implement that feature.

**Comment by taylorotwell** [comment]
I haven't seen it done in a way that's totally backwards compatible. If someone can PR that I will consider it. Maybe I overlooked one that was?

**Comment by maximusblade** [comment]
Hey there,
Wondering if this was ever looked at again ?

**Comment by marcwieland95** [comment]
@taylorotwell What's the problem with backwards compatibility there?

Why not add this snippet to the homestead.rb file. It will check if the hostupdater plugin is installed and when not, it won't do anything.
```
# Updating the hosts file with all the sites that are defined in Homestead.yaml
if Vagrant.has_plugin?("vagrant-hostsupdater")
  hosts = []
    settings["sites"].each do |site|
    hosts.push(site["map"])
  end
  config.hostsupdater.aliases = hosts
  config.hostsupdater.remove_on_suspend = false
end
```
