### ISSUE TITLE
[Proposal] Fill model and the relationships from other model in addition to array.

### ISSUE THREAD

**Issue by montyclt** [laravel/internals#660]
I propose the posibility of fill model (only fillable columns and relationships) using other model as a base.

For example:

```
// I create a new unsaved domain with some attributes and some relationships.

$domain = new Domain(['name' => 'ivanmontilla.es']);
$domain->user()->associate(User::find(1));

// Now, I retrieve a model from DB and I need replace all
// data with the other domain (except primary key and timestamps,
// maybe only the fillable columns).

$saved_domain = Domain::find(1);
$saved_domain->fill($domain);
```

I propose fill method accept too a model for fill the data of other model (maybe too a StdClass object).

And if posible, permet fill relationships, maybe with a new property `$fillableRelationships` as array of fillable relationships.

**Comment by troelskn** [comment]
Will `$saved_domain->fill($domain->getAttributes());` do?

**Comment by troelskn** [comment]
On the matter of fillable-relations, see: https://github.com/laravel/internals/issues/32

**Comment by montyclt** [comment]
Ok, I'm using `getAttributes()` method (I did not know the method) and your package with trait `HasFillableRelationships` (Thanks for write it 😘).

Now, I only need get the relationships as array too with `getAttributes()` (or other) method.

**Comment by montyclt** [comment]
I write this method on my model base class

```
public function fillFromModel(Model $model)
    {
        if (! $this instanceof $model) {
            throw new ModelException($this, 'Cannot fill a model with from a model of different class');
        }

        $this->fill($model->getAttributes());

        if ($model->fillable_relations) {
            $relations = $model->fillableRelations();

            foreach ($relations as $key => $relation) {
                $relations[$relation] = $model->{$relation};
                unset($relations[$key]);
            }

            $this->fillRelations($relations);
        }
    }
```
Is not tested, but if you like, you are free to your trait. Only caution with ModelException is created by me.

**Comment by montyclt** [comment]
I get my first problem doing it, `$domain->getAttributes()` returns the attributes as are stored in DB, without using the accessors methods, but fill try to set using the mutator methods, and the mutator expects the format that the accesor returns. I will change it to `attributesToArray()` and try to check it.

**Comment by montyclt** [comment]
It's works ;)

```
    /**
     * Fill a model using attributes from other model.
     *
     * @param Model $model
     */
    public function fillFromModel(Model $model)
    {
        if (! $this instanceof $model) {
            throw new ModelException($this, 'Cannot fill a model with from a model of different class');
        }

        $this->fill($model->attributesToArray());

        if ($model->fillable_relations) {
            $relations = $model->fillableRelations();

            foreach ($relations as $key => $relation) {
                $relations[$relation] = $model->{$relation};
                unset($relations[$key]);
            }

            $this->fillRelations($relations);
        }
    }
```
