### ISSUE TITLE
[Proposal] Add twiceMonthly($first, $second) & endOfMonth() to scheduler.

### ISSUE THREAD

**Issue by coderabbi** [laravel/internals#667]
Pretty self-explanatory, the proposed additions are to `framework/src/Illuminate/Console/Scheduling/ManagesFrequencies.php` to conveniently accommodate two very common use cases for scheduled tasks: twice a month, and end of month. 

Precedent exists for `twiceMonthly($first, $second)` as `twiceDaily()` already exists, even though it, too, could be accommodated via method chaining.

A related interesting possibility would be to add the ability to specify `"end"` as a parameter in `twiceMonthy($first, $second)` and the exiting `monthlyOn($day, $time)`;

I'm open to submitting a PR, just wanted to measure interest, gather feedback first.

**Comment by decadence** [comment]
How do you plan implement "end of month"? CRON doesn't support that.
One option is use `when` callback but seems like none of rules uses it internally.

**Comment by coderabbi** [comment]
Indeed, I'd use `when()` which is used internally already by `between($startTime, $endTime)`.

**Comment by coderabbi** [comment]
While on the subject, `endOfQuarter()` & `startOfQuarter()` are also common use cases, but let's start with months... 😄

**Comment by coderabbi** [comment]
`endOfMonth()`: https://github.com/laravel/framework/pull/19870

**Comment by coderabbi** [comment]
`twiceMonthly()`: https://github.com/laravel/framework/pull/19874

**Comment by coderabbi** [comment]
Going to wait on the reaction to those and feedback here before implementing "end" parameter for `twiceMonthly()` and `monthlyOn()`.
