### ISSUE TITLE
laravel.com upgrade from version 5.0.* to 5.2.*

### ISSUE THREAD

**Issue by putheakhem** [laravel/internals#67]
I have seen laravel.com still using **5.0.32** . can anyone upgrade to version latest ?

**Comment by Garbee** [comment]
1) This repository isn't the right place for this kind of discussion. It is for discussion about the *internal code* to the framework.

2) Why does it matter if the site is still on 5.0? It works.

**Comment by putheakhem** [comment]
hi , sorry for wrong place
I am newbie with laravel and github.
Just gonna see the latest version for laravel website
