### ISSUE TITLE
[FEATURE] Validate max length of integers and similar

### ISSUE THREAD

**Issue by LasseRafn** [laravel/internals#673]
### Description:

I'd argue that validating that a integer is 10 (example) characters of length, should be core functionality. Sure, it can be done by looking at e.g. digits, and having it be between 0 and 9999999999.. but that seems excessive.

So, I propose `maxlength` validation. Something like this:

```php
protected function validateMaxLength($attribute, $value, $parameters)
{
    $this->requireParameterCount(1, $parameters, 'maxlength');
        
    return mb_strlen($value) <= (int) $parameters[0];
}
```

### Usage

```php
'number' => 'integer|maxlength:10',
'name' => 'string|maxlength:10' // Yes, you should use max here, but its just to show that it can be used here as well
```

It's mostly useful for integers/digits, as specifying "integer" in the rules, will make `max` validate the value, not the length.

I've also written a short article about it, showing how it works using custom rules: https://lasserafn.com/validating-max-length-laravel-strings-integers-digits/

I think this could improve the experience of validation, especially for newcomers. I remember being confused with `max` and `integers`. Providing a `maxlength` makes it quite straightforward and easy to understand and remember (as its the same parameter used for HTML inputs)

I'd submit a PR; but first let me know if this could potentially be merged.

**Comment by decadence** [comment]
How it's different from `digits_between` rule?

> first let me know if this could potentially be merged

Nobody can say that because Taylor decides when PR is ready and he doesn't look here.

**Comment by LasseRafn** [comment]
Thanks, makes sense :)

It differs as it: 
 
- supports strings as well
- does not require a minimum length

However maybe it's redundant to include

**Comment by timacdonald** [comment]
Having a quick look at the frameworks [`validateDigitsBetween`](https://github.com/laravel/framework/blob/c29b0040427877e3600f4e2a6c5ce2cbc7f4cdd3/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L413) rule - it looks like it actually casts numbers to strings - so it should deal with numbers and strings the same. But I think you're saying that it should act differently for numbers and strings - which could also be confusing for newcomers.

If this was to be a thing, I'd say stick with the naming that already exists, so probably digits_max.

I have a little (hobby) validation package and I've added a `maxDigits` helper to it - which just proxies to `digits_between` with a default `min` of 0.

**Comment by LasseRafn** [comment]
I think you're absolutely right, I'd like the idea og digits_max, would also make more sense, as between (to me) could be confused with the value being between X and Y (just like "whereBetween")
