### ISSUE TITLE
Add some kind of $request->bootMiddleware('web')

### ISSUE THREAD

**Issue by garygreen** [laravel/internals#676]
This is in reference to@ #413 and #508 

At the moment, the middlewares are only booted when a route is matched. This is a problem when a `NotFoundException` is thrown because middlewares won't run and you won't have a session so if you want to output stuff in your views specific to the session, your out of luck.

If there was some kind of way of booting all the middlewares, or simulating that a route was matched in some way, this would allow you to do this in your exception handler:

```php
/**
 * Render an exception into an HTTP response.
 *
 * @param  \Illuminate\Http\Request  $request
 * @param  \Exception  $exception
 * @return \Illuminate\Http\Response
 */
public function render($request, Exception $exception)
{
    if ($exception instanceof \Symfony\Component\HttpKernel\Exception\NotFoundHttpException) {
        $request->bootMiddleware('web');

        return Response::make(view('errors.404')->render(), 404);
    }

    return parent::render($request, $exception);
}
```

**Comment by ajcastro** [comment]
Really?? So you mean, you cannot access the session for the logged in user? So what's the output when you `dd($request->users());` ?

**Comment by vesper8** [comment]
still isn't a good solution to this? the only solution i found is applying the web middleware globally..
