### ISSUE TITLE
[PROPOSAL] Change how Eloquent scopes work

### ISSUE THREAD

**Issue by jerguslejko** [laravel/internals#677]
I am proposing a change to how Eloquent scopes work. In particular, how the return value is handled.

## Feature

Currently, returning the `$query` object from within a scope method is optional. This creates a bit of misdirection in my opinion. But mainly, if the return value was required, it would allow for using scopes like this: 

```php
class Post extends Eloquent
{
    public function scopeFindBySlug($query, $slug)
    {
        return $query->where('slug', $slug)->first();
    }
}

class User extends Eloquent
{
    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

// this would be possible

$post = Post::findBySlug($slug);

// and this as well

$post = $user->posts()->findBySlug($slug);
```

Right now, this is not possible. If the `$query->where('slug', $slug)->first()` call returns `null`, `Post::findBySlug($slug)` would return the query builder.

**This is a breaking change.** All codebases would have to be updated. However, this change could be easily done by searching for scope methods project-wide.

## Implementation

I suppose, the feature could be implemented by updating [this line](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Builder.php#L934). However, I might not be thinking of a use case where the current functionality would be desired. Make sure to let me know if there is one.

What do you think? 🌵

**Comment by decadence** [comment]
Related discussion
https://github.com/laravel/framework/issues/19739

**Comment by jerguslejko** [comment]
I do realise that query scopes are _meant_ to only tweak the query, not execute it.

While this proposal might go against the original design, in my opinion, it allows for really powerful and expressive code.

```php
$post = Post::findBySlug($slug);
// vs
$post = Post::bySlug($slug)->findOrFail();

$post = $user->posts()->findBySlug($slug);
// vs
$post = $user->posts()->bySlug($slug)->findOrFail();
```

By using the proposed approach, we can eliminate chances of accidentally using `find` instead on `findOrFail`, or vice versa.

**Comment by decadence** [comment]
We can discuss it very long. It's faster to do PR and see Taylor reaction. I don't think this is what he wants to change but you can give it a try.

**Comment by timacdonald** [comment]
Perhaps rather than using a return or not return, it was a naming convention. Like dynamic where statements. If the query name start with `findBy` Laravel would execute the query with the `first()` method and return the result. Rather then having to deal with returning or not returning.

**Comment by jerguslejko** [comment]
@timacdonald hmmm, that seems a too bit 'heavy' on the implementation. I do not have my hopes high for this to be merged in, and that's a single line change.
