### ISSUE TITLE
Support a module structure

### ISSUE THREAD

**Issue by alexbowers** [laravel/internals#68]
When building complex applications, which may have multiple purposes, or be suitably complex that it would benefit being split into multiple modules.

An example of this could be a CMS, which deals with three different types of content. Main website content, blog content and an online shop content.

Now, the CMS itself would be considered a 'core' product, but the way you deal with website, blog and e-commerce is probably different. Normally, you'd have many different controllers, models etc within your App. Instead, you may benefit by having a more modular structure, where you extend based on your core feature set, but you then pull in, as modules, your side content. This would be where the modules come in.

A module would follow  the same structure as the current 'app' folder within laravel, where models, controllers, exceptions, policies etc can all be defined.

A module should be self-contained to the highest extent possible, such that it only extends what it requires to work, and most of the code is within the same module. A module should also not cross-reference with another module. 

For all intents and purposes, any one module should be able to work with the core product on its own, without requiring another module be installed.

My current plan, is that all modules must:

- Define a name, and this name must be unique within the lifecycle of the current product.
- Define their location install path (so that files from within that module can be loaded in, such as routes.php)

I'd like to start a discussion around this, before I progress too much further.

To see the rough structure of it so far:

My folder structure is as follows:

![image](https://cloud.githubusercontent.com/assets/842974/14770690/7b9025fe-0a6f-11e6-8b43-8c942e041217.png)

The repositories are:

framework: https://github.com/alexbowers/framework/tree/feature/modules
laravel: https://github.com/alexbowers/laravel/tree/feature/module
modules: https://github.com/alexbowers/laravel_modules_test

**Comment by alexbowers** [comment]
Example of what routes working:

![image](https://cloud.githubusercontent.com/assets/842974/14770715/ff7ebdc6-0a6f-11e6-9aa2-01e5da5165c7.png)


Scope:

Eventually, A module will be able to define:

- migrations
- models
- controllers
- views (Will work as current, with publishing)
- assets (Will work as current, with publishing)
- Policies
- Providers
- Routes
- Events + Event Listeners

**Comment by Mahmoudz** [comment]
@alexbowers I've always been thinking of a feature like that, and after a year of thinking I built this project that implements a special modular architecture https://github.com/Mahmoudz/Hello-API and I documented the architecture on a different repository https://github.com/Mahmoudz/Freestyle-Architecture. I'd love to hear your opinion.

**Comment by arcanedev-maroc** [comment]
We missed the old laravel workbench :cry:

**Comment by alexbowers** [comment]
@Mahmoudz I've only briefly read through it, and bits look decent, but there is a fundamental difference between our approaches. To me, a module should not interact with another module. Perhaps I am overly optimistic on the usefulness of complete separation.

**Comment by Mahmoudz** [comment]
@alexbowers thanks for checking it. That's true, I'm trying to figure out how to do the full separation, without complicating things. My main goals so far was to make everything visible for anyone reading the code and let any developer find any function quickly in a very large code base in 5 seconds :)

**Comment by alexbowers** [comment]
It could easily be my system that I'm building that is somewhat unique in
structure. Perhaps what I want isn't completely feasible for the general
use case.

My actual use case is for core to be an administration panel with the
general methods required, but then each module to add a section for the
panel to display and perform data analysis on etc. For example. The admin
panel may track bugs, performance and uptime of a system. Those would be
there separate modules.

**Comment by deringer** [comment]
I'm not sure that the modularity you're after should be part of the framework necessarily. There's nothing stopping you from using PSR4 to autoload components into your project, but as far as bundling the code in such a way, it seems to me like that would be a layer *on top* of the framework i.e. you'd build some core bundler / CMS on top of the framework, which would allow you to hook these different things in?

The framework itself gives you the ability to do whatever you need; I think workbench was designed more as a tool for building independent packages, as a way to build and test those packages to then be released as standalone components via Composer.

In a past project, I had a root service provider that would spin through a modules directory and look for service providers, route files, etc. to initialise that way, which *seems* like what you're after. Again, something to add on top of the framework, as opposed to be something to build into it. My 2c.c

**Comment by alexbowers** [comment]
The issue then comes that the framework forces a crossing of paths with
respect to migrations etc. If it isn't built into the framework, the only
way that migrations will work would be to have them copied into the
migrations folder. Same for controllers. Currently (unless I'm mistaken)
you can't do namespaces controllers with a namespace other than the default.

Models would work, as would service providers etc. But some crucial parts
would not be able to be separated.
On 25 Apr 2016 08:51, "Michael Dyrynda" <notifications@github.com> wrote:

I'm not sure that the modularity you're after should be part of the
framework necessarily. There's nothing stopping you from using PSR4 to
autoload components into your project, but as far as bundling the code in
such a way, it seems to me like that would be a layer *on top* of the
framework i.e. you'd build some core bundler / CMS on top of the framework,
which would allow you to hook these different things in?

The framework itself gives you the ability to do whatever you need; I think
workbench was designed more as a tool for building independent packages, as
a way to build and test those packages to then be released as standalone
components via Composer.

In a past project, I had a root service provider that would spin through a
modules directory and look for service providers, route files, etc. to
initialise that way, which *seems* like what you're after. Again, something
to add on top of the framework, as opposed to be something to build into
it. My 2c.c

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/laravel/internals/issues/68#issuecomment-214191890>

**Comment by Garbee** [comment]
> If it isn't built into the framework, the only
way that migrations will work would be to have them copied into the
migrations folder.

This is actually a good benefit of the setup. The developers knows exactly what will run and in what order, no surprises. If you want to abstract it away, then it should go into your own CMS package that handles running the migrations for modules.

> Same for controllers.

No, you can reference controllers by their namespace in the package when registering routes. No need to copy them into your app folder.

**Comment by alexbowers** [comment]
It also bloats your system with things you shouldn't change. In your app
directory, you should not have something that isn't your responsibility.
The migration is the responsibility of the module and so shouldn't be
committed in your repository except as a dependency. The order it runs is
still known based on the date that migrations follow. And a developer
should know what runs because they chose that dependency. Choosing a
dependency where you don't understand what it does is dangerous anyway
On 25 Apr 2016 11:56 a.m., "Jonathan Garbee" <notifications@github.com>
wrote:

If it isn't built into the framework, the only
way that migrations will work would be to have them copied into the
migrations folder.

This is actually a good benefit of the setup. The developers knows exactly
what will run and in what order, no surprises. If you want to abstract it
away, then it should go into your own CMS package that handles running the
migrations for modules.

Same for controllers.

No, you can reference controllers by their namespace in the package when
registering routes. No need to copy them into your app folder.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/laravel/internals/issues/68#issuecomment-214263802>

**Comment by alexbowers** [comment]
It also bloats your system with things you shouldn't change. In your app
directory, you should not have something that isn't your responsibility.
The migration is the responsibility of the module and so shouldn't be
committed in your repository except as a dependency. The order it runs is
still known based on the date that migrations follow. And a developer
should know what runs because they chose that dependency. Choosing a
dependency where you don't understand what it does is dangerous anyway.

**Comment by tomschlick** [comment]
you could just add the functionality to run migrations from folders as well...

like doing `php artisan migrate --with-modules` or `php artisan migrate --module=blog`

there was a PR to create migration tags a few weeks ago but it fizzled out https://github.com/laravel/framework/pull/12569

**Comment by alexbowers** [comment]
I'd say that if migrations can be stored in multiple locations, they must always be ran, not selectively.

If they can selectively be ran, things may not necessarily be in tune with one-another.

Perhaps there is scope for both (eg. By default it runs all, and --with-modules could be --only-modules or --module=blog would only do the blog module).

**Comment by tomschlick** [comment]
I think this is more suited to a plugin. Most apps wouldn't use this level of complexity.

**Comment by alexbowers** [comment]
It could work in a fully backwards compatible way I believe, with little
overhead if not used. But i think it would be a valuable extension to the
framework.

**Comment by deringer** [comment]
Modularity is treading into an app-specific territory, whereas the framework is trying to cater to the greatest number of use-cases. There's already functionality built into the framework to cater for migrations and namespaced controllers.

Publishing the migration to the `migrations` folder from the package, in combination with your `composer.json` dependencies for external packages, should be sufficient in most cases.

**Comment by alexbowers** [comment]
It sounds like we're settling for having the migrations in the migration folder, when it really shouldn't be.

Maybe thats the main thing that needs changing, rather than a full modular structure, is to allow multiple migration folders.

**Comment by tomschlick** [comment]
Thats exactly what that tags branch I posted does. I'm all for adding more customization points into the framework, and then having these types of things hook into them, but I don't think the modularity should be default even as someone who would use it myself.

**Comment by srmklive** [comment]
Personally i am totally against having a modular approach in laravel. I totally agree with @michaeldyrynda comment. I have worked with modular frameworks before such as Zend Framework 1 & code igniter. Suppose you have a ecommerce system in zend framework, you may have the following modules:

* User registration & login.
* Storefront for handling categories, products etc.
* Checkout system for product purchase.
* Payments

In my experience, if a framework supports modules by default, then you should use it then. There is a reason why laravel doesn't have modular structure, and it shouldn't support anyway. 

If you really want to implement a modular like structure. Write your own packages, which implements a service provider. That service provider should load all the routes you define in your package. I would simply define an environment variable **MY_MODULE** in my .env file to enable/disable the package. Then in the **App\Providers\AppServiceProvider**'s register method, i would simply do this:

    if (!empty(env('MY_MODULE')) && env('MY_MODULE'))
        app()->register('MyModule\MyModuleServiceProvider');

**Comment by happyDemon** [comment]
There are packages out there that can help you: 
https://github.com/caffeinated/modules  https://cartalyst.com/manual/extensions/1.2

I also don't think this is needed to come 'out-of-the-box', the majority of projects built using laravel don't require this.

**Comment by vinicius73** [comment]
I have my own approach modules without having to modify the framework. Only with a few adjustments in the folders I apply DDD
https://github.com/vinicius73/laravel-modularized/tree/modularized-5.2/
No major change is required, just some adjustments in the command "make" and Http/Console Kernel.

**Comment by alexbowers** [comment]
This has been merged into 5.3. Closing.
