### ISSUE TITLE
[Proposal] Exit code for migrate:status

### ISSUE THREAD

**Issue by NFarrington** [laravel/internals#689]
The `migrate:status` command (`Illuminate\Database\Console\Migrations\StatusCommand`) currently returns 0 as an exit code under all circumstances.

It would be useful if the command returned a zero/non-zero status code when there are still migration(s) to be run, so that this can be used in deployment scripts. In my use case, if we knew there were no pending migrations, this would mean we would not need to take the application down before running the `migrate` command.

The command could be adapted to only return a non-zero code (when appropriate) if the `--exit-code` flag is used, to maintain backwards compatibility.

Alternatively, a `--pending` flag could be used, which would utilise the non-zero exit code and also return the number of pending migrations to STDOUT.

I would be happy to submit a pull request for this.

**Comment by deleugpn** [comment]
I think you should do it and see what Taylor has to say. It doesn't sound like something that would take too much time to implement.

**Comment by Dylan-DPC** [comment]
@NFarrington you can close this issue as the PR was closed and there is no plans of adding it soon
