### ISSUE TITLE
Support Multiple Machines with Scheduler

### ISSUE THREAD

**Issue by tomschlick** [laravel/internals#69]
Laravel has a great scheduling feature to allow you to manage cron jobs in your codebase, but one of the biggest problem's is when it comes to multiple machines. 

Right now if you have 3 application servers behind a load balancer, you are forced to choose one that will initiate these cron jobs. If that server goes down your cron jobs won't execute. This is especially troublesome when you are using something like an auto-scaling group which can initiate / terminate instances at any time.

My proposal is to allow storing the cron's lock file in the cache (redis, memcached, etc) instead of storing it in the file system only.

That would allow you deploy all of your servers with the same cron configuration and the first server to get to a specific cron job would lock the others out and release when they are done. If a server goes down it's no longer a problem as any other server can pick up the slack and execute the cron jobs.

I started [a pull request for this back in November](https://github.com/laravel/framework/pull/10965) but didn't have time to complete it with the limited free time I had. Before creating a new PR, I wanted to see what everyone else thought about this idea or if there were any better ways to accomplish this.

**Comment by taylorotwell** [comment]
This has been implemented in 5.4.

**Comment by tomschlick** [comment]
❤️

**Comment by Lambik** [comment]
Thanks!

**Comment by lbm-trentm** [comment]
Does anyone happen to know whether this was fixed implicitly, or whether you still need to code for it somehow?

**Comment by tomschlick** [comment]
@lbm-trentm it should "just work" so long as your cache is set to something shared between the servers
