### ISSUE TITLE
[Proposal] Use Hash::make() instead of a direct call to bcrypt in ResetsPasswords.php

### ISSUE THREAD

**Issue by ArondeParon** [laravel/internals#695]
In `ResetsPasswords.php` there is a direct call to `bcrypt` on [line 104](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Auth/ResetsPasswords.php#L104). This in itself is not really a problem since `Hash::make()` acts as a wrapper for `bcrypt`, but would it not be more elegant to use `Hash::make()`, as this is also the [recommended way](https://laravel.com/docs/5.4/hashing) to create password hashes?

**Comment by joshmanders** [comment]
`bcrypt` is a wrapper around `Hash::make()` https://github.com/laravel/framework/blob/698a6356b2aa91cd61f07832330832dcef7d7883/src/Illuminate/Foundation/helpers.php#L183-L195

**Comment by koenhoeijmakers** [comment]
Yes its a wrapper, but given that Argon2 is becoming optional in `php7.2`, calling `bcrypt()` while it actually uses Argon2 is kindof odd (this is the case with my Argon2 package which replaces bcrypt completely), and as a matter of fact, bcrypt isnt really dynamic too, i'm totally for `Hash::make()` everywhere.

**Comment by ArondeParon** [comment]
Oops! Seems I got it backwards. My bad 🤦‍♂️. 

Anyway: I agree with @koenhoeijmakers; using `Hash::make()` does some more consistent and future-proof.

**Comment by browner12** [comment]
wouldn't a solution just be to rename the `bcrypt` helper to something more generic?

I don't think this is really a future proofing issue, but rather simply a semantic one.

**Comment by m1guelpf** [comment]
@browner12 Renaming the bcrypt() helper would be "VERY" breaking...

**Comment by browner12** [comment]
yup, would definitely have to go to master. But as we all know, bcrypt won't be around forever, so abstracting the name to something generic will help put it in line with how Hash:make works.

**Comment by m1guelpf** [comment]
Opened https://github.com/laravel/framework/issues/20155, but I don't have hope with this one...

**Comment by Dylan-DPC** [comment]
@ArondeParon you can close this issue as the PR is merged for 5.5
