### ISSUE TITLE
make:factory inconsistent with other make-related commands

### ISSUE THREAD

**Issue by svenluijten** [laravel/internals#696]
## Expected result
Running `php artisan make:factory PostFactory` should create a class named `database/factories/PostFactory.php` without any typehints and/or boilerplate, just like a `make:controller` call without any other options set:

```php
$factory->define('App\Model', function (Faker $faker) {
    return [
        //
    ];
});
```

The `'App\Model'` is similar to the boilerplate in the `AuthServiceProvider`'s `$policies` property.

## Actual result
Running `php artisan make:factory PostFactory` results in `database/factories/PostFactoryFactory.php` being created, with typehints for `App\PostFactory` in the factory definition:

```php
$factory->define(App\PostFactory::class, function (Faker $faker) {
    return [
        //
    ];
});
```

## In closing
A nice addition to the proposed change would be a `--model` flag, which *would* automatically insert the typehints for the right model. So `php artisan make:factory PostFactory --model=App\Post` would generate the following: 

```php
$factory->define(App\Post::class, function (Faker $faker) {
    return [
        //
    ];
});
```

This would be more in line with the current `make:*` commands (like `php artisan make:controller` and `php artisan make:model`), allowing developers to expect the command(s) to have a similar outcome.

**Comment by deleugpn** [comment]
Should not be a hard PR

**Comment by svenluijten** [comment]
@deleugpn Indeed, but I wanted to gather some feedback before getting into it 🙂

**Comment by svenluijten** [comment]
Appears to have already been fixed & tagged with https://github.com/illuminate/database/commit/34b82ed8294f39a69128f0ab84db7a1dc7b35925!

**Comment by adaugochi** [comment]
Command "make:factory" is not defined

i got the above command while trying to  run this 

php artisan make:factory ArticleFactory
--

please i need help
