### ISSUE TITLE
Allow multiple formats for Eloquent dates

### ISSUE THREAD

**Issue by kohenkatz** [laravel/internals#699]
Right now, Eloquent uses a default format for changing SQL `TIMESTAMP` columns into Carbon objects.

That format is database driver dependent, unless the user has overridden it on the model by setting `$this->dateFormat`.

One good example of when this format needs to be changed is when using PostgreSQL `TIMESTAMP WITH TIME ZONE` columns. The default format (for all databases except one) is `Y-m-d H:i:s`. However, the default format for PostgreSQL `WITH TIME ZONE` columns is `Y-m-d H:i:se` (the `e` is for the timezone).

The problem is that we have situations in which a model might have multiple `TIMESTAMP` columns, some with time zones and some without.  Right now, there is no mechanism for handling such a setup.

I propose that we extend the `protected $dates` field of Eloquent to support per-column formats.

For example (from an actual model we want to use):

```
protected $dates = [
	'created_at',
	'updated_at',
	'deleted_at',
	'expires_at' => 'Y-m-d H:i:se',
	'completed_at' => 'Y-m-d H:i:se',
];
```

The columns with no custom value will use the default.

I can do a PR for this, but I wanted to talk about it first.

**Comment by timacdonald** [comment]
Bit of discussion around this kinda thing happening here: https://github.com/laravel/internals/issues/669 | https://github.com/laravel/internals/issues/630

**Comment by kohenkatz** [comment]
Something wrong with GitHub issues search. I got no results yesterday when I searched this project for `eloquent dates`.
