### ISSUE TITLE
Post the output of a completed job to a URL

### ISSUE THREAD

**Issue by fitztrev** [laravel/internals#7]
Currently, `->thenPing($url)` just does a GET request to a URL you specify to let you know the scheduled command has run.

Either modifying it to support POSTs or creating a new method like `->thenPost($url)` would allow you to send the output to another application for further processing.

For example, you could have your Laravel app send the POST request to Zapier which then formats it and could pass it along to any number of services (Slack, Google Docs, etc).

**Comment by pafelin** [comment]
This can be simply a trait. 
Personally don't see lots of usage but maybe it is nice to have

**Comment by Mevrael** [comment]
Hardcoding GET is not the best option anyway. Giving flexibility to set method and data would be a better approach, i.e. `->thenPing($url, $method = 'HEAD', $data = [])`. I also would recommend HEAD instead of GET by default. If it's ping no1 cares about response body.

**Comment by bobsta63** [comment]
+1 for HEAD (by default) instead of GET!

**Comment by fitztrev** [comment]
Closing in favor of [Notifications](https://laravel.com/docs/master/notifications)
