### ISSUE TITLE
Make @yield Support Prefix

### ISSUE THREAD

**Issue by meness** [laravel/internals#703]
Hi friends,

It's good to make `@yield` blade directive support prefix. Prefixes are useful in the following scenario: **Web pages titles**

```blade
<!-- parent layout -->
<title>Laravel - @yield('subtitle')</title> <!-- note a dash character already exists there -->
```

```blade
<!-- child layout -->
@section('subtitle','Welcome!')
```

This works well because dash character in the title already exists, but some pages don't need a subtitle, so a dash character would exist in the title (and this is the problem).

The solution is, make `@yield` support prefix and use that prefix if any value for the `@yield` provided.

**Comment by lk77** [comment]
Why you do not pass the prefix with the value then ?

**Comment by meness** [comment]
@lk77 I can do that but it's weird to me! I think it's not a good solution.

**Comment by lk77** [comment]
i don't think it's a good solution to change yield behaviour to include prefix, for me it's not the purpose of this directive, for me yield are just placeholders, that can be filled with some data, i don't see the point of prefixing those data.

You can add the prefix before the yield, in the default value or in the value, and it's works, so i dont see the problem.
