### ISSUE TITLE
[Proposal] `date_equals` validation rule

### ISSUE THREAD

**Issue by huntie** [laravel/internals#707]
### Background

It would be useful to have a validation rule to check that an attribute value is equal to a given date. Use cases include requiring a match with the current date, or ensuring that the date value is unchanged in the context of a record.

Currently, the `between:min,max` rule is the best built-in way to do this that I can see. Using `in:date` won't work if the submitted date format differs.

#### New rule

The new rule would accept a single parameter and perform a simple `strtotime` comparison similar to the other date validation methods.

```
'data.attributes.date' => 'date|date_equals:' . $date,
```

#### Extend `date`

Alternatively, this could be implemented as an extension of the current `date` rule by implementing an optional parameter, which would look like so.

```
'data.attributes.date' => 'date:today',
```

Let me know and I'll be happy to implement this :)

**Comment by Dylan-DPC** [comment]
@huntie this issue can be closed since the PR has been merged

**Comment by huntie** [comment]
@Dylan-DPC Ah wow, awesome :D
