### ISSUE TITLE
Common route interface for Laravel and Lumen

### ISSUE THREAD

**Issue by yuloh** [laravel/internals#71]
Laravel and Lumen both use `Illuminate\Http\Request`, which expects a route object.  Right now Lumen uses an array for the current route, since that is what is used by fast route internally.  This has caused a couple of issues for users of Lumen:

https://github.com/laravel/lumen-framework/issues/291
https://github.com/laravel/lumen-framework/issues/348
https://github.com/laravel/lumen-framework/issues/484

You can see the code that expects a route object in the request class here:

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Http/Request.php#L894
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Http/Request.php#L912

I propose we come up with a simple interface that both frameworks can use, and replace the Lumen array with an object.  As far as I can tell, this interface should solve the issues with the Request class:

``` php
interface Route
{
    public function parameter($name, $default = null);
    public function methods();
    public function domain();
    public function uri();
}
```

This would also make the current route more useful in Lumen.  Right now you can only get the handler and an array of parameters; you can't get the uri or the methods.

**Comment by yuloh** [comment]
@taylorotwell is this something you would accept a PR for?

**Comment by taylorotwell** [comment]
The two frameworks are not meant to be 100% compatible.
