### ISSUE TITLE
SoftDeletes in pivot tables

### ISSUE THREAD

**Issue by gabriel-caruso** [laravel/internals#725]
Hello, folks. This is more a question than a proposal (or maybe this can become a proposal).

Recently I need to work with softDeletes in a pivot table. I need to add some `wherePivot('delete_at', null)` for querying not trashed records, and `wherePivot('delete_at', '<>', null)` for trashed ones. Then, I realize Laravel has a `Illuminate\Database\Eloquent\Relations\Pivot` class. 

Will be more easy to create a pivot model and extend that class, to work with softDeleting, or this is the best way, querying the related models of this pivot?

**Comment by markwalet** [comment]
A generic solution for this is a really good feature request.
