### ISSUE TITLE
Redesign Laravel csrf protection 

### ISSUE THREAD

**Issue by bittenApple** [laravel/internals#73]
## This is moved from Laravel repo

We use Laravel 5.1 and Redis as our session drive on our production environment, and have randomly came up withTokenMismatchException over last two months, which made us very annoyed.
I know this is a known issue which hasn't been fixed yet, because of session persistence bug. So I refer [Django's solution](https://github.com/django/django/blob/master/django/middleware/csrf.py) to rewrite the csrf middleware, just compare the token in cookie and request header, avoiding dependency with laravel session. It works fine now.
This bypasses the session bug but could be a temporal solution to help people who need csrf protection.

**Comment by valorin** [comment]
Correct me if I'm wrong, but wouldn't comparing the token from the cookie and the request header simply mean you're comparing two pieces of user-provided data together? Meaning it's trivial to bypass.

The point of storing it in the session is so you compare the user-provided data with the expected server-side data.

**Comment by bittenApple** [comment]
> Cross-Site Request Forgery (CSRF) is a type of attack that occurs when a malicious Web site, email, blog, instant message, or program causes a user’s Web browser to perform an unwanted action on a trusted site for which the user is currently authenticated. 

The attacker cannot read value of the cookie and set it to header due to the same-origin policy, so this protection works. If the attacker could get user's cookie, the token based on session method is also insecure.

**Comment by Garbee** [comment]
Any MiTM attack will be able to handle forging this. Sessions are a
necessity here to do things properly. IMO the solution here isn't in
Laravel's corner but instead in application developers to architect their
systems properly.

Based on the information provided, there is no way to tell where the issue
truly lies. You assert it is in session handling but provide no evidence of
this. However, this isn't a support channel so for more help on figuring
out how you can restructure your application to work better, or finding the
actual bug, use the Laravel forums or stackoverflow.

**Comment by bittenApple** [comment]
> You assert it is in session handling but provide no evidence of
> this.
FYI https://github.com/laravel/framework/issues/8172

**Comment by Garbee** [comment]
Without a test-case to reproduce the problem the asserted fact that Laravel has a problem is only a theory. Any number of things could be the cause of that bug and clearly there isn't enough information available to determine where it is coming from.

**Comment by denjaland** [comment]
hmm - I've come across quite some issues now with the session handling.
At this point, the session issue is becoming such an issue that it might be the showstopper for us when it comes to using Laravel, which would be such a pity, because we absolutely love working with Laravel.

Can https://github.com/laravel/framework/issues/18187 contribute to this?
