### ISSUE TITLE
Move to Bootstrap 4

### ISSUE THREAD

**Issue by m1guelpf** [laravel/internals#730]
The Bootstrap v4 beta just launched!
How about moving from Bootstrap 3 to Bootstrap 4?

**Comment by ntzm** [comment]
Why not wait until it's stable first 😄

**Comment by NowNewStart** [comment]
They just released the beta after 2 years of alpha, who knows when Bootstrap stable comes out

**Comment by sisve** [comment]
It seems like it has been done. Bootstrap is still in beta. https://github.com/laravel/internals/issues/730

**Comment by markwalet** [comment]
Hmm weird. Anyway. I think we can close this issue
