### ISSUE TITLE
DB pre-transaction hook

### ISSUE THREAD

**Issue by OzairP** [laravel/internals#733]
### Description:
This is more for discussion; but what are thoughts on having a database hook that is called before the query is called. This could be useful for caching database calls that are called from third party libraries or global caching queries.

Not sure how this could be incorporated or designed within the system but this is an example I was thinking of.

```PHP
function(Builder $builder) {
    if(Cache::has($builder->getQuery()->toSql()) {
        return Cache::get($builder->getQuery()->toSql());
    }
}
```

If the function returns null, continue with the transaction.

**Comment by sisve** [comment]
The issue title says pre-transaction, but you're talking about a query event that can replace the execution of a query, and an after-query event that can update the cache with the value. You would also need events on every update/insert to keep the cache up-to-date, and that alone will not be enough.

Your two use-cases are weird.
1. Third party libraries needs to be up dated to support caching. It's harder than just returning a cached response, there could have been outside changes that needs to be read. There's no one-solution-fits-all scenario here.
2. Global caching is evil. Assuming you're implementing this with your example code; this will not work with queries that aren't idempotent. It will not reliably work with idempotent queries either.

Caching is hard. Keeping a cache up-to-date is hard.

Also, when you think you got it all worked out ... then soft-deletes and the deleted_at column starts haunting you.
