### ISSUE TITLE
Tests for the auth:make command

### ISSUE THREAD

**Issue by DCzajkowski** [laravel/internals#734]
## Description
When a `php artisan make:auth` command is ran, there are no tests being added. That is pretty scary for people, who use TDD all the way, and most of them don't even use the `auth:make` command for this very reason.

## Proposition
My proposition is to add [stubs](https://github.com/laravel/framework/tree/master/src/Illuminate/Auth/Console/stubs/make) for the next Laravel release with the tests for authentication routes.

## Implementation
I went ahead and created four feature tests that should do the job. They will change in a course of a few weeks. I'll make a PR to the [framework](https://github.com/laravel/framework) when they are done, hopefully before final 5.5 release. They are [here](https://github.com/DCzajkowski/auth-tests/tree/master/tests/Feature/Auth), in a fresh Laravel 5.5 installation with just `php artisan make:auth` ran.

The tests are in very early stages and any help is highly appreciated. PRs are more than welcome.

**Comment by drbyte** [comment]
Linking https://github.com/laravel/internals/issues/658

**Comment by DCzajkowski** [comment]
Good to know :)

**Comment by DCzajkowski** [comment]
I have made a PR here: https://github.com/laravel/framework/pull/20562

**Comment by DCzajkowski** [comment]
The tests are available in my package here: https://github.com/DCzajkowski/auth-tests :)
