### ISSUE TITLE
Laravel 5.5 Automatic package discovery and conditional packages loading

### ISSUE THREAD

**Issue by ruijsdev** [laravel/internals#736]
Hi.
Laravel 5.5 will allow one to just add a package (if the package is updated with the extra section in its composer.json file) and forget about register service providers and aliases in ```app/config.php``` .

Take a look at the Laravel Debugbar package which has already been updated for package autodiscovery.

The package is now registered for both local and production (```bootstrap/cache/packages.php```)
How can I register the package provider for local environment only? This package is not needed in production and I can name a bunch of "development packages" : 
barryvdh/ide-helper
appstract/laravel-tracer
laravel/dusk.

With Laravel 5.4.x one can load development packages only in the register method of ```app/Providers/AppServiceProvider.php```

```
if ($this->app->environment('local')) {
    $this->app->register(\Barryvdh\Debugbar\ServiceProvider::class);
    ...
}
```

Is there a way to solve this issue in L5.5?

Cheers

**Comment by decadence** [comment]
https://getcomposer.org/doc/04-schema.md#require-dev

**Comment by ruijsdev** [comment]
Thanks, @decadence.
That's the way I require development packages.
I need to add ```php artisan package:discover``` to the deploy script.

Cheers
