### ISSUE TITLE
Implementing the Macroable trait on RouteRegistrar 

### ISSUE THREAD

**Issue by dbonner1987** [laravel/internals#741]
Whilst experimenting with Route macros I came across a user case in which I need to get various attributes from the route. Unfortunately because the Macroable trait exists on the Router object and not RouteRegistrar this isn't possible. 

I would like to propose adding Macroable to the RouteRegistrar class. Happy to submit the PR if acceptable?

```php
<?php

namespace Laravel\Passport;

use Illuminate\Support\Traits\Macroable;
use Illuminate\Contracts\Routing\Registrar as Router;

class RouteRegistrar
{
    use Macroable;

    //
}
```

Many thanks

**Comment by joshmanders** [comment]
What's a usecase of this?

**Comment by dbonner1987** [comment]
For instance, in an attempt to contribute to https://github.com/tightenco/ziggy and implement the filter feature using a macro instead of a config file, I require the name to be able to add it to a list of blacklisted routes (https://twitter.com/dbonner1987/status/897861212167426051)

Currently the hacky workaround is: 
```php
Route::macro('blacklist', function ($routes) {
    collect(array_wrap($routes))->each(function ($route) {
        $blacklist = array_merge(
            config('ziggy.blacklist', []), [$route->getName()]
        );

        config()->set('ziggy.blacklist', $blacklist);
    });
});

// Use case
Route::blacklist(
    Route::name('posts.index')->get('/posts', 'PostsController@index')
);
```

However it would be much more preferable to do this:
```php
Route::macro('blacklist', function () {
    config()->set('ziggy.blacklist', array_merge(
        config('ziggy.blacklist', []), [$this->attributes['name']]
    ));
});

// Use case
Route::name('posts.index')->get('/posts', 'PostsController@index')->blacklist();
```

This is untested, only starting to look at the best way to implement something that allows interaction of route attributes during the registration of the route.

**Comment by dbonner1987** [comment]
Please ignore this for the time being. Working on something a little different – RouteRegistrar is the wrong place for this.

**Comment by sebastiaanluca** [comment]
Can we reopen this? I could use a macroable `\Illuminate\Routing\Route` class. Being able to add your own route methods is a good feature to have anyhow.

For example the follow shorthand way to add middleware (and other useful use cases):

```php
Route::macro('permit', function (...$permissions) {
    $permissions = join('|', $permissions);

    $this->middleware("permission:$permissions");

    return $this;
});
```

**Comment by mikerockett** [comment]
In the meantime, I've resorted to a single macro that handles both cases. Works of course, but would eventually like to revert back to the chained approach.
