### ISSUE TITLE
[Question] Glyphicons pre-installed?

### ISSUE THREAD

**Issue by balping** [laravel/internals#745]
Is there a reason why glyphicon fonts are not included in `public/fonts` by default?

They [used to be there](https://github.com/laravel/laravel/tree/5.0/public/fonts) in 5.0, but in later versions they have been excluded. ([This](https://github.com/laravel/laravel/commit/5e11f87de2c8f9303e6e296d74ec5f7f2093fd9b) was the particular commit of removal.)

Since JS and CSS mix builds are shipping with laravel, it would be logical to include these font files too. As they are produced by the default mix build.

But these might be intentionally excluded from `public/fonts/vendor/bootstrap-sass/bootstrap`.  If it is intentional indeed, then what's the reason behind it?

**Comment by sisve** [comment]
The linked issue in laravel/laravel was closed with an answer. I believe you can close this issue.
