### ISSUE TITLE
Custom queue failed job drivers

### ISSUE THREAD

**Issue by gmsantos** [laravel/internals#751]
Currently only Database or Null failed jobs are supported by Laravel.

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Queue/QueueServiceProvider.php#L189-L203

It's not easy to create a custom failed jobs, considering that not everyone is using a relational database with Laravel. An example is how [jenssegers/laravel-mongodb](https://github.com/jenssegers/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/MongodbQueueServiceProvider.php) tries to solve this issue.

Since Laravel already has an [interface for Failed Job](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Queue/Failed/FailedJobProviderInterface.php), I suggest to make a driver-like configuration for failed jobs:

```
    /*
    |--------------------------------------------------------------------------
    | Failed Queue Jobs
    |--------------------------------------------------------------------------
    |
    | These options configure the behavior of failed queue job logging 
    | so you can control which database and table are used to 
    | store the jobs that have failed.
    |
    | Supported: "database", "null"
    |
    */
    'failed' => [
        'driver' => env('QUEUE_FAILED_DRIVER', 'database'),

        'database' => [
            'connection' => env('DB_CONNECTION', 'mysql'),
            'table' => 'failed_jobs',
        ],
    ],
```

**Comment by gmsantos** [comment]
ping @jenssegers

**Comment by gmsantos** [comment]
Any thoughts @taylorotwell?

**Comment by themsaid** [comment]
You can override the `queue.failer` container alias and swap it with an implementation of `FailedJobProviderInterface` which will allow you to write your own failer.

**Comment by gmsantos** [comment]
Yes @themsaid, I know that is possible to override `queue.failer`, but I wish to know if I making some steps further and make this configurable is something desirable to be in Laravel core.

**Comment by sisve** [comment]
Just write a PR, explain why your solution is so good that you should break every existing failed-jobs configuration section in existance, submit and check the response. It's not like you're suggesting a large refactoring of the queue system, it's just a breaking change in the configuration.

**Comment by gmsantos** [comment]
I just don't want to waste time if its not gonna be accepted anyway

**Comment by aik099** [comment]
I'm also wondering why in contributing docs PR are preferred to just issues reports, but some PRs are closed soon after being submitted. It's faster to report issue and send PR only one agreed that any code changes made would be accepted.

**Comment by taylorotwell** [comment]
If you have a feature request you don't want to spend time on without it being accepted. You should mention @themsaid in the thread and ask him to triage the issue to me for an approval.
