### ISSUE TITLE
Add a function to the Request class

### ISSUE THREAD

**Issue by NGT-11** [laravel/internals#753]
I'm in a case where I won't use the fullUrl method on the request class but a "fullPath" instead.

For example, if my url is :
`https://mywebsite.com/page?key=value`

`Request::path()` will return `page`
`Request::url()` will return `https://mywebsite.com/page`
and `Request::fullUrl()` will return `https://mywebsite.com/page?key=value`

but what I want is to have in return : `/page?key=value`

That could be simply done by using str_replace like that :
```php
echo str_replace(Request::root(), '', Request::fullUrl());
```
or with a new function who will do the same as follow :
```php
$path = Request::getPathInfo();
if ($query = Request::getQueryString())
    $path .= '?' . $query;
echo $path;
```

If it is accepted I could do a PR on the Request class

**Comment by NGT-11** [comment]
@taylorotwell why do you think about that ? should I do a PR to add a new method ?

**Comment by sisve** [comment]
How does this differ from `$request->getRequestUri()`?

**Comment by NGT-11** [comment]
I have searched in the symfony Request class and in the laravel Request class for almost 1 hour without finding a method to do what I wanted, thanks @sisve
