### ISSUE TITLE
Delete expired sessions via Schedule

### ISSUE THREAD

**Issue by aik099** [laravel/internals#758]
Right now expired sessions are deleted from database using lottery from config. This can result in 2 problems:

1. if website was visited, but isn't now, then expired sessions aren't deleted
2. if website is visited a lot, then some of user visits might experience slow down because sessions are scheduled to be deleted before response is sent to user (the `\Illuminate\Session\Middleware\StartSession::collectGarbage` method call in `\Illuminate\Session\Middleware\StartSession::handle` method)

Proposing to:

1. make this behavior configurable
2. add scheduled command (with configurable schedule) to delete expired sessions

**Comment by themsaid** [comment]
Thank you for your suggestion, but looks like not enough members are interested in such change so I'm going to close this issue.

**Comment by CupOfTea696** [comment]
@aik099 this seems like something you could just create a PR for, and Taylor will probably approve.

**Comment by heathdutton** [comment]
I like the idea of a PR for this. At high volume (2.5k or more) concurrent users the collectGarbage command causes one user out of the lottery to have a slow page load. These spikes are highly visible in tools like NewRelic at scale. Reducing the lottery makes the spikes less frequent but taller. Best solution would be an optional scheduler to offload GC to the backend.
