### ISSUE TITLE
New Feature for Seeding Database in production

### ISSUE THREAD

**Issue by ARKKYN** [laravel/internals#760]
I use laravel for couple of projects i always use .sql dump or  Migration file to add data to database.
I use Db seeder in dev for some times

If db seeder is featured like migrations for production environment then it would be more usefull to dump app data for app usage

**Comment by sisve** [comment]
What do you want to change? You can already run seeders in an production environment.

**Comment by ARKKYN** [comment]
we can but there is a danger of running again
@sisve

**Comment by sisve** [comment]
So write your seeders so they only create-or-update-existing data, not blindly create new data.

**Comment by ARKKYN** [comment]
i tried it, and I wanted this to be hassle free so i requested for a new feature, so it might reduce code

**Comment by Dylan-DPC** [comment]
I agree with @sisve on this. If you don't want to use DB seeders just write your own command that seeds the database and then delete the command so nobody can reexecute it

**Comment by sebastiandedeyne** [comment]
When I need to seed data to production exactly once, I call it from a migration. No need to introduce a new concept imo.

**Comment by mnabialek** [comment]
I also think it's not necessary. When I want to add some data into production (for example invoice types, some units and so on) I use migrations for this purpose.
