### ISSUE TITLE
Allow changing the view after a view is constructed

### ISSUE THREAD

**Issue by axyr** [laravel/internals#761]
### Usecase
Overriding a Controller, only to have different views.

```php
class InterviewController extends AdminController
{
    public function index(InterviewCandidateFilter $filters)
    {
        return parent::index($filters)->setView('admin.standalone.interviews.index');
    }
}
```

The parent controller handles the authorization, gather all the required view data and the same goes for show() and edit(). All the store, update and destroy remains the same.

This will not work, since setView does not exist. We can make it work like this like : 

```php
class InterviewController extends AdminController
{
    public function index(InterviewCandidateFilter $filters)
    {
        $view = parent::index($filters);
        $view->setPath(resource_path('views/admin/standalone/interviews/index.blade.php'));
        return $view;
    }
}
```

It's not bad, but as pretty I would like to..

Now to make the first example to work, a new method setView need to be added to `Illuminate\View\View`
like : 

```php
public function setView($view)
{
    $this->path = $this->factory->getFinder()->find(
        $this->view = $this->factory->normalizeName($view)
    );

    return $this;
}
```

and the`normalizeName` method on `Illuminate\View\Factory` needs to be changed to public.

Not sure if I am talking about an edge case here, but I would assume it would be easier to change a template after a view is instantiated then assembling the absolute path to a template myself.

Before creating a PR, I would like to see some opinions about this.

**Comment by themsaid** [comment]
Thank you for your suggestion, but looks like not enough members are interested in such change so I'm going to close this issue.
