### ISSUE TITLE
IP-based filter on "app.debug" setting

### ISSUE THREAD

**Issue by aik099** [laravel/internals#766]
Right now the `app.debug` config setting value is specified in the `.env` file. It is perfectly fine for development/staging servers to have debug mode always turned on. However on production websites you likely want to enable it dynamically only for developers.

Proposing to add `app.debug_ips` config setting, that would:

* fallback to `APP_DEBUG_IPS` env setting from `.env` file
* contain comma-separated list of: ip (xxx.xxx.xxx.xxx), subnets (xxx.xxx.xxx.xxx/xxx), ip ranges (xxx.xxx.xxx.xxx-xxx.xxx.xxx.xxx), hostnames (www.google.com)

Then IP address from Web Request is matched (keep in mind Symfony Request trusted ips from proxies) and if not matched then `app.debug` setting is set to `false` automatically.

**Comment by Dylan-DPC** [comment]
I don't think that's a good idea to have in the framework. An IP can be spoofed. If you need it, you can implement in a package that does this

**Comment by laurencei** [comment]
You can even just create a middleware that handles it

**Comment by wangta69** [comment]
coinfig/app.php

$local_debug = isset($_SERVER['REMOTE_ADDR']) ?  in_array($_SERVER['REMOTE_ADDR'], array('what you want ip')): false;

return [
................................
'debug' => $local_debug,
...............................
]

**Comment by sisve** [comment]
@wangta69 That would not work if you use cached configuration files, which is usually done in production.

**Comment by DevCentre** [comment]
A cleanest way would be:

'debug' => env('APP_DEBUG', getenv('REMOTE_ADDR') == '10.61.228.82' ? true : false)

But as sisve mentioned, it will not work with config:cache…
