### ISSUE TITLE
Automatically create missing plain text Mailable version from html

### ISSUE THREAD

**Issue by aik099** [laravel/internals#767]
Right now, when using Mailable and a `->view('view_for_html');` call the HTML version of email is populated, but plain text version stays empty. Instead of a need to manually create 2 views for each email I'm proposing at view rendering stage (the `\Illuminate\Mail\Mailer::addContent` method) in case of missing plain text email version automatically generated it from html version by doing this:

1. replace `<br/>` with `\n` (avoid any trailing `\n` in the process)
2. remove all HTML tags

**Comment by themsaid** [comment]
Thank you for your suggestion, but looks like not enough members are interested in such change so I'm going to close this issue.

**Comment by krtcom** [comment]
This could actually be a very useful feature. When sending notofications emails or any other type of emails we detected that some antispam software detect emails without plaintext, or with plaintext that is noticeably different than html email.

Example of SpamAssassin checks: 
```
MIME_HTML_ONLY=0.723
MIME_HTML_MOSTLY=0.428, MPART_ALT_DIFF=0.79
```
Having this feature was required for a project we are working on. Creating 2 separate views for every email was not a way for us so I forked and updated laravel codce with proposed functionality. 
If there is a will I can submit a pull request.

**Comment by kw-pr** [comment]
@krtcom I think that would be a nice feature to have.
It would be nice if you can make a push request.

Note: I am in no position to merge your PR but I do like to see this feature in laravel.

**Comment by krtcom** [comment]
Actually I found some solution without modifying laravel code: In our class that extends `Mailable` we add this code to `build` method if automatic plaintext is needed:

```
$htmlContent = Container::getInstance()->make('mailer')
        ->render($this->buildView(), $this->buildViewData());

$this->withSwiftMessage(function ($message) use ($htmlContent) {
    $plainContent = Html2Text::convert($htmlContent, true);
    $message->addPart($plainContent, 'text/plain');
});
```

`Html2Text` comes [from here](https://github.com/soundasleep/html2text)
If I understand laravel code there is one disadvantage: it makes your mail view render twice but for me it was barely noticeable.
