### ISSUE TITLE
ability to change errors folder path

### ISSUE THREAD

**Issue by hierarchy-id** [laravel/internals#77]
laravel create errors folder in

```
resources->views->errors
```

how to change this ?

**Comment by vlakoff** [comment]
The `errors` subdirectory appears to be hardcoded, see [`Exceptions\Handler::renderHttpException()`](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Exceptions/Handler.php).

However, you can add custom view root directories in `config/view.php`.
