### ISSUE TITLE
[5.5] Auto registered commands are missing when calling all() method on Foundation\Console\Kernel

### ISSUE THREAD

**Issue by roshangautam** [laravel/internals#770]
### Scenario 
Resolve `Contracts\Console\Kernel` through IOC and try to call all() method to get a list of all registered artisan commands

### Problem
all() method on `Foundation\Console\Kernel` is not returning auto registered commands.

### Analysis
unlike the call() method which makes a call to commands() method to make sure all commands are loaded, all() method doesn't do any such thing

```
    public function call($command, array $parameters = [], $outputBuffer = null)
    {
        $this->bootstrap();

        if (! $this->commandsLoaded) {
            $this->commands();

            $this->commandsLoaded = true;
        }

        return $this->getArtisan()->call($command, $parameters, $outputBuffer);
    }
```

all() method is missing the logic to make sure all commands have been loaded

```
    public function all()
    {
        $this->bootstrap();
    
        return $this->getArtisan()->all();
    }
```

The reason being a call to load(__DIR__.'\Commands') in app/Console/Kernel.php

### Possible Solutions

1. Modify all() method to include the logic (of making sure that all commands have been loaded) as follows:

```
    public function all()
    {
        $this->bootstrap();
    
        if (! $this->commandsLoaded) {
            $this->commands();

            $this->commandsLoaded = true;
        }

        return $this->getArtisan()->all();
    }
```

--- OR ---

2. Move the logic (of making sure that all commands have been loaded) to bootstrap method and remove it from every other method which already calls bootstrap

```
    public function bootstrap()
    {
        if (! $this->app->hasBeenBootstrapped()) {
            $this->app->bootstrapWith($this->bootstrappers());
        }

        // If we are calling an arbitrary command from within the application, we'll load
        // all of the available deferred providers which will make all of the commands
        // available to an application. Otherwise the command will not be available.
        $this->app->loadDeferredProviders();

        if (! $this->commandsLoaded) {
            $this->commands();

            $this->commandsLoaded = true;
        }
    }
```

**Comment by m1guelpf** [comment]
ping @themsaid as this seems to be a bug rather than a feature suggestion.

**Comment by themsaid** [comment]
https://github.com/laravel/framework/pull/20863 Worked on that, thanks :)

**Comment by m1guelpf** [comment]
@roshangautam The PR was merged, this issue can be closed.

**Comment by roshangautam** [comment]
Thanks guys.
