### ISSUE TITLE
[Proposal] 5.6 uses PHP 7 scalar and return type

### ISSUE THREAD

**Issue by gabriel-caruso** [laravel/internals#771]
As we now have Laravel 5.5 with PHP 7, why not to use [scalar type](https://secure.php.net/manual/en/migration70.new-features.php#migration70.new-features.scalar-type-declarations) and [return type](https://secure.php.net/manual/en/migration70.new-features.php#migration70.new-features.return-type-declarations) in Laravel 5.6? Would not be more secure?

Futter more, it would not simplify some code, like: `(string) $name` became just `$name`, as the PHP take care to just receive a `string`?

**Comment by brayniverse** [comment]
Make some pull requests where you see fit, however, Taylor and some other prominent Laravel community members prefer the flexibility loosely typed methods allows. If I recall correctly, strict typing has been countered with the argument "It's just changing the error message you see". That's not to say strict typing is wrong, I'm just warning you that I think it's unlikely to be merged unless it adds a notable benefit.

**Comment by sisve** [comment]
And if we're ignoring if type-hints are preferable; this would still be a gazzillion (slightly over estimated number) changed method signatures, which is a large amount of breaking changes. Every implementation/override of that method needs to change. This makes it hard to write packages that target both versions of Laravel, you would need separate classes for everything.

Assuming that we've initially created a `method($value)`, and then change the signature to `method(string $value): string`, then my existing and previously working code will fail.

> Fatal error: Declaration of Derived::method($value) must be compatible with Base::method(string $value): string in /in/3cLts on line 13

**Comment by RemiCollin** [comment]
@sisve : good point, even as a pro typehinting myself as think it makes our code more robust, all this potential BC makes it hard to consider before a 6.0 release.

**Comment by Dylan-DPC** [comment]
@RemiCollin 
> all this potential BC makes it hard to consider before a 6.0 release.

Laravel doesn't follow semver so it is "fine" to introduce a BC in any of the releases. 

The point is the core team doesn't want it and this discussion has come up a lot of times earlier.

**Comment by RemiCollin** [comment]
I know. Still the less BC the better, but I assume your use of quotes for "fine" is speaking for itself ;)

**Comment by gabriel-caruso** [comment]
I've seen your points @brayniverse @sisve and @RemiCollin, thanks about it.

@sisve I think you undertood that I want to use in every where, in every class, every pattern, etc. Actually no, just in simple ones, like `Helpers`.

My ideia was to first introduce this in `Helpers`, we use them every day, every where in Laravel Framework, and see the benefits and disbenefits of this implementation.
