### ISSUE TITLE
[proposal] JS Component Generator

### ISSUE THREAD

**Issue by JayteeNZ** [laravel/internals#774]
Ideas:

- Generate Vue/React/Angular components via Artisan using a bunch of commands
- Generate Vue/React/Angular components using NPM commands

I'll go through it in depth. I was watching one of @JeffreyWay 's forum videos and noticed that he was manually creating Vue components. Usually he'll either generate files from the terminal or use a plugin.

What if there was an official package such as Laravel Sketch (crappy name, just an example) where you have a set of commands to run in the terminal to generate component files for your projects?

@bycedric from the Laravel Slack chat, mentioned about possibly baking it into the preset command.

Once a command has been executed, the idea is it'll give you the basic boilerplate just like any artisan make command, only for that specific JS framework. To go further, perhaps it could determine whether you wanted to register it globally or within a certain parent component.

Thoughts/Ideas ?

**Comment by Dylan-DPC** [comment]
I don't see why this should be in framework. Also each of the front-end frameworks have good cli tools (like vue-cli). You could create your own package that does it if needed.

**Comment by brunogaspar** [comment]
As @Dylan-DPC mentioned, this is best suited for an external package.

For Vue, you have laravel-vue-generators already.

**Comment by Dylan-DPC** [comment]
@JayteeNZ this issue can be closed. I don't see it being implemented.
