### ISSUE TITLE
Implement Server Sent Event with Laravel

### ISSUE THREAD

**Issue by lkmadushan** [laravel/internals#776]
https://www.w3schools.com/html/html5_serversentevents.asp
https://www.html5rocks.com/en/tutorials/eventsource/basics/

What do you think about this?

**Comment by m1guelpf** [comment]
Isn't this what Laravel Echo is about?

**Comment by lkmadushan** [comment]
Laravel echo does two way communication and SSE does one way (Server to Client) communication. Echo is great for more complex scenarios and SSE is useful for simple things like voting systems, realtime news updates. We don't need Redis or Pusher for this.

**Comment by Dylan-DPC** [comment]
How else will you send events without listening to web sockets?

**Comment by lkmadushan** [comment]
it's over http, we don't need web sockets. you can get more information from those articles.

it would be great if we can implement this into Laravel core we don't need websockets sometimes.

**Comment by crynobone** [comment]
It's already possible with what's available on Laravel at the moment.

**Comment by ariaenggar** [comment]
> 
> 
> It's already possible with what's available on Laravel at the moment.

What is "what's available on Laravel" you mentioned about?

**Comment by crynobone** [comment]
1. You can already use Symfony stream response.
2. Disable output buffering is possible with nginx, should be possible with other web server.

So what's preventing you to do it now?

**Comment by badpaybad** [comment]
https://github.com/badpaybad/sse_intergrated_with_laravel here you go
