### ISSUE TITLE
[Proposal] Conform all AWS_* env KEYS to AWS recommended conventions

### ISSUE THREAD

**Issue by alnutile** [laravel/internals#778]
In a number of files the defaults now are:

```
        's3' => [
            'driver' => 's3',
            'key' => env('AWS_KEY'),
            'secret' => env('AWS_SECRET'),
            'region' => env('AWS_REGION'),
            'bucket' => env('AWS_BUCKET'),
        ],
```
So that is: 

  * AWS_REGION
  * AWS_SECRET
  * AWS_KEY

I would suggest this change:

```
        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
        ],
```

So it would become: 
  * AWS_DEFAULT_REGION
  * AWS_SECRET_ACCESS_KEY
  * AWS_ACCESS_KEY_ID

The reason for this suggestion is that in the AWS docs there are references to that naming convention.

Example one [here](http://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html)

```
export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
$ export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
$ export AWS_DEFAULT_REGION=us-west-2
```

Also note how the SDK will use these defaults from the machines environment settings seen [here](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.AwsClient.html#methods) 

>credentials: (Aws\Credentials\CredentialsInterface|array|bool|callable) Specifies the credentials used to sign requests. Provide an Aws\Credentials\CredentialsInterface object, an associative array of "key", "secret", and an optional "token" key, false to use null credentials, or a callable credentials provider used to create credentials or return null. See Aws\Credentials\CredentialProvider for a list of built-in credentials providers. **If no credentials are provided, the SDK will attempt to load them from the environment**.

Lastly it goes further, I think, if you see a few lines down:

>profile: (string) Allows you to specify which profile to use when credentials are created from the AWS credentials file in your HOME directory. This setting overrides the AWS_PROFILE environment variable. Note: Specifying "profile" will cause the "credentials" key to be ignored.

Pulling in the information from the users properly formatted `~/.aws/credentials` and `~/.aws/config`. Have not tried this yet but I think it would be interesting when making calls like:

```
        $config = [
            'profile' => "project-foo",
            'version' => 'latest'
        ];

        $batch = new BatchClient($config);
```

One last notice of how these defaults work in the bigger workflow.

As a developer working locally interacting with aws I can type `aws --profile=project-foo s3 ls`

These same settings then work into the Laravel app.

And then into TravisCI, for example, since those defaults are set there as well.

Making Laravel, imo, fit in better to an AWS workflow.

**Comment by Dylan-DPC** [comment]
Why don't you send a PR?
