### ISSUE TITLE
Adding a reverse dot method in Illuminate\Support\Arr.

### ISSUE THREAD

**Issue by lukasoppermann** [laravel/internals#78]
Laravel uses dot-notation for arrays fairly extensively, trying to work with a validation array I needed to turn an array with dot notation back into a multidimensional array.

However looking into the `Illuminate\Support\Arr` class I discovered that while there is the `dot` method which `flattens a multi-dimensional associative array with dots` there is no method to reverse this.

I think this function could be pretty beneficial, and I would love to see it being added.

**Comment by lagbox** [comment]
laravel/framework#1851

**Comment by lucasff** [comment]
+1

**Comment by MatthewRuddy** [comment]
+1, ran into this issue myself.

**Comment by glennkarlsen** [comment]
+1

**Comment by dasbit** [comment]
+1

**Comment by spedley** [comment]
+1

**Comment by dasbit** [comment]
i solve it by adding recursive method

**Comment by Quezler** [comment]
+1

**Comment by DivineOmega** [comment]
I've gone ahead and created a tiny composer package for this. It provides an `array_undot` helper function that expands a dot notation array into a full multi-dimensional array. Might be of help!

https://github.com/rapidwebltd/array_undot

**Comment by mityukov** [comment]
Here's my version:
https://gist.github.com/mityukov/f7f6847d142323b1c947c69d1317a4ad

It takes an optional `$initialArray` parameter — if you have some data that you'd like to "complete" with the data from the dotted array.

Example client code:
````php
    public function setParams($params, $activityId)
    {
        $activity = $this->find($activityId);
        // $params may have keys like: 'field1', 'field2', 'extra.extra_field1', 'extra.extra_field2', etc.
        // plus we don't want to reset all the extra_fields not present in the request.
        // , so, we pass existing data into `$initialArray`
        $update = array_undot($params, [ 'extra' => $activity->extra ]);

        return $this->update($update, $activityId);
    }
````
