### ISSUE TITLE
[Proposal] Migration where in adding a foreign key will not require you to put the column datatype

### ISSUE THREAD

**Issue by ajcastro** [laravel/internals#782]
Sometimes in a fast-paced and rapid development, and you need to put a foreign key, and the major thing you have in your mind is the foreign key column name.
For example, you just know you want to put `user_id` in the table, then it is there in a snap!

Currently we have this:
```php
Schema::table('posts', function (Blueprint $table) {
    $table->integer('user_id')->unsigned();

    $table->foreign('user_id')->references('id')->on('users');
});
```

What if we have only this:
```php
Schema::table('posts', function (Blueprint $table) {
    // this will automatically resolve to add a column with the same datatype from users.id
    $table->foreign('user_id')->references('id')->on('users'); 
});
```

The shortest:
```php
Schema::table('posts', function (Blueprint $table) {
    $table->foreign('user_id'); // automatically references to users.id
});
```

This puts a convention on declaring foreign keys, and following conventions saves you a lot of time! :)
This will also avoid human errors on declaring mismatched column datatype.

My current workaround is this: https://github.com/ajcastro/fk-adder.
But it is only effective during a one-time execution of `php artisan migrate`.

**Comment by themsaid** [comment]
Thank you for your suggestion, but looks like not enough members are interested in such change so I'm going to close this issue.
