### ISSUE TITLE
[Proposal] Disable Auto-Discovery with configuration Flag

### ISSUE THREAD

**Issue by johannesschobel** [laravel/internals#787]
Hey guys,

would it be possible to disable  Auto-Discovery  using a configuratin flag in `/config/app.php`? I think, that would be better than using the `dont-discover` array in the `composer.json` file.

This is related to [this issue here](https://github.com/laravel/framework/issues/21025).

What is your opinion on this?

**Comment by Dylan-DPC** [comment]
I don't see the problem of having it in `composer.json`

**Comment by johannesschobel** [comment]
its just, that people wont look in the `composer.json` file to configure something.. they will actually look in the config files - most likely the `app.php` configuration file..

I think, it would be better / more consistent / more convenient / ... to have it in a config file..

**Comment by themsaid** [comment]
Thank you for your suggestion, but looks like not enough members are interested in such change so I'm going to close this issue.
