### ISSUE TITLE
[Proposal] Make validateXXX methods in ValidatesAttributes trait public.

### ISSUE THREAD

**Issue by trip-somers** [laravel/internals#788]
My issue is this: https://github.com/laravel/framework/issues/18839

I have attempted this -- https://laracasts.com/discuss/channels/laravel/validator-using-required-with-and-required-without-together -- and ran into the same issue as above.

Having looked at the trait in question -- `Illuminate\Validation\Concerns\ValidatesAttributes` -- the methods in question do not appear to gain anything from being `protected` as opposed to `public`; while making them `public` opens up a variety of possibilities within `Validator::extend()`.

Alternatively, if the scope of `$this` within the callback of `Validator::extend()` can be changed to refer to the Validator, this would accomplish the same goal.

**Comment by Dylan-DPC** [comment]
What's the gain of this?

**Comment by trip-somers** [comment]
I thought that was self-explanatory, but... The gain is allowing `Validate::extend()` to access the `validateXXX()` methods.

**Comment by trip-somers** [comment]
For more context, here's what I tried:

```
Validator::extend('required_with_and_without', function ($attribute, $value, $parameters, $validator) {
    $with       = $parameters[0];
    $without    = $parameters[1];

    return (
        $validator->validateRequiredWith($attribute, $value, [$with]) &&
        $validator->validateRequiredWithout($attribute, $value, [$without])
    );
});
```

`$validator` is made available to the closure, but its use is *extremely* limited in that you can only take actions on the Validator object (addRules, setData, etc.).

If there is a good reason not to allow `$validator` to access methods like `validateRequiredWith`, then I'd like to see it.

**Comment by trip-somers** [comment]
Annnnd... I just saw that this was done for 5.5. Closing this.
