### ISSUE TITLE
[Proposal] Artisan app:name with no arguments returns actual name

### ISSUE THREAD

**Issue by fairbraxton** [laravel/internals#789]
## Description
Let's say you have already set the applications namespace to 'ServiceX' by the console command:
```php artisan app:name ServiceX```

Now if you, let's say, deployed the application to production, and you forgot if you had set the application namespace, would it be sensible to be able to have the **app:name** command, if supplied with no arguments or **--check**, it would return:

Command: ```php artisan app:name [--check]```

Output: ```The application namespace is: ServiceX ```.

This is open to discussion, I can edit this as new ideas or revisions.

**Comment by ntzm** [comment]
I don't think is necessary, you could just check in any of your files in `app/` 👎
