### ISSUE TITLE
[proposal] about deleting a file with Filesystem class

### ISSUE THREAD

**Issue by atefBB** [laravel/internals#790]
https://github.com/laravel/framework/blob/7bfe4a10387d726569856bb4ceaec576e60ae7bb/src/Illuminate/Filesystem/Filesystem.php#L114 
if there's an error while deleting a file in such path why not to simply `return false` and not to complete `looping` ?

**Comment by scrwdnet** [comment]
It is so the other files are removed even if it fails to delete the 4th file of, say, 8 files.

**Comment by atefBB** [comment]
What about returning an array of the `failed` files?

**Comment by scrwdnet** [comment]
IMO generally I prefer not to mix return values. This is just a delete operation so if `$success` is false the file probably didn't exist anyway and in which case your delete function still worked for the paths you provided.

If you want to know specifics I'd personally loop each file myself and delete the individual file separately then you can run you own logic?

**Comment by atefBB** [comment]
I don't know if you undestand me? I mean this:
`foreach ($paths as $path) `
`{` 
   ` if ( ! @unlink($path) )` 
    `{`
     `// $success is an array` 
     `$success[$path][] = false;` 
    `} else {`
      `$success[$path][] = true; `
    `}`

**Comment by jmarcher** [comment]
@atefBB Do not want to be rude but that is just not a good thing, never do something like that.

**Comment by atefBB** [comment]
@jmarcher no prob ! thx for the advice.
