### ISSUE TITLE
Decouple or allow overriding of Carbon 

### ISSUE THREAD

**Issue by AdenFraser** [laravel/internals#8]
Correct me if I am wrong but as far as i'm aware there's no way of doing this currently.

It's certainly something i'd be interested in undertaking if it's agreed that it would be worthwhile.

Currently Carbon is used for Auth, Cache, Console Scheduling, Eloquent, the Artisan Optimize command, Queues (DB Interaction) and Session middleware.

What i'd propose is to allow any DateTime extending Class to be used as a Carbon replacement (but continue to use Carbon as the default). Perhaps this could be done through the app configuration, in the app service provider or another means - I'm not too sure what would be best suited yet as I havn't experimented.

This would be particularly useful for those who wish to:
- Extend Carbon (fairly likely)
- Translate Carbon (fairly likely)
- Replace Carbon (fairly unlikely?)

i guess if this was something that was undertaken it would also affect Lumen (since it uses a number of the illuminate components which would obviously be the areas of the internals that are affected). 

Thoughts?

**Comment by IsraelOrtuno** [comment]
Carbon already supports localization http://carbon.nesbot.com/docs/#api-localization

**Comment by AdenFraser** [comment]
I was under the impression that only worked with the Localization that was built into the package? I'm not sure if there are locales missing, but you certainly wouldn't be in a situation where you can adjust the strings for diffForHumans I'd expect?

**Comment by IsraelOrtuno** [comment]
I think you could set a `Translator` instance manually to Carbon but actually you are right, Carbon is not very opened to changes

**Comment by Mevrael** [comment]
Not a fan of Carbon but had no problems using it, however I agree it's, in times, complicated and should be bindable/injectable/replacable.

**Comment by AdenFraser** [comment]
I actually like Carbon a lot but there are instances where it would be nice to be able to extend / replace it for different purposes, but it seems baked pretty tightly, especially with Eloquent which is where you are most likely to be want to extend it I imagine.

**Comment by scrubmx** [comment]
I have a trait that I use in my BaseModel class:
```php
<?php

namespace App\Models\Traits;

use Jenssegers\Date\Date;

trait TranslatesDates
{
    /**
     * Return model date attributes as a Jenssegers\Date\Date instance.
     *
     * @override \Illuminate\Database\Eloquent\Model
     *
     * @param mixed $value
     * 
     * @return \Jenssegers\Date\Date
     */
    protected function asDateTime($value)
    {
        return new Date(parent::asDateTime($value));
    }
}
```
As far as I know is the easiest way.

**Comment by rtconner** [comment]
Man this just seems like it would make already bulky date/time handling even bulkier.

**Comment by AdenFraser** [comment]
@rtconner Surely providing the opportunity to remove an 'already high memory' date/time handler would be beneficial, if you see it as such a problem?

**Comment by AdenFraser** [comment]
@taylorotwell What are your thoughts in regards to this?

If it's something that you think is a feasible improvement to the core, I'll set about putting together a PR.

**Comment by Jeroen-G** [comment]
See also this: https://hashnode.com/ama/with-taylor-otwell-cilmj90zh000k6t53il0rdgqp#cilx5el0u00m3gb53xbey9i1o

**Comment by AdenFraser** [comment]
Interesting @Jeroen-G, I shall start putting together a PR then

**Comment by taylorotwell** [comment]
Carbon has new maintainers now which may improve the quality / maintenance of the library going forward.
