### ISSUE TITLE
Laravechat is not running

### ISSUE THREAD

**Issue by imsidz** [laravel/internals#805]
i trying to go https://larachat.co/slack
getting error 
(3/3) QueryException

> SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8mb4_unicode_ci,COERCIBLE) for operation '=' (SQL: select * from `announcements` where (`entry` = We've just created #homestead-dev for discussing Laravel Homestead 🙂) limit 1)

**Comment by Dylan-DPC** [comment]
Hi @imsidz 

Yes we are aware of this issue. Will be fixed soon. You can visit https://larachat.co/live or any of the other pages as the error affects just the home page. Sorry for the inconvenience.

**Comment by Dylan-DPC** [comment]
The website has been fixed and you can close this issue
