### ISSUE TITLE
Collection pad method

### ISSUE THREAD

**Issue by rogervila** [laravel/internals#806]
Hello,

It would be nice to have the php [`array_pad`](http://php.net/manual/es/function.array-pad.php) equivalent for [laravel collections](https://laravel.com/docs/5.5/collections#available-methods).

**Comment by Dylan-DPC** [comment]
@rogervila this is already merged. You can close the issue :+1:

**Comment by rogervila** [comment]
@Dylan-DPC amazing! Thank you very much
