### ISSUE TITLE
Blade escape js feature

### ISSUE THREAD

**Issue by shiroamada** [laravel/internals#809]
Is there any existing function / helper to escape js in blade?
something like this?
https://www.texelate.co.uk/blog/post/131-convert-php-strings-for-use-as-javascript-strings/

or twig

{{ something | e('js') }}

**Comment by michaeldyrynda** [comment]
Any reason you couldn't use the new `@json` [Blade directive](https://laravel.com/docs/5.5/blade#displaying-data) (scroll to *Rendering JSON*)?

**Comment by shiroamada** [comment]
It a string prepared in controller. So the only thing want to output in blade is escape the single quote or double quote. It break my JS if I didn't escape it. It is a gmap marker information. Basically I prepared the markers js variable in controller then echo it out to the blade.

The issue now someone input the name with single quote which is possible. **La'Code Hair Studio** is the one break the code.
```
var markers = new Array();
 markers = [
 ['La'Code Hair Studio', 3.1047856, 101.59523279999999, 0], ['Tadika Murni', 3.195768, 101.67346850000001, 0], ['Tadika seri murni", 3.116673, 101.67355400000007, 0], ['Fashionista  Boutique', 3.16878889, 101.63653240000005, 0]
];

```

So if there is a helper to escape it will be very handy.

**Comment by jakebathman** [comment]
The `@json` directive is just what you want. Something like this:

In controller:
```
$markerName = “La'Code Hair Studio”;
```

In blade:
```
var markers = new Array();
 markers = [
 ['@json($markerName)', 3.1047856, 101.59523279999999, 0], ['Tadika Murni', 3.195768, 101.67346850000001, 0], ['Tadika seri murni", 3.116673, 101.67355400000007, 0], ['Fashionista  Boutique', 3.16878889, 101.63653240000005, 0]
];
```

**Comment by shiroamada** [comment]
@jakebathman  I tested with Laravel 5.5.13.

For your controller
U set double quote for the "La'Code Hair Studio". In normal loop case, it should be under same pattern.

In Controller: part of my code.
```
$str_marker = '[[';
foreach($businesses as $business)
{
    $str_marker .= "'" . $business['title'] . "', " . $business['long'] . ", " . $business['lat'] . ", 0],"
}
```
So by above result. It will build something like this
```
$data['markers'] ="[['La'Code Hair Studio', 3.1047856, 101.59523279999999, 0],['Tadika Murni', 3.195768, 101.67346850000001, 0],['Tadika seri', 3.116673, 101.67355400000007, 0],['Fashionista  Boutique', 3.16878889, 101.63653240000005, 0]]";
```

in Blade:-
```
            <script>
                var markers = new Array();
                markers = @json($markers);
            </script>
```

Output:-
```
            <script>
                var markers = new Array();
                markers = "[['La'Code Hair Studio', 3.1047856, 101.59523279999999, 0],['Tadika Murni', 3.195768, 101.67346850000001, 0],['Tadika seri', 3.116673, 101.67355400000007, 0],['Fashionista  Boutique', 3.16878889, 101.63653240000005, 0]]";
            </script>

```

It didn't escape the single quote in the first business title.

**Comment by jakebathman** [comment]
You don't need to build the string, just use an array in the `@json` directive.

**Controller**
```
$businesses = [
    [
        "title" => "La'Code Hair Studio",
        'long'  => 3.1047856,
        'lat'   => 101.59523279999999,
        0,
    ],
    [
        "title" => "Tadika Murni",
        'long'  => 3.195768,
        'lat'   => 101.67346850000001,
        0,
    ],
    [
        "title" => "Tadika seri",
        'long'  => 3.116673,
        'lat'   => 101.67355400000007,
        0,
    ],
    [
        "title" => "Fashionista  Boutique",
        'long'  => 3.16878889,
        'lat'   => 101.63653240000005,
        0,
    ],
];

foreach ($businesses as $business) {
    $markers[] = [$business['title'], $business['long'], $business['lat'], 0];
}

return view('test', compact('markers'));
```

**Blade**
```
<script type="text/javascript">
var markers = @json($markers);
</script>
```

**Output**
```
<script type="text/javascript">
var markers = [["La'Code Hair Studio",3.1047856,101.5952328,0],["Tadika Murni",3.195768,101.6734685,0],["Tadika seri",3.116673,101.673554,0],["Fashionista  Boutique",3.16878889,101.6365324,0]];
</script>
```

**Comment by shiroamada** [comment]
OK, got it. In this case. User have to change the logic in controller. If it have the blade helper feature that will be handful change in blade instead in controller. Just a proposal to make it more handy.

Thanks!

**Comment by Dylan-DPC** [comment]
Are you still pursuing this? If not you can close the issue.

**Comment by drakerehfeld** [comment]
I used php's ```addslashes()``` method in a <?php tag to throw a string with single quotes in a onmouseover() param. Might be what you want instead of building a json object
