### ISSUE TITLE
[Proposal] Gracefully allow already attached/detached IDs in "attach" and "detach" methods

### ISSUE THREAD

**Issue by SirLamer** [laravel/internals#818]
For simplicity's sake, I am going to describe the below for the "attach()" method only, however this pattern is proposed to be applied to the "detach()" method as well.

In the current implementation, the attach() expects the provided ID or array of IDs to not already exist in the pivot table. For a situation such as an interface with asynchronous API actions which are attaching and detaching models via a relationship, it can occur that two simultaneous attach requests for the same remote ID could come in at the same time. In this case, the first request will return successful and the second event will throw a database integrity constraint error, assuming your pivot table is set up with foreign keys and appropriate indexing restrictions. Logically, it makes no difference to the second case whether or not it was that very action which performed the relationship bind or if another request happened to do it right before, so a graceful solution is to return a "success" result, acknowledging the existing relationship as equivalent to adding it.

A solution is for the "attach()" method to check for if any of the IDs exist and then add the relationship only for those which need to be newly added. Alternatively, the SQL query could just be amended to an "INSERT ON DUPLICATE KEY UPDATE" syntax so that the pivot table entry is just skipped over by the database itself.
https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html

I refer to the JSON API spec v1.0 which requires relationship actions in this scenario to return as successful in order to avoid async collision issues.
http://jsonapi.org/format/#crud-updating-relationships

Currently I am affecting this with my own external work-around check however I suspect this scenario will become increasingly more commonplace as the world moves towards API interactions in place of page refreshes. Also, currently the sync() method already performs a check like this so I don't think the code change is substantial.

Of course this can be an optional toggle on attach() or an alternative method like "attachIfRequired()". Also, as a reminder, the same reasoning can apply to "detach()" except in that case we are not worried about foreign key integrity constraints on the database.

**Comment by Dylan-DPC** [comment]
Well can't you ue `sync`?

**Comment by SirLamer** [comment]
ACK, yes! I misunderstood the function of the "detaching" attribute on the sync method. Also, laravel offers a "syncWithoutDetaching" method which does the same. Silly me, thanks!
