### ISSUE TITLE
[5.3] [Proposal] Can we extract all helper functions to another repository?

### ISSUE THREAD

**Issue by Modelizer** [laravel/internals#82]
Yes, its an idea to use all [helper](https://laravel.com/docs/5.2/helpers) function or classes outside laravel framework which has no dependency.

**Comment by jlaswell** [comment]
There are a lot of helpers in the [illuminate/support](https://github.com/illuminate/support/blob/master/helpers.php) already. What outside of this repo are you thinking of? I'm always up for more reusable helpers.

**Comment by JosephSilber** [comment]
@Modelizer Use this: https://github.com/tightenco/collect

**Comment by Modelizer** [comment]
@jlaswell yes laravel have lots of helpers but i was thinking if we able to extract functions, classes from laravel `Support` folder and make it independent. 

@JosephSilber That's what i was talking about. We need to find a way when a new version of laravel is release it will automatically pull out `Support` folder and commit to your `tightenco/collect` repo. What do you say?

**Comment by salarmehr** [comment]
Good idea. I also only need collection  in `ary` package. https://github.com/salarmehr/ary
