### ISSUE TITLE
[Proposal] New carbon helper function

### ISSUE THREAD

**Issue by gabriel-caruso** [laravel/internals#828]
Recently, @taylorotwell [created two new date helpers](https://github.com/laravel/framework/commit/3c888b6c7b89c3d3f90e9024ffbebed3ee80bd23). I was wondering if a `carbon()` helpers wouldn't be nice to have.

Many times we need to call `Carbon::someFunction()`, and with this new method, it would be much easier and cleaner, especially for views.

## My goals for these helper are:
- [x] [Helpers](http://carbon.nesbot.com/docs/#api-instantiation): `Carbon::yesterday()`
- [x] [Relative phrases](http://carbon.nesbot.com/docs/#api-testing): `Carbon('last friday')`
- [x] [Strings](http://carbon.nesbot.com/docs/#api-getters): `Carbon::parse('2017-10-13 22:00:00.000000)`
- [x] Timezones, for example: `Carbon::now('America/Sao_Paulo')->tomorrow()`
- [x] [Datetime](http://php.net/manual/pt_BR/class.datetime.php), for example: `Carbon::instance(DateTime::createFromFormat('Y-m-d', '2017-10-13'))`

## Things that it can support:
- [ ] [Timestamps](https://www.wikiwand.com/en/Unix_time)
- [ ] [DateTimeImmutable](http://php.net/manual/pt_BR/class.datetimeimmutable.php)

This helper is not intended to support receive an instance of `Carbon`, since an instance has all `Carbon`'s methods.

What do you guys think?

_Edit_: PR already made ([laravel/framework#21660](https://github.com/laravel/framework/pull/21660)), and not merged yet :disappointed:

**Comment by jakebathman** [comment]
So it'd be `carbon()->someFunction()` instead?

**Comment by gabriel-caruso** [comment]
@jackbathman yes, like this!

**Comment by ajcastro** [comment]
I created my own carbon() helper. I think it is good to have a built-in in laravel

**Comment by gabriel-caruso** [comment]
@ajcastro What have you build? This helper accepts data, functions, etc.?

**Comment by ajcastro** [comment]
I did this:
```php
function carbon($datetime = null)
    {
        if ($datetime instanceof \Carbon\Carbon) {
            return $datetime;
        }

        if ($datetime instanceof \DateTime) {
            $datetime = $datetime->format('Y-m-d H:i:s');
        }

        return new \Carbon\Carbon($datetime);
    }
```

**Comment by gabriel-caruso** [comment]
As Laravel already have the `now()` and `today()` methods, what about this new helper:
```php
/**
 * Create a new Carbon instance of given time, or return new instance.
 *
 * @param  \DateTime|null $datetime
 * @return \Illuminate\Support\Carbon
 */
function carbon($datetime = null)
{    
    if ($datetime instanceof \DateTime) {
        return new \Illuminate\Support\Carbon($datetime->format('Y-m-d H:i:s'));
    }

    return new \Illuminate\Support\Carbon;
}
```

Is this format a standard? Or maybe should we receive it?

**Comment by CupOfTea696** [comment]
@gabriel-caruso what you did doesn't allow you to instantiate an new Carbon instance by providing any parameters. I suggest the following:

```php
/**
 * Create a new Carbon instance.
 *
 * @param \DateTime|string|null     $time
 * @param \DateTimeZone|string|null $tz
 * @return \Illuminate\Support\Carbon
 */
function carbon($time = null, $tz = null)
{    
    if ($datetime instanceof \DateTime) {
        return new \Illuminate\Support\Carbon::instance($time);
    }
    
    return new \Illuminate\Support\Carbon($time, $tz);
}
```

**Comment by sebastiandedeyne** [comment]
Would be nice to do `Carbon::parse` if a string is passed. I've added that helper to my own projects in the past.

**Comment by jakebathman** [comment]
Here's an updated method, adding `Carbon::parse` and a wrapper to drop into `Foundation\helpers.php`. This fixes an issue with returning `new \Illuminate\Support\Carbon::instance`, and adds `setTimezone` after that in order to have the `tz` parameter still apply even if it's being created from a `DateTime` instance.

```php
if (! function_exists('carbon')) {
    /**
     * Create a new Carbon instance for the given datetime and/or timezone.
     *
     * @param  \DateTime|string|null $datetime
     * @param  \DateTimeZone|string|null $tz
     * @return \Illuminate\Support\Carbon
     */
    function carbon($datetime = null, $tz = null)
    {
        if ($datetime instanceof \DateTime) {
            return \Illuminate\Support\Carbon::instance($datetime)->setTimezone($tz);
        }
        
        return \Illuminate\Support\Carbon::parse($datetime, $tz);
    }
}
```

**Comment by gabriel-caruso** [comment]
@CupOfTea696 Timezone, good one, I've forgotten about that. Also, thanks for the `instance` method, haven't know about that!

**Comment by gabriel-caruso** [comment]
@jakebathman That looks awesome to me. I'll write some tests and make the PR! :smile:

**Comment by ryanwinchester** [comment]
i've been using this helper for a while and recently made a gh repo for it:

https://github.com/ryanwinchester/carbonize/blob/master/src/functions.php

It's a helper that takes a `Carbon` instance, `DateTime` instance, `DateTimeImmutable` instance, `timestamp`, `datetime string`, or `null` and returns a new carbon instance.

**Comment by gabriel-caruso** [comment]
@ryanwinchester What an amazing helper, love how did you used `switch`. I’ve already [submitted a PR](https://github.com/laravel/framework/issues/21660) with my version. What do you think?

**Comment by gabriel-caruso** [comment]
@vlakoff Let’s discuss here about the new helper 😄
What things should we use from @ryanwinchester’s helper?

**Comment by vlakoff** [comment]
* `new Carbon(null, $tz)`: allows creating a datetime now, but with a different timezone. Currently your code discards the supplied timezone.
* `Carbon::parse` just calls `Carbon::__construct`, for syntaxic sugar that is unneeded here. So let's economize one function call.

**Comment by ryanwinchester** [comment]
@gabriel-caruso it looks good just doesn't cover all my use cases :)
