### ISSUE TITLE
[Proposal] App getUrl method

### ISSUE THREAD

**Issue by gabriel-caruso** [laravel/internals#829]
In Laravel we can get the current locale by calling `app()->getLocale()`. 

`app()->getUrl()` instead of `config('app.url')` would be nice to have?

**Comment by Dylan-DPC** [comment]
Hey

Yeah sure you can do it. This should be an easy PR

**Comment by jakebathman** [comment]
I like this, maybe even as a standalone function like `appUrl()` or something?

**Comment by gabriel-caruso** [comment]
@jakebathman I’ve thanked on ah helper, but as we already have a method on a class, let’s follow this, and maybe Taylor can extract it.

**Comment by jakebathman** [comment]
Makes sense. I'd say put in the PR with `app()->getUrl()` and see what everyone thinks!
