### ISSUE TITLE
Collect Map/transform procs

### ISSUE THREAD

**Issue by michaelachrisco** [laravel/internals#83]
array_map already supports a string argument that will call on a function:
```php
$arr = ['first' => 'taylor', 'last' => 'otwell'];
array_map('strtoupper', $arr)
=> [
     "first" => "TAYLOR",
     "last" => "OTWELL",
   ]

?>
```

This is a convenience method as we don't need to push an entire proc to the array_map.
Not sure about the best method to apply, but I believe something like:
```php
      $data = new Collection(['first' => 'taylor', 'last' => 'otwell']);
      $data = $data->mapProc('strtoupper');
```
could be feasible.

**Comment by michaelachrisco** [comment]
Sample working solution is here: https://github.com/michaelachrisco/collect/tree/mapping-procs

I feel iffy on the naming...but the implementation is easy enough.

**Comment by JosephSilber** [comment]
Uh... there's nothing stopping you from passing it directly to `map`:

```php
$uppercased = collect(['first' => 'taylor', 'last' => 'otwell'])->map('strtoupper');
```

**Comment by michaelachrisco** [comment]
@JosephSilber If you run your code sample:
```php
$uppercased = collect(['first' => 'taylor', 'last' => 'otwell'])->map('strtoupper');
PHP warning:  strtoupper() expects exactly 1 parameter, 2 given in LaravelFoo/bootstrap/cache/compiled.php
```

That is because the underlining code is: 
```php
    /**
     * Run a map over each of the items.
     *
     * @param  callable  $callback
     * @return static
     */
    public function map(callable $callback)
    {
        $keys = array_keys($this->items);

        $items = array_map($callback, $this->items, $keys);

        return new static(array_combine($keys, $items));
    }
```

**Comment by JosephSilber** [comment]
You're totally right. Forgot about that.

I'm still 👎 on adding these methods. You can simply pass a closure to `map` when you cal it.

**Comment by michaelachrisco** [comment]
Closing this,as the community seems to not like the idea. Too bad, as this breaks expected behavior.
