### ISSUE TITLE
[5.6] Migrate from Carbon to Chronos

### ISSUE THREAD

**Issue by gabriel-caruso** [laravel/internals#839]
Recently, while [proposing a new helper `carbon`](https://github.com/laravel/framework/pull/21660), I've found an extension of Carbon made by CakePHP called [Chronos](https://github.com/cakephp/chronos).

Is something to consider this migration, as Carbon has [a lot of PR made](https://github.com/briannesbitt/Carbon/pulls) and not merge, so have many bugs, or no, is fine as it is?

**Comment by drbyte** [comment]
Related: #362
