### ISSUE TITLE
New Validation Rule: Presence

### ISSUE THREAD

**Issue by lindyhopchris** [laravel/internals#85]
I believe there's a need for a validation `presence` rule. This is different from `required` and `present`, because it should say that the attribute should be validated *if* any value has been submitted for that key, but that it is acceptable for the data to not have that attribute key in it.

### Use Case - PATCH

In API `PATCH` requests it is acceptable for a key to not be present in data received from the client. However, if the key is present, then the value submitted by the client must be validated.

At the moment `present` and `required` are not usable because they force the client to submit a value. `sometimes` could be used, but this is unnecessarily complicated for this use case considering that you need access to the decoded JSON data in the request body content (i.e. the data passed into the validator) to work out if the key has been submitted by the client.

#### Example

``` http
PATCH /api/people/1 HTTP/1.1
Content-Type: application/vnd.api+json

{
	"data": {
		"type": "people",
		"id": "1",
		"attributes": {
			"name": ""
		}
	}
}
```

``` php
$rules = [
	"data.attributes.name": "string|min:3"
	"data.attributes.email": "email"
];
```

In this scenario, the data would be deemed valid, because the `data.attributes.name` rules would not be invoked. The same if the client submitted `null` as the value of `data.attributes.name`. `required` or `present` cannot be added to the rules, because then `data.attributes.email` would fail because the client hasn't included this in the `PATCH` request.

### Proposed Solution

Add an `existenceRules` property to the `Illuminate\Validation\Validator` class to differentiate these rules from `implicitRules`. Add a `presence` rule to cover the above scenario. *(For info, I'm not fussy on the names of the property/rule!)*

When determining whether an attribute is validatable, there will need to be a check using `Arr::has()` rather than just getting the value (which defaults to `null`) at this line:
https://github.com/illuminate/validation/blob/master/Validator.php#L491

I'm obviously more than happy to submit a pull request with full tests etc. I think this would be a great addition, because the use case is increasingly common with APIs. The spec I'm using, [JSON-API](http://jsonapi.org) has `PATCH` as it's resource update request, so a lot of the validation rules I'm writing have to deal with this scenario.

**Comment by lindyhopchris** [comment]
Ok, I've just spotted that the `sometimes` rule can be used inline rather than having to have a callback. So actually I can do this already...

**Comment by lindyhopchris** [comment]
Obviously complete my bad for missing this. But FYI I missed it because `sometimes` is not listed in the available validation rules:
https://laravel.com/docs/5.2/validation#available-validation-rules

So I've been scanning those for rules I could use. Might be worth adding `sometimes` to the list of rules?

**Comment by kdbcinco** [comment]
It is already in the docs, just not in the 'Available Validation Rules'.
https://laravel.com/docs/5.2/validation#conditionally-adding-rules
