### ISSUE TITLE
[Proposal] Unplug Collections from Support namespace

### ISSUE THREAD

**Issue by gabriel-caruso** [laravel/internals#858]
Laravel `Collections` lives inside `Illuminate\Support` namespace, with also contains a lot of stuff that isn't related to `Collections`. 

Recently, I want to use `Collections `in a no Laravel app. I discovery a package called [`tightenco/collect`](https://github.com/tightenco/collect), but I think: why not extract `Collections` to its own namespace inside `Illuminate`. 

One reason is `Lumen`. If I want to use `Collections`, why not simple import `illuminate/collections`?

This change would be applied to Laravel `5.6` version. What do you guys think?

**Comment by jmarcher** [comment]
https://github.com/laravel/framework/blob/cc72992dd18915c552e389f8a96370be7ebfe58a/composer.json#L71

Laravel uses tightencos package.

**Comment by RemiCollin** [comment]
@jmarcher : not really, it's just an alias to allow tightenco/collect and laravel as dependencies to work nicely together, but `Illuminate\Support\Collection` does not extends the former. 

The fact that `tightenco/collect` exists is proof there is a need for a separate `Illuminate\Collection` package anyway.

**Comment by gabriel-caruso** [comment]
@jmarcher Ow, I haven’t seen that! But, I agree with @RemiCollin that there’s a need to unplug `Collections` to its own `namespace`

**Comment by brayniverse** [comment]
I do believe you can port `Illuminate\Support\Collection` into it's own package and maintain the namespace.

**Comment by gabriel-caruso** [comment]
@brayniverse My ideia is to move `Collections` to its own namespace is because `Collections` isn’t more something under the `Support`, it’s  something unique, something to use with other frameworks, projects, `Lumen`, etc.

**Comment by brayniverse** [comment]
With what I proposed, you'd maintain the namespace *and* be able to require the package in other projects without everything else that is in support.

I'd personally prefer it being in its own namespace, but if it's a problem for anyone, you've got an option that doesn't break backward compatibility.

**Comment by RemiCollin** [comment]
I suppose we could have `Illuminate\Support\Collection` extends `Illuminate\Collection\Collection` for that matter

**Comment by brayniverse** [comment]
That sounds good too

**Comment by gabriel-caruso** [comment]
@RemiCollin @brayniverse Good one, these extensions would save us at compatibility. I guess we can work on this `Collections` unplugging like `Carbon` is used in Laravel. We move `Collections` to its own namespace and extend this on `Illuminate\Support\Collection` class to avoid brakes. 

Thanks for your help and opinions, I'll start to work on that. :clap:

**Comment by gabriel-caruso** [comment]
I’ve tried some tests, but this is going to be harder than I think 😢

**Comment by RemiCollin** [comment]
What difficulty did u face ? Maybe we can help ?

**Comment by gabriel-caruso** [comment]
@RemiCollin I’ve deleted the branch, but I’ll be creating another one soon. The major problem was the current `Illuminate\Support\Collection` class, that somehow crashes some tests when I have a `Illuminate\Collection\Collection` class

**Comment by sebastiandedeyne** [comment]
This has been attempted a few times in the past (even by Taylor iirc), but given how hard it was they decided to let it go, which is when the Tighten package was created.

Don't remember where the previous discussions were made though :/
