### ISSUE TITLE
Re-add 'preserveKeys' flag to 'Collection#reverse()' but with backwards compatible default

### ISSUE THREAD

**Issue by nadinengland** [laravel/internals#859]
I came cross this [old feature](https://github.com/laravel/framework/issues/9948) that was added in 5.2 that allowed `reverse()` to function like [PHP's `array_reverse`](https://secure.php.net/manual/en/function.array-reverse.php) and not preserve the keys. A few days later this seems [to have been removed](https://github.com/laravel/framework/commit/de3ec2094a59b467073f6f6789b3504900c0de8f) presumably because it broke the default functionality of the API. However, the fix commit says that it is "making preserve keys the default" when in fact it makes it the only thing the method can do :(

If it had just changed the argument default to `true` it would have maintained the same interface as before the feature was added. I have a branch with which re-adds the feature and unit tests [here](https://github.com/nadinengland/laravel-framework/commit/65eb48312ff312f7b5378bd233d258fe6fb05788) and I have also documented it in the docs repo [here](https://github.com/nadinengland/laravel-docs/commit/790dcace4c617f58eceda281e1229ba3c84617ce).

I am aware that I may have simply missed a conversation on chat from around that time (new to Laravel!) So please let me know if this is something that is wanted, if so I'll raise the pull requests.

P.s. as I am new, let me know if branching from 5.5 was the correct thing to do, [contrib docs](https://laravel.com/docs/5.5/contributions#which-branch) say the latest stable branch for backwards compatible features.

**Comment by Dylan-DPC** [comment]
Hi. 
Well if your PR is backwards compatible - doesn't change the behaviour for the function in different use cases - you can PR it to 5.5. That isn't a big problem though as if it can be rebased and targetted to master later on if found to be breaking. Since you already have the PR ready, submit it.

**Comment by nadinengland** [comment]
PRs closed and told to use `values()` on the reversed collection which resets the indexes to consecutive integers:

```php
collect(['a', 'b', 'c'])->reverse()->values()->all();
// [0 => 'c', 1 => 'b', 2 => 'a']
```

**Comment by nadinengland** [comment]
Having thought about this for a bit longer, could [the docs](https://laravel.com/docs/5.5/collections#method-reverse) for the method be to demonstrate the preserve key behaviour? Perhaps to something like:

> The reverse method reverses the order of the collection's items, preserving the original keys:
> 
> ```php
> $collection = collect(['a', 'b', 'c', 'd', 'e']);
> 
> $reversed = $collection->reverse();
>
> $reversed->all();
>
> // [4 => 'e', 3 => 'd', 2 => 'c', 1 => 'b', 0 => 'a']
> ````

**Comment by ntzm** [comment]
You can PR the docs on laravel/docs repo. I think it would be a good idea to document this 👍

**Comment by nadinengland** [comment]
Cheers all!
