### ISSUE TITLE
Add Model::makeHidden() method

### ISSUE THREAD

**Issue by misog** [laravel/internals#86]
Hi, in 5.2, Model has this method

```
    /**
     * Make the given, typically hidden, attributes visible.
     *
     * @param  array|string  $attributes
     * @return $this
     */
    public function makeVisible($attributes)
    {
        $this->hidden = array_diff($this->hidden, (array) $attributes);

        return $this;
    }
```

but there is not the opposite method, makeHidden().

Use case:

```
$model = Model::find($id);
$model->makeVisible('password');
$password = $model->password;
// do something with $password
$model->makeHidden('password');
return $model;
```

I propose to implement Model::makeHidden(), the implementation:

```
    /**
     * Make the given, typically visible, attributes hidden.
     *
     * @param  array|string  $attributes
     * @return $this
     */
    public function makeHidden($attributes)
    {
        $this->hidden = array_merge($this->hidden, (array) $attributes);

        return $this;
    }
```

**Comment by fragkp** [comment]
Pls correct me, if i'm wront, but $hidden and $visible has only an effect for json. So, you could change the password on the model without changing visibility.

**Comment by misog** [comment]
You are right, presence in $hidden does not hide a property in Model.

In fact, there is method addHidden which is the same as the proposed makeHidden, but accepts argument list and **does not** return $this object.

```
    /**
     * Add hidden attributes for the model.
     *
     * @param  array|string|null  $attributes
     * @return void
     */
    public function addHidden($attributes = null)
    {
        $attributes = is_array($attributes) ? $attributes : func_get_args();

        $this->hidden = array_merge($this->hidden, $attributes);
    }
```

I think the proposed name makeHidden makes sense becasue:
- it is opposite to existing makeVisible
- it returns $this just like makeVisible and enables chaining
- it is a better name than addHidden (Model::addHidden feels like it appends a new hidden value to the Model - in fact, the true action here is "make a property hidden")
- there is addVisible and addHidden, but only makeVisible and not makeHidden

**Comment by jrnk** [comment]
To add to this, in the documentation there is an example on this for an Eloquent model (and not a collection) for `makeHidden` but this method is only available on a collection:

https://laravel.com/docs/master/eloquent-serialization#hiding-attributes-from-json

**Comment by koerel** [comment]
Method was added in https://github.com/laravel/framework/commit/c94ceec0ee5e9ed51039ddc6729afe07f726825a

**Comment by poisa** [comment]
Is it possible to do this with relationships? Sometimes it is not useful to get the related object. I'm having a particularly bad case where related objects are bloating the response and this would work wonders in such a case.

**Comment by Shpartko** [comment]
@koerel, @misog : makeHidden() work's great. But, when I use makeHidden() with paginate() method, the result is not correct - properties **total**, **per_page**, and others was broke .

Correct result:
```
>>> \App\Coupon::paginate(3)->toJson()                                                                                                     
=> "{"total":9,"per_page":3,"current_page":1,"last_page":3,"next_page_url":"http:\/\/localhost?page=2","prev_page_url":null,"from":1,"to":3,"data":[{"id":1,"orders_count":0,"orders":[]}]}"                           
```

Don't correct result:
```
>>> \App\Coupon::paginate(3)->makeHidden('orders')->toJson()                                                                               
=> "[{"id":1,"orders_count":0}]"                                                                                                                                                                                         
```

**Comment by timothyallan** [comment]
I'm running into this as well @Shpartko , makeHidden wrecks pagination.

**Comment by nuqz** [comment]
@Shpartko @timothyallan I ran into this, but I have found a workaround:

```php
$properties = ExtraProperty::orderBy('code')
    ->paginate($this->perPage)
    ->appends($this->appendsToQuery);

$properties->getCollection()->makeVisible([
        'code',
        'name',
        'type',
        'unit',
]);

return response()->json($properties);
```

Hope, this will help somebody)

**Comment by fokoz** [comment]
@nuqz code can work without `->getCollection()` I have tried.

**Comment by sisve** [comment]
I believe that the new API Resources functionality in 5.5 removes the need for hiding attributes. This introduces a transformation layer between your models and your api output, allowing you to include just those properties that you need.

> When building an API, you may need a transformation layer that sits between your Eloquent models and the JSON responses that are actually returned to your application's users. Laravel's resource classes allow you to expressively and easily transform your models and model collections into JSON.

Source: https://laravel.com/docs/5.5/eloquent-resources

**Comment by taylorotwell** [comment]
Exists now.

**Comment by samson1998** [comment]
Using make::Hidden() method on the result of a query builder gives an error:

DB::table('houses')->whereBetween('price', [$minPrice, $maxPrice])
                                    ->where('house_area', $location)
                                    ->get()->makeHidden($this->hiddenKeys());  

while this work:

 House::whereBetween('price', [$minPrice, $maxPrice])
                                    ->where('house_area', $location)
                                    ->get()->makeHidden($this->hiddenKeys());

Why is this so?

Thanks.
