### ISSUE TITLE
[5.5] Package auto-discovery - Package routes doesn't work with https

### ISSUE THREAD

**Issue by marcus-campos** [laravel/internals#860]
I am trying to install a package that has routes, however, when it is with the packager auto discovery it does not recognize and when I register directly in config / app.php, it works perfectly.

**Comment by marcus-campos** [comment]
The package discovery works only in http mode

**Comment by skyrpex** [comment]
Why should HTTP/HTTPS affect the package auto-discovery thing?

**Comment by marcus-campos** [comment]
I used the include instead of using the function to load the routes of my package.
