### ISSUE TITLE
[Proposal] Standard Deviation function for collections

### ISSUE THREAD

**Issue by BackEndTea** [laravel/internals#866]
Collections already offers functions for doing calculations with its entries, so calculating the standard deviation shouldn't be too strange a function to have.

It should work roughly the same as [stats_standard_deviation](http://php.net/manual/en/function.stats-standard-deviation.php) but without the need for the extension. 

It should be able possible to call it in the same way as the [```sum()```](https://laravel.com/docs/5.5/collections#method-sum) function. Except that the second parameter should be a bool which tells the function if it is working with sample or population data.

* With no parameters for the stdev of the collection
* With a string to determine which values to calculate with
* With a callback, incase you'd need to alter/calculate the numbers first.

An issue i can think of beforehand is that it won't be 100% accurate, simply because of how decimal numbers are handled in php.

If i created this issue in the wrong place or something like that, please let me know.

**Comment by sisve** [comment]
This is indeed the correct place for these type of suggestions.

I see one ambiguity in the specification:

> * With a string to determine which values to calculate with
> * With a callback, incase you'd need to alter/calculate the numbers first.

There's no clear definition of "callback"; it should be either `callable` or `Closure`. You are probably thinking of `callable`, but those can also be strings and arrays, and that would cause coding problems; how would you know if the string I give you should be treated as a callable or as a "string to determine which values to calculate with"? A closure, on the other hand, only supports anonymous functions and will not support normal functions.

**Comment by BackEndTea** [comment]
I was thinking of a ```Closure```, so it would be possible to use the function in the following matter

```php
$collection->stDev(function ($product) {
    return count($product['colors']);
});
```
If you were trying to get the standard deviation of the amount of colors of your products. This would be in line with how other collection functions work. As i don't think those support ```callable```.

I should get around to coding it later today, so I'll see if i run into any problems with the Closures.
