### ISSUE TITLE
[Proposal] migrate:refresh from newest to oldest

### ISSUE THREAD

**Issue by icetique** [laravel/internals#868]
Would be great if there will be a possibility to specify (or even make it by default) the order of the migrations that are going down in the reverse order. It would help rebuilding the database properly when the foreign keys are present. Right now the migrations are going down from the oldest to the newest which is quite not-natural.

For example we could do something like this:
```
public function up()
{
    ...
    $table->foreign('some_another_table')->...
```

```
public function down()
{
    Schema::table('some_table', function (Blueprint $table) {
        $table->dropForeign(['some_another_table']);
    });
    Schema::dropIfExists('some_table');
}
```

Instead of disabling foreigns checks with `Schema::disableForeignKeyConstraints();` which do not give such control over specified migration. What do you think?

**Comment by LKDevelopment** [comment]
I think, the way from the oldest to the newest is the only right way. You make a migration once, and every new migration represents a new state of the database. So it is normal that the oldest will be executed first.

**Comment by sisve** [comment]
It's unclear what this suggestion is about. Can you provide a more clear example of what you're trying to accomplish? What is the current problem, and what is your suggestion?

**Comment by icetique** [comment]
@LKDevelopment If you want to revert last 3 migrations you do what? First, you undo the last one, then you undo the previous one and so on. I only say that the refresh (which in my opinion is "revert all the migrations" should revert the migrations in the reverse order they were created. I don't see the point for down() method without this kind of behavior but maybe I get it wrong.

Maybe you guys can explain me for what purpose the down() method is if every migration represents new state, do you suggest me that I should undo things with new migration file? I understand that this is expected behavior for the collaboration and sharing migrations with the team, but on local development I would expect that refresh will fire the migrations down in the reversed order they were created, so I could revert the changes I made. I think that's why up() method CREATES table, and down() method DELETES it, it's just the opposite. The same should be with foreign keys: up() method creates foreign key, down() method delete it. It's impossible to do a refresh without disabling foreign key check when the migration down() method fires from the first to last. The foreign keys need to be deleted in the reverse order they were created.

**Comment by sisve** [comment]
> I only say that the refresh (which in my opinion is "revert all the migrations" should revert the migrations in the reverse order they were created.

>  I would expect that refresh will fire the migrations down in the reversed order they were created, so I could revert the changes I made.

This is already how it works. `migrate:refresh` calls `migrate:reset` which calls Migrator::reset() which in turn executes the migrations in the reverse order they were originally executed. https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Migrations/Migrator.php#L275-L278

**Comment by 36864** [comment]
I'm unable to replicate your problem. When I use `migrate:refresh`, rollbacks are called from newest to oldest and then migrations are run from oldest to newest.
```
D:\projects\test>php artisan migrate:fresh
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2017_11_07_105317_create_notes_table
Migrated:  2017_11_07_105317_create_notes_table
Migrating: 2017_11_07_105339_create_plans_table
Migrated:  2017_11_07_105339_create_plans_table

D:\projects\test>php artisan migrate:refresh
Rolling back: 2017_11_07_105339_create_plans_table
Rolled back:  2017_11_07_105339_create_plans_table
Rolling back: 2017_11_07_105317_create_notes_table
Rolled back:  2017_11_07_105317_create_notes_table
Migrating: 2017_11_07_105317_create_notes_table
Migrated:  2017_11_07_105317_create_notes_table
Migrating: 2017_11_07_105339_create_plans_table
Migrated:  2017_11_07_105339_create_plans_table
```

**Comment by icetique** [comment]
You are right, I double checked this and now it runs as expected. Not sure what was the problem before.

Sorry for taking your time.
