### ISSUE TITLE
[Proposal] Default values on pivot table

### ISSUE THREAD

**Issue by sushchyk** [laravel/internals#872]
When you define a Many-To-Many relationship in your model, you can use `wherePivot` method for filtering it.
Some people use this feature, and create relationships like these in models:

```
class Club extends Model
{
    ....
    public function admins()
    {
        return $this->belongsToMany(User::class)->wherePivot('is_admin', 1);
    }

    public function members()
    {
        return $this->belongsToMany(User::class);
    }
   ...
}
```
But when you save relationship you still have to set pivot data:
`$club->admins()->save($user, ['is_admin' => 1]);`

I think, it confusing at first sight, and a little tedious because you always need to define pivot data if it different from default table values.
   And I didn't find the way to set default pivot values on Many-To-Many relationship in documentation actually.
   Also, some people([link](https://github.com/laravel/framework/issues/5242), [link](https://laravel.io/forum/07-21-2014-default-values-on-pivot-table-for-attachsave)) asked how to do it, but they didn't get the answer.

So my proposal is to allow to define default pivot values, which will be used both for filtering and for saving:
Something like this:
`$this->belongsToMany(User::class)->pivotValues(['is_admin' => 1]);`

**Comment by zohaibhassan156** [comment]
Is there any to set default value of additional attributes??
Something like I want to set default status id

```
    public function equipments()
    {
        return $this->belongsToMany(Inventory::class, 'ticket_equipments')
            ->withPivot(['billing_type_id', 'amount', 'date_time_returned', 'status_id'=>TicketEquipment::STATUS_PENDING])
            ->withTimestamps();
    }
```

like default attributes on Model
```

    protected $attributes = [
        'status_id' => self::STATUS_PENDING,
    ];


```

**Comment by Stalinko** [comment]
Why is it closed? This proposal wasn't implemented. It is still impossible to specify default attributes for a `Pivot`.

**Comment by PEscar** [comment]
my case:
i add an extra column uuid in every table of my db, as unique column.
then, i build a "Base" model, extending Model, and in the constructor:
public function __construct(array $attributes = []){

		$this->uuid = Str::uuid();
        parent::__construct($attributes);
    }

All OK until here.

Now, i have some polimorphic relations, and i cant do a 
$model_instance->relation()->attach([$polimorfic_id]);

because it dont call the constructor method, and i receive this exception:

General error: 1364 Field 'uuid' doesn't have a default value (SQL: insert into  ......

Workaround ?? I like to use attach / sync / and variations on my polimorfic relations...

**Comment by forrestedw** [comment]
I'd also like to be able to set a default value on a custom pivot. I like @zohaibhassan156's suggestion.

**Comment by bilogic** [comment]
Same here, can we have it like @zohaibhassan156's suggestion?

**Comment by djhrcode** [comment]
Think I've found the way to do this, but, maybe it's not documented yet. Basically you only need to use the `withPivotValue` method. You can find the function's definition here 👉🏼 👉🏼  https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L453

Your relationship definition will end up like this.

```
    public function tags(): BelongsToMany
    {
        return $this->morphToMany(Tag::class, 'taggable')
            ->withPivotValue('is_explicit', true)
            ->wherePivot('is_explicit', true);
    }
```

Also you can define the pivot table default values using an associative array ['column' => defaultValue] as shown in the example below. This could be useful to define multiple columns default values.

```
    public function tags(): BelongsToMany
    {
        return $this->morphToMany(Tag::class, 'taggable')
            ->withPivotValue(['is_explicit' => true])
            ->wherePivot('is_explicit', true);
    }
```

This way worked for me. Hope this may helps someone else 😃
