### ISSUE TITLE
[Question] Is there any reason the base Eloquent Model class handles timestamp fields (created_at, updated_at) as Carbon objects but not the softDelete field (deleted_at)?

### ISSUE THREAD

**Issue by Payden-Pringle** [laravel/internals#877]
Relevant Laracast thread: https://laracasts.com/discuss/channels/eloquent/timestamps-are-formatted-as-carbon-objects-while-softdelete-fields-are-not

An example:

```
>>> Task::find(2)->withTrashed()->get()->first()->deleted_at
=> "2017-11-10 10:57:59"

>>> Task::find(2)->withTrashed()->get()->first()->updated_at
=> Carbon\Carbon {#793
     +"date": "2017-11-10 10:56:09.000000",
     +"timezone_type": 3,
     +"timezone": "America/Chicago",
   }
```

I would expect them to be handled similarly or the same, but it seems they are not.

**Comment by brunogaspar** [comment]
It's mentioned on the [documentation](https://laravel.com/docs/5.5/eloquent#soft-deleting) that you need to add the `deleted_at` column to the `$dates` property on your model.
