### ISSUE TITLE
[Proposal] Compile blade @lang to Lang::trans instead of app('translator')

### ISSUE THREAD

**Issue by progsmile** [laravel/internals#878]
I suppose it would be faster for performance to compile blade `@lang` to `Lang::trans`, instead of resolving `translator`. May be it's nano seconds optimization, but we can do it)

**Comment by brayniverse** [comment]
Doesn't the `Lang` facade just defer to the `translator` instance in the service container anyway?

**Comment by progsmile** [comment]
I realized that's silly optimization, but still Facade makes less 'body-movements'.
All facades refer to static `$resolvedInstance` field, while Container getting alias, and goes to instances. 
There are more issues to do, so no need
