### ISSUE TITLE
[Proposal] Log to different files

### ISSUE THREAD

**Issue by clarkeash** [laravel/internals#884]
Instead of only logging to the standard 'laravel.log' file (or similar for daily files) it would be useful to be able to log to a different file.

```php
Log::info('something' []); // logs to laravel.log
Log::to('other-file')->info('something' []); // logs to other-file.log
```

What are your thoughts on this?

Also it would be nice to be able to set the default file name in config rather than it always being named 'laravel.log'

**Comment by clarkeash** [comment]
Or maybe it could work more like how database is configured:

```php
'default' => 'main',
'connections' => [
    'main' => [
        'file' => 'laravel',
        'setting' => 'single'
    ],
    'other' => [
        'file' => 'other-file',
        'setting' => 'daily'
    ]
]
```

And then you would do something like:

```php
Log::to('other')->info('something' []);
```

Would need to figure out better names for this.

**Comment by tomschlick** [comment]
This PR should handle what you're looking for: https://github.com/laravel/framework/pull/21152

**Comment by clarkeash** [comment]
Great thanks @tomschlick
