### ISSUE TITLE
[BUG] Laravel 5.3 and route model binding

### ISSUE THREAD

**Issue by kaidoj** [laravel/internals#890]
Hey.
Little bug i found. When you have used "php artisan route:cache" then the route model binding lets say post/comments/{comment} (yes comment is binded to model in routes file) returns id in custom middleware not the whole object. I tested it live and dev. On dev i have route:cache disabled and it returns object. On live i disabled route cache and it started returning object instead id, wich is the right way.

**Comment by Dylan-DPC** [comment]
2 things:
1) 5.3 is no longer supported
2) bugs should be reported in laravel/framework repo

**Comment by sisve** [comment]
Workaround: Call `Route::bind` in your RouteServiceProvider instead of using your routes file.
