### ISSUE TITLE
[Proposal] Improve migrations speed

### ISSUE THREAD

**Issue by gabriel-caruso** [laravel/internals#898]
I've got deep into `Laravel`'s core, and as I've understood, every `migration` opens a connection, creates its table and goes to the next one. Isn't faster to generate one single `.sql` file and then submit to the connection?

By single `.sql` file I mean: 

![img](http://alderprogs.com/Tutorials/TableImport_SqlFile/TableImport_SqlFile_04_view_file_Still.gif)

**Comment by skyrpex** [comment]
How would you report which of the migrations has crashed, in case there's one?

**Comment by 36864** [comment]
Is it really that big of a deal if your migrations take a few extra seconds to run? How often are you running them?

**Comment by gabriel-caruso** [comment]
@skyrpex When you say crash, you mean an `SQL` error? In this big migration file, if there is an error, it will be report.

**Comment by gabriel-caruso** [comment]
@36864 I have a project as an example:

- 33 `migrations`, each one with minimum 1 relationship;

**Comment by gabriel-caruso** [comment]
@36864 I have a project as an example: 33 `migrations`, each one with minimum 1 relationship. I'm testing an ACL algorithm with `Laravel Gates`, and I need to constantly run them.
It usually takes `1m20s` (I'm testing with an outside chronometer, if you can teach me how to do it inside Laravel :sweat_smile:), but, with this big `.sql` file, both in the command line and [`MySQL Workbench`](https://www.mysql.com/products/workbench/), it takes `15s`, between generate the file and import it.

**Comment by skyrpex** [comment]
> @skyrpex When you say crash, you mean an SQL error? In this big migration file, if there is an error, it will be reported.

But you will never know which one of the migrations have crashed.

Regarding speed: have you tried testing with in-memory SQLite? It's quite fast. Also, you can cherry-pick whatever tests are relevant to your code when you're developing.

**Comment by gabriel-caruso** [comment]
Hm, didn't think about changing my database. Gonna test it :thinking:
