### ISSUE TITLE
Improve Typecasting

### ISSUE THREAD

**Issue by AdenFraser** [laravel/internals#9]
This has been discussed before in different issues raised laravel/framework.

I think it would be rather handy if Eloquent's typecasting was extendable, so that as well as being able to automatically cast to the existing:
`integer`, `real`, `float`, `double`, `string`, `boolean`, `object`, `array`, `collection`, `date` and `datetime`
That we could also cast to custom cast types. 

For instance when using value objects this would allow the automatic casting of a dec to a Money type object.

Thoughts?

**Comment by sebastiandedeyne** [comment]
Been pondering about the idea of casting to custom objects myself. Rough idea: classes that implement an interface with some sort of serialize & unserialize method, the class name could then be passed in the `casts` array.

```php
interface DatabaseCastThing
{
    public function fromDatabase();
    public function toDatabase();
}
```

```php
class Email implements DatabaseCastThing
{
    // ...
}
```

```php
protected $casts = ['email' => Email::class];
```

**Comment by valorin** [comment]
Is there a reason you don't want to use [Accessors & Mutators](https://laravel.com/docs/5.2/eloquent-mutators#accessors-and-mutators) for this purpose?

**Comment by AdenFraser** [comment]
Well for starters, if you use accessors and mutators the result is an awful lot of code duplication.

If you have a Model with 10 castable values, that's 10 accessors and mutuators you'd have to setup, chances are this would be across multiple models. The only way I can see you'd avoid that is either through an abstract model (assuming each model shares similar values) or through a castable trait. 

The other problem with accessors & mutators (and even the existing casting) is that nullable values required additional logic which again adds code duplication.

Imagine reproducing this:
```
    public function getOriginalPriceAttribute($value) 
    {
        if (is_null($value)) {
            return $value;
        }

        return new Money($value);
    }


    public function setOriginalPriceAttribute($value)
    {
        if (is_null($value)) {
            $this->attributes['money'] = $value;
        }

        $this->attributes['money'] = $value->toDecimal(); // or automatically to string via __toString(); etc.
     }
```

^That's an awful lot of code for what is essentially some incredibly simple typecasting.

Neither of these is a terribly elegant solution, compared to that of @sebastiandedeyne's idea above. Even there the toDatabase() method shouldn't be required in the interface... since an a value casted to an object with __toString(); would work just fine (assuming that is what the end-developer wants).

**Comment by martinbean** [comment]
I’m in the Accessors & Mutators camp for this.

**Comment by alexbilbie** [comment]
Casting to and from JSON would be useful too

**Comment by arcanedev-maroc** [comment]
How about dynamic casting (like polymorphism) sorted in a custom db column (castables) ?

**Comment by valorin** [comment]
Thanks for the detailed answer @AdenFraser - that's definitely a valid use case, would simplify a lot of repeated code for common things (common value objects come to mind!). Accessors and Mutators are great for simple one-off stuff, but it'd be nice to have the power of a class too without a lot of scaffolding. :-)

> Casting to and from a JSON blob would be useful too
@alexbilbie I thought you could already do this using `object` or `array`?

**Comment by robclancy** [comment]
Not sure why anyone would ever be against this. I actually expected it to just allow a custom type when I first used casting. It's just something one would naturally expect it to support and would be very easy to do so.

**Comment by AdenFraser** [comment]
@taylorotwell What are your thoughts in regards to this? Obviously there are quite a few thumbs ups above aswell but having your go ahead before spending some time on a PR would be great!

**Comment by themsaid** [comment]
@AdenFraser I think you need to make the PR man :) the idea is quite interesting, now it's time to discuss implementation.

**Comment by taylorotwell** [comment]
Agree could be cool!

**Comment by AdenFraser** [comment]
Going to start putting some code together today and will put a PR together as a WIP

**Comment by AdenFraser** [comment]
Thrown together an early draft https://github.com/laravel/framework/pull/13315

**Comment by barryvdh** [comment]
Casts are usually one-way right? Just for getting the data from the database, with the exception of json/datetime, which are also converted back. So do you want to account for the 'back', case as well?

Also, isn't it easier to register custom casts, like the Validation? https://laravel.com/docs/5.2/validation#custom-validation-rules

```php
TypeCaster::extend('money', function($attribute, $value, $parameters, $caster) {
	$currency = isset($parameters[0]) ? $parameters[0] : '$';
	return new Money($value, $currency);
});

TypeCaster::extend('html', 'App\Html@convert');
```

Usage like this:
```
 protected $casts = [
        'amount' => 'money:£'
	'html_string' => 'html',
    ];
```

If you want to convert back, perhaps we could consider a second callback.

```php
TypeCaster::extend('money', function($attribute, $value, $parameters, $caster) {
	return Money::fromString($value);
}, function($attribute, $value, $parameters, $caster) {
	return Money::toString($value);
});

TypeCaster::extend('html', 'App\Html@encode', 'App\Html@decode');
```

Which would essentially be mutators I guess, but with easier configuration.

**Comment by robclancy** [comment]
Just do it like mutators in the model. You are overthinking this a lot. It
can be as simple as looking for a method called `{castname}Cast`. Or could
just be a single method where you can insert your own catings just like the
current ones work.

Models dont use a factory so doing it like the validator extending or blade
extending just wont work. It should be in object scope not class scope.

**Comment by robclancy** [comment]
Also why would this need converting back?

**Comment by barryvdh** [comment]
If you cast it to an object and modify it, you want to return it to a value you can store in database, right?

**Comment by tomschlick** [comment]
Yeah I definitely think there should be a `toDatabase` method of some sort. By default it could just use `__toString()` but for more complicated implementations it would be useful to have, especially since `__toString()` is horrible for reporting errors.

**Comment by robclancy** [comment]
What, no? If you need to return it to the database you are using this
wrong. That is what mutators are for. Casting has a single use, to cast for
the JSON response. So for example JS doesn't do dumb things because you
accidently sent it your int in string form. If you need to cast something
and return it to the database at a later date that is the exact use case
for attribute mutators.

**Comment by tomschlick** [comment]
If you modify something in the cast object and then save the model it has to find its way back to the database. This is how the current casts system works. Try it with the carbon dates, it uses __toString() on the carbon instance.

**Comment by robclancy** [comment]
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L2473

I don't see how that is modifying the model at all? It just casts for the attributes it is returning?

**Comment by tomschlick** [comment]
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L2484

Shows how the dates are formatted with the `serializeDate()` method

**Comment by robclancy** [comment]
Yes, for the `toArray` method which then goes to a JSON response. It
doesn't touch the underlying attributes? Casting an object returns the
casted attributes, it doesn't change anything you can save like normal
(unless I am missing something, and if I am I would say that is a bug).

**Comment by AdenFraser** [comment]
If you cast to datetime and simply use Carbon's ->addDay () method before
saving... the date stored in the database will be one day in the future
than it was before.

For instance

```php
    $product->released_at->addDay ();
    $product->save ();
```

On the save action the Carbon instance is converted __toString in the
format the Eloquent date format is required in... with any modifications.

The same way if you modify a casted json array and subsequently save... it
gets updated. Or an array or any ither cast for that matter.

**Comment by robclancy** [comment]
Then you are using casts wrong and shouldn't do that. Why would you ever cast something and then save it? Casting happens as the last thing to send a response. And even if you did need to save after casting if you have a cast method that changes the model attributes in some way that is a bug in your code because you are doing it wrong.

**Comment by robclancy** [comment]
The exact thing could happen with attribute mutators because it is simply not how you should do things.

**Comment by AdenFraser** [comment]
In the case of a Money cast, something like this could be very simple (and
relatively useless) use case:

```php
    $invoice->balance->reduce (2.50):
    $invoice->due_date->addYear ();
    $invoice->save ();
```

The resulting row update for the model would perform the Money reduction
and the Date addition based on the casted objects __toString () return
value...
On 27 Apr 2016 00:21, "Aden Fraser" <aden@fraserjilani.com> wrote:

If you cast to datetime and simply use Carbon's ->addDay () method before
saving... the date stored in the database will be one day in the future
than it was before.

For instance

```php
    $product->released_at->addDay ();
    $product->save ();
```

On the save action the Carbon instance is converted __toString in the
format the Eloquent date format is required in... with any modifications.

The same way if you modify a casted json array and subsequently save... it
gets updated. Or an array or any ither cast for that matter.

**Comment by robclancy** [comment]
What? You are making zero sense. What has that code got to do with casting at all?

**Comment by AdenFraser** [comment]
This is achievable using mutators, you are correct. But i don't understand how you can claim that casting can only be the last thing that happens before we send a response.

If that's the case then why is Eloquent casting dates to Carbon objects? Presumably based on what you are saying, just for response purposes, rather than for providing an API for manipulating dates.

**Comment by robclancy** [comment]
It doesn't even matter if it is last or not. Casting doesn't change the attributes at all. Eloquent casts to Carbon completely separate to casting. Casting has a single use, to cast attributes to their types for use in a JSON response. Casts are done when `toArray` is called and that is then JSON encoded.

**Comment by robclancy** [comment]
Dates are mutated: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L2867

Casts have nothing to do with this. Casts ONLY return different types for the JSON response. They do not modify attributes in any way (unless you do it wrong after the proposed PR is merged).

**Comment by AdenFraser** [comment]
No it's not separate at all, try it out for yourself. Add a few extra columns, date, datetime, collection and cast them. Look at the Eloquent Model Api: 

```php
 public function getAttributeValue($key)
    {
        $value = $this->getAttributeFromArray($key);

        // If the attribute has a get mutator, we will call that then return what
        // it returns as the value, which is useful for transforming values on
        // retrieval from the model to a form that is more useful for usage.
        if ($this->hasGetMutator($key)) {
            return $this->mutateAttribute($key, $value);
        }

        // If the attribute exists within the cast array, we will convert it to
        // an appropriate native PHP type dependant upon the associated value
        // given with the key in the pair. Dayle made this comment line up.
        if ($this->hasCast($key)) {
            $value = $this->castAttribute($key, $value);
        }

        // If the attribute is listed as a date, we will convert it to a DateTime
        // instance on retrieval, which makes it quite convenient to work with
        // date fields without having to create a mutator for each property.
        elseif (in_array($key, $this->getDates())) {
            if (! is_null($value)) {
                return $this->asDateTime($value);
            }
        }

        return $value;
    }
```

Clearly when you call for an attributes value, if a mutator doesn't exist the next operation is to check for a cast AND PERFORM CASTING if a cast exists.

**Comment by robclancy** [comment]
Then I stand corrected. And disagree with the casting working like that altogether. And also then disagree with custom casting doing more than just small things because of reversing being needed and when you add that you have just made attribute mutators.

**Comment by AdenFraser** [comment]
But you have made attribute mutators which can readily be reused, on multiple models and multiple attributes without the duplicate code bloat required by using mutators.

**Comment by robclancy** [comment]
Then instead I think you should be adding the ability to do exactly as you just described. Not manipulating casts into a form of mutators that are a little more reusable. Just make current mutators reusable.

**Comment by AdenFraser** [comment]
@robclancy Now that is a new tanget of discussion entirely and one perhaps worth exploring. It all comes down to the expected functional difference between a cast and a mutator and making that clearly defined.

**Comment by robclancy** [comment]
Well the definitions are fairly clear. One is for casting types and one is mutating values. Once casts do more than change type they are mutating.

**Comment by robclancy** [comment]
This could be as simple as the base model having methods (or a trait) like `usdGetMutator` and `usdSetMutator`. Then a `$mutate` array working similar to the casts array.

But with better names for things.

**Comment by AdenFraser** [comment]
Sure. But if you are casting a monetary figure from a column into a monetery data type, then it's not exactly being mutated (because the underlying value hasn't immediately chnaged) it has just been cast to a different data type.

According to the eloquent docs:
```The $casts property on your model provides a convenient method of converting attributes to common data types. ```

``` The supported cast types are: integer, real, float, double, string, boolean, object, array, collection, date, datetime, and timestamp.```

**Comment by robclancy** [comment]
If that can easily save back then sure casts can work for that. And I still think we need to be able to do our own castings but it should be for very simple things. Anything more should be a mutator.

**Comment by robclancy** [comment]
Also if you clone the object before modifying it in the custom cast then this reverse issue goes away for the most part.

**Comment by AdenFraser** [comment]
Obviously it depends largely on use scenario. The docs suggest accessors and mutators for lowercase, uppercase, titlecase etc for first_name and I completely agree with that.

Casting to a Laravel Collection is provided as one of the cast types but I don't see any reason why an extended instance of a Collection shouldn't be castable too.

**Comment by AdenFraser** [comment]
I don't understand how the reverse issue is an issue. For instance if I store a json_encoded array of data in a column and I cast it to a collection, I want to be able to do things such as:

```php
     $casts = [
         'casted_collection' => 'collection'
     ];
```

```php
     $model->castedCollection->prepend('new first value')->push('new end value');
     $model->save();
```

And when the Eloquent Model is saved, the casted Collection is converted back to JSON, thanks to:

```php
 /**
     * Convert the collection to its string representation.
     *
     * @return string
     */
    public function __toString()
    {
        return $this->toJson();
    }
```

And thus my revised values are stored in the database.

This is far simpler than having to define this combo in the model, no?

```php
    public function getCastedCollectionAttribute($value)
    {
          return new Collection(json_decode($value));
    }
  
    public function setCastedCollectionAttribute($value)
    {
          $this->attributes['casted_collection'] = $value->toJson();
    }
```

**Comment by robclancy** [comment]
That is a very weak way of attribute mutating restricted to just `__toString()`.

**Comment by AdenFraser** [comment]
It's late and I don't quite follow, so I'll let someone chime in and await some feedback on the WIP PR.

But as far as I'm aware this can prove to be a useful piece of additional functionality and I'm sure others agree but I'll wait for some other voices to confirm one way or another.

**Comment by JosephSilber** [comment]
I for one agree with Aden: casts should definitely work both ways.

**Comment by robclancy** [comment]
Then they should just be more "global" mutators.

**Comment by tomschlick** [comment]
On another note, the approach by @barryvdh was very nice. I would only suggest one thing, if only one param is submitted it should just be the class name and we would assume there is a `toDatabase()` /  `fromDatabase()` or some default method on the class from the interface.

```php
TypeCaster::extend('html', App\Html::class);
```

**Comment by tomschlick** [comment]
That allows you to do the class imports and leaves less room for error as its no longer in a string.

**Comment by deringer** [comment]
Mutating should go both ways, but I'd be inclined to leverage `__toString` in most (all?) cases, given you're going to be putting text representations of your data into the database most of the time, right? Even a binary field is a textual representation of that content.

Or is the intention to store the serialized object wholesale into the database and unserialize it? In @AdenFraser's earlier example, he's using a mutator (`setOriginalPriceAttribute`) to explicitly call a method on the `Money` value object. Would it not make sense to just leverage `__toString`? Then again, you still have issues in dealing with `null`.

**Comment by tomschlick** [comment]
Using __toString() also removes your ability to debug if there are errors. Instead of the normal stack trace, you'll get "__toString() must not throw an exception" and it mutes the actual exception from the error.

**Comment by barryvdh** [comment]
The money object could be a formatted amount as strong, but perhaps you would want to store the integer value in the database. Or you could store an uuid as 16 bytes, but still want the 36 string version displayed as string in the front end.

What this could also achieve perhaps, is using the casts for the where* clause. En ->where('amount', $moneyObject), same as the datetime conversions.

And yes, custom casts would be very similar to mutators, only easier to reuse.

**Comment by sebastiandedeyne** [comment]
What if we'd have the caster mutate the model instead of returning a serialized value? Another example implementation, similar to @barryvdh's:

```php
class MyModel extends Model
{
    protected $casts = [
        'price' => 'money',
    ];
}
```

```php
class CastsMoney
{
    public function get($model)
    {
        return new Money($model->price_amount, $model->price_currency);
    }
    
    public function set($model)
    {
        $model->price_amount = $value->getAmount();
        $model->price_currency = $value->getCurrency();
    }
}

Casts::extend('price', CastsMoney::class);
```

Advanced: You could pass values as parameters, for example the field names, or a hard coded currency like in the previous example.

```php
class MyModel extends Model
{
    protected $casts = [
        'price' => 'money:amount,currency',
    ];
}
```

```php
class CastsMoney
{
    public function get($model, $amount, $currency)
    {
        return new Money($model->$amount, $model->$currency);
    }
    
    public function set($model, $value, $amount, $currency)
    {
        $model->$amount = $value->getAmount();
        $model->$currenct = $value->getCurrency();
    }
}

Casts::extend('price', CastsMoney::class);
```

I think this would cover everything we want:

- Define reusable custom accessors and mutators in `$casts`
- Getters and setters
- Create value objects from multiple fields

**Comment by tomschlick** [comment]
FYI, a new PR has been opened by @tillkruss to further the work that was started on this.

https://github.com/laravel/framework/pull/18106

For now discussion it is locked as it is a work in progress.

**Comment by lioannou** [comment]
@tillkruss - in your PR (which is locked so I cant comment there) - your example says:

```
// set entire object
$user->address = new Address('19111 Pruneridge Avenue', null, 'Cupertino', 'CA', '95014', null);
$user->save();
```
and
```
// This however does not work:
$user->token = new Token('larav3l-secr3t');
$user->save();
```

What is the difference between those two examples that will cause one to work and not the other? I cant see an obvious reason.

**Comment by tillkruss** [comment]
That was actually a typo. I fixed it earlier today.

```php
$user->token = 'larav3l-secr3t'; // does not work
$user->save();
```

**Comment by robclancy** [comment]
Why is it locked?

**Comment by tillkruss** [comment]
Because I don't want people to comment, yet. If you have valuable feedback, ping me in Slack.

**Comment by robclancy** [comment]
What a bizzare thing to do. Just don't PR until ready...

**Comment by tillkruss** [comment]
Valueless, off-topic comments like that. That why it's locked.

**Comment by robclancy** [comment]
Wow I see now. Because you're a disrespectful little snowflake.

**Comment by franzliedke** [comment]
Ignoring Robbo's comments for a while, I too agree that it would be helpful to allow feedback directly on the PR, *especially* since it is work in progress. ;)

**Comment by robclancy** [comment]
That's actually agreeing with my comments. It's the entire point of a pull
request. Locking it is just disrespectful to anyone following this feature
request. It is saying to every one of them that they aren't good enough to
comment on the super amazing PR.

Regardless they will just discuss here anyway. So not only is the reason
for the lock stupid but it is ineffective.

**Comment by franzliedke** [comment]
Well, I don't agree with your tone.

**Comment by robclancy** [comment]
Yeah because his tone was so welcoming. He was hostile first and the reason
for "valueless" discourse in the first place. Ironic really.

On Sun, 26 Feb 2017, 04:27 Franz Liedke <notifications@github.com> wrote:

Well, I don't agree with your tone.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/laravel/internals/issues/9#issuecomment-282502595>, or mute
the thread

**Comment by sisve** [comment]
The current implementation in https://github.com/laravel/framework/pull/18106 has a large flaw; it requires ownership of the objects you cast to. That is often not the case; an example are people using https://github.com/nicolopignatelli/valueobjects which would require an intermediate casting layer. Something like a TokenConverter that has a `convertToPHPValue($value)` and `convertToDatabaseValue($value)`

**Comment by sisve** [comment]
Can someone explain why this issue is so secretive that I need to talk to @tillkruss in a hidden thread in #internals on Slack instead of commenting in the PR?

Additional things I've told @tillkruss in previously mentioned secretive thread;
1. The intermediate casting object (hereby known as ConverterThingie) should have an interface, and all methods should be instance methods.
2. The ConverterThingie should be instantiated using the container so it can have dependencies.
3. The current implementation will not ask the ConverterThingie about null values. This sounds wrong, the ConverterThingie's sole purpose in life is to convert things, it should be asked how to convert null values.

**Comment by barryvdh** [comment]
I don't get it either. If you're not sure about the architecture, discuss that privately before creating a PR.
If you're not ready for feedback, work on it locally before creating a PR.

If you do create a PR, accept feedback on it. These discussions are very valuable to read back later, to understand why something is done this way. Redirecting to Slack just means it's lost after a few days.

I really hope this isn't a trend.. IMHO locking should be reserved for out of control threads with just spam, not reasonable discussions..

**Comment by lagbox** [comment]
Can we please stop this secretive nonsense. The point of this repository is so that shit isn't just on slack which disappears. This creates paper trails so other people can actually see the conversations and IDK maybe not waste their fucking time on things that have already been discussed that they couldn't possibly fucking know because they weren't on slack.   How many times does this obvious issue have to be pointed out?

**Comment by tillkruss** [comment]
Unlocked the thread and closed it. Will open new PR when it's ready.

**Comment by sisve** [comment]
For those that missed it; a new PR was opened and merged before further discussions were possible.

Every single point I made was ignored.

1. There is no "casting object" that can declare constructor dependencies needed for conversion.
2. No interfaces for this new functionality to conform to, instead it's specially named methods that need to implemented in every model.
2. Null values are still ignored by the casting layer.

A quick reminder from that hidden-in-history Slack thread.

![image](https://cloud.githubusercontent.com/assets/748375/23691793/061b6d6e-03cb-11e7-9ab7-76816914ffdc.png)

Did any of that happen?

**Comment by sisve** [comment]
It's way early in the morning and I misread the PR. It's not yet merged, and I updated my previous comment to remove that part.

I know I am bitter and filled of hatred, but could there at least be some notes about the different suggested implementations that show why those were declined? It's almost a year since the most thumbed-up (which I think means some kind of approval) comment suggested a way to do this, why wasn't that implemented? https://github.com/laravel/internals/issues/9#issuecomment-196547408

**Comment by robclancy** [comment]
I mean... his first PR showed he doesn't care what other people think. Instead of closing he will just ignore everyone because he is better than them (unless one of the Laravel "inner circle twitter gods").
