### ISSUE TITLE
Pagination Customization

### ISSUE THREAD

**Issue by browner12** [laravel/internals#90]
I submitted this [PR](https://github.com/laravel/framework/pull/11985) awhile ago to add support for Bootstrap 4 pagination, since we currently only supported Bootstrap 3.  It was merged, but I think it was agreed on by all that we need a better way to customize the paginator presenter so we are not coupled to  BS3, BS4, or any other concrete implementation.

Opening this issue to start the conversation.

My initial suggestion was a `pagination.php` to define the different markup for parts of the paginator.

Another possibility could be the user creates custom 'simple' and 'basic' presenter classes that then are bound in the `AppServiceProvider`.

**Comment by pedrommone** [comment]
:+1:

**Comment by taylorotwell** [comment]
This is done for 5.3.

**Comment by browner12** [comment]
thanks taylor.  appreciate it.
