### ISSUE TITLE
Improve support for legacy databases with soft-delete

### ISSUE THREAD

**Issue by alexbowers** [laravel/internals#92]
Currently when `use SoftDeletes` is used in a model, you can only override the `DELETED_AT` column. For legacy code bases, it is quite common for the `deleted` column to be a `boolean`. I can not find any support for this currently, with the current checks being `is null`. The ability to extend this using constants, as we can in the current `const DELETED_AT` method would be useful for people porting over old code bases.

**Comment by ameliaikeda** [comment]
For legacy, you can implement this with a custom global scope (and some event handlers on boot) in a trait, the same way `SoftDeletes` currently does.

I don't think Laravel should really be supporting legacy aside from providing the tools to do so, to be honest (which it does).
