### ISSUE TITLE
[5.3][Proposal] Blade Scope Directive / Scope for @section

### ISSUE THREAD

**Issue by AdenFraser** [laravel/internals#95]
I'm not sure if this is possible but could be a potential feature enhancement if it doesn't already exist? See below...

There are a couple fo Laravel Packages for extending for blade for @set directives which have not made it into the framework for whatever reason - presumably because it's agreed variables should be provided from controllers.

My idea (if it's not possible already) is to offer a '@scope' directive and potentially extend '@section' to allow setting of scope variables for use within a section.

This would allow variables to be temporarily set or aliases while inside the scope.

Take the following hypothetical example:

``` php
    // Make example view with a Collection of Users assigned to $users 
    // and a random variable assigned to $team;
    return view('example', ['users' => $users, $team => 'This could be anything!']);

```

``` php
{{ $team }} {{-- Outputs: This could be anything! --}}

@foreach($users as $user) 

    {{-- Do lots of stuff with $user --}}

    @scope(['team' => $user->team])

        {{-- Within the scope, $team = $user->team --}}

        {{ $team->name }}

        {{-- Do lots more  stuff with $team--}}

    @endscope

    {{-- Scope has been closed, so $team is 'This could be anything' --}}

@endforeach

{{ $team }} {{-- Outputs: This could be anything! --}}

```

This would behave in a similiar fashion to @includes second parameter, which can receive an array of data and assign the data to variables.

@section could be extended to allow:

``` php
@section('header', ['user' => \Auth::user()])
    <h1>
        You are logged in {{ $user->name }}
    </h1>
@endsection
```

I believe this would be extremely beneficial for instances where model relations of many levels are to be output, especially within loops, in blade templates.

Through the use of nested scopes long model method chaining could be eliminated for reach 'far away' relationship data.

Obviously this is all achievable using @include directives and creating separate blade templates which is fine for a lot of use cases. Though, there are occasions where it would be preferable to keep certain pieces of information within the single view  - especially if we are able to reduce long chained relation methods to more readable ones.

Thoughts?

**Comment by JosephSilber** [comment]
Use @php

@php($foo = 'bar')
