### ISSUE TITLE
[Proposal] Better HTTP 503 response view 

### ISSUE THREAD

**Issue by NicFontana** [laravel/internals#954]
Hello everyone,
when we put our application in maintenance mode with `php artisan down --messagge "Some info"`
the 503.blade.php view doesn't use the message we provide.

An improvement could be:

```blade
@extends('errors::layout')

@section('title', 'Service Unavailable')

@if ($message = $exception->getMessage())
    @section('message', $message)
@else
    @section('message', 'Be right back.')
@endif
```

instead of the current

```blade
@extends('errors::layout')

@section('title', 'Service Unavailable')

@section('message', 'Be right back.')
```

Cheers,
Niccolò

**Comment by sisve** [comment]
1. Are you attempt to file a bug report? Create an issue in laravel/framework.
2. Do you have code that solved the problem? Send a PR to the laravel/framework.

I do not think that you'll get anything out of submitting this for discussions as a new feature in laravel/internals.

**Comment by NicFontana** [comment]
Ok understood.
Thanks
