### ISSUE TITLE
HasOne and HasMany relation detach method

### ISSUE THREAD

**Issue by huuuk** [laravel/internals#96]
Hi, I wonder will be very handy to have method in HasManyOrOne class, which sets foreign key in related model to null. Something like detach method in ManyToMany class.
Perhaps It will be very handy when you need delete some model instance, but  keep it relations.
For example:
User.php

``` php
public function posts()
{
    return $this->hasMany('App\Post');
}

public function delete()
{
    $this->posts()->detach();
    return parent::delete();
}
```

**Comment by Decadence** [comment]
I was wondering about similar method once.
Now only way is delete related model or set key to NULL manually.
Detach could accept ID or Model instance to detach only this model not all.

**Comment by Radiergummi** [comment]
@taylorotwell you closed this issue, but `HasMany` still doesn't have a `detach` method. What is the canonical way of removing a relationship? I'm well aware I could just do `$model->post_id = null`, but manually dealing with ID fields seems counter-intuitive to using an ORM, especially one as high level as Eloquent.
