### ISSUE TITLE
Reconsidering the index offset when chunking or splitting a collection

### ISSUE THREAD

**Issue by michaeldzjap** [laravel/internals#963]
Take a simple collection
```php
$collection([1, 2, 3, 4])->chunk(2);
```
When you `dump()` this you get something like
```php
Collection {#558 ▼
  #items: array:2 [▼
    0 => Collection {#556 ▼
      #items: array:2 [▼
        0 => 1
        1 => 2
      ]
    }
    1 => Collection {#557 ▼
      #items: array:2 [▼
        2 => 3
        3 => 4
      ]
    }
  ]
}
```
Note that the indices of the second chunk don't start from 0, but instead reflect the index of the item in the original, unchunked collection. To be honest, I find this rather unintuitive for a collection holding an ordinary array. For a collection holding an associative array, e.g.
```php
$collection = collect(['a' => 1, 'b' => 2, 'c' => 3, 'd' => 4])->chunk(2);
```
then I'd say the original behaviour is correct, but for an ordinary array it really doesn't make much sense to keep the original indices for the chunks. The same applies to the `split()` method of `Collection` by the way. Thoughts?

**Comment by mfn** [comment]
Seems pretty legit to me.

That's simply the way `\array_chunk` works and no one is hiding that detail and I don't see a reason it should be done.

What is the problem exactly it causes to you?

**Comment by michaeldzjap** [comment]
Well let's agree to disagree then I guess. Take for instance
```php
collect([1, 2, 3, 4])
    ->chunk(2)
    ->map(function ($chunk) {
        // I want to access the items in the chunks manually for whatever reason
        $chunk->get(0);   // No go for the 2nd chunk, since its index starts at 2
        $chunk->get(1);   // same here... 
        ...
        return $something;
    });
```
Of course the above can be solved by doing
```php
collect([1, 2, 3, 4])
    ->chunk(2)
    ->map(function ($chunk) {
        $chunk = $chunk->values();   // This "resets" the indices of all chunks
       
        // This works now
        $chunk->get(0);    
        $chunk->get(1);
        ...
        return $something;
    });
```
Other than that I just find it counter intuitive. It's no big deal of course (it is easy enough to work around) but it just struck me as odd and not entirely correct.

**Comment by 36864** [comment]
One possible use of chunk is to process bits of an array in parallel. The original index of each element is important to properly report the results of said processing.

As you pointed out, there is an easy way of resetting indices in a chunk. If they were reset automatically, there would be no easy way of retrieving the original indices.

**Comment by michaeldzjap** [comment]
@36864 Yes, that is a good point actually. Retrieving the original index in case of index reset wouldn't be that hard really, but it will probably be more inconvenient than simply resetting indices in a chunk.

**Comment by mfn** [comment]
Agree to both of you. @36864 example is very poignant.

Given you figured our the trade-off, I don't think it makes sense to reconsider this.

> Well let's agree to disagree then I guess. Take for instance

Sorry if it sounded offensive what I wrote! I used `array_chunk` before I came to Laravel so it never occurred to me this might be an issue 🤷‍♀️

**Comment by michaeldzjap** [comment]
> Sorry if it sounded offensive what I wrote!

Not at all, don't worry. Just didn't agree 😄 

You make a good point there actually:
> That's simply the way \array_chunk works

I agree that if it is PHP's way of handling array chunks then it would not be a good idea to diverge from this for *Laravel* collections. I am not a huge PHP person, so wasn't aware of `array_chunk` working this way, so thank you for pointing this out.

So in conclusion, I still find it kind of an odd way of handling chunk indexes, but I agree that it shouldn't be changed for *Laravel* collections. You both convinced me. Thanks for your input.
