### ISSUE TITLE
[Proposal] Ability to return a 404 status code instead of 403 on authorization failure

### ISSUE THREAD

**Issue by nesk** [laravel/internals#964]
I have an idea for Laravel, I would like to know what you think about it before creating a PR. 🙂

Sometimes, on authorization failure, you need to hide the fact that a resource exists, this is frequently done by returning a 404 status instead of a 403 (like Github does for private packages you can't access). There's nothing to do that in a simple way with Laravel.

My proposition here is to alter the `authorize` and `authorizeForUser` method definitions, from:

```php
Response authorize(mixed $ability, mixed|array $arguments = [])
Response authorizeForUser(Authenticatable|mixed $user, mixed $ability, mixed|array $arguments = [])
```

to:

```php
Response authorize(mixed $ability, mixed|array $arguments = [], bool $anonymous = false)
Response authorizeForUser(Authenticatable|mixed $user, mixed $ability, mixed|array $arguments = [], bool $anonymous = false)
```

and create two method shortcuts which will call the respective methods above with `$anonymous` set to `true`:

```php
Response anonymouslyAuthorize(mixed $ability, mixed|array $arguments = [])
Response anonymouslyAuthorizeForUser(Authenticatable|mixed $user, mixed $ability, mixed|array $arguments = [])
```

When a `AuthorizationException` needs to be thrown, the `$anonymous` value would be passed to the exception constructor and stored in its instance. Then [the exception handler will check the `AuthorizationException`](https://github.com/laravel/framework/blob/205efa8701f18c996c8255161fdebd8c4646d291/src/Illuminate/Foundation/Exceptions/Handler.php#L200-L201) to see if the `anonymous` flag is set to `true`, and create accordingly a `AccessDeniedHttpException` or a `NotFoundHttpException`.

What do you think about that?

**Comment by mfn** [comment]
I agree with your goal (make it easier).

I'm not sure I agree with the API change though. Before discussing the API change you proposed: you said
> There's nothing to do that in a simple way with Laravel

Did you find any way to do it?

It seems to be the reason for 403 is the code in `\Illuminate\Auth\Access\Gate::authorize`:
```php
        $result = $this->raw($ability, $arguments);

        if ($result instanceof Response) {
            return $result;
        }

        return $result ? $this->allow() : $this->deny();
```
Because `deny` is implemented as:
```php
    protected function deny($message = 'This action is unauthorized.')
    {
        throw new AuthorizationException($message);
    }
```
However: what I also see is that if `$result` is of type `Reponse`, it's just returned to the client

Isn't enough in your authorization callback to just return the response you want, i.e. a 404 response?

**Comment by nesk** [comment]
Yes, you can *return* a response, but cannot *throw* it, thus you need to do this in your controller:

```php
public function index()
{
    if (($response = $this->authorize('my-ability')) instanceof Response) {
        return $response;
    }

    // Your code...
}
```

You will also need to return a `Response` from your authorization callback:

```php
Gate::define('my-ability', function ($user) {
    if (/* authorized */) {
        return true;
    } else {
        return response(/* ... */);
    }
});
```

I feel like returning a `Response` from your authorization callback when you authorize the user is a bit hackish… In addition to that, it's difficult to document.

With my proposal, you can simplify all of that with:

```php
public function index()
{
    $this->anonymousAuthorize('my-ability');

    // Your code...
}
```

>I'm not sure I agree with the API change though.

Could you explain what's bothering you?

**Comment by mfn** [comment]
> Could you explain what's bothering you?

It feels "too special cased".

Thanks for the insights about your workflow!

**Comment by nesk** [comment]
I understand what you mean, but anonymizing forbidden resources is pretty common. Since I don't find any easy solution provided by Laravel, I thought about this solution.

However, I admit there are some ways to implement that nicely in a custom project. For example, by overriding the `AuthorizesRequests` trait and adding the `anonymousAuthorize` and `anonymouslyAuthorizeForUser` methods to it.

**Comment by jrbarnard** [comment]
You could just throw a NotFoundHttpException in the policy method or gate ability function:
`
$gate->define('my-ability', function () {
        throw new NotFoundHttpException('test');
});
`

**Comment by nesk** [comment]
And what if I need to check this ability in another context ?

```php
if (Gate::allows('my-ability')) {
    //
} else {
    //
}
```

The `else` block will never execute.

**Comment by jrbarnard** [comment]
@nesk Good point, in that case why not just in the first place do the below instead of ->authorize()? If it requires reusing a lot you could just abstract it to be a method in your base controller?
`
if (!$gate->allows('my-ability')) {
    throw new NotFoundHttpException();
}
`

**Comment by MustafaMagdi** [comment]
Thanks @nesk, first, if we have to add a mask, so we add it not just for 403, but for 500, 503 and etc, so the end user doesn't know what is going on.
Second, if we need to add a mask for just `AuthorizationException`, we have another option, just check: https://laravel.com/docs/5.5/errors#the-exception-handler

```
public function render($request, Exception $exception)
{
    if ($exception instanceof AuthorizationException) {
        return new Response('Not found', 404);
    }

    return parent::render($request, $exception);
}
```

**Comment by nesk** [comment]
@jrbarnard Yes, the code is pretty to write. However, if it's that easy, why do we even have a `authorize` method? We could simply write:
`if (!$gate->allows('my-ability')) { throw new AccessDeniedHttpException(); }`

See my point?

@MustafaMagdi I don't really understand why the mask should be added for other kind of errors? Masking 403 codes with a 404 is a common practice to hide the existence of a resource if the user doesn't have access to it. Masking other errors with a 404 would only add confusion, so we can't use your code in the exception handler.

**Comment by nesk** [comment]
I'm closing the issue since I've got enough feedback, thank you guys. If you still want to argue, be free to write a message below, I will still answer you. 🙂

I will think of a better approach to implement that in Laravel and will create a PR.

**Comment by isometriq** [comment]
Why not use a try/catch block in the `anonymously` methods to catch `AuthorizationException` then "re-throw" a `NotFoundHttpException` or even `abort(404)` ?

This way it would not alter the original `authorize` method signatures.

**Comment by danielbachhuber** [comment]
@nesk Do you recall what approach you ended up taking here?

**Comment by danielbachhuber** [comment]
Here's how I ended up solving this (for a `product` resource) in `app/Exceptions/Handler.php`:

```php
/**
 * Render an exception into an HTTP response.
 *
 * @param  \Illuminate\Http\Request  $request
 * @param  \Exception  $exception
 * @return \Illuminate\Http\Response
 */
public function render($request, Exception $exception)
{
    // Turn a product 403 into a 404
    // to avoid exposing product names,
    // similar to how GitHub works with
    // private repos.
    if ($exception instanceof AuthorizationException
        && $request->route()->hasParameter('product')) {
        // use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
        $exception = new NotFoundHttpException;
    }

    return parent::render($request, $exception);
}
```

**Comment by MustafaOmarIbrahim** [comment]
I implemented some logic, wish it helps someone.
First, I call the method for example as nesk suggested `$this->anonymouslyAuthorize($model)`
Example:
```
public function show(Post $post)
{
    $this->anonymouslyAuthorize($post);

    // The user is authorized.
}
```
in your base controller which leaves in Controllers directory add this method.
```
public function anonymouslyAuthorize($model)
{
    Auth::user()->can('see', $model);
}
```
in AuthServiceProvider in the boot method define this Gate.
```
public function boot()
{
    $this->registerPolicies();

    Gate::define('see', function ($user, $model) {
        if ($user->id !== $model->user_id) {
            abort(404);
        }
    });
}
```

**Comment by lunfel** [comment]
I found this thread and wanted to share my solution which seems very close to how the OP wanted to use the functionality.

In my base Controller I define this method and use it when I want to throw a Not Found instead of Forbidden response:

```
/**
     * Same as authorize but instead throw Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     * instead of Illuminate\Auth\Access\AuthorizationException
     *
     * @param $ability
     * @param array $arguments
     * @return \Illuminate\Auth\Access\Response
     */
    public function authorizeAnonymously($ability, $arguments = [])
    {
        try {
            return $this->authorize($ability, $arguments);
        } catch (AuthorizationException $exception) {
            throw new NotFoundHttpException();
        }
    }
```
This could have also been defined in a trait and used in specific controllers.
