### ISSUE TITLE
"resource" is a soft reserved word in PHP 7

### ISSUE THREAD

**Issue by joshuanoyes** [laravel/internals#966]
I suspect this is already on the radar and is not a high priority issue, but just in case it's been overlooked: `resource` is a soft reserved word since PHP 7, so it has the potential to cause problems with `Illuminate\Http\Resources\Json\Resource` if the word does become reserved in the future.

From http://php.net/manual/en/reserved.other-reserved-words.php

> Whilst they may still be used as class, interface, and trait names (as well as in namespaces), usage of them is highly discouraged since they may be used in future versions of PHP.

Also see https://wiki.php.net/rfc/reserve_even_more_types_in_php_7

**Comment by mfn** [comment]
Good catch!

**Comment by laurencei** [comment]
@joshuanoyes - thanks for raising the issue! Good pickup.

I've done a PR for this here: https://github.com/laravel/framework/pull/22969

It'll be up to Taylor if it gets merged or not.

**Comment by joshuanoyes** [comment]
@laurencei Happy to help! Thanks for the PR.
