### ISSUE TITLE
[Proposal] Add Macroable trait to Paginator

### ISSUE THREAD

**Issue by monooso** [laravel/internals#986]
The `Illuminate\Database\Eloquent\Collection` class is currently macroable. This allows me to (for example) assert that the collection contains the desired number of items, and throw an exception if that is not the case.

```php
$result = User::whereIn('id', [1, 2, 3])->get();
$exception = new ExampleException('Some of our users are missing');
$result->assertCount(3, $exception);
```

Unfortunately, the `Illuminate\Pagination\LengthAwarePaginator` class is not macroable, meaning that I can't make the equivalent assertion on a paginator instance:

```php
$result = User::whereIn('id', [1, 2, 3])->paginate();
$exception = new ExampleException('Some of our users are missing');
$result->assertTotal(3, $exception);
```

Adding the macroable trait to the `AbstractPaginator` base class would fix this limitation. I'm happy to submit the PR, if this proposal is approved.

**Comment by joelbradbury** [comment]
Go for it.

**Comment by monooso** [comment]
Closing this, as the `LengthAwarePaginator` already supports macros, albeit it in an extremely obtuse way.

The `AbstractPaginator` implements the `__call` magic method, which proxies all unknown method calls to the paginator's `Illuminate\Support\Collection` instance. As the `Collection` class is macroable, this effectively means the `AbstactPaginator` inherits the functionality.

As I said, it's rather obtuse, but it works.
