### ISSUE TITLE
Internal Cache Mappings

### ISSUE THREAD

**Issue by alexbowers** [laravel/internals#99]
When using cache, invalidation is often one of the hardest things to get right.

A way around this is Internal Cache Mapping, where you relate one cache key with another, either on its own, or as part of a set.

A code example of how this may work is as follows: Mostly in pseudo-php code.

``` php
<?php namespace App\Http\Controller;

class ProductController extends Controller
{
    public function index($slug)
    {
      if(!Cache::has("Products/Search/{$slug}")) {
        $result = Search::logic();

        Cache::set("Products/Search/{$slug}", $result);

        Cache::map("Products/Search/{$slug}", "Products/Id/{$result->id}");
      }

      return Cache::get("Products/Search/{$slug}");
    }

    public function store()
    {
      $data = Input::data(); // Full form submitted 

      $result = Store::from($data);

      Cache::mappings("Products/Id/{$result->id}")->flush();

      return $result;
    }
}
```

The general idea of this is that on the index method, you may be getting a product by the `slug`. You will not, at this time, know what the `id` of the product is, but you have a unique identifier for a cache record. At this point here, it makes sense to use the `slug` for the cache key, and we can immediately either return the result if it is cached, or calculate the data and set the cache. 

The problem as it currently stands though, is that what happens when you update the product, for example, you change the price of the product in your admin system. This change now needs to be reflected across the system, however, currently you would have to flush all of the cache paths, and hope you got them all. A better way is to have an internal map between all related caches, so that flushing the parent one, would flush all the mapped caches too.

In the example here, clearing `Cache::mappings("...")->flush();` would flush `"Products/Search/..."` as well.

This means that there is no messy logic anywhere, with arrays containing all the related queries etc. 

Once you have a result, you will have the `id` to setup the map relationship, and so the mapping is just a single line that needs to be added.

Further benefits from this could come from searching. If you perform a search, there may be many hundreds of products in that one search, but not all of your products are. You want to be able to clear the search cache if it needs clearing, but not touch it if it doesn't need clearing.

What you can do with this internal cache map, would be  to have a loop mapping that product search cache key to each of the product ids in the search. Then, if you edit a specific product, all the searches  that contained that product can be flushed, and you will have left intact the ones that are not affected.

**Comment by alexbowers** [comment]
Example usage on a `remember` method call.

```php
<?php
Cache::remember("Product/Search/{$search_term}", function($cache) use ($search_term) {
  // Do something expensive, but non-deterministic
  $products = Product::search($search_term);

  $products->each(function($product) use ($cache) {
    $cache->map("Product/Get/{$product->id}");
  });

  return $products;
});
```

**Comment by taylorotwell** [comment]
Seems like a kinda cool idea.
